### ISSUE TITLE
M2K Autoset Feature

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#1]
An Autoset feature, similar to what is available on benchtop scopes that automatically adjusts the settings based on the input signal, would be a good enhancement for Scopy.

**Comment by dNechita** [comment]
Marking this as an enhancement for the Oscilloscope instrument.

**Comment by adisuciu** [comment]
Implemented with https://github.com/analogdevicesinc/scopy/pull/370

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the feature is implemented.
