### ISSUE TITLE
Color underlines

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#10]
I have an observation about the orange underlines that are used in various places like indicating which channel the controls are operating on. The use of the same color, orange, as the waveform color for CH1, is confusing under the channel 2 heading label. Use the CH2 color under channel 2 heading or always use some other color not related to the channels.

**Comment by DanielGuramulta** [comment]
I've changed the color for the tabs, it looks like this: 
![signalgeneratorbluecolor](https://user-images.githubusercontent.com/26142210/28717537-e76d90ae-73aa-11e7-9b72-039b62bcc5e4.png).
![asfafafa](https://user-images.githubusercontent.com/26142210/28717682-772c6f12-73ab-11e7-9204-1d8682f4d825.png)
Here is the branch with the changes: https://github.com/analogdevicesinc/scopy/tree/siggen_quickfix

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/6fd7ece53a1010c2eb7ed401e4067028c5c0163f

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
