### ISSUE TITLE
Signal Generator: Wrong preview scale

### ISSUE THREAD

**Issue by avatarof** [analogdevicesinc/scopy#1032]
**Environment:**
OS: win10
FW Version V0.26
SW Version or git tag V1.2.0-d2a467f

**Describe the bug**
Wrong preview scale.
![image](https://user-images.githubusercontent.com/57388011/110278265-e9307b00-8011-11eb-86d4-e5fe4f93f1d1.png)

**To Reproduce**
1. Signal Generator
2. sine wave
3. amp.=50mV p2p
4. see the plot
**Expected behavior**
Right amp. scale

**Additional context**

[Scopy .txt](https://github.com/analogdevicesinc/scopy/files/6099085/Scopy.txt)

**Comment by kimpaller** [comment]
Issue is still replicated on the following environment:

OS: Windows 10
FW Version: https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.27
SW Version or git tag: [v1.3.0-rc2](https://github.com/analogdevicesinc/scopy/releases/tag/v1.3.0-rc2)

![image](https://user-images.githubusercontent.com/73711098/116520184-f6c4fb80-a904-11eb-9c2a-00aa8a7cd02a.png)

**Comment by tagoylo** [comment]
Issue not reproducible anymore in v1.4.0 rc2. Closing this issue.
