### ISSUE TITLE
Pattern generator: Cannot be triggered by logic analyzer

### ISSUE THREAD

**Issue by avatarof** [analogdevicesinc/scopy#1033]
**Is your feature request related to a problem? Please describe.**
AD2(analog discovery 2)'s Pattern Generator allow user hold their pattern until logic analyzer being triggered while M2K don't.

**Describe the solution you'd like**
Pattern Generator allow user hold their pattern until logic analyzer being triggered.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/57388011/110281516-d9b43080-8017-11eb-8165-d93420ad8bf4.png)

**Comment by rgetz** [comment]
Can you describe the use case? (Why you want to do this?)
