### ISSUE TITLE
Scopy hangs when Math Channel is manipulated

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#104]
Scopy build: [059faef](https://github.com/analogdevicesinc/scopy/commit/059faef9a92f2e001c32f38125f179a35dad145d) ; OS: Windows; Firmware: v0.13
Run Oscilloscope, then add a Math Channel .
There are several actions (but cannot be reproduced exactly) that will make Scopy hang:
-adding the channel
-switching between channels
-removing math channel
-moving channels axis

The bug appears with commit [5a8e4c3](https://github.com/analogdevicesinc/scopy/commit/5a8e4c3c66f29f3d2aa1575f6a9462d029d6c195)

Note: Scopy either will hang or disconnect in one of the situations mentioned above. The disconnect behavior is solved via [b846ab7](https://github.com/analogdevicesinc/scopy/commit/b846ab74080b7fab63052dbf9a399dc996ee7c9a), but not merged with master.

**Comment by pcercuei** [comment]
I reverted the commits that were involved in this issue, it works fine now.
