### ISSUE TITLE
<Instrument>: <Short description of the bug>

### ISSUE THREAD

**Issue by aniellodefelice58** [analogdevicesinc/scopy#1058]
OS Version: Windows 10 Version 2004
FW Version: 
SW Version: v1.2.0

Description of the bug:<description>
Steps to reproduce:
-
-

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/aniel/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Anything more specific ?

**Comment by adisuciu** [comment]
Reopen if you have anything more specific - reproduction steps, etc
