### ISSUE TITLE
hello unable to build scopy on windows msys2

### ISSUE THREAD

**Issue by keleisibo** [analogdevicesinc/scopy#1060]
build the project like this : https://wiki.analog.com/university/tools/m2k/scopy/build-windows
![ninjia](https://user-images.githubusercontent.com/74234892/112175985-adf99300-8c32-11eb-8b50-dff7c1033189.PNG)

and occur the error below:
FAILED: CMakeFiles/scopy.dir/resources/properties.rc.res
CreateProcess failed: The system cannot find the file specified.
![properties](https://user-images.githubusercontent.com/74234892/112176523-219ba000-8c33-11eb-94ea-75762964323c.PNG)
help me!

**Comment by adisuciu** [comment]
The Windows build instructions are not great. Even on our side, things go sideways sometimes. This is why we use the CI to build the latest version which is somewhat stable. We will create new build scripts in the future. Why do you want to build Scopy on Windows. You can get the latest from our CI. Currently this is the latest working build - https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38266090

**Comment by keleisibo** [comment]
you mean that I execute the script "build_appveyor_mingw.sh"，and then build success?

**Comment by keleisibo** [comment]
Thank you for answering my question，you mean that I execute the script "build_appveyor_mingw.sh"，and then build success?

**Comment by adisuciu** [comment]
No, you need to install gnuradio, then scopy-mingw-build-deps , then build scopy. The scripts do a good job of building this in the cloud (appveyor), but don't work that well on users machines without tweaking. We primarily use Linux to develop(which make things a lot easier) and only once in a while use Windows to test. 
Like I said, your best bet is either compiling on Linux if you want to do development or using already built binaries for the platforms we provide (win/linux/mac). We will create some scripts that are easier on user's machines on Windows, but meanwhile I'd stick to the things that work - building on linux/using the provided installers (for Windows)

**Comment by keleisibo** [comment]
got it,Thank you
