### ISSUE TITLE
Logic analyzer: Not going low correctly

### ISSUE THREAD

**Issue by kes-electronics** [analogdevicesinc/scopy#1063]
**Environment:**
 - OS: Windows 10 build 1902
 - FW Version 0.26
 - SW Version 1.2.0

**Describe the bug**
Logic analyzer trace will only show a low signal when followed by a high signal. The digital IO shows correct level.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build switch circuit, using 5V supply from ADALM2000 (issue also present with external supply). Connect output to DIO0.
![active-high switch](https://user-images.githubusercontent.com/47384108/112298314-ca2b1d80-8c8e-11eb-9795-a0ca33fbf48f.png)
2. Use logic analyzer, 20 ksps ,200 ksamples, enable DIO0, rising edge trigger.
3. Run single, press switch to trigger analyzer
4. See results

**Expected behavior**
Trace to match switch presses (and digital IO)

**Screenshots**
![scopy 4](https://user-images.githubusercontent.com/47384108/112299211-7d941200-8c8f-11eb-9464-5b591137b78c.gif)

**Additional context**
Work computer, cannot find .ini file!
Similar issue when I use one digital IO pin as output connected to another set as input, and take trace on logic analyzer as output state is toggled.

**Comment by adisuciu** [comment]
Yes, this issue should be fixed in the latest version. You can download it here - https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38266090 . We will create a release candidate in the following days.

**Comment by kes-electronics** [comment]
Excellent, thank you.
