### ISSUE TITLE
<Instrument>: <Mixed Signal View crashes when changing time base>

### ISSUE THREAD

**Issue by alex-t-nguyen** [analogdevicesinc/scopy#1074]
OS Version: Windows 10 Version 1909
FW Version: 
SW Version: v1.2.0

Description of the bug:<Mixed signal view crashes when changing time base>
Steps to reproduce:
- Turn on Mixed signal view
- Change time base

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/Niem/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Can you try the latest version - https://github.com/analogdevicesinc/scopy/releases/tag/v1.3.0-rc1 ?

**Comment by alex-t-nguyen** [comment]
It appears to be working now when you change the time base. However, if I click autoset on the oscilloscope while mixed signal view is on it still crashes.

**Comment by adisuciu** [comment]
Closing this as this issue is related to autoset - https://github.com/analogdevicesinc/scopy/issues/913
