### ISSUE TITLE
<ADALM2000>: <keeps disconnecting from my macbook pro>

### ISSUE THREAD

**Issue by rohansonecha** [analogdevicesinc/scopy#1075]
OS Version: macOS 10.16
FW Version: 
SW Version: e02cebe

Description of the bug:<description>
Steps to reproduce:
-
-

The ini files might be useful to reproduce the error.
The ini file is located at: /Users/rohan/.config/analog.com/Scopy.ini
Please consider attaching it.

**Comment by teoperisanu** [comment]
Can you try the new version (https://github.com/analogdevicesinc/scopy/releases/tag/v1.3.0-rc1) and see if the bug is still there.
Same problem as: #1071
