### ISSUE TITLE
Oscilloscope: Confused Snapshot Handles

### ISSUE THREAD

**Issue by pvatkins** [analogdevicesinc/scopy#1083]
**Environment:**
 - OS: [e.g. iOS] Windows 10 Home 64 Bit Version 20H2 OS Build 19042.867 Windows Feature Experience Pack 120.2212.551.0
 - FW Version v0.26
 -  SCOPY Version 1.3.0-441fd19

**Describe the bug**
This bug was noticed in SCOPY version 1.3.0 release candidate. When selecting first Snapshot (From a dual channel presentation) , the shapshot "handle" (Square box to left of 'scope) that should be associated with snapshot trace display trace, is now associated with CH2 trace. The CH2 handle is now associated with the Snapshot trace. If additional snapshots are selected and then cancelled, the CH2 trace may be left with the incorrect handle.

1. Start Scopy
2. Select M2k USB 1.12.5
3. Connect
3. Select Oscilloscope, note 2 channels displayed normally
5. Select CH1 Settings Menu
6. Scroll down to the bottom
7. Select Snapshot pushbutton
8. See green snapshot trace associated with purple handle. Selecting green handle and dragging it so that CH2 trace is again on scope face, note that the green handle is now associated with the purple CH2 trace.
9. Select Snapshot button
10. Note CH2 (purple) handle trace is associated with Aqua trace, Aqua handle is associated with CH2 trace, Snapshot #1 handle is now associated with snapshot 1 trace, and CH1 handle associated with CH1 trace.
11. Delete (X-Out) Ref1 trace and Ref2 trace.
12. Note: Aqua handle now associated with CH2 trace, and there is no CH2 handle.

**Expected behavior**
The trace handles should always be associated with the correct trace.

**Screenshots**

**Additional context**

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/ali/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by DanielGuramulta** [comment]
Should be fixed with pull request: #1085
