### ISSUE TITLE
Digital IO (UI): DIO indicator initially says "Individual" even if the IOs are grouped

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#1086]
**Environment:**
 - OS: Windows 10 Enterprise 64-bit (10.0, Build 17763)
 - FW Version: [v0.26](https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.26)
 - SW Version or git tag: 441fd19

**Describe the bug**
The groups of DIOs 0-7 and DIOs 8-15 initially indicate "Individual" even if the DIOs are initially grouped. Please see screenshot below.

**To Reproduce**
1. Go to 'Digital IO'
2. Note the setting and orientation of each of the two DIO groups to see the error.

**Expected behavior**
The initially grouped DIOs must be labeled as "Group", not as "Individual."

**Screenshot**
![image](https://user-images.githubusercontent.com/43806793/113833120-db5e4900-97bb-11eb-867c-5f0102d0afea.png)

**Comment by DanielGuramulta** [comment]
Should be fixed with pull request: https://github.com/analogdevicesinc/scopy/pull/1081

**Comment by jpineda3** [comment]
Verified fixed in v1.3.0-rc2.

**Comment by HRosete** [comment]
> Verified fixed in v1.3.0-rc2.

Screenshot:
![image](https://user-images.githubusercontent.com/43806793/116502586-7b545180-a8e6-11eb-812b-e69ade98568f.png)

Closing this issue now.
