### ISSUE TITLE
Item 5 from issue #8: DMMs peak hold feature

### ISSUE THREAD

**Issue by ABanut** [analogdevicesinc/scopy#109]
Item 5 from issue #8 

"Many DMMs have a peak hold feature. You might want to consider adding this feature for both a max ( positive ) peak hold and min ( negative ) peak hold. With a button to reset the held values of course."

**Comment by AlexandraTrifan** [comment]
This feature was added with commit ce5ec0f279095c54c31b101664be29e3c30180b7.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the enchancement is implemented.
