### ISSUE TITLE
Logic Analyzer: Oscilloscope as External Trigger Source has conditions

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1090]
**Environment:**

- OS: Windows 10 Enterprise 64-bit (10.0, Build 17763)
- FW Version: v0.26
- SW Version or git tag: 441fd19

**Describe the bug**
When selecting oscilloscope as the external trigger source, sometimes the dropdown menu for conditions is enabled.

**To Reproduce**

1. Open Logic Analyzer
2. Click on the Trigger menu.
3. Turn ON external trigger.
4. Select Oscilloscope as Source. This time the conditions are disabled. 
5. Do not change the Source, leave it as oscilloscope. 
6. Turn OFF external trigger. 
7. Then turn it ON again. The source is still Oscilloscope but the Conditions are now enabled.

**Expected behavior**
Conditions should stay disabled when the oscilloscope is set as an external trigger source.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/113990735-5854f580-9884-11eb-9706-4e65ba8a0807.png)

**Comment by DanielGuramulta** [comment]
Should be fixed with pr: #1091

**Comment by tagoylo** [comment]
Issue verified fixed in v1.3 RC2. Closing this item.
