### ISSUE TITLE
<Instrument>: <Short description of the bug>

### ISSUE THREAD

**Issue by tadashi2014** [analogdevicesinc/scopy#1094]
OS Version: macOS 10.15
FW Version: 
SW Version: e02cebe

Description of the bug:<description>
Steps to reproduce:
-
-

The ini files might be useful to reproduce the error.
The ini file is located at: /Users/tadashi/.config/analog.com/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Can you elaborate ?

**Comment by tadashi2014** [comment]
With the adalm2000 connected, I selected a logic analyzer and tried to run it without connecting anything to the IO connector, and the application quit.
I have multiple USB drivers installed, which may be the effect.

**Comment by adisuciu** [comment]
https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38632761/job/im3mrfswwg3oa1gb/artifacts 
Would you mind giving this version a try ?

**Comment by tadashi2014** [comment]
The downloaded application seems to be working without problems.

**Comment by adisuciu** [comment]
Awesome. This will be part of the new release coming soon. Stay tuned. I'm closing this for now

**Comment by tadashi2014** [comment]
OK. I'm looking forward to the release of the new version.
