### ISSUE TITLE
Pattern Generator: Selecting UART pattern crashes Scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1096]
**Environment:**

- OS: Windows 10 Enterprise 64-bit (10.0, Build 17763)
- FW Version: v0.26
- SW Version or git tag: 441fd19

**Describe the bug**
When selecting UART as the pattern for a channel. Scopy then crashes.

**To Reproduce**
1. Enable a channel
2. Double Click on the channel handle
3. Select UART as pattern. Scopy crashes.

**Comment by adisuciu** [comment]
Cannot reproduce - can you also try it with this version ? https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38632761/job/dyee5dcpre1plp7l/artifacts

**Comment by adisuciu** [comment]
Does it crash with the latest ?

**Comment by tagoylo** [comment]
> Does it crash with the latest ?

No, it now doesn't crash with the latest. >https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38787957 used this build. Also checked with the new firmware and it doesn't crash.

**Comment by adisuciu** [comment]
alright, thanks !

**Comment by tagoylo** [comment]
Issue verified fixed in v1.3 RC2. Closing this item.
