### ISSUE TITLE
Logic Analyzer: UART decoder not on the list

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1099]
**Environment:**
- OS: Windows 10 Enterprise 64-bit (10.0, Build 17763)
- FW Version: v0.26
- SW Version or git tag: 441fd19

**Describe the bug**
UART is missing from the list of decoders.

**To Reproduce**
1. Go to Logic analyzer
2. Click on select a decoder to add
3. Look for UART,  it can be noticed that UART is not on the list.

**Expected behavior**
UART should be on the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/114361666-f6103380-9ba8-11eb-852c-29ee188e372a.png)

**Comment by adisuciu** [comment]
Cannot reproduce - can you also try it with this version ? https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38632761/job/dyee5dcpre1plp7l/artifacts

**Comment by tagoylo** [comment]
> Cannot reproduce - can you also try it with this version ? https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38632761/job/dyee5dcpre1plp7l/artifacts

Tried this version and UART is still not on the list. Also tried uninstalling scopy first before installing this version but still the same issue occurs.

**Comment by adisuciu** [comment]
Can you browse to your Scopy installation directory/decoders and check if you have an uart folder in there and inside that folder tehre should be pd.py and __init__.py ?

-Adrian

**Comment by tagoylo** [comment]
Yes, uart folder is present as well as the pd.py and init.py files

**Comment by adisuciu** [comment]
Can you try this build ? https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38787957

**Comment by tagoylo** [comment]
> Can you try this build ? https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/38787957

The uart is now showing on this build.

**Comment by tagoylo** [comment]
Issue verified fixed in v1.2 RC2. Closing this item.
