### ISSUE TITLE
Oscilloscope: The grids don't have labels

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/scopy#11]
Moving this from a list of issues at #9 into its own issue.

Initial issue:
"The grid has no labels. The horizontal axis needs time labels and the vertical axis should have color coded labels for each channel ( because position and scale might be different )."

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/2b3c6723fc79c54bb71f72e83a466b4322f7e7ad

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
