### ISSUE TITLE
Logic Analyzer: Saved export file has redundancy in file extension (.csv.csv)

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1101]
**Environment:**

-  OS: Windows 10 Enterprise 64-bit (10.0, Build 17763)
- FW Version: v0.26
- SW Version or git tag: 441fd19

**Describe the bug**
When exporting and checking the saved file. The saved file has the following filename, **_filename.csv.csv_**

**To Reproduce**
1. Go to logic analyzer
2. Click on export button
3. Add a filename, ex. sample
4. Check the file that is saved.
It can be observed that together with the filename a .csv is added aside from the file extension.

**Screenshots**
![Screenshot 2021-04-12 163215](https://user-images.githubusercontent.com/25096080/114366780-5655a400-9bae-11eb-9d9e-4178de3610cd.png)
![bug](https://user-images.githubusercontent.com/25096080/114366788-581f6780-9bae-11eb-8f77-5f9d89609b73.png)

**Comment by adisuciu** [comment]
Fixed here - https://github.com/analogdevicesinc/scopy/pull/1105

**Comment by tagoylo** [comment]
Issue verified fixed in v1.3 RC2. Closing this item.
