### ISSUE TITLE
Signal Generator: Persistent CH1 indicator (orange line) even when channel is turned off.

### ISSUE THREAD

**Issue by kimpaller** [analogdevicesinc/scopy#1106]
**Environment:**
 - OS: Windows 10
 - FW Version: https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.26
 - SW Version or git tag: https://github.com/analogdevicesinc/scopy/commit/441fd19324d7256b64ede2551e4e7bff9e525a86

**Describe the bug**
CH1 indicator (orange line) does not disappear even when CH2 is turned off. It will just go back to a straight line at 0.00V after CH1 is switched off.

Before CH1 is turned off:
![image](https://user-images.githubusercontent.com/73711098/114507237-6d0b0200-9c65-11eb-8bd6-a953aa4e95b3.png)

After CH1 is turned off:
![image](https://user-images.githubusercontent.com/73711098/114507397-a5124500-9c65-11eb-997f-0012e9db4729.png)

**To Reproduce**
1. Go to 'Signal Generator'.
2. Click on CH1 (orange circle) to activate the channel.
3. Click again on CH1 to deactivate channel.
4. Observe orange straight line at 0.00V.

**Expected behavior**
After deactivating the channel, the orange line (CH1 indicator) shuld disappear just like CH2 indicator (blue line).

**Comment by adisuciu** [comment]
Fixed https://github.com/analogdevicesinc/scopy/pull/1107

**Comment by kimpaller** [comment]
Confirmed fix on:

OS: Windows 10
FW Version: https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.27
SW Version or git tag: [v1.3.0-rc2](https://github.com/analogdevicesinc/scopy/releases/tag/v1.3.0-rc2)
