### ISSUE TITLE
General: Automatic M2K FW update doesn't work

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#1111]
**Environment:**
 - OS: Windows 10 Enterprise 64-bit (10.0, Build 17763)
 - FW Version: [v0.26](https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.26)
 - SW Version or git tag: a751ed5

**Describe the bug**
The automatic M2K FW update doesn't work. On April 14th (5 days upon posting this), M2K's new firmware version [v0.27](https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.27) has been released. My instrument still has the v0.26 FW. When I enabled the automatic update checking on the Preferences and opened Scopy, it says that my "Firmware is up to date" even if it isn't. Please see the pictures below:

**Screenshots**
![image](https://user-images.githubusercontent.com/43806793/115222027-df378700-a13c-11eb-9174-2ee331f2df5e.png)

![image](https://user-images.githubusercontent.com/43806793/115222521-65ec6400-a13d-11eb-81a5-c7ef5fbd3349.png)

**To Reproduce**
1. There are two ways to enable the automatic update feature.
1.1. Click 'Yes' on the dialog box prompt upon opening Scopy. It will automatically enable the corresponding checkbox on the Preferences.
![image](https://user-images.githubusercontent.com/43806793/115223636-9a145480-a13e-11eb-9f18-a9ed090b2d0e.png)

1.2. If you've initially clicked 'No' on the prompt, enable it by clicking the "Enable automatic update checking" checkbox on the Preferences.
![image](https://user-images.githubusercontent.com/43806793/115224162-1e66d780-a13f-11eb-8b8d-0b8d46323292.png)

2. Attach M2K loaded with a v0.26 firmware.
3. Click on 'Home.'
4. Click on the M2K device icon.
5. Check on the message below the 'Connect' button and see the error.

**Expected behavior**
Scopy must correctly compare whether the FW loaded on the M2K device is the same as the newly released FW version on GitHub. Also, it must accurately state whether the FW on the device is truly up to date or not.

**Comment by adisuciu** [comment]
It should work now. I updated the file on the server.

**Comment by HRosete** [comment]
This issue is now confirmed fixed on Scopy v1.3.0-rc2 (c625d89). Please see screenshot for proof:

![image](https://user-images.githubusercontent.com/43806793/116502092-3380fa80-a8e5-11eb-9619-bc206ef9055d.png)

Closing this issue now.
