### ISSUE TITLE
Logic Analyzer: Delay doesn't seem to work

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1119]
**Environment:**
 - OS: Windows 10
 - FW Version : v0.27
 - SW Version or git tag:  v1.3.0-rc2  c625d89

**Describe the bug**
Adding delay to the plot does not seem to add delay to the plot. Also, is delay supposed to be disabled when in stream mode?

**To Reproduce**
1. In pattern generator, enable a channel and set it to any pattern to generate a signal
2. In logic analyzer monitor that channel 
3. Add delay to the plot.
4. Observe that there are no changes to the plot.

![image](https://user-images.githubusercontent.com/25096080/116376050-74740300-a842-11eb-9426-45592451849c.png)

5. Also when changing to stream, delay becomes disabled. is this expected? 
![image](https://user-images.githubusercontent.com/25096080/116376116-8655a600-a842-11eb-88f7-14e5034acbb0.png)

**Comment by adisuciu** [comment]
Yes, it's supposed to be disabled in stream mode
You did not set a trigger. Delay sets the trigger delay - basically the trigger will occur on the blue vertical line.

**Comment by tagoylo** [comment]
> Yes, it's supposed to be disabled in stream mode
> You did not set a trigger. Delay sets the trigger delay - basically the trigger will occur on the blue vertical line.

Oh right. Thanks for the clarification. Closing this item.
