### ISSUE TITLE
Change Time Base through +/- buttons crashes Scopy

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#113]
Scopy version: [6915e70](https://github.com/analogdevicesinc/scopy/commit/6915e709e99630b7cf8d243b099c23b0772d999f) , OS: Windows, Firmware: v0.13

Delete Scopy.ini file first, then open Scopy, select Oscilloscope -> Channel Settings. Press + or - button corresponding to Time Base. The application crashes.
![untitled2](https://cloud.githubusercontent.com/assets/26061529/26493510/ac59b88a-4222-11e7-9b0d-a2419ddad9c3.png)

![untitled](https://cloud.githubusercontent.com/assets/26061529/26493412/18cef04e-4222-11e7-8018-3baf1d564f5f.png)

**Comment by dNechita** [comment]
Fixed in commit https://github.com/analogdevicesinc/scopy/commit/e653e6f0f987405e1b97f9eac602e7a77ee0af47 and in https://github.com/analogdevicesinc/scopy/commit/c03357032446589543726c16b5f3e6260598e8e8 (by default, with no .ini to load the time position should be 0 not -5 seconds).

**Comment by amiclaus** [comment]
Fixed via [e653e6f](https://github.com/analogdevicesinc/scopy/commit/e653e6f0f987405e1b97f9eac602e7a77ee0af47) & [c033570](https://github.com/analogdevicesinc/scopy/commit/c03357032446589543726c16b5f3e6260598e8e8)
