### ISSUE TITLE
Osc: Scopy Minimum Size window make texts and buttons overlap from Issue #60

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#114]
Select Oscilloscope feature and open:
1. Trigger Settings 
![untitled4](https://cloud.githubusercontent.com/assets/26061529/26494685/8b96531e-4228-11e7-9a12-c5676be1c6b2.png)

2. Measure Settings
![untitled5](https://cloud.githubusercontent.com/assets/26061529/26494714/b70d0dee-4228-11e7-88b6-7f3fa1eac645.png)

**Comment by AlexandraTrifan** [comment]
Fixed with commit c79a90e58a84fd0b206a6eb1307f3b4396287f49.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bugs are fixed.
