### ISSUE TITLE
ADALM2000 not getting detected by Scopy while using a Dell docking station

### ISSUE THREAD

**Issue by vsethia-adi** [analogdevicesinc/scopy#1142]
I have connected ADALM2000 through a USB cable to the Dell docking station.
READY LED glows permanently While the LED1 blinks frequently.
However, the ADALM2000 is not detected by the Scopy although the Device Manager is able to detect it as M2k serial device.
Any permanent solution is very much appreciated, as nowadays the laptop is going to have two or lesser usb ports and we will have to use USB hub in field or  at workshop as all of the existing ports will be in use one way or the other.

**Comment by adisuciu** [comment]
We've been seeing the same behavior unfortunately with no permanent solution right now. Just to confirm, what docking station and laptop are you using ?

-Adrian

**Comment by vsethia-adi** [comment]
It is Dell Precision 5530 and Docking station TB16.

**Comment by mhennerich** [comment]
Does it make a difference if you plug into the USB SS (blue) or HS ports on the back?
Have you tried using a different cable?

**Comment by vsethia-adi** [comment]
No difference irrespective of the SS or HS USB ports on the docking station.
I did notice that sometimes the Scopy is able to detect the kit momentarily and lost the connection unless the Scopy is relaunched again.

**Comment by teoperisanu** [comment]
Did you install the updates provides by Dell. There are some important updates such as:
- Dell Precision 5530 System BIOS
- Intel Thunderbolt Controller Driver
- Dell Thunderbolt Dock TB16 Firmware Update Utility
and others

The updates that can be found on Dell Support website and some of them can be installed via the Dell Update App.

**Comment by vsethia-adi** [comment]
Yes, the above DELL drivers are installed.

I did an install of Scopy of 1.2 verson (downgrade form v1.3) and it was able to detect and connect the hardware. I was able to use them for short time. but the connection was patchy and the Scopy would crash several times. At times, I have to reset the Scopy software in the preferences, as it fails to recognize the hardware. I am using the following options - Oscilloscope, and Logic Analyzer.

**Comment by teoperisanu** [comment]
Just out of curiosity, have you tried to connect via IP (192.168.2.1)?

**Comment by vsethia-adi** [comment]
let me know how to use that.

**Comment by teoperisanu** [comment]
Click on the '+' button, then enter the IP (192.168.2.1) in the URI field, then 'Connect', 'Add' and again 'Connect'

**Comment by vsethia-adi** [comment]
No, it does not connect using the IP address.

**Comment by rgetz** [comment]
what shows up in device manager? it should look like:
https://wiki.analog.com/_media/university/tools/pluto/drivers/device_manager_m2k_installed.png

**Comment by vsethia-adi** [comment]
![Screenshot 2021-07-27 192601](https://user-images.githubusercontent.com/79247663/127166589-396bfd8e-8e5c-4ca4-bd17-5032071318b6.jpg)
Snapshot attached. 
I see that sometimes it shows up as a normal USB device.
![Screenshot 2021-07-27 192719](https://user-images.githubusercontent.com/79247663/127166841-6b913513-10a7-4abd-b4e1-5bb287260703.jpg)

**Comment by rgetz** [comment]
Does it help to plug the USB power supply on the M2k into a USB power supply (while you are plugged into the dock?)

**Comment by vsethia-adi** [comment]
I did not understand your last question.

**Comment by adisuciu** [comment]
Robin is asking if you see similar behavior when connecting an additional USB cable to an external power brick (not to the dell docking station) to the rightmost USB connector. This additional USB connector is used for power delivery only.

**Comment by vsethia-adi** [comment]
The workaround in this case is 
1. Go to Device Manager tool in Windows OS
2. Go to Universal Serial Bus Controllers
3. Select ASMedia USB Root hub, Right click on its properties
4. uncheck the "Allow the computer to turn off this device to save power" in the Power management tab
5. Reboot.

It works for me.. Do confirm if it fixes the issues for you.  I have the Dell laptop model 5530 and docking station TB16.
ADALM2000 is connected via TB16. No issues if connected directly to laptop.

**Comment by adisuciu** [comment]
Awesome - we updated our troubleshooting page - https://wiki.analog.com/university/tools/m2k/scopy-troubleshooting?rev=1643979322#make_sure_the_system_doesn_t_limit_the_usb_power_consumption
