### ISSUE TITLE
PG: Scopy Minimum Size window make texts and buttons overlap from Issue #60

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#115]
Select Pattern Generator Feature and scroll inside the plot area until overlap is obtained as shown in the picture below:
![untitled6](https://cloud.githubusercontent.com/assets/26061529/26494884/af0b85ca-4229-11e7-89f5-8d897d8eedbf.png)

**Comment by AlexandraTrifan** [comment]
This happens in the Logic Analyzer as well. The issue should be fixed after commit 966468798a0ee13d035d605da43935b597e6fdf3. (The initial fix was introduced with commit ce616a6d2a7987f5ee24f726c57a621ae3c36815.)

**Comment by AlexandraTrifan** [comment]
The previous commits did not solve the problem completely. Commit 93f7e5e7c977e049b8c9e0c2198e9f431ce80bd0 introduces another fix.

**Comment by amiclaus** [comment]
Fixed via [93f7e5e](https://github.com/analogdevicesinc/scopy/commit/93f7e5e7c977e049b8c9e0c2198e9f431ce80bd0)
