### ISSUE TITLE
Error Check: Could I get the checksum of the file 'scopy-v1.3.0-Windows-setup.exe'

### ISSUE THREAD

**Issue by hellosemiconductor** [analogdevicesinc/scopy#1157]
I have been tried to install the scopy software and due to some issue I am getting a weird downloads happening. Could you send me the checksum if the file so that I could verify the file ?

Please help how I could verify the file before opening it.

**Comment by adisuciu** [comment]
If you want to install the windows version of Scopy, this is the download you want https://github.com/analogdevicesinc/scopy/releases/download/v1.3.0/scopy-v1.3.0-Windows-setup.exe

The file you mentioned only contains debug symbols that are useful if the application crashes and further investigation is required

**Comment by hellosemiconductor** [comment]
Yes, Sorry I needed the checksum of the file that you mentioned.
[https://github.com/analogdevicesinc/scopy/releases/download/v1.3.0/scopy-v1.3.0-Windows-setup.exe](https://github.com/analogdevicesinc/scopy/releases/download/v1.3.0/scopy-v1.3.0-Windows-setup.exe)

**Comment by adisuciu** [comment]
> adisuciu@DESKTOP-UT41HHH:/mnt/c/Users/Adi/Downloads/tmp$ sha256sum scopy-v1.3.0-Windows-setup.exe
> 390455c790f333d7019b247452b13495d7514d3600319035eea10d796aa9f3af  scopy-v1.3.0-Windows-setup.exe

**Comment by hellosemiconductor** [comment]
Thanks a lot
