### ISSUE TITLE
Spectrum Analyzer: Can not zoom in on y-axis

### ISSUE THREAD

**Issue by davidparent** [analogdevicesinc/scopy#1169]
Windows 10 FW=.28 SW=V1.3.0 dda5ec6

One can not zoom in on the y-axis more than a range of 10 on VRMs or Vpeak.  I sued to be able to zoom into a range of 1. (V1.2)

Set a 1k sin wav with a 1V amplitude and run.  Got to specvtrm analsyer and change sweep uintil ne can see the 1kHz peak Change y-axis to Vpeak or Vrms. Adjust top and bottom and range to zoom in.    
One can only zoom in to a min of 10.  Can not set tp and bottom closer than 10.

**Expected behavior**
Use to be able to zoom into a range of 1

 
![image](https://user-images.githubusercontent.com/1963366/140405740-4dbd2fa3-6346-408c-88e8-b4662d81953f.png)

**Comment by ioanachelaru** [comment]
Can you download [scopy-x86_64-setup.exe](https://github.com/analogdevicesinc/scopy/actions/runs/1439644639)  and let me know how it works?
Thanks in advance

-Ioana

**Comment by davidparent** [comment]
Hi Ioana,
It works by setting the scale factor to what you want first.  Thanks!
BTW when I start the program I get this error:
[image: image.png]
Best,
-Dave

**Comment by ioanachelaru** [comment]
The image isn't available, but I believe you are referring to a problem with libsigrokdecode. We are aware of it and it will be solved soon. 

-Ioana

**Comment by davidparent** [comment]
Yep that was it. Thanks so much.
