### ISSUE TITLE
Pattern Generator not working with alpha v0.4

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#120]
When starting pattern generator, only 1st channel is generated rest of the channels are set low. This behavior suggests that the direction is set properly, but the buffer is not. My local builds work fine. I think there is a mismatch between the libiio library in the installer and the one the M2K.

**Comment by pcercuei** [comment]
Libiio builds were updated on appveyor.

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
