### ISSUE TITLE
<Instrument>: <Title>

### ISSUE THREAD

**Issue by dj444** [analogdevicesinc/scopy#1200]
**Environment:**
 - FW Version 
 - SW Version or git tag

**Describe the bug**
After installation in Win 10 Scopy does not start. I tried everything and having the latest FW and SW and drivers
Please contact me name404@gmail.com
 
**To Reproduce**
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/ali/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Solved on EZ I think ..
