### ISSUE TITLE
Scopy: Workspace Configuration

### ISSUE THREAD

**Issue by vsethia-adi** [analogdevicesinc/scopy#1203]
Is there any option to create a workspace configuration and save the same according to different project requirements?
Currently I have to create all the I/O configurations on all virtual instruments - mostly power supply, oscilloscope, pattern generator, signal generator and logic analyzer, while switching between different products. 
It will make my work easier if there is any option to save and recall each configuration as per the project requirements.

**Comment by adisuciu** [comment]
There's save/load button in the bottom left of the application.
