### ISSUE TITLE
Auto Trigger not working for high Time Base

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#121]
Scopy version: [0a2ee9a](https://github.com/analogdevicesinc/scopy/commit/0a2ee9a6b5e0675a5026e93bdf35343ebe899cea), OS: Windows, Firmware: v0.13
Generate a sine wave and view it on Oscilloscope.  Set Trigger Mode: Auto
For Time Base >= 1ms the signal won't be triggered.

**Comment by dNechita** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/commit/969444271b76d8fae4428cedc8249df47527db93

**Comment by amiclaus** [comment]
On Scopy build: 21bb304 the bug is fixed.
