### ISSUE TITLE
'App not installed' on android

### ISSUE THREAD

**Issue by albhm** [analogdevicesinc/scopy#1225]
Hi, 

when I try to install the 1.4-rc1 apk package on my older android 6.0.1 tablet I'm getting the error "App not installed".
Maybe adding the "V1 signature" option as mentioned in the first answer here
https://stackoverflow.com/questions/4226132/app-not-installed-error-on-android
could help (or has it already been selected)? I did disable "Google Play Protect", but that didn't change a thing.
If the package is only compatible with certain android versions please state them somewhere.

**Comment by ioanachelaru** [comment]
Hi,

At the moment, Scopy only runs on Android 9 and above.

-Ioana

**Comment by adisuciu** [comment]
We updated the release notes.
