### ISSUE TITLE
Digital IO: After reset, operation indicator does not match with IO settings

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1233]
**Environment:**
 - OS: macOS Catalina 10.15.7, Windows 
 - FW Version: 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9
 
**Describe the bug**
The operation indicator does not match with the IO settings after reset. It shows Individual although the IO settings is for Group.

**To Reproduce**
1. Click on Digital IO instrument. Note that the default operation is Group and the settings are for Group.
2. Then go to Preferences, click on Reset Scopy.
3. Go back to Digital IO after resetting.
4. Notice that it now shows the operation as Individual but the IO settings are for Group.

**Expected behavior**
After reset, the configuration should be the same with default.

**Screenshots**
Before reset:
![before-reset](https://user-images.githubusercontent.com/25096080/160044374-f6c724ad-b822-410d-8bcb-d864530ea511.png)

After reset:
![after-reset](https://user-images.githubusercontent.com/25096080/160044392-f54ebb28-6f70-4d98-8a43-6c32e0675421.png)

**Comment by IonutMuthi** [comment]
this should fix it https://github.com/analogdevicesinc/scopy/pull/1241
