### ISSUE TITLE
General: Mouse Pointer turns to a "Double-Headed" Arrow over 100mV Interval Knob

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#1235]
**Environment:**
 - OS: Windows 10
 - FW Version: v0.28 
 - SW Version or git tag: [v1.4.0-rc1](https://github.com/analogdevicesinc/scopy/tree/refs/tags/v1.4.0-rc1), 895c0e9

**Describe the bug**
The mouse pointer turns to a double-headed arrow when hovered above the knob. The double-headed arrow gives an impression that something is to be resized. Please advise if this has something to do with Scopy or if this is an OS thing.

**To Reproduce**
1. Go to any instrument. For the test's sake, go to 'Power Supply'.
2. Hover over the knob beside 'Value' and click the dot in the middle.
3. Observe how the mouse pointer changes.

**Expected behavior**
The cursor must retain its normal arrow orientation.

**Screengrab**
https://user-images.githubusercontent.com/43806793/160052878-39bd430e-1f43-4ac8-9f2a-d1b214749b37.mp4

**Comment by adisuciu** [comment]
This is not a bug as it shows that you can use the scroll wheel to change the knob.
