### ISSUE TITLE
Digital IO: Gray out or disable the setters below the DIO pin if in Input (IN) mode

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#1237]
**Is your feature request related to a problem? Please describe.**
I always mistake the logic setter below the DIO pins as an indicator just like the oblong beside the DIO name. On that note, I mistakenly assigned it as a bug ( #1236 ).
![image](https://user-images.githubusercontent.com/43806793/160068146-34ceef7b-145f-4bc6-a8d3-daf6f273a192.png)

**Describe the solution you'd like**
It might be good if the setters (0 and 1) are grayed out/disabled if the pin is the IN mode. This way even the first time users will not confuse them as indicators too.
![image](https://user-images.githubusercontent.com/43806793/160068262-f1044f5b-9019-45b5-bf73-e490e9a3c2f5.png)

**Comment by adisuciu** [comment]
The reasoning behind having this control enabled is that you can preset it so when you move to output, the pin goes from HiZ straight to HIGH/LOW without additional user interaction. This can be useful in some situations.
