### ISSUE TITLE
Pattern Generator: Channel handles gets messy when changing to full screen

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1239]
**Environment:**
 - OS: macOS Catalina 10.15.7, Windows 10
 - FW Version: 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
Channel handles gets messy when shifting to full screen. The channel handles does not seem to retain with its designated plot.

**To Reproduce**
1. Do not set Scopy window to full screen yet.
2. Open pattern generator instrument
3. Enable all channels.
4. Run pattern generator in single-shot. Just to have plot.
5. Notice the location of the channel handles.
6. Now set Scopy window to full screen.
7. Notice that some of the handles are missing and some plots do not have channel handles.

**Expected behavior**
Channel handles should stay/follow its designated plot.

**Screenshots**
![channel-handles](https://user-images.githubusercontent.com/25096080/160076467-4f3621c1-81bf-4afa-aaea-93447889298d.png)

**Comment by IonutMuthi** [comment]
this should fix it https://github.com/analogdevicesinc/scopy/pull/1273
