### ISSUE TITLE
Pattern Generator: End of scroll bar does not show DIO 14/15 on the preview screen

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1240]
**Environment:**
 - OS: macOS Catalina 10.15.7, Windows 10
 - FW Version: 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
End of scroll bar does not show DIO 14 and DIO 15 on the preview screen unless both channel handles are dragged upward into the screen.

**To Reproduce**
1. Open pattern generator instrument.
2. Enable DIO 13, 14, and 15 (or all channels). At this point they are not visible on the preview screen.
3. Using the scroll bar, scroll until the end.
4. Notice that only DIO 13 is visible on the screen.
5. DIO 14 and DIO 15 are still not visible even if we scrolled to the end.

**Expected behavior**
The end of the scroll should enable user to view until DIO 15.

**Screenshots**
![scroll-bar](https://user-images.githubusercontent.com/25096080/160080189-96bda0d8-a9e2-4dcb-a075-798c00899057.png)

**Comment by IonutMuthi** [comment]
this should fix it https://github.com/analogdevicesinc/scopy/pull/1242
