### ISSUE TITLE
Android: Enable touch scroll

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1246]
**Is your feature request related to a problem? Please describe.**
When using scopy on android, it is quite hard to use especially when list is involved. The user has to use the scroll bar to navigate especially in smaller screens when UI is more compressed.

**Describe the solution you'd like**
It would be a convenience to the user if touch scroll is enabled. Just like scrolling on Facebook.

**Comment by ioanachelaru** [comment]
Hi,

Touch scroll is enabled, but you must use two fingers in order for it to work.

-Ioana

**Comment by tagoylo** [comment]
Got it. Thanks. Closing this item.
