### ISSUE TITLE
General: "Enable Demo" is not applicable to Android

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#1248]
**Environment:**
 - OS: Android 11
 - Device: Samsung A70
 - FW Version
 - SW Version or git tag: 895c0e98

**Describe the bug**
You can't enable the demo mode on Android. It should be enabled with ease even if no M2K device is connected.

**To Reproduce**
1. On Home, click the '+' icon.
2. Click on 'Enable Demo'. The IP '127.0.0.1' should appear on top.
3. Click 'Connect'.

**Expected behavior**
You should enable the demo mode on Scopy even if no M2K device is connected.

**Screenshots**
![Screenshot_20220328-084411](https://user-images.githubusercontent.com/43806793/160310817-0504936e-1636-4c5d-a09d-651368203d6b.jpg)

https://user-images.githubusercontent.com/43806793/160310834-c9f4fca9-c053-489d-87a0-3fc8b2e11986.mp4

**Comment by adisuciu** [comment]
This depends on the platform I think. For us it works on our test machines. There is not much that we can do unless we have a physical machine that fails. The emulator is not really a required feature for the Android platform so I'm going to close this.
