### ISSUE TITLE
Simple mode for smaller screen size

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1249]
**Is your feature request related to a problem? Please describe.**
I've been using my phone (6.7in screen size) with scopy since I don’t have a tablet with me.
It is working and all important features are accessible. But one thing to note is that most of the parts are small (e.g. buttons, plots like histogram in oscilloscope). Sometimes it takes time to tap the right area. Ex. When All channels are enabled in oscilloscope plus the reference/math channels, the area to select is very tight and difficult to navigate. Maybe, this is not an issue if the screen size is big, like a tablet. See picture:

![image](https://user-images.githubusercontent.com/25096080/160325154-ae3b62a6-3b3b-4a62-b203-ae3097935aa0.png)
![image](https://user-images.githubusercontent.com/25096080/160325195-f8a5962f-3a91-41ef-86d2-11bf315d4593.png)

**Describe the solution you'd like**
Maybe having a simple mode for smaller screen sizes android devices? Like all important features are there but the UI is more small screen size friendly. Maybe add to preferences an option to switch to simple mode.

**Comment by adisuciu** [comment]
The application is really targeted towards tablets.
There is a preferences option to do tabbed plots in the oscilloscope which may help with the clutter. There is not much that we can do right now regarding number of channels.

**Comment by tagoylo** [comment]
This is noted. Should I close this item or keep it open?

**Comment by adisuciu** [comment]
Close for now
