### ISSUE TITLE
Scope: Order things are drawn on the screen

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#125]
In the waveform display area, the blue horizontal position line needs to be drawn behind the waveform trace. As we can see in this screen shot the rising edge of the trace is obscured by the blue line.

![image](https://cloud.githubusercontent.com/assets/11668458/26738843/b8951eac-479d-11e7-8d97-60f7c8748b1b.png)

This would also be true for the other horizontal position lines and maybe the cursor lines as well. As a general case the waveform traces should be drawn on top of everything else ( i.e. last I'm guessing ).

Doug

**Comment by DanielGuramulta** [comment]
Fixed with commit : https://github.com/analogdevicesinc/scopy/commit/10de3a9934c74771870fd9abf1b030f9d1058f39

**Comment by amiclaus** [comment]
On Scopy build: d85de1c (v0.10) the feature is implemented.
