### ISSUE TITLE
General: After reset, collapsed main menu remains collapsed

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1256]
**Environment:**
 - OS: linux-arm32, windows, macOS
 - FW Version: 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
After resetting scopy, collapsed main menu remains collapsed. The instruments name are cut off.

**To Reproduce**
1. Collapse main menu.
2. Go to Preferences and click Reset Scopy.
3. Wait until reset process is done.
4. Notice the main menu is still collapsed. See picture.

**Expected behavior**
Back to default.

**Screenshots**
![main-menu-after-reset](https://user-images.githubusercontent.com/25096080/160545235-5320f614-8095-45aa-bc0b-16ed7715d24a.png)

**Comment by IonutMuthi** [comment]
this should fix it https://github.com/analogdevicesinc/scopy/pull/1263
