### ISSUE TITLE
General: Widgets windows are somewhat transparent in linux

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1259]
**Environment:**
 - OS: linux-arm32(ubuntu 21.1)
 - FW Version: 0.28 
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
Widgets windows are somewhat transparent in the sides in linux-arm32. It is not the case in windows.

**To Reproduce**
1. Open Preferences.
2. Enable dockable widgets.
3. Go to oscilloscope or any instruments with plot.
4. Click on the ">" to detach widget.
5. Notice that the widget window is transparent on the sides.

**Screenshots**
![dockable-widget](https://user-images.githubusercontent.com/25096080/160581891-5fecd098-4da6-40df-8f15-dee27735fde9.png)

**Comment by adisuciu** [comment]
That's weird it does not seem to reproduce on Kuiper raspberry-pi (arm) nor on my Ubuntu PC ..

**Comment by tagoylo** [comment]
I will confirm this on another Linux machine.

**Comment by adisuciu** [comment]
I think this may be related to Ubuntu 21.10 but cannot test. Do you have it running on a PC(not raspi) ?

**Comment by adisuciu** [comment]
Can you run Scopy like this ?  XDG_SESSION_TYPE=x11 flatpak run org.adi.Scopy

**Comment by tagoylo** [comment]
Running Scopy with command `XDG_SESSION_TYPE=x11 flatpak run org.adi.Scopy` solved the issue in Ubuntu 21.10 on Rpi4. Widgets are now not transparent. See screenshot below.
![Screenshot from 2022-03-31 08-43-43](https://user-images.githubusercontent.com/25096080/160954206-8ac86d35-9048-4686-85ec-bb45a0237193.png)

**Comment by tagoylo** [comment]
Using the command _XDG_SESSION_TYPE=x11 flatpak run org.adi.Scopy_ is also applicable in rc2. Closing this item.
