### ISSUE TITLE
Voltmeter: Label "Notes" in bigger font

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1261]
**Environment:**
 - OS: linux-arm32, windows10
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
When notes per instrument is enabled, the "Notes" label in voltmeter is in bigger font compared to what is in other instruments.

**To Reproduce**
	1. Open Preferences.
	2. Enable all instrument notes.
	3. Go to voltmeter.
	4. Notice that the "Notes" label is in bigger font.

**Expected behavior**
Should be the same with other instruments.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/160592410-eaf7b3fc-c250-48c2-9d42-3b07cd9e3c3e.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1262

**Comment by tagoylo** [comment]
Bug verified fixed in v1.4.0 rc2. Closing this item.
