### ISSUE TITLE
General: No label on other detached plot

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1270]
**Environment:**
 - OS: linux-arm32 (rpiOS)
 - FW Version :0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
No label on other detached plots. For oscilloscope views, there is a labels such as Time Domain, FFT, XY, Histogram. But for other plots, it is only "Scopy". If there are many detached plots, there's confusion as to which is which.

**To Reproduce**
	1. Open Preferences.
	2. Enable dockable widgets.
	3. Detach plots e.g. in oscilloscope, network analyzer, signal generator, etc.
	4. Minimize these windows.
	5. Notice that the labels of the plots are "Scopy", there's no way to know whose plot is that window unless user opens it one by one.

**Expected behavior**
Add specific label to detached plots.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/160770664-66513ca4-416e-4ad2-beb4-3630d8ae76e6.png)

**Comment by AlexandraTrifan** [comment]
Fixed with PR #1295

**Comment by tagoylo** [comment]
Labels are verified implemented in v1.4. rc2. Observed that only network analyzer and oscilloscope have the dockable widgets feature, is this expected?

**Comment by adisuciu** [comment]
Yes, as they are the onlyones that have multiple plots
