### ISSUE TITLE
Oscilloscope: Right arrow for tabbed plots does not work

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1271]
**Environment:**
 - OS: linux-arm32 (rpiOS), Windows10
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
The right arrow for tabbed plots for oscilloscope views does not work.

**To Reproduce**
1. Open Preferences.
2. Enable dockable widgets.
3. Go to Oscilloscope.
4. Enable all views. Select XY tab.
5. Expand left plots to the right. (See picture)
6. Tabs (FFT and XY) are compressed and "<" and ">" arrows are visible.
7. Click on "<" to view FFT tab.
Try clicking ">" to view again XY tab but it does not respond.

**Expected behavior**
The XY tab should show after clicking ">". 

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/160778942-266fe629-5c58-43ac-a281-3e6b7a71a854.png)

**Comment by adisuciu** [comment]
This does not reproduce for me, the arrows work fine. Also this happens really due to the histogram bug where you cannot resize the plot. We're investigating that.

**Comment by AlexandraTrifan** [comment]
I was able to reproduce it on MacOS, when the FFT/XY tab is resized to its minimum width. 
I added some changes that fix the arrow behaviour in PR #1295

**Comment by tagoylo** [comment]
Bug verified fixed in v1.4.0 rc2. Closing this item.
