### ISSUE TITLE
Network Analyzer: 0dB value on graph unavailable even when set under Preferences

### ISSUE THREAD

**Issue by jpineda3** [analogdevicesinc/scopy#1277]
**Environment:**
 - OS: Windows 10, macOS 11.4 Big Sur, Ubuntu 21.10 on RPi
 - FW: v0.28
 - SW Version or git tag: v1.4.0 rc1 https://github.com/analogdevicesinc/scopy/commit/895c0e98615a4579dca1746db63b061db25ef18c

**Describe the bug**
The 0dB line and label does does appear when the "Always display 0dB value on graph" is checked under Preferences.
Also, that option should be dB, not db.
The vertical axis starting at 3.3dB just shifts downward but the 0dB label does not appear.

**To Reproduce**
1. Under Preferences, enable "Always display 0dB value on graph"
2. Go to Network Analyzer and observe how 0dB is missing.

**Expected behavior**
The 0dB line should be displayed, regardless if the instrument is running or with it is connected to a physical circuit. See the screenshots from previous release.
![network_0db _expectedpng](https://user-images.githubusercontent.com/76926625/160958401-b4585ed2-8f1a-418b-bc8b-5f772436ca0f.png)

**Screenshots**
This is the error.
![network_0dB](https://user-images.githubusercontent.com/76926625/160958548-c2f89508-b3a6-4cf9-b3ff-8f6fbe1bc360.png)

**Additional context**
[network_0db.zip](https://github.com/analogdevicesinc/scopy/files/8385234/network_0db.zip)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1306

**Comment by jpineda3** [comment]
Bug verified fixed in v1.4.0 rc2. Closing this item.
