### ISSUE TITLE
Oscilloscope: Mixed Signal View text does not fit in button

### ISSUE THREAD

**Issue by jpineda3** [analogdevicesinc/scopy#1279]
**Environment:**
 - OS: Windows 10
 - FW Version: v0.28
 - SW Version or git tag: v1.4.0 rc1 https://github.com/analogdevicesinc/scopy/commit/895c0e98615a4579dca1746db63b061db25ef18c 

**Describe the bug**
The "d" in Enable/Disable Mixed Signal view is not fully displayed in the button. At least on my Windows, the issue is only during Disable and the "d" is partially displayed. On others', the d is completely gone.

**To Reproduce**
1. Go to Oscilloscope.
2. Check if the complete text is visible in the "Enable Mixed Signal View" button.
3. Check if the complete text is visible in the "Disable Mixed Signal View" button.

**Expected behavior**
The full text should be visible.

**Screenshots**
![mixed_signal1](https://user-images.githubusercontent.com/76926625/160966720-b4356a3a-6c21-495b-ad69-e90511acf50f.png)
![mixed_signal](https://user-images.githubusercontent.com/76926625/160966725-a234a2a3-3abd-4fcd-a810-58a2a4b745d8.png)

**Additional context**
[mixed_signal.zip](https://github.com/analogdevicesinc/scopy/files/8385553/mixed_signal.zip)

**Comment by AlexandraTrifan** [comment]
Fixed with PR #1310

**Comment by jpineda3** [comment]
Bug verified fixed in v1.4.0 rc2. Closing this item.
