### ISSUE TITLE
Scopy Menu - Instruments Arrangement

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#128]
Is there any logic in the arrangement of the Instruments in the Menu panel? 
Shouldn't they be somehow arranged/grouped based on Instruments functionality(analog/digital) or Instrument type(input/output)?

**Comment by acozma** [comment]
The default order should be: 
Oscilloscope
Spectrum Analyzer
Network Analyzer
Signal Generator

Logic Analyzer
Pattern Generator
Digital IO

Voltmeter
Power Supply

Users can change the order by dragging the instruments around.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/6aa85d4cc886000bdb79dd9bc12808c7838c80b0

**Comment by amiclaus** [comment]
On Scopy build: d85de1c (v0.10) the feature is implemented.
