### ISSUE TITLE
General: Add restart prompt when changing "Enable IIO Debug Instrument"

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1281]
**Is your feature request related to a problem? Please describe.**
When changing "Enable IIO Debug Instrument" that requires scopy restart in order to take effect, there is no window prompt that shows after changing. 

**Describe the solution you'd like**
Add restart prompt when changing "Enable IIO Debug Instrument". Like the one that prompts when changing "Enable dockable widgets"

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1289
