### ISSUE TITLE
Oscilloscope: XY plot initial state does not match with X-Y settings

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1283]
**Environment:**
 - OS: linux-arm32 (ubuntu21.10, rpiOS), Windows10
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9
 
**Describe the bug**
Upon enabling XY plot in oscilloscope, the plot does not match with default x-y settings. See picture below.

**To Reproduce**
1. Delete profile.ini first or reset scopy. 
2. Go to Oscilloscope.
3. Enable XY.
4. Look at XY settings on the panel. It is set by default as x-axis = CH1 and y-axis = CH2.
5. Notice that in the XY plot it does not follow the default. There is no y-axis.
6. Change y-axis to CH1, now the plot updates and y-axis is seen on plot.

**Expected behavior**
Plot labels the same as in default

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/160980154-a4f01b46-ff6e-4eb6-9fe5-a04bb4830406.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1291
