### ISSUE TITLE
Network Analyzer: +/- in Start/Stop/Center/Span, response is twice per click

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1287]
**Environment:**
 - OS: linux-arm32 (ubuntu 21.20, rpiOS)
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
Clicking once on +/- for the following parameters Start/Stop/Center/Span has twice the response. See video. This does not happen in windows.

**To Reproduce**
1. Go to Network Analyzer
2. Under Sweep settings, click on the +/- of parameters Start/Stop/Center/Span.
3. Notice that in every click there's twice the response. Increment/decrement is doubled.

**Expected behavior**
One click one increment/decrement.

**Screenshots**

https://user-images.githubusercontent.com/25096080/161022940-9cf00fc7-c506-4d54-b267-33767e2e83a5.mp4

**Comment by adisuciu** [comment]
Even though I could not reproduce this on the PC, this happens when the GUI thread does more computation that it is supposed to. With this PR i decoupled the computation of sample points from the GUI update. https://github.com/analogdevicesinc/scopy/pull/1293

**Comment by tagoylo** [comment]
In v1.4.0 rc2, the "Start" button is now okay, but for the rest, "Stop/Center/Span", the issue is still there.

**Comment by IonutMuthi** [comment]
this should fix it https://github.com/analogdevicesinc/scopy/pull/1338
