### ISSUE TITLE
Scopy - System Error

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#130]
When I try to run Scopy build either from an own build or from an appveyor build, the following error pops-up:
![scopy-system error](https://user-images.githubusercontent.com/26061529/27379097-9d56c886-5682-11e7-8d77-64e3e842f514.PNG)
In my C:\msys64\mingw64\bin there is only "libpython3.6m.dll".
I've tried to update the environment variables to python3.6 but that doesn't solve the problem.

**Comment by DanielGuramulta** [comment]
Renaming the dll to libpython3.5m will let Scopy run.

**Comment by dNechita** [comment]
The reason this is happening is that MSYS2 switched from Python 3.5 to 3.6. 

We need to update some of the files from the bundle that we have stored at http://swdownloads.analog.com/cse/build/msys64.tar.xz,.
I think that libsigrokdecode-3.dll needs to be recompiled by taking into account the new version of Python.

**Comment by pcercuei** [comment]
So this bug itself is fixed, but it doesn't work 100% right yet, see #143.

**Comment by amiclaus** [comment]
On Scopy build: 21bb304 the bug is fixed.
