### ISSUE TITLE
android: do not sleep while app is running

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#1303]
App goes to sleep while the app is running

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1308

**Comment by tagoylo** [comment]
Observed that Scopy is still running after going to Home Screen, notification is also available when output instruments are left running. Opening scopy again does not restart the app but rather continue the previous session. Only when the app is exited scopy restarts when opening it again. Closing this item.
