### ISSUE TITLE
mixed_signal: cannot move digital channels past 3/4 of the screen 

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#1305]
When scope is set to 10V/div - the location seems to snap - you can't move a signal to the bottom 1/4 of the screen. When set to a different setting (5V/div) it seems to work fine.

![image](https://user-images.githubusercontent.com/8676912/161563791-7c5060e0-b4eb-44fc-84c6-8a3590cd8ba3.png)

**Comment by tagoylo** [comment]
In v1.4.0 rc2, signals are observed to be moved to the bottom 1/4 of the screen. Issue is not reproducible. Closing this item.
