### ISSUE TITLE
Pattern Generator:  Crashing when closing a group of channels

### ISSUE THREAD

**Issue by DanielGuramulta** [analogdevicesinc/scopy#131]
When clicking on the x button of a group of channels, Scopy crashes:
![pgbug](https://user-images.githubusercontent.com/26142210/27386688-404ffbd6-569f-11e7-91a3-466766752325.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/commit/fb92e6530cc75afdc9ced2ac42983fd3413d56cf

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
