### ISSUE TITLE
State mismatch for input digital pin display 

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#132]
Connect channel 0 to channel 7.
Set channel 0 as output in high state.
Set channel 7 as input.

Channel 0 is set to logic value '1' and the state circle is filled.
For channel 7 the circle is filled corresponding tot the state detected, but the values '0'/'1' can be changed by the user even though they have no use in this situation.
This might create confusion:
![high0-7](https://user-images.githubusercontent.com/26061529/27588865-42c782a0-5b52-11e7-91aa-0b8738626a63.png)

I think that when a digital pin is set as input, the logic value displayed should be uneditable by the user and correlated with the state circle.

**Comment by adisuciu** [comment]
When the device is set to input , it is possible to preset a channel so that when setting output, the device will go from input directly to the desired state.
