### ISSUE TITLE
Spectrum Analyzer: Can not zoom in on y-axis

### ISSUE THREAD

**Issue by davidparent** [analogdevicesinc/scopy#1324]
Note this was solved in issues 1169, 1176, and 1177 by [ioanachelaru](https://github.com/ioanachelaru), but it did not seem to be put into version 1.3, and the version that ioanachelaru created that fixed the issue has expired.
 
Windows 10 FW=.28 SW=V1.3.0 https://github.com/analogdevicesinc/scopy/commit/dda5ec620b82725c39bf69f34e111fa04f2852eb

One can not zoom in on the y-axis more than a range of 10 on VRMs or Vpeak. I sued to be able to zoom into a range of 1. (V1.2)

Set a 1k sin wave with a 1V amplitude and run. Got to the spectrum analyzer and change sweep until one can see the 1kHz peak Change y-axis to Vpeak or Vrms. Adjust top and bottom and range to zoom in.
One can only zoom in to a min of 10. Can not set tp and bottom closer than 10.

Expected behavior
Use to be able to zoom into a range of 1
![image](https://user-images.githubusercontent.com/1963366/163056981-c164eecc-5979-4f67-bc1f-dc250f0a3d81.png)

**Comment by adisuciu** [comment]
This is fixed on master. We have a release candidate https://github.com/analogdevicesinc/scopy/releases/tag/v1.4.0-rc1 which should have this fix but it has some other bugs :). We are working on a new v1.4.0 release which we'll have out in a month or so .. 

![image](https://user-images.githubusercontent.com/8676912/163201130-8b877bb6-1d77-4497-8ae1-50cf3f2c2b1b.png)
