### ISSUE TITLE
Signal Generator: Individual instrument Notes for signal generator not showing up

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1330]
**Environment:**
 - OS: macOS, windows 10
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc2 cca49b2

**Describe the bug**

**To Reproduce**
1. In Preferences, click "Enable all instrument notes"
2. Go to Signal Generator.
3. Notice that there is no Notes section, unlike other instruments.

**Expected behavior**
A notes section is also in signal generator.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/165658863-f4936866-bd24-4a88-b384-4a04053bcf48.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1332
