### ISSUE TITLE
Pattern Generator: No alert notification when left running on background

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1334]
**Environment:**
 - OS: android
 - FW Version: v0.28 
 - SW Version or git tag: v1.4.0 cca49b2

**Describe the bug**
There is no alert notification _"Scopy is still running in the background. Device outputs are still enabled."_

**To Reproduce**
1. Open Scopy
2. Run pattern generator
3. Go to home screen
4. There is no alert notification _"Scopy is still running in the background. Device outputs are still enabled."_

**Expected behavior**
Expected to have alert notification.

**Comment by IonutMuthi** [comment]
this should fix it https://github.com/analogdevicesinc/scopy/pull/1335
