### ISSUE TITLE
Oscilloscope: Setting horizontal position unit to s/min/hr crashes scopy when time base in s

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1337]
**Environment:**
 - OS: windows
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc2 cca49b2

**Describe the bug**
Setting horizontal position unit to s/min/hr crashes scopy with time base in s

**To Reproduce**
1. Go to oscilloscope
2. Set time base unit to s
3. Set horizontal position unit to s/min/hr. 
4. Click + for horizontal position.
5. Wait few seconds and then Scopy crashes.

**Comment by AlexandraTrifan** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/1341
