### ISSUE TITLE
scoopy: MacOS ARM

### ISSUE THREAD

**Issue by Timorleiderman** [analogdevicesinc/scopy#1356]
What about adding the support for apple MacOS with m1 chip (ARM64V8)?

**Comment by adisuciu** [comment]
We're investigating this as it doesn't seem related to the M1

**Comment by AlexandraTrifan** [comment]
Hi,

Added some changes that we think might help. Could you try the following version: https://transfer.sh/oDom9C/Scopy-macos11.6.7-bac2d8f.dmg.zip ?

-Alexandra

**Comment by richardklingler** [comment]
Seems to work......thanks (o;

But did a firmware upgrade of the ADALM2000 before as it was shipped with 0.25...

Will there be an Apple silicon version soon? But I assume that would be a nightmare to port all libs to it (o;

Good to see Robin is still at ADI....used to help him 20 years ago with the Blackfin u-boot bootloader...greetings to him ;-)

**Comment by adisuciu** [comment]
Apple silicon version is not currently planned, but it might be something we do in the future. This bug seems a little more prevalent than we hoped for, we may create a bugfix release.

**Comment by adisuciu** [comment]
We created a new release that should fix that bug. 
This bug can also be worked around if you install the newest firmware version.
Closing this. Repoen if you are still having issues.
