### ISSUE TITLE
Building Scopy on MacOS

### ISSUE THREAD

**Issue by Jobsbu** [analogdevicesinc/scopy#1358]
I try to build Scopy on MacOS Monterey but I have some errors. It seems libsigrokdecode was not found. (Error No package 'libsigrokdecode' found).
Do you have any idea what could go wrong? I installed libsigrokdecode using homebrew.

Thanks in advance.

**Comment by AlexandraTrifan** [comment]
Hi,

Can you try to append the path to libsigrokdecode to an environment variable that can be found by CMake?
You can try something similar to the following (run this in the terminal before trying to build scopy)
`export PKG_CONFIG_PATH=/usr/local/Cellar/libsigrokdecode/0.5.3/lib/pkgconfig/:$PKG_CONFIG_PATH`

That's the location where libsigrokdecode gets installed by Homebrew (you might have a different version there) and it's not added to a known path for CMake to find. 
When building the libsigrokdecode project from source, you will get it installed in /usr/local/lib probably - which is a location where CMake will actually look for these dependencies.

Can you let me know if this works for you?

-Alexandra

**Comment by adisuciu** [comment]
Closed due to inactivity
