### ISSUE TITLE
Scopy 1.4.0: Oscilloscope hangs

### ISSUE THREAD

**Issue by TOIVI61** [analogdevicesinc/scopy#1359]
**Environment:**
 - OS: Windows 10 21H2 (the same on Ubuntu 22.04 LTS)
 - FW Version 0.27
 - SW Version or git tag Scopy v1.4.0 gitTag=f8fd4de

**Describe the bug**
Scopy quits or hangs when  the time base is changed, or the memory depth is reduced or the "Autoset" is started in the oscilloscope tool during "Run".

**To Reproduce**
1.  Started the Signal Generator with the following configuration: 1khz 5V square wave on channel 1;
2.  Started the Oscilloscope;
3.  On the Oscilloscope, selected the CH1 menu;
4. When changing Time base  Scopy hangs.

(Also hangs or quits when memory depth is reduced or the "Autoset" is started.)

**Additional context**
The attached logging file shows the result of the "Autoset".

[ScopyLog-20220713-141344.11908.log](https://github.com/analogdevicesinc/scopy/files/9102053/ScopyLog-20220713-141344.11908.log)

**Comment by AlexandraTrifan** [comment]
Hi,

Can you update the firmware version to v0.28 and check if this still happens?

-Alexandra
