### ISSUE TITLE
Removing channel from group using drag and drop crashes Scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#137]
Scopy build : [1839ee5d](https://github.com/analogdevicesinc/scopy/commit/1839ee5d7a90b30ff9221116ac4fd61f20edc389) OS: Windows ; Firmware: v0.13-dirty

When a group is created and want some channels to be removed from that group using the drag and drop feature, Scopy crashes.

![pattern generator dd](https://user-images.githubusercontent.com/25096080/27718332-f75b6844-5d7d-11e7-9876-f08e5544bc20.JPG)

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
