### ISSUE TITLE
Scopy: Oscilloscope not displaying waveforms correctly on ext monitor with MacBook

### ISSUE THREAD

**Issue by nialltc** [analogdevicesinc/scopy#1374]
**Environment:**
 - OS: MacOS 12.6 (21G115)
 - FW Version: v0.25
 - SW Version or git tag: 1.41 -f4beeb1
 - MacBook Pro (14-inch, 2021) M1
 - Builtin display 3024 × 1964
 - External display: Dell P2717H 1920x1080
 
**Describe the bug**
When viewed on an external monitor, the oscilloscope does not display waveform correctly.   The waveform is shifted up vertically.  Also, the plot on the signal generator is not displayed.  When the Scopy window is dragged from ext display to computer's build-in display, both the scope and signal generator function correctly. 

**Screenshots**
On ext display:
![image](https://user-images.githubusercontent.com/39237476/192284632-ba2cab7a-17ca-4f1e-a9e5-f5b0a8dc1046.png)

![image](https://user-images.githubusercontent.com/39237476/192284490-78f30020-a8e0-4449-838f-f35739a650cd.png)

On built-in display:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/39237476/192284775-e542a8c2-e049-4be6-a81c-0625e9709424.png">

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/39237476/192284212-fce7eae4-dcd5-4858-b967-e45932daed49.png">

**Comment by AlexandraTrifan** [comment]
Hi!

Tested Scopy v2.0.0 on a MacBook M2 using the same screen resolutions you provided for both the builtin display and the extended one and couldn't reproduce the issue. 

If you can, please try the latest Scopy v2.0.0 release candidate and reopen the issue if the issue persists.

Thank you!
