### ISSUE TITLE
Renamed channels changes to default name when grouped

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#139]
Scopy build : [1839ee5d](https://github.com/analogdevicesinc/scopy/commit/1839ee5d7a90b30ff9221116ac4fd61f20edc389) OS: Windows ; Firmware: v0.13-dirty

When a channel is renamed then is added to a group, the name changes to default, i.e. DIO 0. The name should not change since the user already renamed it.

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
