### ISSUE TITLE
Scopy: Full screen displays everything lower than it is

### ISSUE THREAD

**Issue by ARandomAsian** [analogdevicesinc/scopy#1390]
**Environment:**
 - OS: Windows 10
 - FW Version: v0.28
 - SW Version or git tag: v1.4.1 f4beeb1

**Describe the bug**
When I fullscreen scopy there is a black bar at the top that shift everything downwards. However the position is only visual, so I have to hover my mouse above everything to select them. 
First screenshot below shows the black bar. 2nd shows that when I hover above the home icon it goes dark and is selected, while the 3rd shows that when hovering over the home button in the middle its not selecting it. 

**Screenshots**
![1](https://user-images.githubusercontent.com/132995382/237062696-80b17d74-8ae4-46d0-a28f-51b6143efabb.png)
![2](https://user-images.githubusercontent.com/132995382/237062791-de0064fd-3f34-42ac-8dc1-de301b75205d.jpg)
![3](https://user-images.githubusercontent.com/132995382/237063107-372e0e9b-cb39-49c7-befc-41c20d4fdb11.jpg)

**Comment by adisuciu** [comment]
That is very weird. We have never encountered that. What resolution are you running ? Do you have scaling enabled ? Or Multiple monitors ? Does it reproduce for 1920x1080p, 100% scaling, single monitor ?
