### ISSUE TITLE
Oscilloscope: Handling two sets of independent trigger controls

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/scopy#14]
Moving this from a list of issues at #9 into its own issue.

Initial issue:
"Having two set of independent trigger controls for channel 1 and channel 2 is confusing. Most scopes have one set of controls and they apply to whichever channel is selected as the source."

**Comment by amiclaus** [comment]
This feature is implemented on 290a894 (v0.8). Therefore, i will close the issue.
