### ISSUE TITLE
Overlapping values in graph when in minimum window size

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#140]
Scopy build :[1839ee5d ](https://github.com/analogdevicesinc/scopy/commit/1839ee5d7a90b30ff9221116ac4fd61f20edc389) OS: Windows ; Firmware: v0.13-dirty

Values in the horizontal axis of the graph overlaps when settings button is clicked and the panel on the right opens. This happens when window is in minimum size. This does not appear when in full screen. The issue is illustrated in the picture below.

![spectrum analyzer ff](https://user-images.githubusercontent.com/25096080/27719588-116e7106-5d86-11e7-8331-269b837e4238.JPG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/86a7d7ee270d49152efddc29f8f0a336202b01f5

**Comment by amiclaus** [comment]
On Scopy build: 152efe0(v0.7) the bug is fixed.
