### ISSUE TITLE
Voltmeter: When the input value is -10V or less, the negative sign will not be visible

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#141]
OS: Windows 7 64bit
 Scopy Version:  1839ee5 
 Firmware Version: v0.13

Open Voltmeter instrument.

1. Connect the positive supply pin to scope ch1- and the negative supply pin to scope ch1+
2. Set the supplies to +5V and -5V, the voltmeter should read a -10V input. The history graph will plot the voltage to -10V but the numerical value won't have the negative sign. 

![vm1a](https://user-images.githubusercontent.com/20266602/27724350-257818be-5da4-11e7-8a76-14951de23b8d.png)

Voltmeter's channel 2 also have the same behavior.

![vm2a](https://user-images.githubusercontent.com/20266602/27724375-433eabec-5da4-11e7-93c6-4604ec2050fe.png)

Turning off the history graph will not make the negative sign visible.

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
