### ISSUE TITLE
Scopy crashes during/after connecting to board

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#143]
Scopy build: [1443eb1b](https://github.com/analogdevicesinc/scopy/commit/1443eb1b3028487bc0128d79bee30709e4033813) ; OS: Windows ; Firmware: v0.13-dirty

Open scopy then select the connected board on the pc and click connect. After few seconds, Scopy crashes.

![s](https://user-images.githubusercontent.com/25096080/27818971-ad1c9988-60ca-11e7-8ace-a1a5e338c605.JPG)

**Comment by pcercuei** [comment]
This is somewhat related to #130. Both issues happen after the dependencies were updated.
This bug happens in the libraries of GNU Radio.

**Comment by pcercuei** [comment]
Fixed in commit 1e648f6.

**Comment by amiclaus** [comment]
On Scopy build: 21bb304 the bug is fixed.
