### ISSUE TITLE
Uninstalling Scopy does not delete the installation folder

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#147]
When uninstalling Scopy, the content of the installation folder is deleted, but the folder itself remains.

**Comment by pcercuei** [comment]
Sorry, I can't reproduce. Uninstalling Scopy does remove the "C:\Program Files\Scopy" folder.

**Comment by amiclaus** [comment]
I'll close the issue since on the latest release the bug is not present.
