### ISSUE TITLE
Logic analyzer - Cannot delete group while disabled

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#150]
Scopy Version: a90e179
Create a DIO group in the Logic Analyzer. Disable the group. The delete button for the group is not clickable.
![capture](https://user-images.githubusercontent.com/26061529/27914467-f1f7404c-626b-11e7-8fc2-492410299913.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 4f5baa99a2fc802d75d29d0e3d4968a0016cb290.

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
