### ISSUE TITLE
Destroying channel group scrolls down automatically the DIO list

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#152]
Scopy Version: a90e179

Open Scopy in minimum window size. Create a channel group in the Pattern Generator instrument. Delete the group. The channel list automatically scrolls down to the last DIOs.

**Comment by adisuciu** [comment]
Fixed with 75f0f81531cbfa4eaad5cb9e618def3f86e0a847

**Comment by amiclaus** [comment]
On Scopy build: f759590 (v0.6) the bug is fixed.
