### ISSUE TITLE
Scopy crashes: right click while drawing a cursor box

### ISSUE THREAD

**Issue by DeflateAwning** [analogdevicesinc/scopy#1522]
**Environment:**
 - OS: Linux Mint 22 (with Wayland)
 - FW Version: unsure; shouldn't matter
 - SW Version: v1.4.1

**Describe the bug**
Right click while drawing a cursor box (using left click to draw the box)

**Expected behavior**
I don't know what I thought would happen, but I don't think it should have crashed haha

**Comment by AlexandraTrifan** [comment]
Hi!

The initial release candidate for the new Scopy v2.0.0 is now available in the official releases page: https://github.com/analogdevicesinc/scopy/releases/tag/v2.0.0-beta-rc1 .

This issue can no longer be reproduced on the new version.

Thank you!
