### ISSUE TITLE
ADALM2000: Crash if "calibration failed" upon first connection

### ISSUE THREAD

**Issue by NoRePercussions** [analogdevicesinc/scopy#1555]
**Environment:**
- OS: Sonoma 14.2.1
- Hardware: M1 Macbook Air
- FW: v0.25
- SW: v1.4.1 (f4beeb1)

**Describe the bug**
When connecting to the ADALM2000, either the status shows "Calibrating" followed by "Calibrated", or it shows "Calibration failed".

If it calibrates successfully:
- Pressing calibration again causes calibration to fail every time, but never crash during this connection.

If it says calibration failed:
- Pressing calibrate crashes Scopy.

I thought this might be an OpenGL problem in #1549, but this seems very consistent.

If Scopy is started some time after the ADALM is connected, it seems to very reliably fail. If the ADALM is connected after Scopy is started, then it seems to calibrate successfully if done in the first few seconds, and then fail afterwards.

Note: the ADALM is on FW 0.25. I couldn't find a mention of this in the changelogs, but I understand that the calibration has changed somewhat since then. I am not in a position to change the firmware of my device.

This is tested without the BNC board connected.

**To Reproduce**
Success case:
1. Open Scopy,
2. Plug in ADALM2000
3. As soon as it shows up, press Connect
4. Calibrate as many times as you want

Failure case:
1. Plug in ADALM2000
2. Wait a while
3. Open Scopy
4. Connect to ADALM2000
5. Either calibration failed, or press disconnect and connect until calibration fails
6. Press Calibrate. App crashes. Crash log is in Additional Context.

**Expected behavior**
For calibration failure to not cause a crash.

**Screenshots**
<img width="380" alt="image" src="https://github.com/analogdevicesinc/scopy/assets/66567994/611ff246-3c28-47a2-9671-68146f4aa843">

**Additional context**

[scopy crash 2024-02-29.txt](https://github.com/analogdevicesinc/scopy/files/14451069/scopy.crash.2024-02-29.txt)

I'm happy to attach session logs, but I can't find them on Mac.

**Comment by adisuciu** [comment]
The problem is related to the firmware version. 
Without testing with a newer firmware version, there is not much that we can do.
