### ISSUE TITLE
Scopy crashes after clicking on Channel Settings in Oscilloscope

### ISSUE THREAD

**Issue by hrayl** [analogdevicesinc/scopy#1568]
**Environment:**
 - OS: Windows 11
 - FW Version: v0.25
 - SW Version or git tag: v1.4.1 - f4beeb1

**Bug Description:**
Scopy crashes whenever I click on the settings icon for CH1 and CH2 in Oscilloscope (sometimes for CH1 and CH2 in Signal Generator too). 

**To Reproduce**
1. Go to 'Oscilloscope'
2. Click on either Channel Settings for CH1 or CH2.
3. Scopy crashes.

**Expected behavior**
Go into the channel settings menu/Programme not crashing.

**Screenshots**
My screen after clicking on CH2 Channel Setting. It just freezes there.
![Screenshot 2024-03-17 152252](https://github.com/analogdevicesinc/scopy/assets/163715058/5a85b38e-c3c5-4881-a220-d47aed8ef1d4)

**Comment by Benlexhi** [comment]
I am having the same issue. Was there any fix?

**Comment by AlexandraTrifan** [comment]
Hi!

The initial release candidate for the new Scopy v2.0.0 is now available in the official releases page: https://github.com/analogdevicesinc/scopy/releases/tag/v2.0.0-beta-rc1 .

Could you give this version a try and reopen the issue if the bug still appears? We ran a test with this version on a Windows 11 and couldn't reproduce it.

Thank you!
