### ISSUE TITLE
Zoom out issue

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#158]
Move the trigger position left or right, zoom in and then zoom out. After zoom out the channels signal is not displayed on the entire plot window. Only if you move again the trigger position the channel signal will be displayed on the plot window.
![zoom_bug](https://user-images.githubusercontent.com/13637543/27949858-f71e82a0-6307-11e7-9b26-2f0f4f77908b.png)
![zoom_bug_2_](https://user-images.githubusercontent.com/13637543/27949980-532eae08-6308-11e7-90e6-44c0ae1f8efb.png)

**Comment by msuciu** [comment]
Bug fixed.

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
