### ISSUE TITLE
Settings button located at the upper right corner negates use of the select button

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#159]
Scopy build: [a90e179](https://github.com/analogdevicesinc/scopy/commit/a90e1793fd2ab7f9d490b170afc27a1ae429e671)
OS: Windows
Firmware: v0.13-dirty

Select cursor settings and open it
Deselect cursor settings. This will close the panel
Click on the settings button located at the upper right corner of the interface. The cursor settings panel will open even if it has been deselected. 

This also happens with the measure settings. It negates the use of the select button. The behavior of the settings button on the upper right corner is that it remembers the last settings used and acts like it.

![bug3](https://user-images.githubusercontent.com/25096080/27950203-fc922aae-6332-11e7-92dd-94bf775b6af0.JPG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/cc1870280c20eb9dd85bfdd0952831f1c1a99851

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
