### ISSUE TITLE
Oscilloscope: A set-trigger-level-to-50% button would be helpful

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/scopy#16]
Moving this from a list of issues at #9 into its own issue.

Initial issue:
"You might consider adding a "set trigger level to 50%" button where the trigger level for the currently selected trigger source is set to mid way between the min and max values of that waveform."

**Comment by rgetz** [comment]
Do we need a 50% button, or an autoset button?

I think autoset would get more use...

-Robin

**Comment by damercer** [comment]
Sometimes ( most times ) an "Auto" set button does more than just adjusting the trigger level so it probably will alter setting that you wanted left untouched. Both kinds would be useful.

**Comment by amiclaus** [comment]
Yes, and also with #161

**Comment by amiclaus** [comment]
On Scopy build: 01d69df (v1.0.1) the feature is implemented.
