### ISSUE TITLE
Display cursor arrea

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#160]
When cursors are enabled I guess it will be a good idea to make the background transparent to see the signal behind, or to have the option to move the cursor window somewhere else in plot.

![ca](https://user-images.githubusercontent.com/13637543/27956595-3f14e160-6323-11e7-91b1-0115e98ca6bc.png)

**Comment by damercer** [comment]
I agree the area around the cursor text should be "transparent" so as not to block the waveforms. 
There could be four options to place the text in any of the four corners of the display, Upper left/right
lower left/right.

Doug

**Comment by DanielGuramulta** [comment]
I've implemented the above enhancement with commit: https://github.com/analogdevicesinc/scopy/commit/2c2c7ff5022a58814aa435887ecae923bbd5a1c3

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the the features are implemented.
