### ISSUE TITLE
Reset Vertical and Horizontal position by double click

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#161]
When you double click on the trigger or channel position, the position should be reset at 0.

![dcc](https://user-images.githubusercontent.com/13637543/27956896-8a356bc8-6324-11e7-8a80-f022da6f6190.png)

**Comment by damercer** [comment]
I like this idea. It would be convenient to have a quick way to reset things to a know state.

Doug

**Comment by AlexandraTrifan** [comment]
This was added with commit cf98b0f71cbe2d53bcaa40c3d76e0cb6a81854c5 .

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the enchancement is implemented.

**Comment by msuciu** [comment]
![horizontal_position](https://user-images.githubusercontent.com/13637543/40298466-e9719a28-5ceb-11e8-944b-ecc4a93a2847.gif)

**Comment by amiclaus** [comment]
It's really strange. This issue is valid only sometimes when Scopy horizontal window size is different than minimum or maximum. It happens both for Oscilloscope and Logic Analyzer

**Comment by amiclaus** [comment]
Update: The issue persists for custom Scopy window size.

**Comment by DanielGuramulta** [comment]
Should be fixed with commit: https://github.com/analogdevicesinc/scopy/commit/1a7674ab612d1733ce9d782087f5f1bd8dd50c67

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
