### ISSUE TITLE
Extend right click option for default zoom

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#163]
If generated waveform is moved on horizontal or on vertical axe or is zoomed in or out is not possible to go on the default zoom only if you zoom in the waveform using left click and than press right click to zoom out on the default zoom. Since is possible to come back on the default zoom using right click when you zoom in using left click, I guess is easy to extend this functionality when you zoom in, zoom out using the mouse scroll or move the waveform using left click.

Also it will be a good idea to limit the horizontal and vertical axe ranges.  

![wg](https://user-images.githubusercontent.com/13637543/27961266-d73b8008-6336-11e7-84a5-1d743cc93967.png)

**Comment by adisuciu** [comment]
This is implemented with the latest signal generator preview rework.f2876e55e1d1ece4a1b2f3d358a623d9a0368e55

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the enchancement is implemented.
