### ISSUE TITLE
Value overlaps unit after turning on history when reading in min window size

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#166]
Scopy build: [a90e179](https://github.com/analogdevicesinc/scopy/commit/a90e1793fd2ab7f9d490b170afc27a1ae429e671)
OS: Windows
Firmware: v0.13-dirty

Steps to reproduce:

Open scopy power supply,then monitor using voltmeter. Set any value on the power supply.

History plot is on, by default.
Turn off history plot.
Then turn it on again.

The value now overlaps the unit. Unlike before doing the steps.The size of the history plot also is now bigger. This only happens when the voltmeter is reading. And also when window size is at minimum.

![bug](https://user-images.githubusercontent.com/25096080/28007831-91bd079c-6587-11e7-8529-177f711aba73.JPG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/2a500d89566c81e2c335e13b1bc9c3443059a1b9

**Comment by amiclaus** [comment]
On Scopy build: 5bb6466 (v0.7) the bug is fixed.
