### ISSUE TITLE
Cannot see cutoff frequency for large sweep range

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#168]
Scopy version: 4b0a59a, OS: Windows 7, Firmware: v0.14

Connect a simple RC HPF (Fc ~ 340Hz) to the Network Analyzer.
Make a sweep between 100Hz-10MHz.

If I want to see the cutoff frequency on the plot in order to compare it with the calculated one, I cannot do this because the step value for the cursor is too large:
![fc](https://user-images.githubusercontent.com/26061529/28020222-39c3eb1e-658c-11e7-8202-9ec81fa0e4e8.png)
The issue regarding the spikes was stated in #167 .

**Comment by rgetz** [comment]
For the computer science folks - can you describe the exact circuit, showing Schematic and implimentation...

Thanks

**Comment by amiclaus** [comment]
Sure: the circuit consists of a a capacitor(C) of 47nF value and resistor(R) of value 10kohm value. The circuit schematic is presented in the figure below, where V1 is the AC voltage source:
![hpf](https://user-images.githubusercontent.com/26061529/28022460-eb848686-6593-11e7-9e55-0eb2f18f211c.png)
The breadboard implementation of this circuit for the network analyzer is the following:
![apn_f3](https://user-images.githubusercontent.com/26061529/28021144-8491cdd4-658f-11e7-99fa-d0020bf6ec0c.png)
The purpose of this circuit is to attenuate the amplitude of the signals that have a frequency less than a specific cutoff frequency that is computed using the following formula: Fc = 1/(2*pi*R*C) = 338Hz (in our case). This cutoff frequency value is considered to correspond to a -3dB attenuation of the signal (where power of the signal drops at half value/ max. amplitude voltage value is ~0.7 of the initial one). Therefore, for the sweep setup mentioned above (100Hz-10MHz) I wanted to see if the cutoff frequency (at -3dB) on the plot corresponds to the calculated value.
The circuit was taken fro the activity lab material.
[Activity, The voltage dependent capacitance of the PN junction](https://wiki.analog.com/university/courses/electronics/electronics-lab-pn-junction-cap)

**Comment by rgetz** [comment]
Thanks

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
