### ISSUE TITLE
Sweep gets stuck. 

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#169]
Scopy version: 4b0a59a, OS: Windows 7, Firmware: v0.14

Connect a simple RC HPF (Fc ~ 340Hz) to the Network Analyzer.
Make a sweep between 100Hz-10MHz.

Sometimes, after repeated runs, the sweep gets stuck and never finishes.
![stuck](https://user-images.githubusercontent.com/26061529/28019615-3734e152-658a-11e7-88db-9294ff5f1ae2.PNG)

**Comment by pcercuei** [comment]
I've been using the network analyzer quite extensively last week, in order to fix #167 and #168, and it never got stuck. Can other people reproduce this issue?

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug does is not available.
