### ISSUE TITLE
Signal Generator: Sine, Triangle and Sawtooth signals are distorted on odd valued frequency

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#170]
OS: Windows 7 64bit
 Scopy Version:  95565b3
 Firmware Version: v0.14

Connect scope ch1+ to AWG ch1 and scope ch- to gnd

1. Set the signal generator's channel 1 to the following configuration:
           Waveform type: Triangle
           Amplitude: 6V - 10V  (it's easier to reproduce on higher voltage)
           Frequency: 100Hz (it's easier to reproduce on lower than 200Hz frequency)
           Offset: 0V
           Phase: 0deg
The signal is still good at this point

![signal gen bug 1](https://user-images.githubusercontent.com/20266602/28057149-d5bac2a2-6651-11e7-98ab-b67f04079790.png)

2. Click the knob on frequency to have an increment of only 1Hz or input 101Hz frequency. The signal will be distorted. sometimes it doesn't work on a single try but try to increment the frequency by 1 and check the oscilloscope on every odd numbered value.

![signal gen bug 1a](https://user-images.githubusercontent.com/20266602/28057271-1674e85e-6652-11e7-9137-b806df0371f0.png)

The same behavior is also present on channel 2. Even in different frequency and waveform type.
![signal gen bug 2a](https://user-images.githubusercontent.com/20266602/28057337-4c421ef2-6652-11e7-89ef-fc0ff6204d39.png)

![signal gen bug 2b](https://user-images.githubusercontent.com/20266602/28057397-7f1793ca-6652-11e7-820a-d4f4540bdf33.png)

**Comment by pcercuei** [comment]
The signal generator switches a lot between the sample rates for the DAC to find the perfect setting.

The problem right now is that we use a single correction factor for the Volts-to-sample conversion, calculated during the calibration. But that correction factor depends on the sample rate, we probably should run the calibration at each sample rate available. I think @dNechita is working on a fix.

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
