### ISSUE TITLE
Add options for Strip Chart

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#172]
I think it will be a good idea to have the possibility to change the displayed range in the Strip Chart and also to have the possibility to add the temperature of the board in chart.

**Comment by rgetz** [comment]
There are lots of things that might be nice. How is this used in a lab by a student?

-Robin

**Comment by msuciu** [comment]
It can see in more detail small voltage variations.

**Comment by rgetz** [comment]
Why not use the oscilloscope? We can't re-create the oscilloscope in the strip chart.

-Robin

**Comment by msuciu** [comment]
Ok, I understand. I was thinking you want to implement same features like a DMM have. You're right, you can do this using the oscilloscope.
