### ISSUE TITLE
Use only one channel for measurements

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#173]
It is possible to disable and hide one channel if is not necessary for some applications? 
Also, is possible to double the sampling rate for the remaining active channel?

**Comment by pcercuei** [comment]
I'd say if you're just interested in one channel, ignore the second one...
About the sampling rate, we already refresh 10 times a second, I think it's more than enough.

**Comment by mbanciso** [comment]
You use the measurements in the oscilloscope if you need different sampling rates.
The voltmeter tool is meant to be simple and resemble the real instrument
