### ISSUE TITLE
Zoom in outside the plot

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#175]
If you zoom outside the plot like in the first picture the signal is not displayed on the entire plot.
![zoom_outside](https://user-images.githubusercontent.com/13637543/28155022-61d7bc90-67b5-11e7-8c0d-b1ca88162937.png)
![zoom in bug](https://user-images.githubusercontent.com/13637543/28155027-652e304a-67b5-11e7-8df3-bf3f56cd8a3f.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/40224da29011096de83497a3d925f678985b1adc

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
