### ISSUE TITLE
Volts/Div reset to 1 after zoom out

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#177]
Connect channel 1 of the Signal Generator on the channel 1 of the Oscilloscope. Generate any signal on channel 1. Go to the Oscilloscope and change the Volts/Div value to any value greater than 1, zoom in and zoom out. The Volts/Div value looks like is reset to 1. A similar thing is happening when the Volts/Div value is changed to any value lower than 1, but the measured signal is limited in amplitude.

Original signal:
![1o](https://user-images.githubusercontent.com/13637543/28160950-679af5ce-67ca-11e7-82ce-e21ce7f5322e.png)

After zoom out when Volts/Div value is greater than 1:
![2o](https://user-images.githubusercontent.com/13637543/28161029-a47369c2-67ca-11e7-8f16-d9f61d617325.png)

After zoom out when Volts/Div value is lower than 1:
![3o](https://user-images.githubusercontent.com/13637543/28161110-ef102984-67ca-11e7-8a80-09efc124a40b.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit:https://github.com/analogdevicesinc/scopy/commit/8159977b625de12d0a54aaaa1f1af8704cec47bf

**Comment by amiclaus** [comment]
On Scopy build: 152efe0(v0.7) the bug is fixed.
