### ISSUE TITLE
Signal Generator interruptions when Oscilloscope is started

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#178]
Generate a signal using the Signal Generator and visualize the generated signal with an external oscilloscope. While the Signal Generator is running start the Scopy Oscilloscope.

![rigol print screen7-13-2017 2_50_35 pm 847](https://user-images.githubusercontent.com/13637543/28165036-b28c8ae2-67da-11e7-9540-ea78c4fd41e6.png)
![rigol print screen7-13-2017 2_51_39 pm 793](https://user-images.githubusercontent.com/13637543/28165060-d0bb48d2-67da-11e7-923e-033cef9a165f.png)

**Comment by damercer** [comment]
Glitch seems to be small and probably a non-issue when user is only using M2K to do their experiments / lab measurements. Can sort of expect short interruptions when the software makes changes to what the board is doing.

Doug

**Comment by pcercuei** [comment]
That's not a software issue, the signal generator just pushes a cyclic IIO buffer then idles. Probably a DMA issue then.

**Comment by lclausen-adi** [comment]
@msuciu can you share the pattern generator and scope configuration under which this issue was observed.

**Comment by msuciu** [comment]
Sure. Keep running the Scopy Signal Generator and connect an external oscilloscope on one of the channels. If you are using build 3aae9de use channel 1 because channels 2 is not working for some reason. Then press the play button on the Scopy Oscilloscope. When you do this observe on the external oscilloscope the issue described above. The configuration looks like is not important. I hope this helps. 
![b1](https://user-images.githubusercontent.com/13637543/28523741-6c6304f6-7086-11e7-9edc-d8b61842e82e.png)
![image](https://user-images.githubusercontent.com/13637543/28523850-c04bd322-7086-11e7-8c91-d57a95d39fca.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/issues/316 addresses this issue.
