### ISSUE TITLE
Increment or decrement using selected frequency measurement unit

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#179]
When you try to increment or decrement any parameter on the "Sweep" menu from the Spectrum Analyzer using selected frequency measurement unit doesn't work for "Hz" or "kHz", only for "MHz".

**Comment by adisuciu** [comment]
With commit: [b247736](https://github.com/analogdevicesinc/scopy/commit/b2477368bebdd642b4eaea76bb72a31b2fc039a4) the issue is fixed.

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
