### ISSUE TITLE
Signal Generator: Waveform's amplitude is not stable on lower frequency

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#180]
OS: Windows 7 64bit
Scopy Version:  b210916
Firmware Version: v0.14

      1.	Connect M2K to scopy.
      2.	Connect scope ch1+ to AWG ch1 and scope ch- to gnd.
      3.	Open signal generator instrument and set it to the following setting:
                  a.	Amplitude: 6V
                  b.   Frequency: 1kHz
                  c.	Offset: 0V
                  d.   Phase: 0degrees
      4.	Run signal generator and oscilloscope
      5.	The parameter reading in the oscilloscope is correct here.
                    
![signal gen bug 4a](https://user-images.githubusercontent.com/20266602/28194747-ebc7e1f0-6878-11e7-9752-55e8056a7f08.png)

      6.	Change the frequency to 100Hz
      7.	The parameter reading in the oscilloscope will be wrong.

![signal gen bug 4b](https://user-images.githubusercontent.com/20266602/28194750-efe333b6-6878-11e7-8bc3-82bf3fa33da0.png)

This behavior is present on the different waveforms. 
I tried looking at these waveforms on an external oscilloscope to make sure that the one with problem is the signal generator.
There are frequencies between 100Hz to 999Hz showing unstable amplitude.

**Comment by damercer** [comment]
I added a comment similar to this to issue #170 

Doug

**Comment by pcercuei** [comment]
I'll close this bug as it's a dup of #170. We can continue the discussion there.
