### ISSUE TITLE
Signal Generator: Constant voltage, value mismatch on numerical and graphical

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#182]
OS: Windows 7 64bit
 Scopy Version:  b210916 
 Firmware Version: v0.14

Connect scope ch1+ to AWG ch1 and scope ch1- to gnd.
Connect scope ch2+ to AWG ch2 and scope ch2- to gnd.

1. Open signal generator instrument.
2. Set channel 1 on Constant voltage and channel 2 on waveform (My setting 5V amplitude, frequency: 5kHz, offset: 0V and phase: 0 degree). [it's easier to reproduce this way]
3. Run signal generator instrument.
4. on channel 1. change the voltage value from -5V to 5V or 5V to -5V by holding the arrow button. repeat it until the bug is reproduced.

![signal gen bug 6](https://user-images.githubusercontent.com/20266602/28199943-c96df5ea-689b-11e7-8d8c-83828f57d108.png)

I also observed that the bug is easier to reproduce when the voltmeter instrument is already running while performing step 4.

![signal gen bug 6b](https://user-images.githubusercontent.com/20266602/28200201-29443686-689d-11e7-9cbe-9272835ecf6f.png)

I'm also not sure whether the value is set to 4V or 5V because of bug #181 where the instrument can't generate a signal to 5V or -5V.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
