### ISSUE TITLE
Horizontal cursor lines are hidden by the plot

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#183]
On the oscilloscope when you enable cursors and you move channel 2 vertical position outside the plot the vertical cursor lines are hidden by the plot. They are comeback in front of the plot only if you move the horizontal position.
![c1](https://user-images.githubusercontent.com/13637543/28204375-607d5bb2-6886-11e7-90dc-fa99da6d8815.png)
![c2](https://user-images.githubusercontent.com/13637543/28204380-6461e1a8-6886-11e7-8d69-9336c25ac16c.png)

**Comment by msuciu** [comment]
To be more specific, this bug is "activated" when Volts/Div value for channel 2 is changed.

**Comment by msuciu** [comment]
Also, if you increase the time base at maximum the vertical cursor line length is changed depending on channel 2 vertical position.
![c1](https://user-images.githubusercontent.com/13637543/28205985-f5c37d2c-688c-11e7-8a2c-1b9995b1c22a.png)
![c2](https://user-images.githubusercontent.com/13637543/28205989-f8961c8a-688c-11e7-9786-f1b48a35d0d8.png)

**Comment by rgetz** [comment]
Just to be clear - the measurement/cursor lines should be "behind" the waveform plots. (The cursors shouldn't obscure the voltage lines from either channel) - but they shouldn't dissapear either. 

They should move with the voltage scale. For example -  A voltage cursor on channel 1, if you change the channel 1 voltage scale - the positions of the cursors on the screen will change (and may even move off the screen, to the top or bottom), but should keep the same voltage position. 

Measuring on the time axis should do the same. It should track the seconds offset, not the relative position on the screen; and be between the grid (on the bottom), and the voltage plot (on the top).

**Comment by mbanciso** [comment]
I looked at 2 brands of bench scopes and the cursors are fixed to the screen. 
They don't change with time base or v/div

**Comment by dNechita** [comment]
Fixed in commit https://github.com/analogdevicesinc/scopy/commit/3eb261041d9d863203de5af4adc42bde6cb769c1

**Comment by msuciu** [comment]
I confirm this fix after testing with Scopy 3eb2610.

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
