### ISSUE TITLE
Switching between channels menu interrupt the generated signals

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#184]
When you switch between channels menu the generated signals are interrupted. It is normal when you change the configuration for any channel, but it's not ok when the configuration is the same.

![rigol print screen7-14-2017 5_18_44 pm 369](https://user-images.githubusercontent.com/13637543/28216192-66b92294-68b9-11e7-9d38-8fea67bff9d3.png)

**Comment by rgetz** [comment]
Does it make a difference on the sample rate of the generated signal?

It looks like that is a super slow signal...

**Comment by msuciu** [comment]
Yes, depending on the sample rate this interruptions take a different amount of time. Below you can see how much time takes this interruptions for a generated signal of 1 Hz, 1kHz and 1 MHz when I switch between channels menu.
![rigol print screen7-17-2017 10_14_01 am 791](https://user-images.githubusercontent.com/13637543/28258388-ade3a5a0-6ad9-11e7-9be6-1433f3ea8df6.png)
![rigol print screen7-17-2017 10_15_36 am 172](https://user-images.githubusercontent.com/13637543/28258392-b1cdb138-6ad9-11e7-8946-9bcb6b8e0543.png)
![rigol print screen7-17-2017 10_16_35 am 172](https://user-images.githubusercontent.com/13637543/28258393-b3e07c80-6ad9-11e7-9d6f-3595e7f5d8ae.png)

**Comment by msuciu** [comment]
I confirm this fix after testing with Scopy 3eb2610.

**Comment by amiclaus** [comment]
On Scopy build: f759590 (v0.6) the bug is fixed.
