### ISSUE TITLE
Signal Generator: Square and Triangle waveform distorted on high phase shift value

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#185]
OS: Windows 7 64bit
 Scopy Version:  b210916 
 Firmware Version: v0.14

Connect scope ch1+ to AWG ch1 and scope ch1- to gnd.

Square Wave:
1.Open signal generator instrument.
2.Set channel 1 on Waveform mode and apply the following setting: Waveform type: Square wave, Amplitude: 2V, Frequency: 20kHz, Offset 0V and Phase: 200 degrees.
3. For the oscilloscope, apply the following setting on channel 1: Time Base: 20us, Volts/Div: 1V/Div and trigger: auto.
4.Run signal generator and oscilloscope instrument.

![square wave distorion 200 deg phase](https://user-images.githubusercontent.com/20266602/28256981-d4b99868-6af9-11e7-8596-4575acb71f1c.png)

It is seen in the Signal generator window that the signal already has an error. In the oscilloscope, it shows that it's effecting the actual signal output of the Signal generator.

This distortion gets worse going to 360 degrees phase shift.

![square wave distorion 360 deg phase](https://user-images.githubusercontent.com/20266602/28257037-45af342e-6afa-11e7-9973-14dc24814252.png)

--------------------------------
Triangle Wave
1.Open signal generator instrument.
2.Set channel 1 on Waveform mode and apply the following setting: Waveform type: Triangle wave, Amplitude: 2V, Frequency: 10kHz, Offset 0V and Phase: 271 degrees.
3. For the oscilloscope, apply the following setting on channel 1: Time Base: 20us, Volts/Div: 1V/Div and trigger: auto.
4.Run signal generator and oscilloscope instrument.

![triangle wave distorion 271 deg phase](https://user-images.githubusercontent.com/20266602/28257053-711f763c-6afa-11e7-8e1a-56aa16ce926e.png)

It is seen in the Signal generator window that the signal already has an error. In the oscilloscope, it shows that it's effecting the actual signal output of the Signal generator.

This distortion gets worse going to 360 degrees phase shift.

![triangle wave distorion 360 deg phase](https://user-images.githubusercontent.com/20266602/28257078-9c2f3a92-6afa-11e7-8e63-5b8b5a6b3f46.png)

Same behavior is found on different amplitudes and frequencies.
Same behavior is seen in the channel 2 of the signal generator.

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
