### ISSUE TITLE
Signal Generator: Channel 2's color indicator for configuration menu is similar with channel 1's

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#188]
OS: Windows 7 64bit
 Scopy Version:  3eb2610
 Firmware Version: v0.14

The color indicator for channel 2's configuration is similar with channel 1 which is orange.
I think it would be good if the color is similar to the waveform and the on/off button for channel 2 to avoid confusion.

![signal gen enhancement](https://user-images.githubusercontent.com/20266602/28297495-d9af83f8-6ba0-11e7-9916-8355f2760065.png)

**Comment by dNechita** [comment]
This is a duplicate of #10

**Comment by pcercuei** [comment]
The tabs are underlined with orange in the theme, independently of the colors of the channels. Maybe we should change that to the same blue we use everywhere.

**Comment by DanielGuramulta** [comment]
Fixed with commit: 6fd7ece

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
