### ISSUE TITLE
Amplitude and Scale knobs not showing up (or cropped) in the menu

### ISSUE THREAD

**Issue by wkester** [analogdevicesinc/scopy#19]
The time/division and amplitude/division "knobs" do not show up in the box on the right.

**Comment by rgetz** [comment]
I think it is poor form, to close an issue without making a comment on why it was closed. 

was this an issue that was fixed?

**Comment by dNechita** [comment]
@DanielGuramulta Please try to reproduce using different resolutions.

**Comment by DanielGuramulta** [comment]
I tried to reproduce this issue, on Windows and Scopy version b846ab74 using different resolutions and I have encountered problems only when setting the resolution to 800x600 which is way lower than the minimun resolution that Scopy should be used(1280x720).

**Comment by AlexandraTrifan** [comment]
I think this is not applicable anymore.
