### ISSUE TITLE
Network analyzer sweep speed?

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#194]
Scopy version 3aae9de with firmware 0.14.
Why does the network analyzer sweep so slowly? I timed a sweep from 100 Hz to 25 KHz and 200 steps. It took 2 min. 28 sec to run. I timed the same sweep with M1K at 15 seconds. More than 5 times faster. The current sweep speed is painfully slow???

Doug

**Comment by DanielGuramulta** [comment]
With pr: #571 the Network Analyzer should run faster. I timed a sweep from 100Hz to 25KHz with 200steps and it took around 23 seconds.

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the NA sweep speed is improved consistently.
