### ISSUE TITLE
Coarse fine range is not limitated at 20 MHz

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#197]
When coarse fine is enabled the frequency of the generated signal can be set more than 20 MHz, up to 31 MHz when the application crash in my case at least.
![b2](https://user-images.githubusercontent.com/13637543/28525010-6edb855a-708b-11e7-931f-c105184dc147.png)

**Comment by adisuciu** [comment]
Fixed with Fixed with dd0a1a8

**Comment by amiclaus** [comment]
On Scopy build: dd0a1a8 (v0.6) the bug is fixed.
