### ISSUE TITLE
In WG, putting a large freq in KHz then selecting MHz is causing a crash. 

### ISSUE THREAD

**Issue by CElkhoury** [analogdevicesinc/scopy#198]
Hi guys,
When I was playing with the waveform generator, I put 500KHz, but I decided to jump to Mhz but didn't lower the freq. That caused the software to crash. 
It did correct the freq down to 37.5MHz but it was too late.
Charly

**Comment by adisuciu** [comment]
Fixed with dd0a1a8

**Comment by amiclaus** [comment]
On Scopy build: dd0a1a8 (v0.6) the bug is fixed.
