### ISSUE TITLE
In the Osc, the Volts per division number currently just says a number  in Volts without per div.

### ISSUE THREAD

**Issue by CElkhoury** [analogdevicesinc/scopy#199]
In the Oscilloscope, please add to the number "V/div" to be more clear for the users.
Thanks
Charly

**Comment by DanielGuramulta** [comment]
Added the enhancement with commit: https://github.com/analogdevicesinc/scopy/commit/a36d98e84d9135197a0af3e5b4b9b15102793843

**Comment by amiclaus** [comment]
On Scopy build: f759590 (v0.6) the bug is fixed.
