### ISSUE TITLE
Default Trigger Settings

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#2]
As it now stands the initial Trigger state does not produce stable triggering.  Adding about 100 mV of hysteresis produces stable triggering.  The initial Trigger state should produce stable triggering for the majority of input signals so the user does not have to access the advanced triggering functions when first setting up the scope for basic operation.

**Comment by dNechita** [comment]
Marking this as an enhancement for the Oscilloscope instrument.
I believe there are some techniques that can reduce the instability. We should discuss about how we can solve this issue.

**Comment by adisuciu** [comment]
Oscilloscope hysteresis triggering was implemented with commit f1264ecb05139217f5ed21a557b2cda6fc28789d

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the enchancement is implemented.
