### ISSUE TITLE
Zooming not working properly on Signal Generator

### ISSUE THREAD

**Issue by wkester** [analogdevicesinc/scopy#20]
Clicking around on the vertical or horizontal axis sometimes makes the waveform disappear. 
Would it make sense to put in a "reset" button to restore to the default settings?

**Comment by rgetz** [comment]
I see this on the signal generator.

double click in the graph would be a convenient way to autoscale.

![image](https://cloud.githubusercontent.com/assets/1017869/23867552/9f4e6218-07f2-11e7-87fb-0c8fd6bb01ca.png)

I do get this quite often:

![image](https://cloud.githubusercontent.com/assets/1017869/23867608/d30ef75c-07f2-11e7-9aab-0fa2ae7ebc0c.png)

If you want to plot out to 5 seconds - that's fine, but then there should be data...

**Comment by rgetz** [comment]
You should see at least two periods.

**Comment by dNechita** [comment]
Fixed in https://github.com/analogdevicesinc/scopy/commit/d42f260809a169998dd5fb0cc0fe78702caff237
A right click brings you to the default zoom (acts as a reset).

**Comment by rgetz** [comment]
How do you right click on a touch screen?

Does pinch work?

**Comment by dNechita** [comment]
The right click functionality is something that came with the plot widget that we're using. We didn't start adapting this functionality (or others) to work on touch screens yet.

**Comment by adisuciu** [comment]
The zooming/preview system was reworked with f2876e55e1d1ece4a1b2f3d358a623d9a0368e55 and f3e3f436ce07e6fc18038d2370f5f0a8163951df . The signal will always display 2 periods of the slowest waveform.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
