### ISSUE TITLE
Hysteresis Trigger Negative Values

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#201]
Scopy version: f759590

In the trigger settings panel the user is able to set negative values for the Hysteresis trigger.

![capture](https://user-images.githubusercontent.com/26061529/28578516-a91b26c6-7162-11e7-9ed2-a480806ab572.PNG)

Is this an issue? (I'm not 100% sure).

**Comment by dNechita** [comment]
Yes it is. Negative values should not be accepted.
Fixed with: https://github.com/analogdevicesinc/scopy/commit/c27d74917b16e3999f0dd0d89fe5dd3682234019

@lclausen-adi 
It would make sense for the linux driver to not accept negative values as well.

**Comment by amiclaus** [comment]
On Scopy build: 5bb6466 (v0.7) the bug is fixed.
