### ISSUE TITLE
Scopy crashes when destroying math channel

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#202]
Scopy version: f759590

Create new math channel. Hide channel 1 and channel 2. Delete math channel.

Scopy crashes.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/56c36ee142d41c33dfc09b3a0876d6594f1e723d

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
