### ISSUE TITLE
Inappropriate display of the signal amplitude

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#204]
Scopy version: dd0a1a8

When going through MHz frequencies the amplitude of the the signal displayed on the plot does not correspond to the set amplitude.

![capture](https://user-images.githubusercontent.com/26061529/28657850-81e44d58-72b1-11e7-9c07-54469840e139.PNG)

**Comment by adisuciu** [comment]
This issue is related to how the samples are generated at high frequencies. There is not much we can do to prevent this. We need to define limits for each waveform so that they are generated with minimal distortions.

**Comment by rgetz** [comment]
I'm not sure what you mean.

if someone says 10Vp-p, then that is what should come out the pins. We don't spec how good the signal will look (distortions/harmonics/etc). Other equipment does the same. The only thing that is accurate is the p-p output value.

-Robin

**Comment by adisuciu** [comment]
This was fixed with f3e3f436ce07e6fc18038d2370f5f0a8163951df and f2876e55e1d1ece4a1b2f3d358a623d9a0368e55. The preview will display the ideal waveform.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
