### ISSUE TITLE
Switching connection via usb to ip/ip to usb crashes scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#206]
scopy build: [dd0a1a8](https://github.com/analogdevicesinc/scopy/commit/dd0a1a82cbb3bf56649dedb1fa144af51680c2d9)

Steps to reproduce:

Connect device first via usb. Disconnect device then connect via ip by add button. Scopy will then crash after few seconds. This also happens vice versa,  from ip then switch to usb.
![aa](https://user-images.githubusercontent.com/25096080/28659822-5567bc60-72e3-11e7-8801-2709d756612a.JPG)

**Comment by DanielGuramulta** [comment]
Solved with commit: https://github.com/analogdevicesinc/scopy/commit/8406b3043e72ebd5755094674c4a57aa839a565a

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
