### ISSUE TITLE
Plus button doesn't increase frequency until 37.5MHz, stuck at 20MHz  

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#207]
Scopy build: [8406b304](https://github.com/analogdevicesinc/scopy/commit/8406b3043e72ebd5755094674c4a57aa839a565a)

Steps to reproduce:

Set frequency knob without orange dot in the center, large interval. 

Click on plus sign until 20 MHz. Once in 20 MHz, try clicking the plus button, it will respond.

Set the frequency value to 50 MHz, the value will then set to the max possible frequency which is 37.5 MHz.

Click on the plus button again, the frequency value will decrease to 20 MHz instead of staying at 37.5 MHz.

![capture](https://user-images.githubusercontent.com/25096080/28708319-6b4b45f8-73ae-11e7-86cd-591f06cd94c6.JPG)

**Comment by adisuciu** [comment]
Fixed with 9f2f0b1

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
