### ISSUE TITLE
Logic Analyzer: Signal plot may be moved not in sync with the channel manager

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#210]
OS: Windows 7 64bit
 Scopy Version:  fc64aff
 Firmware Version: v0.14

Open the logic analyzer instrument.

1. Click on the signal plot area.

![logic analyzer screen 1](https://user-images.githubusercontent.com/20266602/28765950-da4f0d24-75ff-11e7-83c4-2b795bfe9bec.png)

2. The signal plots may be moved using the up and down arrow key from your keyboard but the channel manager won't move, leaving it behind.

![logic analyzer screen 2](https://user-images.githubusercontent.com/20266602/28766053-50a0bbd0-7600-11e7-86a8-cef5adb677dd.png)

*clicking on the channel manager area and clicking the up and down arrow key from the keyboard will move both the channels and signal plot in sync with each other.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 131e57e3883083403ac4618ebc60257a6ff72018.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
