### ISSUE TITLE
Phase returns to 0 after selecting other channel

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#211]
Scopy build: [8406b304](https://github.com/analogdevicesinc/scopy/commit/8406b3043e72ebd5755094674c4a57aa839a565al)

Steps to reproduce:

Enable DIO0. Change phase to any value i.e. 45 deg. Then use the left/right arrows to select other channel or juct click to other channel.

Return back to DIO0, the phase that we set previously as 45 deg has now returned back to 0. But the display/trace stays the same, showing the shift. 

![bug](https://user-images.githubusercontent.com/25096080/28767618-f6295318-7606-11e7-9f53-5018f6937140.JPG)

**Comment by adisuciu** [comment]
Fixed with 47b6899

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
