### ISSUE TITLE
Logic Analyzer: Groups can't be deleted when the pin members are hidden

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#213]
OS: Windows 7 64bit
 Scopy Version:  21cb436
 Firmware Version: v0.14

1. Group any pins and hide the pins. see picture for reference.

![logic analyzer deleting channels](https://user-images.githubusercontent.com/20266602/28864262-870c3c68-779e-11e7-95f9-c904b2e9561b.png)

2. The group in this state cannot be deleted

**Comment by AlexandraTrifan** [comment]
Fixed with commit 44c11e090d70641ff7e9b101f6e9836e68436614.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
