### ISSUE TITLE
Dragging out DigitalIO resizes inaccurately the window.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#215]
Scopy version: 9f20b1

Drag DigitalIO out.
Initially, the instrument window looks like this:
![capture1](https://user-images.githubusercontent.com/26061529/28865479-c325983c-7778-11e7-9eca-a818b7aaae18.PNG)
P.S. try several times the drag/drop if needed.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/fcfee39b3447fc607564a350b2296f121047038a

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
