### ISSUE TITLE
Choosing black as Edge, low and high color doesn't show black

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#216]
scopy build: [caf075e3](https://github.com/analogdevicesinc/scopy/commit/caf075e389be1320eba48722393f7a89eb949dd1)

Choosing black as Edge, low and high color doesn't show black. Instead the default colors are displayed. This happens on all channels. All other colors work except for black.

![aaaa](https://user-images.githubusercontent.com/25096080/28911100-fec18d8a-7861-11e7-9d05-27fb480fb776.JPG)

**Comment by AlexandraTrifan** [comment]
I think we can replace this color anyway, since it is not visible on the current color configuration.

**Comment by AlexandraTrifan** [comment]
The color was replaced with a color from the mockup.
Fixed with commit a5819c51e193e9a37fc4f3cada4a569de1ee70b1.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
