### ISSUE TITLE
Phase widget increment inconsistent

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#217]
scopy build: [bc312ffa](https://github.com/analogdevicesinc/scopy/commit/bc312ffa0218c28fac664a1c2375bf4ce0e53adf)

Steps to reproduce:
Set phase knob with orange dot in the center, ±1° interval.
Click on + button.
The result would be:
       0,2,3,5,6,8,9,11.. and so on.
Sometimes its 1° interval then sometimes its  2°. It's not consistent with the ±1° interval. It doesn't happen with the - button, only with the + button.

**Comment by adisuciu** [comment]
Fixed with 8f49b9581ff653dac698b3cae1108e08ec312867

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
