### ISSUE TITLE
Channel manager appears cut on right side when SPI protocol is selected

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#218]
Scopy build: [bc312ffa](https://github.com/analogdevicesinc/scopy/commit/bc312ffa0218c28fac664a1c2375bf4ce0e53adf)

Steps to reproduce:
On current channel manager, change pattern to SPI.
 The channel manager now appears cut on right side when SPI protocol is selected even in full screen.
The picture below shows the issue.

![z](https://user-images.githubusercontent.com/25096080/28959031-4e3374cc-792b-11e7-960f-61264c593be2.JPG)

**Comment by adisuciu** [comment]
Fixed with 6b9d280693e981041a31903294a721e316021707

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
