### ISSUE TITLE
Logic Analyzer: External trigger won't automatically turn off when activating any DIO channel's trigger within a group

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#220]
OS: Windows 7 64bit
 Scopy Version:  454babc 
 Firmware Version: v0.14

Open Logic Analyzer instrument

1. Activate External Trigger from the Trigger settings
2. Group any DIO channels
3. Activate a trigger from any DIO channel within the group.
4. The external trigger won't automatically turn off.
![external trigger setting behavior](https://user-images.githubusercontent.com/20266602/29018344-52e7d5b2-7b8d-11e7-8d98-7f0dcb708e9e.png)

*Activating a trigger of any DIO channel outside the group will automatically turn off the external trigger function.
*Turning on the external trigger function will automatically turn off the triggers within and outside DIO channel groups.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 44417160818dc9f94b056e7ff95f5ac80d6873c2.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
