### ISSUE TITLE
Changing background color doesn't appear to be changed totally

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#221]
scopy build: [a5819c51](https://github.com/analogdevicesinc/scopy/commit/a5819c51e193e9a37fc4f3cada4a569de1ee70b1)

Changing background color doesn't appear to be changed totally. The selected color is transparent such that black is still visible and the selected background color doesn't appear as expected but I'm not totally sure how this is supposed to be implemented. Also in the new update regarding the black color, for the background color the only way to get back to black background is to reset instrument. 

![bbb](https://user-images.githubusercontent.com/25096080/29059517-7e65ba90-7c48-11e7-98a9-bcce72c4cad5.JPG)

**Comment by AlexandraTrifan** [comment]
Commit b9089cf128873bd54a85b86d132e7ce801342651 introduces a fix for the issue with the black background color. Black is kept as an option for background colors, while another color is used as an option for 'edge', 'high' and 'low'.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
