### ISSUE TITLE
Adjusting time base crashes Scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#222]
scopy build: [a5819c51](https://github.com/analogdevicesinc/scopy/commit/a5819c51e193e9a37fc4f3cada4a569de1ee70b1)
Steps to reproduce:

Create group of 3- channels in pattern generator and change pattern to binary counter.
Monitor in logic analyzer. Create 3-channel group. Parallel as decoder. 
Run both instruments. 
In logic analyzer, adjust time base. Click '-' few times. After few seconds, scopy crashes.

![dfdhgj](https://user-images.githubusercontent.com/25096080/29060991-9b235c04-7c4e-11e7-85da-45e813350e1f.JPG)

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
