### ISSUE TITLE
Logic Analyzer: Locked cursor mode not in sync with the signal plot

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#225]
OS: Windows 7 64bit
 Scopy Version:  d6f5253 
Firmware Version: v0.14

1. Open Pattern Generator Instrument.
2. Enable DIO0 and set as pattern: Clock, Frequency: 100Hz and phase degrees: 50% [any setup will do] and run the instrument.
3. Open Logic Analyzer, enable DIO0 and set the time base to 5ms, enable cursor and measure the signal's frequency. The cursor's measured value is quite accurate.

![1](https://user-images.githubusercontent.com/20266602/29157943-8db018f8-7ddb-11e7-934c-5ce3cd5be875.png)

4. Enable the lock function and try to move the cursor.

![2](https://user-images.githubusercontent.com/20266602/29158144-7dbf7dd4-7ddc-11e7-9185-f4facafc1b8d.png)

5. The cursor's reading is still the same, but the visual representation changed and not in sync with the signal plot.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 01dd5d00fad03eef00e77190d4a7f9b8d67b3a75.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
