### ISSUE TITLE
Adding Lines/Points option for XY feature

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#226]
Currently, the graph for the XY feature is represented using only points:

![xy-dots](https://user-images.githubusercontent.com/26061529/29210165-ca395b26-7e9a-11e7-954d-92fff2c8f1c3.PNG)

Is it relevant to introduce the Lines/Points option for this feature? Similar to the ADI IIO Oscilloscope.

![linesvpoints](https://user-images.githubusercontent.com/26061529/29210210-124586d8-7e9b-11e7-8efe-8f6706f3b391.png)

**Comment by damercer** [comment]
Lines. Connecting the sample points should always default to lines.

Doug

**Comment by dNechita** [comment]
With this commit https://github.com/analogdevicesinc/scopy/commit/bd7546d592fb2cce376f5c156150fe9ddd90c916 the XY plot defaults to displaying lines but there is also an option to switch to points.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
