### ISSUE TITLE
Logic Analyzer: Scopy crashes when exporting csv file format

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#227]
OS: Windows 7 64bit
 Scopy Version:  b241b20
 Firmware Version: v0.14

1. Open pattern generator and generate different signals on each channel. 
2. Open Logic Analyzer instrument and run both pattern generator and logic analyzer.
3. Click the export function and save as csv format.

![1csv](https://user-images.githubusercontent.com/20266602/29400175-d74c3eaa-835e-11e7-83fe-856f4e29bbc6.png)

4. After clicking save and confirm on the default option. Scopy will crash.

![error](https://user-images.githubusercontent.com/20266602/29400201-f70437ac-835e-11e7-8686-3bb05ae1f314.png)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 9487204b3ec2d8a84336f58795565d2fd4d05965.

**Comment by amiclaus** [comment]
On Scopy build: 49a4f93 (v0.7) the bug is fixed.
