### ISSUE TITLE
Changing Sampling Frequecy affects XY Plot

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#229]
Modifying the time base which determines a change of sampling frequency will affect the XY representation:
![cap1](https://user-images.githubusercontent.com/26061529/29452126-dd708ad4-840d-11e7-8e42-a871de6bcc72.PNG)
![cap2](https://user-images.githubusercontent.com/26061529/29452125-dd704628-840d-11e7-94f4-858de8c80aac.PNG)
![diff](https://user-images.githubusercontent.com/26061529/29452127-dd7234ce-840d-11e7-9c0b-3189386946ef.png)

**Comment by adisuciu** [comment]
This is expecteed behavior.
