### ISSUE TITLE
Update linux drivers for axi_adc_decimation to include scale correction

### ISSUE THREAD

**Issue by acostina** [analogdevicesinc/scopy#230]
Moved adc decimation scale correction from the AD9963 IP to the decimation IP in HDL. The correction is done at the end of the decimation chain.

Register map at:
https://wiki.analog.com/resources/fpga/docs/axi_adc_decimate#register_map
Registers of interest 0x48, 0x4c 0x50

**Comment by lclausen-adi** [comment]
Added in https://github.com/analogdevicesinc/linux/commit/4b5da0cdc03c8cece86e818672b137fe3bcdb897

Driver interface stays the same as with the old calibscale attributes.
