### ISSUE TITLE
Update linux drivers for axi_dac_interpolate to include scale correction

### ISSUE THREAD

**Issue by acostina** [analogdevicesinc/scopy#231]
Moved dac interpolation scale correction from the AD9963 IP to the interpolation IP in HDL. The correction is done at the beginning of the interpolation chain.

Register map at:
https://wiki.analog.com/resources/fpga/docs/axi_dac_interpolate#register_map
Registers of interest 0x54, 0x58 0x5c

**Comment by lclausen-adi** [comment]
Added in https://github.com/analogdevicesinc/linux/commit/98d651486c138a2317cfc2f6f28f27f17e23774c
