### ISSUE TITLE
Update linux drivers for triggering to support triggered bit (both analog and digital path)

### ISSUE THREAD

**Issue by acostina** [analogdevicesinc/scopy#232]
This register is set when triggering occurs and is reset by writing 1 to clear. If there is a large delay between the time of the trigger and the display of the data. This should notify the user data is in the acquisition stage.

https://wiki.analog.com/resources/fpga/docs/axi_adc_trigger#register_map 
register 0x3c

https://wiki.analog.com/resources/fpga/docs/axi_logic_analyzer#register_map
register 0x48

**Comment by lclausen-adi** [comment]
Added in https://github.com/analogdevicesinc/linux/commit/f173c38b9cd2dbe0ba27f9fadda40f6007e9ff4e and https://github.com/analogdevicesinc/linux/commit/3f3bb29d0d98e6d70ba4717ad56b7d33503eb1c4
