### ISSUE TITLE
Update linux drivers for triggering to support streaming bit (both analog and digital path)

### ISSUE THREAD

**Issue by acostina** [analogdevicesinc/scopy#233]
The streaming bit allows for capturing successive buffers without data loss. The first buffer starts when the triggering condition has occurred. 

https://wiki.analog.com/resources/fpga/docs/axi_adc_trigger#register_map
register 0x44

https://wiki.analog.com/resources/fpga/docs/axi_logic_analyzer#register_map
0x4c

**Comment by lclausen-adi** [comment]
Added inhttps://github.com/analogdevicesinc/linux/commit/92707537105b2efb6553d19118dbbdefa1d0ff6c and https://github.com/analogdevicesinc/linux/commit/0b7b29b4dcb261d122cd6e70717ae5d0ba056386
