### ISSUE TITLE
Logic Analyzer: Toggling the Trigger Mode without Stopping the instrument makes the triggering unstable

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#235]
OS: Windows 7 64bit
 Scopy Version:  d0f3ca5
 Firmware Version: v0.14

A. From Normal Mode to Auto Mode
      1. Open Digital IO instrument and set DIO0 to output and logic 0.
      2. Open Pattern Generator, Disable Digital DIO0 and set the rest of channels to any signal.
      3. Open Logic Analyzer, set DIO0's trigger to rising edge toggle the trigger mode to normal.
      4. Run the three instruments. Try to trigger DIO0 on normal mode to see if the logic analyzer is working.
      5. Toggle the Trigger mode to Auto. Auto mode should automatically capture signals even when there's no trigger event, but this time it won't capture data.
![auto trigger 1](https://user-images.githubusercontent.com/20266602/29652936-5e4db944-88da-11e7-9f9a-bfc5f120a57e.png)
      6. It will continuously start capturing data by activating a trigger once.

B. From Auto Mode to Normal Mode
      1. Open Digital IO instrument and set DIO0 to output and logic 0.
      2. Open Pattern Generator, Disable Digital DIO0 and set the rest of channels to any signal.
      3. Open Logic Analyzer, set DIO0's trigger to rising edge, toggle the trigger mode to auto.
      4. Run the three instruments, Logic analyzer should start capturing in auto mode. 
      5. Toggle the trigger mode to Normal mode. the capturing should stop because DIO0's trigger is set to rising edge, but the Logic Analyzer continuously captures data.
![auto trigger 2](https://user-images.githubusercontent.com/20266602/29653334-efbe361e-88db-11e7-900a-e72aff5576c5.png)
      6. The only way to make the instrument start waiting for the trigger again is by changing the trigger option of DIO0 or by toggling to auto mode, then stop the instrument and toggle to back to normal mode before starting the instrument again.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 55c6e7cafde50426d866f6ae7fb7ea70caf015a6.

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
