### ISSUE TITLE
Incorrect Initial channel state 

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#236]
Scopy version: be46948

Delete Scopy.ini file. Open DigitalIO Instrument. The channel state is set to low while all channels are set as input.
![capture](https://user-images.githubusercontent.com/26061529/29810779-e052d2da-8ca9-11e7-9b00-802f21b42eaa.PNG)

By changing the type of the channel(in/out) or run the instrument, all the channels are refreshed and set to high.
![capture1](https://user-images.githubusercontent.com/26061529/29810784-e4e539b4-8ca9-11e7-8a21-393ab6455771.PNG)

Since all the channels are set as input by default, the high state should appear as default.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/d4e3291f04476142a971f9e3e3b6ea394fafffd5

**Comment by amiclaus** [comment]
On Scopy build: 5bb6466 (v0.7) the bug is fixed.
