### ISSUE TITLE
Incorrect RMS value

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#237]
Scopy version: be46948

Generate via external/Scopy a square wave with frequency 40kHz, amplitude 5V.

Oscilloscope RMS value of the signal:
![sg-rms](https://user-images.githubusercontent.com/26061529/29811218-5ca4c5b8-8cab-11e7-9b07-34d13d33c00a.PNG)
Voltmeter RMS value of the signal:
![vm-rms](https://user-images.githubusercontent.com/26061529/29811233-6927ccc2-8cab-11e7-8dfe-36adb180728a.PNG)
It seems that the voltmeter displays the RMS with an error of ~0.3V (should display around 2.5V)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 8651b8326c5ba764ef613c85e50add9d61a36e20.

**Comment by amiclaus** [comment]
On scopy build 40e7d80 (v0.7) the bug is fixed.

**Comment by tagoylo** [comment]
This issue has reappeared in V1.0.2.
Scopy build: [1d173e63](https://github.com/analogdevicesinc/scopy/commit/1d173e633165f0632036963f0b15180598c5add9)


![image](https://user-images.githubusercontent.com/25096080/46591405-1c8f1880-caed-11e8-9ab2-28c9523b21e3.png)

**Comment by DanielGuramulta** [comment]
What hardware revision do you have?

**Comment by tagoylo** [comment]
I'm using a Rev c board.

**Comment by ReiRue** [comment]
Keep in mind what you are doing:
A square wave has an unlimited number of harmonics!
In your example:

frequenzy  relative amplitude
 40kHz        1
120kHz        1/3
200kHz        1/5
280kHz        1/7
...           ...
(check it with the integrated spectrum analyser)

Your voltmetet has an "integrated" low pass filter with an
corner frequency of about 40kHz
-> this filter will attenuate all harmonics above 40kHz!
-> results in a reading below 2.5V

My interpretation:
  There is no bug!

**Comment by amiclaus** [comment]
fixed on Scopy build: 91c4f0c
