### ISSUE TITLE
Changing trigger to Auto crashes scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#239]
Scopy build: [b76864c8](https://github.com/analogdevicesinc/scopy/commit/b76864c81dcb275faae3cd9cfa0b7eaea9e3cc05)

Steps to reproduce
Enable DIO0 channel of pattern generator, set pattern as clock.
Monitor in logic analyzer, set trigger to Auto.
After selecting Auto, after few seconds scopy crashes.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 3f77bdf7d1fa84be2592bae78d8401663fb60029.

**Comment by amiclaus** [comment]
On Scopy build: 5bb6466 (v0.7) the bug is fixed.
