### ISSUE TITLE
Running signal generator when connected remotely crashes scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#240]
Scopy build: [b76864c8](https://github.com/analogdevicesinc/scopy/commit/b76864c81dcb275faae3cd9cfa0b7eaea9e3cc05)

Steps to reproduce
Connect to M2K device using ip address
Open signal generator,set a constant of 1V
Click Run.
A window will pop up as seen in the picture and then Scopy crashes
![aaaaa](https://user-images.githubusercontent.com/25096080/29854343-ea6cd710-8d77-11e7-92ed-7c0c1f7f8f38.PNG)

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/libiio/commit/c8ac1c556a4548a304d3ec2f2cca083ce2adfd0a

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
