### ISSUE TITLE
Oscilloscope not working when in remote

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#241]
scopy build: [b76864c8](https://github.com/analogdevicesinc/scopy/commit/b76864c81dcb275faae3cd9cfa0b7eaea9e3cc05)
steps to reproduce:

connect m2k through ip address
connect DIO0 to scopech1+, gnd to scopech1-.
open pattern generator, enable DIO0 , set as clock then run
Monitor in oscilloscope, there is no trace seen in oscilloscope display. Unlike when connected through USB.

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/libiio/commit/c8ac1c556a4548a304d3ec2f2cca083ce2adfd0a

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
