### ISSUE TITLE
Use Trace Averaging for XY plot

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#243]
Would it be an idea to use trace averaging for the XY plots?
Maybe we can obtain nicer plots than, for example, this one: 
![image](https://user-images.githubusercontent.com/26061529/29915549-d371e00a-8e44-11e7-8272-8b9ae156c068.png)
(photo took from ADALM2000 Lab Material - [Activity 8. Stabilized current source (BJT)](https://wiki.analog.com/university/courses/electronics/electronics-lab-8))

**Comment by rgetz** [comment]
Do you want averaging? Or a "best fit" curve, with the actual math equation?

Best fit would seem to be to be more valuable.

- Robin

**Comment by amiclaus** [comment]
There are several types of curve fitting based on different equations.
For different plot shapes, there might be different curve fitting equations that will construct the plot properly. 
Therefore, should we add multiple fitting methods and will be the user's choice which one to apply? (Like here : https://www.mycurvefit.com/)

**Comment by DanielGuramulta** [comment]
I've implemented a filter: https://github.com/analogdevicesinc/scopy/commit/9dc63dd94ba8d433b73d1696722f2a9079ca34d3 that will create an average curve to be drawn on the plot.
