### ISSUE TITLE
Generated clock frequency is not accurate

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#245]
scopy build: [40e7d80c](https://github.com/analogdevicesinc/scopy/commit/40e7d80cb9767c8bcaa8d63957d34c9345addc26)

When specifying clock frequency, other chosen frequency has inaccurate output as monitored by the oscilloscope.

Steps to reproduce:
open pattern generator
enable DIO0 and set clock frequency to: 170 kHz, 240 kHz, 290 kHz, 470 kHz, 27 MHz, 34-49 MHz, etc.
set duty cycle to 50 %
Monitor in oscilloscope.
The frequency read is not as what is set.

![bug](https://user-images.githubusercontent.com/25096080/30017635-920d9168-918c-11e7-8fa8-7cce241e939e.PNG)

**Comment by adisuciu** [comment]
Fixed with fb5a0f8

**Comment by amiclaus** [comment]
On Scopy build: 49a4f93 (v0.7) the bug is fixed.
