### ISSUE TITLE
Detached Instrument won't appear when clicking on it in the Instrument Menu

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#246]
Scopy Version: 40e7d80

Detach Instrument, minimize it. When pressing on the Instrument in the Scopy menu, it should appear on the screen, but instead it remains minimized.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/5808e2cfa1395f2fb4658e9bf2ba2feae8260a29

**Comment by amiclaus** [comment]
On Scopy build: 49a4f93 (v0.7) the bug is fixed.
