### ISSUE TITLE
Deleting specific Math channel on specific setup generates Scopy crash

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#249]
Scopy version: 49a4f93

Add all math channels. Deactivate all channels except the last math channel. Delete the math channel before the last one. Put your mouse on the plot window. Scopy crashes.

![math](https://user-images.githubusercontent.com/26061529/30058038-e66b1612-9241-11e7-9a36-1aac2fb7ec01.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/2309e1e656d791bb63d79aefc684f417c026f420

**Comment by amiclaus** [comment]
On Scopy build: 152efe0(v0.7) the bug is fixed.
