### ISSUE TITLE
Run Icon still active after Instrument is stopped.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#250]
Scopy version: 49a4f93

Run Oscilloscope/Spectrum Analyzer. Press Single button. The Instrument stops, but the running icon in the Scopy Instruments menu is still active.

![image](https://user-images.githubusercontent.com/26061529/30112991-dceb2a02-931b-11e7-910e-a4c4d5f8c1f9.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/2b71c36233e0ea661041f784740e4e6929aa0648

**Comment by amiclaus** [comment]
On Scopy build: 152efe0(v0.7) the bug is fixed.
