### ISSUE TITLE
Cannot Zoom out after moving the vertical trigger cursor

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#251]
Scopy version: 49a4f93

Generate a signal to see it on the oscilloscope. Zoom in the plot area. Move the trigger cursor. Try to zoom out. The window won't zoom out.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/5f2c366c23f26ea8a3ab76962473b5b68d9c99c6

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
