### ISSUE TITLE
Oscilloscope updates measurements with wrong id when deleting a math channel

### ISSUE THREAD

**Issue by DanielGuramulta** [analogdevicesinc/scopy#252]
Add some math channels, only enable 2 of them, select the first one that is enabled and delete it:
![1](https://user-images.githubusercontent.com/26142210/30168671-c810f2c4-93f2-11e7-8dc7-665e96562187.png)
The measurements will update for the last channel instead of the one that is now selected:
![2](https://user-images.githubusercontent.com/26142210/30168709-e445c406-93f2-11e7-9408-e5527e2fc09b.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/ac63783590beb989b8fa9f88fc56d404ca4dbe1c

**Comment by amiclaus** [comment]
On Scopy build: 152efe0(v0.7) the bug is fixed.
