### ISSUE TITLE
After a math channel is deleted, another channel might be selected

### ISSUE THREAD

**Issue by DanielGuramulta** [analogdevicesinc/scopy#253]
Add some math channels, select a channel and delete another one:
![3](https://user-images.githubusercontent.com/26142210/30168840-3bc4260a-93f3-11e7-9d2d-bf4f71c9cea4.png)
In this case, Math3 is the selected one, but after we delete Math1:
![4](https://user-images.githubusercontent.com/26142210/30168864-542be462-93f3-11e7-831a-a3dec2716f46.png)
Math2 will be the now selected channel.
Another channel should be selected only when deleting the current selected channel.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/30cf24d0acf636c47a7d6bc0cbd13d8d3357dba6

**Comment by amiclaus** [comment]
On Scopy build: 152efe0 the bug is fixed.
