### ISSUE TITLE
Position stuck at high values for small time bases.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#254]
Scopy version: 152efe0c

Delete the Scopy.ini file from your pc. Open Oscilloscope. Set the horizontal position at 4.5s. Try do decrease/increase the position by using the +- buttons. The position is stuck.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 97071c2ffd88ca1a7ade1c9e9365583c8ee57759.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
