### ISSUE TITLE
Duty cycle is inaccurate at high frequencies, >1MHz

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#255]
Scopy build: [152efe0c](https://github.com/analogdevicesinc/scopy/commit/152efe0cd986e08bfb7b4e32c36ba18284214d3e)

When clock frequency is set to high, i.e. 10 MHz and change the duty cycle to value other than 50%, the result monitored in the oscilloscope is far from what is set.

![aaa](https://user-images.githubusercontent.com/25096080/30262383-48bd0ab2-9703-11e7-8a9c-ad586c971231.PNG)
![vv](https://user-images.githubusercontent.com/25096080/30262392-50ad3760-9703-11e7-9eec-e057c7c93129.PNG)

**Comment by damercer** [comment]
At 10 MHz output with a 100 MHz sample rate you only have 10 samples per cycle or 10% steps in the duty cycle. So how can you be allowed set the duty cycle with more resolution than that?

Doug

**Comment by adisuciu** [comment]
Fixed with 1e4e8957717b242a745b33f670dd6b18cf51f321

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
