### ISSUE TITLE
Run/Stop crashes scopy when FFT is on

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#256]
Scopy build: [152efe0c](https://github.com/analogdevicesinc/scopy/commit/152efe0cd986e08bfb7b4e32c36ba18284214d3e)

Steps to reproduce:
case: oscilloscope has nothing to read
Open gear-like icon 
Under views, turn FFT on
Click Run
Then click stop
Scopy then crashes

![bug](https://user-images.githubusercontent.com/25096080/30263556-efe4f6a2-9707-11e7-9f18-51f55ded531c.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 7fd2398be5a1e3939fc22df338d3e372f8040ca3.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
