### ISSUE TITLE
Scopy crashes when using Network Analyzer and Signal Generator

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#257]
Scopy version 152efe0

Two ways to reproduce the bug:
1) Run Signal Generator. Then run Network Analyzer. Stop Network Analyzer. Scopy crashes.
2) Run Network Analyzer. Run Signal Generator. Scopy crashes.

**Comment by AlexandraTrifan** [comment]
Fixed with commit aa97535e000e0f03f354604d898fe53e294633df.

**Comment by amiclaus** [comment]
On Scopy build: 0700bee3 (v0.7) the bug is fixed.
