### ISSUE TITLE
Reset instrument doesn't reset plot to default  state

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#258]
Scopy build: [152efe0c](https://github.com/analogdevicesinc/scopy/commit/152efe0cd986e08bfb7b4e32c36ba18284214d3e)

Steps to reproduce:

Open pattern generator and enable DIO0, set clock frequency as is, then click Run.
Open logic analyzer and enable DIO0, click Run.
Stop first logic analyzer then the pattern generator.
Click Reset Instrument of logic analyzer.
The plot doesn't reset to its default state.

![buuuug](https://user-images.githubusercontent.com/25096080/30311891-e9faf576-97c9-11e7-9597-394f0223121f.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit b1162156655111557fa0fc112ab89eac4fafa9de.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
