### ISSUE TITLE
Closing a detached instrument disrupts main window

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#259]
Scopy build: [0700bee3](https://github.com/analogdevicesinc/scopy/commit/0700bee34e5db9f4840ae45f2b32b66064725bca)

Detach an instrument, ex. Digital IO
Then close it
Select again that instrument in the instrument menu in main window
After selecting, a blank window, appears. See screenshot below

![bug](https://user-images.githubusercontent.com/25096080/30357493-704ddbc8-9871-11e7-8f09-7eb32b0726b3.PNG)

Then if you close the blank window the main window will appear as seen below.

![buug](https://user-images.githubusercontent.com/25096080/30357515-895760a8-9871-11e7-9f9d-d43dda36c82b.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/9332e85355ab4859a9e97306ec54fe484ce5842f

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
