### ISSUE TITLE
Item 6 From Issue #4: Megahertz vs. Millihertz and How to Distinguish Between Them

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#26]
Item 6 from Issue #4 

"Under Frequency you can choose mHz ( mili-Hertz? ), Hz and KHz. Where’s the MHz ( Mega-Hertz )? Not sure you need mili-Hz but you definitely need Mega-Hz."

**Comment by jonpearson** [comment]
Using a lower case "m" for "milli" and an upper case "M" for "Mega" would work, but I don't think we need millihertz.  Adding a "MHz" option to the pulldown menu below "kHz" and eliminating the "mHz" option would be a good solution.

**Comment by pcercuei** [comment]
millihertz was a requirement from @rgetz, since we might want to generate very slow waveforms.
Megahertz is not possible yet, since the signal generator only runs at 750 kHz.

**Comment by rgetz** [comment]
Paul:

The signal generators run at 100MHz. It should be possible to get a reasonable 10MHz sine wave out. And easy to get a 20MHz square wave.

**Comment by pcercuei** [comment]
No, the signal generator runs at 750 kHz. The hardware can do 75 MHz, Scopy configures it to 1MHz and gets 750 kHz (so with a /100 divisor). We can't do higher until we have one DMA per channel which would allow us to have cyclic buffers.

**Comment by rgetz** [comment]
Right - and we said that wasn't going to be for Alpha, but needs to be there before Beta. What is the schedule? 

I thought @acostina said the cyclic DMA was ready. (but could have been mistaken). Adrian - can you confirm?

Thanks

**Comment by acostina** [comment]
The latest FPGA project has one DMA for each TX channel of the AD9963, with the cyclic option active. The interpolation module supports different interpolation rates per channel. 

Not sure if the linux driver supports this infrastructure at this time.

**Comment by pcercuei** [comment]
I think this works fine now.
