### ISSUE TITLE
Values in the Cursor Box overlap

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#261]
Scopy version: 316a80e

Open Oscilloscope. Enable Cursors, open General Settings tab and enable XY plot. Values in the Cursor Box overlap:
![image](https://user-images.githubusercontent.com/26061529/30476009-5459e8de-9a11-11e7-8716-798d1562d9e3.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/2c2c7ff5022a58814aa435887ecae923bbd5a1c3

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
