### ISSUE TITLE
Horizontal Trigger/Channel Cursors Handles dissapear

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#262]
Scopy version: 316a80e

Open Scopy in minimum size window, open Oscilloscope, enable Display All Measurements. Move the Vertical Trigger cursor to the far left/right of the plot:

![image](https://user-images.githubusercontent.com/26061529/30541936-08840bd4-9c86-11e7-890e-6bebefb6e8d8.png)

Restart Scopy in minimum size window. The Horizontal Trigger Cursor Handle dissapears along with the channel position handlers:
![image](https://user-images.githubusercontent.com/26061529/30542109-b14e71d2-9c86-11e7-81db-e609d52d4c1d.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/6e6316fe6f409a793b7cdc4b3d13835475c25dec

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
