### ISSUE TITLE
Cannot Zoom out after changing Volts/Div

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#263]
Scopy version: 316a80e
Generate a signal, run Oscilloscope, zoom in plot,  change Volts/Div. Try to zoom out (right-click on plot). The plot does not zoom out.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/89cf222c8dab77265ece401acbf2002a5d3782bf

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
