### ISSUE TITLE
Measurements values overlap

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#264]
Scopy version: 316a80e

Open Scopy in minimum window size. Run Oscilloscope, enable Measure and set Display All feature. The Measurement Values overlap.
![image](https://user-images.githubusercontent.com/26061529/30544905-b4cf9354-9c90-11e7-9c18-356ef639e946.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/f93bff43e3690a9723f9dfa61ed451bed7e66081

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
