### ISSUE TITLE
Changing values/measurement unit improvement

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#265]
Open i.e. Signal Generator Channel Settings. Suppose that the set value is 5V.

![image](https://user-images.githubusercontent.com/26061529/30548110-eb3eb2e0-9c99-11e7-851f-b316d6681a71.png)

Now I want to change the value to 200 mV. As we do on paper, first we write the value and then the measurement unit. After changing the value to 200, when trying to change the measurement unit to mV, due to defocus, the value changes to automatically to 5 (maximum accepted value in Volts).

An improvement would be in this situation to automatically change the measurement unit to a smaller one (i.e. mV) if the set value is greater than the accepted one.

Not sure if it is bug, so I will consider it an enhancement

**Comment by septimiusarca** [comment]
Fix with commit [75170b6](https://github.com/analogdevicesinc/scopy/pull/374/commits/75170b6a44d6c97a53d213c250d369ead637db9b).

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the feature is implemented.
