### ISSUE TITLE
FFT Plot not working

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#268]
Scopy version: 316a80e

Generate a signal, run Oscilloscope, enable FFT plot. Nothing is displayed on the plot.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 7fd2398be5a1e3939fc22df338d3e372f8040ca3.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
