### ISSUE TITLE
Duty cycle gradually becomes 0 as frequency is increased

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#269]
Scopy build: [1e4e8957](https://github.com/analogdevicesinc/scopy/commit/1e4e8957717b242a745b33f670dd6b18cf51f321)

Steps to reproduce:

Enable DIO0
Set clock frequency to 1MHz.
Enable fine interval, +-1 unit interval, orange dot in center.
Then max out duty cycle to 100%.
Click + to increase frequency.
Monitor Duty cycle value. It decreases until 0. And as seen in the screenshot below, the wheel doesn't correspond to the value.

![buug](https://user-images.githubusercontent.com/25096080/30677236-30982810-9ebd-11e7-85e4-fff3e7cb6e7a.PNG)

**Comment by adisuciu** [comment]
Fixed with  bad81d4

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
