### ISSUE TITLE
Item 7 From Issue #4:  Entering Time/Phase Settings

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#27]
Item 7 from Issue #4 

"Phase ( Delay ) should be selectable in either degrees ( phase ) or time in uS / mS ( delay )."

**Comment by rgetz** [comment]
Delay and phase are the same thing - it should just be a units selector on the same knob.

 You can't have 2 things that control the same characteristic. That would be super confusing.

**Comment by damercer** [comment]
Right. One knob ( entry widget ) with optional Units settings.

**Comment by adisuciu** [comment]
Implemented with https://github.com/analogdevicesinc/scopy/pull/374

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the feature is implemented.
