### ISSUE TITLE
Setting clock frequency to 43 MHz crashes Scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#270]
Scopy Build: [1e4e8957](https://github.com/analogdevicesinc/scopy/commit/1e4e8957717b242a745b33f670dd6b18cf51f321)

Steps to reproduce:

Enable DIO0
Set clock frequency to 43 MHz
Then click + to increase duty cycle.
After few seconds, Scopy crashes.

![buuug](https://user-images.githubusercontent.com/25096080/30677372-ff89db46-9ebd-11e7-8bc4-c7528eae3db8.PNG)

**Comment by adisuciu** [comment]
Fixed with 6d04b41edb0c5b85eadc48fbb0a00e8f8ec77002

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
