### ISSUE TITLE
Disabling a channel doesn't reflect on FFT

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#276]
Scopy build: [54e3bff4](https://github.com/analogdevicesinc/scopy/commit/54e3bff48991ab0b36b01d2fb4b9febf35d2e0d3)

When running the oscilloscope and fft is on, the disabled channel is still showing in fft. See the picture below.

![bug](https://user-images.githubusercontent.com/25096080/30900620-4b4e6050-a397-11e7-8441-ae39f14d1ace.JPG)

**Comment by AlexandraTrifan** [comment]
Fixed with f8e540338f5fe73f659c926f5d8155f942395e1e.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
