### ISSUE TITLE
Cannot zoom in FFT plot 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#277]
Scopy build: [54e3bff4](https://github.com/analogdevicesinc/scopy/commit/54e3bff48991ab0b36b01d2fb4b9febf35d2e0d3)

Zoom doesn't work in FFT. One cannot zoom in FFT plot.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 0408cc62f684672aa18bdf77f52b0dd7d72c1b9f.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.8) the bug is fixed.
