### ISSUE TITLE
No unit specified in Y-axis of FFT

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#278]
Scopy build: [0408cc62](https://github.com/analogdevicesinc/scopy/commit/0408cc62f684672aa18bdf77f52b0dd7d72c1b9f)

As seen in the picture below, there is no unit specified in the y-axis of the FFT plot.
![bug](https://user-images.githubusercontent.com/25096080/30946330-f680273a-a435-11e7-8d95-5c6d0862c022.JPG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit a71f88820779918610382b03927b3d9fe07bd7ac.

**Comment by rgetz** [comment]
I would disagree - this isn't a bug.

Depending on the context, there shouldn't be numbers anywhere - just like other instruments:

![image](https://user-images.githubusercontent.com/1017869/31078896-e498b7fc-a751-11e7-891c-cd73163115b7.png)

![image](https://user-images.githubusercontent.com/1017869/31078923-fc8d599e-a751-11e7-8c67-1039eb6280be.png)


![image](https://user-images.githubusercontent.com/1017869/31078942-0ae86e0c-a752-11e7-8901-0ce8e5c4ebfe.png)

![image](https://user-images.githubusercontent.com/1017869/31079052-632dd05c-a752-11e7-9593-87828f0c2d5b.png)

All are oscilloscopes with a "FFT" view - no numbers anywhere. This is the expectation.

Spectrum analyzers are different, they have numbers.

![image](https://user-images.githubusercontent.com/1017869/31079162-abac66e0-a752-11e7-82fb-a6993f1b1989.png)
No frequency numbers, but they do have amplitude numbers (and a single scale indicator).

![image](https://user-images.githubusercontent.com/1017869/31079233-ecddb4d4-a752-11e7-8806-a85b7e67cb4e.png)
same

![image](https://user-images.githubusercontent.com/1017869/31079266-0661402e-a753-11e7-948d-fabf504c696c.png)

same.

- so, there doesn't need to be units on each number when viewing an FFT from a scope view.

-Robin

**Comment by AlexandraTrifan** [comment]
I understand. I will revert the previous commit.

**Comment by AlexandraTrifan** [comment]
The FFT plot is back to its initial version through commit aa3aacd56687abbc10be61020985208cf80c0be5.
