### ISSUE TITLE
Channels property resets when setting trigger

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#279]
Scopy version: 0408cc6

Group several channels and set the decoder i.e. to SPI. Set for each channel a property (i.e MOSI MISO CLK CS). Then set a trigger for any channel available in the Logic Anayzer. The property of the channels will reset to "None".

**Comment by AlexandraTrifan** [comment]
Fixed with commit 13b6aa3ae625f636500866f7a3e47f841aace4cd.

**Comment by amiclaus** [comment]
On Scopy build: 8f7e63f (v0.7) the bug is fixed.
