### ISSUE TITLE
Item 8 From Issue #4:  Duty Cycle Adjustment for Rectangular Waveform

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#28]
Item 8 from Issue #4 

"For the Square wave shape where’s the duty-cycle ( symmetry ) adjuatment?"

**Comment by jonpearson** [comment]
If we limit the waveform to square, then by definition the duty cycle is 50% and should not be adjustable.  For the most flexibility, we should relabel the waveform as "Rectangular" and provide a duty cycle adjustment.

**Comment by damercer** [comment]
Digilent Waveforms has the Symmetry knob which for a square wave is duty cycle.

I think most people include any flat top waveform with "vertical" edges as Square Waves.

Waveforms with slower edges are referred to as Trapezoidal waveforms.

**Comment by adisuciu** [comment]
Implemented with b267d3c4d8a72e7b615fbbe78ce66963fe9dfcb1

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
