### ISSUE TITLE
Spectrum Analyzer: Instrument doesn't automatically stop when m2k is disconnected

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#280]
OS: Windows 7 64bit
 Scopy Version: 80794965
 Firmware Version: v0.14

Steps to reproduce:
1. Open and run the Spectrum Analyzer instrument.
2. Go to home and disconnect the m2k.

![disconnection bug](https://user-images.githubusercontent.com/20266602/31065587-1c26ba1c-a779-11e7-8a8c-1812f2795ee8.png)

3. see that the run icon is still on for the Spectrum Analyzer.
4. When the m2k is reconnected the run icon is still present but the spectrum analyzer is stopped, but sometimes scopy crahes when reconnected in this situation.

**Comment by dNechita** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/commit/62bd02d123795fa55546a40a35a045bc79fa7ea1

**Comment by amiclaus** [comment]
On Scopy build: 704cb7f (v0.8) the bug is fixed.
