### ISSUE TITLE
Spectrum Analyzer: Previous setting is not saved when Scopy is closed

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#281]
OS: Windows 7 64bit
Scopy Version:  8079496 
Firmware Version: v0.14

Steps to reproduce:
1. Open Spectrum Analyzer instrument.
2. Change the sweep settings, channel settings or the marker settings.
3. Close Scopy
4. Reopen Scopy and the Spectrum Analyzer. The default setting will be the one loaded for the Spectrum Analyzer.

**Comment by adisuciu** [comment]
Implemented with  7d1de1c

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
