### ISSUE TITLE
Automatically select first enabled channel when disabling unselected channel

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#285]
Scopy version: e918c98

Add multiple channels: i.e. M1, M2, M3. Select M2. Disable M1. First channel enabled from the list of available channels is automatically selected (i.e CH1). The selection should remain at M2 which was initially selected before disabling M1 channel.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/e091beb5fbe3ea02af1311e9d8c49ad4749efc90

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
