### ISSUE TITLE
Thickness set in group is retained when reset instrument is done

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#287]
Scopy build: [8f7e63f6](https://github.com/analogdevicesinc/scopy/commit/8f7e63f69fb815457566200f40c6619f6c861dbc)

Steps to reproduce:

Group DIO1-DIO3
Change group thickness to 5
Then click on reset instrument
Then group again DIO1-DIO3
The thickness shown is 5 and is not reset to default. Although, at the widget, thickness is set to 1.
![ds](https://user-images.githubusercontent.com/25096080/31427685-b1f10eda-ae9a-11e7-91e4-65818987c731.PNG)

**Comment by adisuciu** [comment]
Fixed with 704cb7f848700d54c740b7628e9af70ebe31f01e

**Comment by amiclaus** [comment]
On Scopy build: 704cb7f (v0.8) the bug is fixed.
