### ISSUE TITLE
Item 9 From Issue #4:  Tri-Wave Symmetry Adjustment

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#29]
Item 9 from Issue #4 

"For the Tri-wave shape, where is the symmetry adjustment? You don’t need the sawtooth wave shape if you implement symmetry for the tri-wave. 0% would be a sawtooth one way ( up? ) and 100% would be a sawtooth the other ( down? )."

**Comment by jonpearson** [comment]
It makes sense to add the symmetry adjustment feature and eliminate the sawtooth.  This should be categorized as an enhancement.

**Comment by adisuciu** [comment]
Implemented trapezoidal waveform that allows generation of sawtooth with different degrees of simmetry. Commit b267d3c4d8a72e7b615fbbe78ce66963fe9dfcb1.

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
