### ISSUE TITLE
fine mode in duty cycle 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#290]
Scopy build: [290a894c](https://github.com/analogdevicesinc/scopy/commit/290a894c4e38e3b47c898af74593ae8d65f93181)

When enabling the fine mode feature of duty cycle (with orange dot in center), the user cannot change the value using +/- button.

**Comment by adisuciu** [comment]
The fine mode of the phase/duty cycle was removed due to doing the same thing as the coarse mode.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
