### ISSUE TITLE
Spectrum Analyzer: Scopy crashes when the unit is changed

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#291]
OS: Windows 7 64bit
 Scopy Version:  ec8763f3 
 Firmware Version: v0.16

Step to reproduce:

1. reconnect m2k device so that there's no signals on the spectrum analyzer or reopen Scopy.
2. go to spectrum analyzer instrument and go to sweep settings. [do not run spectrum analyzer]
3. change the unit from dbFS to any available unit. 
4. Scopy will crash.

![units bug](https://user-images.githubusercontent.com/20266602/31533706-2cb173e4-b026-11e7-8109-2bcdcb3b9463.png)

*Scopy will not crash if the unit is changed when the spectrum analyzer has been run.

**Comment by dNechita** [comment]
Fixed with: https://github.com/analogdevicesinc/scopy/commit/6ba153bbbc3c6c7d230ee53af5684de335245999

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
