### ISSUE TITLE
Auto Trigger mode shows different behavior when FFT is used

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#292]
Scopy build: [290a894c](https://github.com/analogdevicesinc/scopy/commit/290a894c4e38e3b47c898af74593ae8d65f93181)

Steps to reproduce

In signal generator: 1kHz square wave, 5V

Oscilloscope: 1ms/div, 1V/div
Trigger mode: Auto

Open FFT plot.
FFT size is 1024.
Run instrument.

Then change FFT size,  16384 and above. The scope trace label shows "Auto", unless the user change the trigger mode to Normal, the label is "Triggered".
![q](https://user-images.githubusercontent.com/25096080/31533964-5911561a-b027-11e7-80a9-4fd235216f14.PNG)

Stop instrument.
Turn off FFT. Then run again the oscilloscope, Auto mode, the label now shows triggered.
![ww](https://user-images.githubusercontent.com/25096080/31533983-660dc01a-b027-11e7-9021-3afb81e2a446.PNG)

Then turn on again FFT. FFT size is the same as when closed, 16384. Run instrument. The label now shows "Triggered".
![e](https://user-images.githubusercontent.com/25096080/31533988-6b439c12-b027-11e7-94e6-8e404954df3b.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 4cb208bfac1831ea341a1963492bc8f8e393627a.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
