### ISSUE TITLE
Font Size of Run and Single buttons

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#293]
Scopy build: [33b0b388](https://github.com/analogdevicesinc/scopy/commit/33b0b388d6f39486ad1ff360da4a0078aef89dd4)

 The font size of the Run and Single buttons of spectrum analyzer is bigger compared to the other instruments. It should be the same with the other instruments.

![bugg](https://user-images.githubusercontent.com/25096080/31592721-f0eb53be-b25c-11e7-858b-11c812725cdd.PNG)

**Comment by adisuciu** [comment]
Fixed with cb7f5f96df1809a458cfb80cbb17fa09ab49ff4f

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
