### ISSUE TITLE
Run button also scrolls up

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#294]
Scopy Build: [33b0b388](https://github.com/analogdevicesinc/scopy/commit/33b0b388d6f39486ad1ff360da4a0078aef89dd4)

When in minimum window and the user scrolls down up to the data logging and Timer section, the Run button is nowhere to be seen unless the user scrolls back up again. 

![enh](https://user-images.githubusercontent.com/25096080/31593245-1a6823cc-b260-11e7-84bf-c2a1413b84e1.PNG)

I think it would be convenient for the user to leave the Run button fixed instead of it being part of the scrollable section when in minimum window size.

**Comment by AlexandraTrifan** [comment]
Fixed with commit aa4b1d4f48822a3e5f6ccdd7ca637f165a29b13e.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
