### ISSUE TITLE
Lock and position of cursor settings remains the same after reset instrument

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#295]
Scopy build: [33b0b388](https://github.com/analogdevicesinc/scopy/commit/33b0b388d6f39486ad1ff360da4a0078aef89dd4)

Steps to reproduce:

Enable cursor.
Turn on lock in cursors settings. (off by default)
Move the cursors.
Then reset instrument.

After resetting, enable again cursor and you will see that the cursor position is not on its default. 
Then open cursor settings, the lock is still on in which it should be off.

**Comment by AlexandraTrifan** [comment]
Fixed with commit b7a55c03e285a6ec04a8fb5c5f7dde8e9fb3d238.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
