### ISSUE TITLE
Frequency widget stuck at 2Hz

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#296]
scopy build: [33b0b388](https://github.com/analogdevicesinc/scopy/commit/33b0b388d6f39486ad1ff360da4a0078aef89dd4)

Steps to reproduce:

Set pattern generator to clock pattern
Set frequency to coarse mode.
Set frequency to 1Hz.
Then click + to increase frequency.
The frequency is now stuck at 2Hz. 
But if it is in fine mode, the frequency will continue increasing.

**Comment by adisuciu** [comment]
Fixede with e6430d9dcafd069b8dcdb325085c7a2a7bacb26b

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
