### ISSUE TITLE
Frequency widget: 317 kHz and above the (-) button doesn't work in fine mode

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#297]
Scopy Build: [33b0b388](https://github.com/analogdevicesinc/scopy/commit/33b0b388d6f39486ad1ff360da4a0078aef89dd4)

In setting 317 kHz and above the (-) button doesn't work when in fine mode.

Steps to reproduce:
Set pattern generator to clock pattern
Set frequency to fine mode.
Input frequency: 317 kHz or above 
Click - button.
It doesn't work and is now stuck at the set frequency.

**Comment by adisuciu** [comment]
Fixed with e6430d9dcafd069b8dcdb325085c7a2a7bacb26b

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
