### ISSUE TITLE
Fine mode: 10 kHz and above an addition of atleast 0.001 kHz in every increase of frequency

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#298]
Scopy build: [33b0b388](https://github.com/analogdevicesinc/scopy/commit/33b0b388d6f39486ad1ff360da4a0078aef89dd4)

At 10 kHz and above there is an addition of atleast 0.001 kHz in every increase of frequency.

Steps to reproduce:

Set pattern generator to clock pattern
Set frequency widget to fine mode.
Input 10kHz.
CLick on + button to increase frequency, as you can see as frequency increases there is also an addition of atleast 0.001 kHz.

**Comment by adisuciu** [comment]
This is expected as that is the frequency that is actually generated by the patterngenerator.
