### ISSUE TITLE
Distorted waveform is generated

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#299]
Scopy build: [574c441a](https://github.com/analogdevicesinc/scopy/commit/574c441ad3f1408f2fba5c034ceb7769f6220f64)

Steps to reproduce:
Set signal generator to the following:
sine wave, 10 V Amplitude
Monitor in oscilloscope.
The picture below is the result.
![m2k siggen](https://user-images.githubusercontent.com/25096080/31648937-fe117bd6-b342-11e7-9816-ba6e0e74caff.PNG)

Also monitored it with Discovery and the result is the same.
![oscilloscope](https://user-images.githubusercontent.com/25096080/31648959-1383cef6-b343-11e7-9fcd-29635e1a8e91.PNG)

The distortion happens when amplitude is set to 10 V and frequencies below 1kHz. Set signal generator frequency in fine mode.

**Comment by adisuciu** [comment]
Fixed with f044b3c58b3c40dd54e3ffb0c3581aeb883282f8

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the bug is fixed.
