### ISSUE TITLE
Instrument preferences

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#303]
Implement general instrument preferences

**Comment by DanielGuramulta** [comment]
I've added a preference option that can be checked: https://github.com/analogdevicesinc/scopy/commit/feb401f500937c250b29280aaf911e36cced87ac and a preference menu that will contain this options: https://github.com/analogdevicesinc/scopy/commit/7aa9d10392e3002e39f391f8b8597dc1b0594b99.

**Comment by DanielGuramulta** [comment]
Scopy now has a preferences menu, available under the save/load session buttons in the left menu.

**Comment by amiclaus** [comment]
On Scopy build: 1beb185 (v0.11) the features are implemented.
