### ISSUE TITLE
Save/Load session

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#304]
Implement saving/loading from file, in the same way as saving/loading works when exiting the application

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/808fae454e39fddf1a4f19309a067034f7f0b831

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
