### ISSUE TITLE
Implement CI build script for Linux

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#306]
Implement CI build script for Linux

**Comment by AlexandraTrifan** [comment]
Linux builds are available on Travis-CI starting with commit c104cc4091e8b466fc463eccd236c84027ce1953.

**Comment by rgetz** [comment]
excellent - thanks

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
