### ISSUE TITLE
Implement CI build script for macOS

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#307]
Implement CI build script for macOS

**Comment by AlexandraTrifan** [comment]
macOS builds are available on Travis-CI starting with commit af463e56700686e6b34d07e24ef3e4485e349726.

Apple Disk Images (.dmg) for macOS  for 10.10 and 10.11 are available starting with commit be3de28fd7d1ea0fdb8f83ba44ce5dc578d5a65d.

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
