### ISSUE TITLE
Implement probe attenuation 

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#309]
Probe attenuation should be selectable. This setting will only scale GUI labels by the selected attenuation, the underlying functionality should stay the same.

**Comment by DanielGuramulta** [comment]
Implemented with commit: https://github.com/analogdevicesinc/scopy/commit/6326da3426cb8f6a70deb63410ce7d4a13c79673

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
