### ISSUE TITLE
Oscilloscope FFT enhancements

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#311]
Implement FFT window plot.

Should the FFT instrument from the oscilloscope use the same settings as the spectrum analyzer or we should have a different set of settings ? Which would those settings be ?

**Comment by rgetz** [comment]
From an end user perspective - it may be a 100% overlap, but I think from a learning perspective - there are things that you want to do in the scope side, that don't belong in the spectrum analyzer. (Like a display of the Windowed samples).
