### ISSUE TITLE
Extend zoom and labels features

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#312]
It will be nice to have this features for the instruments which need zoom and labels. 

![zoom](https://user-images.githubusercontent.com/13637543/32610843-a824c854-c56c-11e7-8846-7fc3c7c224a5.gif)

**Comment by DanielGuramulta** [comment]
Implemented feature with commit: https://github.com/analogdevicesinc/scopy/commit/da69c415dd93520308dead22bd3c4a0c9542c630

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
