### ISSUE TITLE
Horizontal Position Control Cursor gets cut at maximum time base

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#315]
Scopy build: [c8ad5838](https://github.com/analogdevicesinc/scopy/commit/c8ad58381896455caa73f7c73be537159b3f8ea7)

Steps to reproduce:
Set time base to 1s.
Move the horizontal control to max left or right.
The picture below is the outcome.
![aa](https://user-images.githubusercontent.com/25096080/33071182-7cf26d70-cef5-11e7-97d7-b15b3e89af6b.JPG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/910d40e0a13a2dc160d894f38d61bd43dfd7be41

**Comment by amiclaus** [comment]
On Scopy build: 1ead1e1 (v0.11) the bug is fixed.
