### ISSUE TITLE
Cannot zoom out 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#318]
Scopy build: [3aff0560](https://github.com/analogdevicesinc/scopy/commit/3aff0560119572a1c4a358715bdbf3a3e5b9ba8f)

Steps to reproduce:

Run Network Analyzer. In my case, I ran it for LPF using 100ohms and 0.1uF.

Then after the sweep, zoom in any part of the magnitude plot.

Adjust Magnitude display settings.

Then try to zoom out.

The display does not respond and won't zoom out.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/8adb0c2e43d369a9e719460fa046db81826fc788

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the bug is fixed.
