### ISSUE TITLE
Scopy hangs when FFT enabled

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#321]
Scopy version: 8adb0c2

Start/Restart Scopy.
Open Oscilloscope. Set time base >=500us. Run instrument and enable FFT (order of these 2 actions does not matter). Scopy hangs/crashes.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 64f6a3d10301d38cf66171093c15fd500fe4418f.

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the bug is fixed.
