### ISSUE TITLE
No limit in adding the same device through ip address

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#322]
Scopy build: [64f6a3d1](https://github.com/analogdevicesinc/scopy/commit/64f6a3d10301d38cf66171093c15fd500fe4418f)

Steps to reproduce:
Click the "Add +" to add device through ip address.
Input the ip address of the device.
After adding the said device, repeat previous steps to add again the same device through ip address.
One will still be able to add the device though it is already added. It is somewhat redundant. There is no limit in adding the same device.

![mmm](https://user-images.githubusercontent.com/25096080/33647920-4e857254-da92-11e7-8c32-7cc1e1124329.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/15cb0e05861abdd02dbb65066493d0ffdd070124

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the bug is fixed.
