### ISSUE TITLE
Voltmeter: Data logging on overwrite mode not working

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#323]
OS: Windows 7 64bit
Scopy Version: 64f6a3d
Firmware Version: v0.16

Scopy doesn't record any data when data logging option is in overwrite mode.
below is the sample execution.

![scopy-datalogging-overwrite](https://user-images.githubusercontent.com/20266602/33694906-955b6a96-db35-11e7-9f66-2d01ef798cc6.png)

![scopy-datalogging-overwrite-excel](https://user-images.githubusercontent.com/20266602/33694909-98b88d18-db35-11e7-8ddb-d14c18eb8960.png)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 4dc75eef4dd3527dff1f4d404f95447aad7b5a13.

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the bug is fixed.
