### ISSUE TITLE
Can't open other instruments when in remote

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#326]
Scopy build: [b09379d6](https://github.com/analogdevicesinc/scopy/commit/b09379d6a97307705eb8c9645f2b313dd2a196a5)

Steps to reproduce:

Add device through ip address
Connect to this device
After the calibration process, the interface looks like the picture below
![buggg](https://user-images.githubusercontent.com/25096080/34087387-afd4e8c4-e3dd-11e7-99a0-9d81492f0561.PNG)

Other instruments cannot be opened or used.

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/libiio/commit/c8ac1c556a4548a304d3ec2f2cca083ce2adfd0a

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
