### ISSUE TITLE
When saving/loading a session, both of the icon is highlighted

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#327]
scopy build: [2b189ef7](https://github.com/analogdevicesinc/scopy/commit/2b189ef7633c25b3ce2aa8fa40290c3d7bd3c30f)

When saving/loading a session, both of the icon is highlighted when hovering through the icon. Same as when clicking the home icon, all of the icons are highlighted. Perhaps when the user wants to save a session the save session icon will be the only icon highlighted when the user hovers the cursor to that icon. And same as with the other two icons. This is to prevent confusion to the user.

![enh](https://user-images.githubusercontent.com/25096080/34714716-46efcd62-f565-11e7-9dad-5a65d564567c.PNG)

**Comment by DanielGuramulta** [comment]
With commit: https://github.com/analogdevicesinc/scopy/commit/0cc360d7f864fd0336b2d5b8e6f39ef89e2d15f0 , the buttons can be found at the bottom of the left menu, with individual highlighting and also text for each of them.
