### ISSUE TITLE
Voltmeter: Scopy Crashes when data logging feature is enabled

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#329]
OS: Windows 7 64bit
Scopy Version: 3d8729d
Firmware Version: v0.17

Steps to reproduce:
1. Enable Data logging feature on either append or overwrite mode.
2. Run Voltmeter. (The data logging itself works. the csv file is being updated)
3. Stop Voltmeter and the Scopy will have a Run Time Error similar to the image below

![scopy-datalogging-runtime-error](https://user-images.githubusercontent.com/20266602/34930905-d646b32c-fa06-11e7-9e33-cf76c871c44a.png)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 5a6603f04b8f4a7a41a67803df5e15ce4d24a05d.

**Comment by amiclaus** [comment]
On Scopy build: 62e9f54 (v0.10) the bug is fixed.
