### ISSUE TITLE
Item 13 from Issue #4:  Adding a Noise Source

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#33]
Item 13 from Issue #4 

"Should there be a built-in noise wave shape? If so what noise distribution, uniform, Gaussian, etc?"

**Comment by jonpearson** [comment]
This would be a great feature to have, but should be categorized as an enhancement for now.  We should have a Gaussian pdf to start with, then maybe add something like Rayleigh later.

**Comment by adisuciu** [comment]
Noise sources supported by gnuradio (uniform/gaussian/laplacian/impulse) are to the signal generator with commit 3377d253504eca5f8d5518c51a66aa01c830269b

**Comment by rgetz** [comment]
Looks great. Thanks.

**Comment by amiclaus** [comment]
On Scopy build e9a6c85 (v0.10) the feature is implemented.
