### ISSUE TITLE
Combination of Adding/deleting/selecting of math channels and enabling labels crashes scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#335]
scopy build: [e9a6c852](https://github.com/analogdevicesinc/scopy/commit/e9a6c8520f3819706d0c2f2489ab2ca92b1d40fc)
firmware version: v0.17

Steps to reproduce:

Add 4 math channels
Combine adding/deleting/selecting of math channels and also enabling labels 
After few attemps, scopy crashes. 
The screenshot is shown below
![buuuuuug](https://user-images.githubusercontent.com/25096080/34974164-86befe20-fac6-11e7-8a43-5f3a3e1ef72c.PNG)

**Comment by AlexandraTrifan** [comment]
This should be fixed after commit b81f3fd90883b4fbf5cab128cec1a687c86ba37e.

**Comment by amiclaus** [comment]
On Scopy build: 62e9f54 (v0.10) the bug is fixed.
