### ISSUE TITLE
Bottom ADI icon doesn't fit in window

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#337]
Scopy build: e9a6c85

In Scopy minimum size window, the ADI logo is not completely visible.
![image](https://user-images.githubusercontent.com/26061529/34983612-ce99f3d6-fab6-11e7-987f-ad1fecf9f575.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/be1b1c82bace1a1b89f009e81b4e9b26442d8922

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
