### ISSUE TITLE
Noise signal visibility changing based on sample rate

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#338]
Scopy version: e9a6c85

Connect AWG1 to channel 1 of the Oscilloscope
Generate a 2V amplitude and 2kHz frequency Sine wave with Uniform Noise Type of 1V Amplitude:
![image](https://user-images.githubusercontent.com/26061529/34989000-7ac9f496-fac9-11e7-8f60-f24520b8830c.png)
View the signal on channel 1 of the Oscilloscope.
By changing the Time Base (implicitly the Sampling Rate) the Noise applied is attenuated, being less visible.
![image](https://user-images.githubusercontent.com/26061529/34989231-6c92f1b0-faca-11e7-8af1-62c4bbdf9e04.png)
![image](https://user-images.githubusercontent.com/26061529/34989243-7da1a1cc-faca-11e7-80e8-3b64b4420ee2.png)
![image](https://user-images.githubusercontent.com/26061529/34989278-a862ff64-faca-11e7-95f1-1c370876af48.png)

I don't think we want this things to happen for this particular setup.

Are there any solutions for this situation?

**Comment by damercer** [comment]
The digital filtering implemented in the M2K to decimate the sample rate will filter out the higher frequency components of the noise which I assume has a BW equal to 1/2 the 75 MHz AWG base sample rate? If you looked at the AWG output with a real digital scope you would not see this effect ( unless you turned on the digital filtering option in the scope ).

M2K software should implement ( allow ) simple decimation where samples are just dropped as an option rather using digital filtering. Then this will effect not happen. And / Or you could allow the user to select the amount of decimation filtering vs sample dropping independent of that automatically chosen by setting the time/base.

Doug

**Comment by adisuciu** [comment]
Added option to remove HW filtering with [623cf33](https://github.com/analogdevicesinc/scopy/commit/623cf33329fdec34c5428b71910bcb2745ae6cea) .

Issue further tracked here:https://github.com/analogdevicesinc/scopy/issues/506
