### ISSUE TITLE
Item 14 From Issue #4: Displaying Both Channel Control Menus in the Same Area

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#34]
Item 14 from Issue #4 

"There seems to be enough blank space in the configuration section ( for all but Math ) to have controls for both channels up at the same time? Saves the time clicking to switching between the two sets of controls."

**Comment by jonpearson** [comment]
I had noticed this as well.  It can be inconvenient to have to keep switching back and forth between the two channel menus, and there is enough space to display both control menus.  This would be a good short-term enhancement.

**Comment by pcercuei** [comment]
This would not be very future-proof, as it would only work when the device has no more than 2 channels.
