### ISSUE TITLE
Scopy crashes when closing a UART group

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#340]
Scopy version: [d5f3f32d](https://github.com/analogdevicesinc/scopy/commit/d5f3f32d1c9f679850d286116ebbb9c5bad79f16)
firmware version: v0.17

steps to reproduce:

create a group for uart, i.e. DIO0

change baudrate to any rate except for 9600

then close/dissolve group channel

Scopy then crashes

![aasd](https://user-images.githubusercontent.com/25096080/35031273-2d71a25a-fb9d-11e7-83e1-466704778a17.PNG)

**Comment by adisuciu** [comment]
Fixed with abdfbff

**Comment by amiclaus** [comment]
On Scopy build: 62e9f54 (v0.10) the bug is fixed.
