### ISSUE TITLE
Signal Generator: Graphical Representation unstable at high frequency setting

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#341]
OS: Windows 10 64bit
Scopy Version: d5f3f32
Firmware Version: v0.17

Steps to reproduce:

1. Open Signal Generator Instrument
2. Set both channels' to waveform type and set both to 10V.
3. Set both channels' frequency to 2MHz or higher.
4. The graphical representation of the set waveform is unstable. 

![unstable graphical representation](https://user-images.githubusercontent.com/20266602/35031430-dbdeb936-fb9d-11e7-9c23-10ccffa026ce.png)

The image shows that channel 2 is set to Sinewave but the graphical representation shows falling ramp sawtooth.

**Comment by adisuciu** [comment]
fixed with  b33fb00

**Comment by amiclaus** [comment]
On Scopy build (v0.10) 92484c8 the bug is fixed.
