### ISSUE TITLE
Icon for instruments in menu does not match

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#344]
Scopy build: [5457ed04](https://github.com/analogdevicesinc/scopy/commit/5457ed048a2d04a27060a5094320dcea6ead494a)
Firmware version: v0.17

In the list of instruments in the menu, the icons of each instruments does not match. 

![bugg](https://user-images.githubusercontent.com/25096080/35077149-964d9bf0-fc36-11e7-9feb-c97953186146.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/6f732fc2da8942536160b48865bdf5674a624c95

**Comment by amiclaus** [comment]
On Scopy build: 62e9f54 (v0.10) the bug is fixed.
