### ISSUE TITLE
Can't zoom in Nyquist plot

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#345]
Scopy build: [5457ed04](https://github.com/analogdevicesinc/scopy/commit/5457ed048a2d04a27060a5094320dcea6ead494a)
firmware version: v0.17

After a run in network analyzer, go to nyquist and try zooming.
User can't zoom in nyquist

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/9d5211a35905f2cf3caa194edb2570729946e8c7

**Comment by amiclaus** [comment]
On Scopy build: 9d5211a (v0.10) the bug is fixed.
