### ISSUE TITLE
Scopy crashes when changing channel trigger options in logic analyzer

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#347]
Scopy build: [62e9f549](https://github.com/analogdevicesinc/scopy/commit/62e9f5493dc2dffed72c1a02bb173a0f2d86ab4c)
firmware version: v0.17

Steps to reproduce:

Group DIO0-1 in pattern generator, then choose binary pattern

In logic analyzer, group DIO0 and 1, then set as parallel.

Run both instrument.

In logic analyzer, set DIO0 trigger to rising edge.

Scopy hangs then crashes.

**Comment by AlexandraTrifan** [comment]
Should be fixed after commit e6fac1584ac78a1c7ad30857f28ff39082cb3f20.

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the bug is fixed.
