### ISSUE TITLE
Voltmeter: some configurations does not load properly with saved profile

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#348]
Scopy build: [62e9f549](https://github.com/analogdevicesinc/scopy/commit/62e9f5493dc2dffed72c1a02bb173a0f2d86ab4c)
firmware version: v0.17

Steps to reproduce:

set the following configurations:
History of both channel = ON
Measurement mode Ch1 = DC
Measurement mode Ch2 = AC 800Hz-40kHz
Display = OFF
Data logging = OFF
Timer = 1 s

save this as profile.ini

then change these parameters to other settings or as follows
History= OFF
change mode to other mode
display on
data logging on
timer = 5s

after setting these, load profile.ini
The following configurations doesn't change:

Measurement modes of voltmeter
Display
Data logging
Timer

**Comment by amiclaus** [comment]
On Scopy build (v0.10) 92484c8 the bug is fixed.
