### ISSUE TITLE
Interval wheel indicator does not fill up when increasing noise voltage

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#349]
Scopy build: [62e9f549](https://github.com/analogdevicesinc/scopy/commit/62e9f5493dc2dffed72c1a02bb173a0f2d86ab4c)
firmware version: v0.17

When increasing noise voltage the interval wheel indicator does not fill up. It just stays as is.

![bg](https://user-images.githubusercontent.com/25096080/35141938-aac96eea-fd37-11e7-85f2-169e076cc018.PNG)

**Comment by amiclaus** [comment]
On Scopy build (v0.10) 92484c8 the bug is fixed.
