### ISSUE TITLE
Item 15 From Issue #4:  Instructions for Math Functions

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#35]
Item 15 from Issue #4 

"Need to add instructions on how to use the Math controls to the Scopy Wiki page. With examples!"

**Comment by jonpearson** [comment]
These can be added as the math functions become available.

**Comment by AlexandraTrifan** [comment]
Documentation for all the instruments and functionalities were added on the wiki page. Instructions on math functions can be found here: https://wiki.analog.com/university/tools/m2k/scopy/siggen#generate_waveform_from_math_function .
