### ISSUE TITLE
 Signal generator: Math input keys are distorted when in minimum window

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#350]
Scopy build: [62e9f549](https://github.com/analogdevicesinc/scopy/commit/62e9f5493dc2dffed72c1a02bb173a0f2d86ab4c)
firmware version: v0.17

Math input keys are distorted when in minimum window. See photo below.

![nnn](https://user-images.githubusercontent.com/25096080/35143095-63871920-fd3b-11e7-9578-4279c8a6bcf0.PNG)

**Comment by adisuciu** [comment]
Fixed with 34cc501

**Comment by amiclaus** [comment]
On Scopy build (v0.10) 92484c8 the bug is fixed
