### ISSUE TITLE
Export All not changed to default after Reset Instrument

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#353]
Scopy build: [92484c88](https://github.com/analogdevicesinc/scopy/commit/92484c88a89ac5ce9eaa9d4144638de022632805)
Firmware version: v0.17

Reset instrument does not return export selection to default which Export All is on.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 34eddef2188f20ad1d5aea0a168f1d26cbdeec28.

**Comment by amiclaus** [comment]
On Scopy build: ccfa8fd (v0.10) the bug is fixed.
