### ISSUE TITLE
Add export feature in network analyzer

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#356]
Scopy build: [909eeb83](https://github.com/analogdevicesinc/scopy/commit/909eeb83999254e7536512149762e992b26e4e77)

Adding export feature will add convenience to the user, especially for data that needs further analysis.

**Comment by DanielGuramulta** [comment]
This feature was implemented in the latest build.

**Comment by amiclaus** [comment]
On Scopy build: 01f2750 (v0.12) the feature is implemented.
