### ISSUE TITLE
Labels not uniform when volts/div is set to mV

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#361]
Scopy build: [9a6660c3](https://github.com/analogdevicesinc/scopy/commit/9a6660c3d64a4ac461944adc750a767a70211d96)
firmware version: v0.18

Steps to reproduce:

check box to enable labels on the plot on general settings
set volts/div: 100mV or 50 mV
position: 0v
the result is shown below
labes are not uniform, others are in mV and others in V

This happens on all channels and math channels.

![bug1](https://user-images.githubusercontent.com/25096080/36081867-f14473ba-0fde-11e8-9267-59bd1fb7eb0c.PNG)
![bug2](https://user-images.githubusercontent.com/25096080/36081868-f17971b4-0fde-11e8-90f9-d5c02376bc97.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/12e03c54bb74a6d81d56ae2bf649a6c61927443f

**Comment by amiclaus** [comment]
On Scopy build: 1beb185 (v0.11) the bug is fixed.
