### ISSUE TITLE
Signal Generator: Signal Distorted at low frequency and high voltage

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#362]
OS: Windows 10 64bit
Scopy Version: af505af
Firmware Version: v0.18

Steps to reproduce:
1. Open Signal Generator and set to any of this waveform type (Sine, Triangle, Trapezoidal or sawtooth).
2. Set amplitude to 9V to 10V
3. Set Frequency to 100Hz or below
4. The signal generated is distorted.

Sample:

![signal generator low frequency_10v_triangle wave](https://user-images.githubusercontent.com/20266602/36084681-76c76798-0ffa-11e8-98a5-d21b1855d3ab.png)

Similar distorted signal is generated on Sinewave and Trapezoidal wave

![signal generator low frequency_10v_sawtooth wave](https://user-images.githubusercontent.com/20266602/36084688-85e08458-0ffa-11e8-8ee5-0cfbd3d84378.png)

Sawtooth wave distortion

**Comment by adisuciu** [comment]
Cannot reproduce the error. Can you reproduce this on each start ? Does the board calibrate when initializing ? Are you using the latest hardware ?

**Comment by drbautista** [comment]
Hi Adrian,

Yes this bug is reproduced each start and the auto calibration is also initiated.
I'm using the latest firmware and scopy version right now but currently using the old board revision. There are new boards coming here and will retest this bug as soon as it gets here.

Thanks a lot.

**Comment by adisuciu** [comment]
Retest this with new boards revision.
