### ISSUE TITLE
Signal Generator: Buffer User Interface gets messed up after loading a file

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#363]
OS: Windows 10 64bit
Scopy Version: af505af
Firmware Version: v0.18

Steps to reproduce:

1. Open Signal generator and go to buffer tab
2. Load any .csv or .mat file
3. After loading the file the UI gets moved to the right and the Offset and Phase options are not accessible.

Sample picture
![buffer](https://user-images.githubusercontent.com/20266602/36087999-4519552e-1010-11e8-8e9d-3f659ceb9ab8.png)

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
