### ISSUE TITLE
Export Feature for other Instruments

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#364]
Opening a discussion on adding the Export feature to other Scopy Instruments like Network Analyzer/Spectrum Analyzer.
(There was also a question on EngineerZone regarding this subject.)

**Comment by DanielGuramulta** [comment]
On scopy version: 1aef8ae7093b852cb87adfa30ddd9b7734d2fd77 the feature is implemented.

**Comment by amiclaus** [comment]
On Scopy build: 70fb08d (v0.12) the export feature is implemented for Network Analyzer and Spectrum Analyzer
