### ISSUE TITLE
Inaccurate generated Math functions

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#365]
It seems that for some math functions, the signal is distorted when using decimal numbers inside a trigonometric function.
Here is the result:
![image](https://user-images.githubusercontent.com/26061529/36262777-0cbffc7e-1271-11e8-8931-6c34ec1fdc3c.png)

![image](https://user-images.githubusercontent.com/26061529/36262909-74894068-1271-11e8-888c-6438b1d6204a.png)

To be mentioned that for integer numbers, the signal is correct.
![image](https://user-images.githubusercontent.com/26061529/36262838-36917be0-1271-11e8-929a-8288d132e4ec.png)
![image](https://user-images.githubusercontent.com/26061529/36262941-8d31de18-1271-11e8-98ea-a013307bae7f.png)

**Comment by rgetz** [comment]
I think this is actually OK - (sort of)

The buffer has n samples - its up to the user to make sure the math in the equation has the same sample at the start of the buffer, and the end of the buffer. It's just a matter of clearly communicating to end users that the n sample in the buffer is (t-n/2) and the end of the buffer is (t+n/2). Or however the mapping is made.

-Robin

**Comment by amiclaus** [comment]
In this case, what happens behind the math functions needs to be documented. At a first glance, as an external user, I would expect in both situations to have modifications only on the signal's frequency (and not on the shape).

**Comment by damercer** [comment]
The average user is thinking in this order when creating math waveforms, First amplitude, offset, frequency and last ( if at all ) the number of samples needed based on sample rate. The math interface should assume the user wants a continuous waveform and adjust the number of samples ( and / or tweak the frequency a little ) to make that happen.

Putting some examples showing how to do that in the documentation for the signal generator math functions of course will go a long way to help the user get the waveform they want.

Doug

**Comment by adisuciu** [comment]
It looks like there is a bug in gnuradio, or am i missing something ?

Inputs:
![screenshot from 2018-03-15 16-23-28](https://user-images.githubusercontent.com/8676912/37469109-3ba47986-286d-11e8-8a4b-bc42c17b37b9.png)

Outputs:
![screenshot from 2018-03-15 16-20-24](https://user-images.githubusercontent.com/8676912/37469117-4028980c-286d-11e8-864b-7e353ba92c92.png)

**Comment by adisuciu** [comment]
related to https://github.com/analogdevicesinc/scopy/issues/821

**Comment by adisuciu** [comment]
This was fixed with #833
