### ISSUE TITLE
Setting channel gain to the same value causes distorsions in the acquisition

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#366]
Steps to reproduce:
1. Start capture in osc or scopy
2. Write gain attribute from m2k-fabric device, input0 or input1 channel.
3. A distorsion occurs on the plot.
![write_gain_error](https://user-images.githubusercontent.com/8676912/36309011-844edcfa-132b-11e8-883e-abba95e08d9f.png)

**Comment by lclausen-adi** [comment]
Fixed with https://github.com/analogdevicesinc/linux/commit/7fbbe9813ffb63a1a6594c0227b9dedcfa510f80

**Comment by amiclaus** [comment]
On Scopy build: 1e62479 (v0.11) the bug is fixed.
