### ISSUE TITLE
Upon launch, output of some channel doesn't correspond to what is set by default

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#368]
scopy build: [7f1b98cd](https://github.com/analogdevicesinc/scopy/commit/7f1b98cd84e2cb1d0cb570d214fa946aeb9c73ef)
firmware: v0.19
 
steps to reproduce

delete first scopy.ini in C:\Users\your_username\AppData\Roaming\ADI 
Connect DIO0 to scope ch1 Go to pattern generator, enable DIO0
Do not change any parameters aside from enabling it, keep it as is
DIO0 is by default in OD output
Then run pattern generator and monitor it in oscilloscope
The result is that DIO0, although output is set to OP, it output as PP. 
The same happens with the following channels set by default as PP but its output is OD: 
DIO2, DIO3, DIO4, DIO5, DIO6, DIO7

It only outputs the correct output once changed to other output option then back to the other. 
OD(default) ->change to PP ->change to OD   or
PP(default) ->change to OD ->change to PP

![bb2](https://user-images.githubusercontent.com/25096080/36410589-c58da3d0-164c-11e8-9f65-be710e0753ec.PNG)
![bb3](https://user-images.githubusercontent.com/25096080/36410591-c5bd580a-164c-11e8-8cb3-6b812e4affba.PNG)

**Comment by adisuciu** [comment]
fixed with f92cd91

**Comment by amiclaus** [comment]
On Scopy build: 355a04c (v0.11) the bug is fixed.
