### ISSUE TITLE
Round border for selected Menu tab

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#369]
A small enhancement for the Scopy UI:
When hover/select a tab from the menu, the borders should be round as most of the UI elements (i.e. buttons)

![image](https://user-images.githubusercontent.com/26061529/36423335-40b09b76-1648-11e8-940c-965491bc9e6f.png)

**Comment by DanielGuramulta** [comment]
On the current version of Scopy, the enhancement is implemented.

**Comment by amiclaus** [comment]
On Sopy build: 87e17a9 the feature is implemented.
