### ISSUE TITLE
Item 17 From Issue #4:  Defining File Formats for Importing Waveforms

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#37]
Item 17 from Issue #4 

"What file formats are supported for importing waveforms? .txt, .csv, .wav etc. Also there should be a way to save a waveform calculated with the math controls to a file."

**Comment by jonpearson** [comment]
This is a good future enhancement, similar to Item #3

**Comment by pcercuei** [comment]
WAV should be easy to add, the pieces are already there.
I think MAT files makes sense (for waveforms generated by Matlab), same for CSV.

**Comment by adisuciu** [comment]
32b366c19ba95b94c751f8eac6f4f069745f7e98 and 5357a6ed74fc298dd0d3b412d4f2627f8f88022c adds support for WAV, CSV and MAT files.

**Comment by amiclaus** [comment]
Closing this and move conversation to #55
