### ISSUE TITLE
Question about the Nyquist axis in network analyzer

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#371]
According to theory, the Nyquist axis are imaginary vs real, but the Nyquist plot in Scopy is in Phase vs gain. I’ve tried to do Nyquist plot in Discovery, and it is in imaginary vs real, unlike in Scopy which is in phase vs. gain. I’d like to ask  if should be the Nyquist plot in scopy be also in imaginary vs real?  

Below are screenshots from discovery and scopy from the same low pass filter.
![nyquist discovery](https://user-images.githubusercontent.com/25096080/36458255-e8252ad4-16e8-11e8-892f-6792e55e5d70.PNG)
![nyquist scopy](https://user-images.githubusercontent.com/25096080/36458257-e857e9b0-16e8-11e8-81ed-b88f823af184.PNG)

**Comment by rgetz** [comment]
https://en.m.wikipedia.org/wiki/Nyquist_stability_criterion#Nyquist_plot

In Cartesian coordinates, the real part of the transfer function is plotted on the X axis. The imaginary part is plotted on the Y axis. The frequency is swept as a parameter, resulting in a plot per frequency. The same plot can be described using polar coordinates, where gain of the transfer function is the radial coordinate, and the phase of the transfer function is the corresponding angular coordinate.

The other plot;
https://en.m.wikipedia.org/wiki/Nichols_plot
Although similar to a Nyquist plot, a Nichols plot is plotted in a Cartesian coordinate system while a Nyquist plot is plotted in a polar coordinate system.

So phase along X and gain along Y axis isn't anything.
