### ISSUE TITLE
Scopy crashes after clicking connect

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#376]
Scopy build: [793bd53c](https://github.com/analogdevicesinc/scopy/commit/793bd53c5c71a46a54210bee1176172b398a26d0)
Firmware: v0.19

Click device then click connect
after a few second Sopy crashes.

![bug](https://user-images.githubusercontent.com/25096080/36516476-1845bb0e-17b9-11e8-867b-09abbd756e9e.PNG)
![bug2](https://user-images.githubusercontent.com/25096080/36516477-187b73a2-17b9-11e8-93b5-951ee3a8c807.PNG)

**Comment by adisuciu** [comment]
You are testing a pull request. That commit is not merged to master. We are currently investigating the crash.

**Comment by AlexandraTrifan** [comment]
The feature implemented in the pull request you were testing is now merged to master and this issue should be fixed after commit 27e453cbeb9606e9bf5884107cff210d3e0fab31.

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
