### ISSUE TITLE
When in minimum window size, network analyzer settings is messed up

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#382]
scopy build: [27e453cb](https://github.com/analogdevicesinc/scopy/commit/27e453cbeb9606e9bf5884107cff210d3e0fab31)

When in minimum window size, network analyzer settings is messed up. See picture 
![bugf](https://user-images.githubusercontent.com/25096080/36882648-0b71d612-1e10-11e8-861f-fc58efdbf560.PNG)

**Comment by claudiupop** [comment]
Fixed with commit 0bc041b0c0feae44b79972aaedcbe93480c78678

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
