### ISSUE TITLE
Math channel label is still M1 when it should be M2

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#385]
Scopy build: [0bc041b0](https://github.com/analogdevicesinc/scopy/commit/0bc041b0c0feae44b79972aaedcbe93480c78678)

Steps to reproduce:
Add a reference waveform
Then add a Math Channel - M1
Then add again another Math channel -M2
Result:
Math channel label for the second math channel is still M1 when it should be M2

![bh](https://user-images.githubusercontent.com/25096080/36962143-52d1fd68-2089-11e8-9e6f-4b28d4a07f5a.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 7ded1074e114f56244d4137788d6fd54b727cfe8

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the bug is fixed.
