### ISSUE TITLE
Channels are set as individual but shows as group

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#386]
Scopy build: [0bc041b0](https://github.com/analogdevicesinc/scopy/commit/0bc041b0c0feae44b79972aaedcbe93480c78678)

Upon launch, open Digital IO instrument. The picture below is what the interface looks like.
It is set as individual channels but the controls are for a group. It will show the individual controls once you click/choose individual again.

![vv](https://user-images.githubusercontent.com/25096080/36962735-b351cad6-208b-11e8-8f6d-4d1719935f00.PNG)

Also, the in/out buttons in group channels do not have the same GUI with the in/out buttons in individual channels.

**Comment by DanielGuramulta** [comment]
Bug fixed with commit: https://github.com/analogdevicesinc/scopy/commit/9044ed49d861aebf864a232796c422dcec2eedf0

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the bug is fixed.
