### ISSUE TITLE
Scopy hangs when switching between Osc and Voltmeter.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#387]
Scopy version: 7c85b21

Run Voltmeter/Oscilloscope then run Oscilloscope/Voltmeter through the instrument interface. Repeat several times if needed.
At some point Scopy hangs.

**Comment by AlexandraTrifan** [comment]
Fixed with commit af71a02291684bcf5b52b32f06df93da82f3d651

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the bug is fixed.
