### ISSUE TITLE
Item 19 From Issue #4:  Function Generator Constant Output Voltage Inverted

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#39]
Item 19 from Issue #4 

"Under the constant controls, the actual output voltage is reversed, inverted. Setting to +5V outputs -5V, setting to -5V outputs +5 V and same for all the settings in between."

**Comment by jonpearson** [comment]
I could not duplicate this.  The DC levels displayed on the oscilloscope were of the correct polarity, and were verified with a DMM.  There was an offset in the function generator output level.

**Comment by damercer** [comment]
This inversion only happens at the + and - extremes of 5 V as with the waveforms. Setting the DC value to +5.00 outputs -5 but +4.9 outputs ~ +4.9. So I think cause of this is the same as the what we see when the sine amplitude is set to the Max. 5.00

( may have miss spoke with the " same for all the settings in between" part of the comment. )

**Comment by pcercuei** [comment]
I'll close this one, as it's a side effect of #41.
