### ISSUE TITLE
Changing run mode crashes scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#390]
Scopy build: [6bd70752](https://github.com/analogdevicesinc/scopy/commit/6bd7075292413ee0bba502c76e9e49a29a5f4a04)

steps to reproduce:

group 3 channels in pattern generator and select random pattern
monitor in logic analyzer in a 3-channel group
run then change run mode 
scopy hangs then crashes

![newbu](https://user-images.githubusercontent.com/25096080/37270054-32cd79f0-2608-11e8-995c-1c16e2a83959.PNG)

**Comment by AlexandraTrifan** [comment]
This should be fixed with commit 2e31a7574540fe2c456235e9800fec482e02ff06.

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
