### ISSUE TITLE
Amplitude of DIO channels decreases as frequency is increased

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#391]
Scopy build: [6bd70752](https://github.com/analogdevicesinc/scopy/commit/6bd7075292413ee0bba502c76e9e49a29a5f4a04)

Steps to reproduce:

Enable DIO1. Set pattern as clock
then monitor its output on oscilloscope
Enable measure to view amplitude reading
In pattern generator start with 5kHz and increase until 25MHz.

result: 
when f = 5kHz, Amplitude = 3.296V
when f = 1MHz , Amplitude = 3.047V
when f= 25MHz, Amplitude = 2.590V

Amplitude should be around 3.3V

**Comment by ccarbunaru** [comment]
Hi, 
You are reading different values at different frequencies because of the bandwidth limitation of the oscilloscope.
You can try measuring with a bench instrument ( oscilloscope ).

**Comment by rgetz** [comment]
yeah, the -3dB point is the "bandwidth" of the scope.

3.3V subtract -3dB, should be about 2.3V, (or about 1 over root(2)) so as long as the -3dB point of the scope is 25MHz, and it is reading above 2.3V, it's within spec.

-Robin
