### ISSUE TITLE
Digital IO window disrupted when detatched

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#393]
Scopy build: [2e31a757](https://github.com/analogdevicesinc/scopy/commit/2e31a7574540fe2c456235e9800fec482e02ff06)

Open Scopy and stay in minimum window size, detach DIgital IO instrument.
As seen in the picture below, the interface is disrupted.
The digital IO window has no limit in its minimum length thus the disruption. 

![av](https://user-images.githubusercontent.com/25096080/37336910-c1df33e6-26ed-11e8-9d27-e8760463ae3f.PNG)

![aav](https://user-images.githubusercontent.com/25096080/37336909-c1ab55a8-26ed-11e8-830e-42982645c87f.PNG)

**Comment by adisuciu** [comment]
Fixed with  8f98fbe

**Comment by amiclaus** [comment]
On Scopy build: 355a04c (v0.11) the bug is fixed.
