### ISSUE TITLE
Power supply instrument does not function

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#395]
Scopy build: [2e31a75](https://github.com/analogdevicesinc/scopy/commit/2e31a7574540fe2c456235e9800fec482e02ff06)

The power supply does not work, both positive and negative

![aasa](https://user-images.githubusercontent.com/25096080/37339855-05f85072-26f7-11e8-8910-6ae501dcb7e5.PNG)

**Comment by mirceacaprioru** [comment]
The power supply now uses calibration attributes. In order to get ensure correct functionality you have to manually copy m2k_calib.ini on the M2K mass storage drive. The file is attached here.

**Comment by rgetz** [comment]
Shouldn't either Scopy use some defaults, or the firmware be updated to make sure a file is there? Still smells like an issue to me.

**Comment by mhennerich** [comment]
https://github.com/analogdevicesinc/buildroot/commit/01c8805e605a84d072ba2543a8bbf505c21fea88

The firmware was already updated to provide the default if both the user or factory calibration files are missing. I shared a firmware build with Mircea to use for testing until we release an new official build.

**Comment by rgetz** [comment]
Ok - sounds great - can you also send that to @tagoylo as well?

**Comment by mhennerich** [comment]
done

**Comment by amiclaus** [comment]
Since all the [test results](https://pl.web.analog.com/hpt/GlobalAlliancesSharing/_layouts/15/WopiFrame.aspx?sourcedoc=/hpt/GlobalAlliancesSharing/Shared%20Documents/Scopy%20QA/v0.11/power_supply_-_test_case.xlsx&action=default) for the Power Supply (v0.11) passed, I will close the issue.
