### ISSUE TITLE
Digital IO: IN and OUT function is reversed

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#396]
Scopy build: [2e31a75](https://github.com/analogdevicesinc/scopy/commit/2e31a7574540fe2c456235e9800fec482e02ff06)

when the channel is set to IN, what it does is it functions as OUT

when the channel is set as OUT, it functions as IN.

Steps to reproduce:
Connect DIO0 and DI01
Set DIO0 as OUT, and DIO1 as IN
You'll notice that as you run the instrument and change the logic level of DIO0, which is configured as out,  there is no response in DIO1.
But when changing the logic levels of DIO1, configured as IN, there is a response in DIO0.

![mmm](https://user-images.githubusercontent.com/25096080/37341483-8251973c-26fc-11e8-9144-5b405ac2dc1c.PNG)

**Comment by adisuciu** [comment]
Fixed with  5634194

**Comment by amiclaus** [comment]
On Scopy build: 1ead1e1 (v0.11) the bug is fixed.
