### ISSUE TITLE
Contrast of position and reading when changing min/max freq

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#397]
Scopy build: [1ead1e18](https://github.com/analogdevicesinc/scopy/commit/1ead1e18eabc2d7cf519fce86775cd3ce9f67413)

Steps to reproduce:
340Hz LPF
run network analyzer with min freq = 10Hz and max freq = 500kHz
Enable cursor and move to -3dB of the trace.
Then change max freq to 50 kHz.

It can be noticed that the position does not correspond to the reading. 
It will only update when the user moves the cursor.
![mog](https://user-images.githubusercontent.com/25096080/37390521-5609baae-27a3-11e8-87c9-d6e421188713.PNG)

**Comment by claudiupop** [comment]
Fixed with 09b64c88293af101efd530aa1f1ea8555358df69

**Comment by amiclaus** [comment]
On Scopy build: 1a38185 the bug is fixed.
