### ISSUE TITLE
Headers in preferences is a mess

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#399]
Scopy build: [c40394f9](https://github.com/analogdevicesinc/scopy/commit/c40394f911bcf026f1d27cb0044164a2312a4d84)

Go to preferences, you can see the headers are in a mess. This happens in either minimum window or full window. 

![newby](https://user-images.githubusercontent.com/25096080/37699243-a1477226-2d21-11e8-822c-b0a7258aa951.PNG)

**Comment by claudiupop** [comment]
Fixed with e59026f6116ef8002eede07f62cda061ca04261b

**Comment by amiclaus** [comment]
On Scopy build: 1beb185 (v0.11) the bug is fixed.
