### ISSUE TITLE
Add Thickness option for other Instruments

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#405]
A good idea would be to add thickness option for Network Analyzer plots (and maybe also for Spectrum Analyzer).

This will improve the visibility of the plots especially when taking captures that will be used afterwards.

**Comment by claudiupop** [comment]
Implemented with https://github.com/analogdevicesinc/scopy/pull/442

**Comment by amiclaus** [comment]
Can we do this also for Spectrum Analyzer? It might be helpful especially when the plot scale is in Volts (Vpeak, Vrms)

**Comment by claudiupop** [comment]
On spectrum analyzer, if we set a higher thickness for the curve, the application will work very slowly because there are too many points to be rendered. We will think for a solution to avoid this.

**Comment by HRosete** [comment]
This is implemented in Scopy v1.2 (verified on 33ca72f9)on Network Analyzer. Closing this item.
