### ISSUE TITLE
Value and unit overlaps in minimum window

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#407]
scopy build: [90429741](https://github.com/analogdevicesinc/scopy/commit/9042974137a2463737fa8381b015ee96d6674ba7)

Value and unit overlaps in minimum window
The interface looks like the picture below
![1](https://user-images.githubusercontent.com/25096080/38600834-2a998470-3d98-11e8-9850-8309e683b7ac.PNG)

**Comment by adisuciu** [comment]
f85804a0435b8124a2ed3a4d771c31c2cff8b279 should fix it

**Comment by amiclaus** [comment]
On Scopy build: 87e17a9b the bug is fixed.
