### ISSUE TITLE
Instrument stopped while one output still running

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#408]
Scopy build: 9042974 

Enable both Positive and Negative Power Supply.
Then, disable one of them.

In the Instrument menu Power Supply looks like instrument is stopped, while one of the output is still enabled.
![image](https://user-images.githubusercontent.com/26061529/38733327-2804a3c8-3f2a-11e8-8b81-b7d42fd83fa0.png)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/4e7d56ecd458b17866ba69d9c3285af3ddfc83eb

**Comment by amiclaus** [comment]
On Scopy build: 87e17a9b the bug is fixed.
