### ISSUE TITLE
PatternGenerator output forced low while configuring

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#409]
While configuring the device, the output is forced low. This causes some issues for some pattern generator application like writing a single UART message. Screenshot is attached.

1. PatternGenerator is idle. It is kept up with a locally installed pullup to the +2V powersupply
2. PatternGenerator reconfigures and receives the buffer from Scopy.
3. PatternGenerator outputs the buffer.

![m2k_pattern_gen_bug](https://user-images.githubusercontent.com/8676912/38986981-e9936906-43d6-11e8-9a7d-e026e6f5ad91.png)

**Comment by adisuciu** [comment]
Fixed with  3ab98e0

**Comment by amiclaus** [comment]
On Scopy build: 87e17a9 the bug is fixed.
