### ISSUE TITLE
+/- does not work 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#411]
Scopy build:  [f2c402a](https://github.com/analogdevicesinc/scopy/commit/f2c402a96bf4ef1a12bcc6f3503dc5894aed5cb2)

Upon launch, open power supply.
Try clicking on +/- on either positive or negative supply, it doesn't work
It will work only after the user changes the value by entering in the box. 

![2](https://user-images.githubusercontent.com/25096080/39114962-fbeddc50-4712-11e8-91d9-2dc5d687d2d3.PNG)

**Comment by amiclaus** [comment]
On Scopy build: 87e17a9b the bug is fixed.
