### ISSUE TITLE
+/- for horizontal position doesn't work 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#423]
Scopy build: [5af87b4e](https://github.com/analogdevicesinc/scopy/commit/5af87b4eb49eb576387e972cb58213495adc2252)

Upon launch, open oscilloscope.
Try clicking on +/- of horizontal position, it doesn't work on both channels.
It will work only after the user changes the value by entering in the widget or by moving the cursor.

![bug o](https://user-images.githubusercontent.com/25096080/39700052-5b05982e-522e-11e8-9a6b-31838b78e328.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit a57d0f56ae663a422f6aaa3c716ae45e1c8a61f0.

**Comment by tagoylo** [comment]
On Scopy build: [`70fb08da`](https://github.com/analogdevicesinc/scopy/commit/70fb08da741b42f0a0b985f4e1804f8bee2de8a1), the bug is fixed.
