### ISSUE TITLE
Spectrum Analyzer: Trace Types

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#424]
The Spectrum Analyzer Features different trace type:

![spectrum trace type](https://user-images.githubusercontent.com/20266602/39742781-54f2e7f6-528e-11e8-9f1b-40adaf3bcfdb.png)

I'm currently not very familiar with all of these trace types but I can only get a response on Peak Hold Continuous and Min Hold Continuous mode. 
Are the other modes already implemented on Scopy? 
I compared it with Analog Discovery's Spectrum Analyzer. Analog Discovery's Spectrum Analyzer Trace type provide different response to the signal.

**Comment by adisuciu** [comment]
What do you mean you only get response from PeakHold and MinHold.

All of them are implemented, you will get more diverse results if you put in a higher averaging value.

**Comment by drbautista** [comment]
oh yeah, I think I may have missed changing the average value.
All of the trace types work Adrian. 

Thanks a lot. I'm closing the issue.
