### ISSUE TITLE
Phase widget issues: value of phase changes 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#425]
Scopy build: [`70fb08da`](https://github.com/analogdevicesinc/scopy/commit/70fb08da741b42f0a0b985f4e1804f8bee2de8a1)

Ways to reproduce behavior:

- enter values in phase widet, ex. 45, after hitting enter, the value will become 46

- click +/- of either Duty or Frequency, the value of phase will increase by 1.

- Enter value to either Duty/Frequency, the value of phase will increase by 1.

- Enter 0 value in phase then hit enter, it will show 1. Then hit enter again, and the value of phase will increase.

**Comment by amiclaus** [comment]
On Scopy build: 01f2750 (v0.12) the bug is fixed.
