### ISSUE TITLE
After switching between devices before calibration is finished the connect button becomes disabled.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#426]
Scopy build: 70fb08d

Add IP device (i.e. 192.168.2.1)

Connect to the USB device.

As soon as available, switch to the IP Device tab and click connect.

Since connection with IP device is made before for the calibration on the USB device is finished, the connect button for the USB device is permanently disabled.

![image](https://user-images.githubusercontent.com/26061529/39804904-07feab4c-537e-11e8-8bc0-1cd99350978e.png)

Scopy restart is required.

**Comment by AlexandraTrifan** [comment]
Fixed with 90a8319b14d1d19a0e5721a2e90686cd6ebe1712.

**Comment by amiclaus** [comment]
On Scopy build: 07076df (v0.12) the bug is fixed.
