### ISSUE TITLE
Write/Read switch label in I2C pattern is reversed

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#427]
Scopy build: [`70fb08da`](https://github.com/analogdevicesinc/scopy/commit/70fb08da741b42f0a0b985f4e1804f8bee2de8a1)

Steps to reproduce:

Group 2 channels together and set pattern to I2C.

On the settings for I2C pattern, write/read mode switch label is reversed.

The highlighted letter is R, but the mode is in write. 

And when in read mode, the highlighted letter is W.

![bigblackbug](https://user-images.githubusercontent.com/25096080/39805684-2c3fe38c-53aa-11e8-86e7-5ddbbe6e1cac.PNG)

**Comment by adisuciu** [comment]
Fixed with  3fd36b1

**Comment by amiclaus** [comment]
On Scopy build: 07076df (v0.12) the bug is fixed.
