### ISSUE TITLE
Space between save icon and save text

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#428]
Scopy build: [70fb08da](https://github.com/analogdevicesinc/scopy/commit/70fb08da741b42f0a0b985f4e1804f8bee2de8a1)

There's no space between save icon and save text, compared to load.
![bugb](https://user-images.githubusercontent.com/25096080/39807856-fc109a20-53af-11e8-9ab0-239d1415396d.PNG)

**Comment by claudiupop** [comment]
Fixed with d8840c91be37fef2b95856a0b27c923dcb2d282d

**Comment by amiclaus** [comment]
On Scopy build: 07076df (v0.12) the bug is fixed.
