### ISSUE TITLE
Ability to Turn All Displayed Knobs

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#43]
For a future enhancement, it would be good to be able to turn the displayed knobs in addition to the up/down controls and direct entry.

**Comment by DanielGuramulta** [comment]
With commit: af2b463 you are now able to turn the knob with the mouse scroll wheel.

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the feature is implemented.
