### ISSUE TITLE
Moving cursor to rightmost side makes it distorted

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#430]
Scopy build: [3fd36b16](https://github.com/analogdevicesinc/scopy/commit/3fd36b16da015e871bb357264e4a1e181d01b40f)

Steps to reproduce:

Enable cursors.
Move cursors to rightmost side, it will now be distorted, as shown below.
It happens in both minimum and full window.

![bug to besh](https://user-images.githubusercontent.com/25096080/39859359-2fed76f8-546c-11e8-9736-ab26766685c8.png)

**Comment by claudiupop** [comment]
Fixed with 07076df19f821732355729f28855a43ecea9340b

**Comment by amiclaus** [comment]
On Scopy build: 07076df (v0.12) the bug is fixed.
