### ISSUE TITLE
plot gets messed up when changing min and max frequency and sample

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#431]
Scopy build: [3fd36b16](https://github.com/analogdevicesinc/scopy/commit/3fd36b16da015e871bb357264e4a1e181d01b40f)

Steps to reproduce:

Run network analyzer 
Then change either the min/max frequency or the sample count.
The result is shown below.
It starts plotting on the part when you changed any of the configurations, but the previous trace is gone.

![bug din to beshhyy](https://user-images.githubusercontent.com/25096080/39859967-3317e56e-546e-11e8-957e-1fd20201c9d7.PNG)

**Comment by adisuciu** [comment]
So you are saying that by modifying min and max frequency, the plot curves are scaled to the new plot area ? If so, I don't think this is a bug.

**Comment by adisuciu** [comment]
Nevermind, I understand now. You were saying changing values while the instrument is running. We will disable those buttons while the instrument is running.

**Comment by tagoylo** [comment]
Keep network analyzer running then modify min/max frequency. A  new plot area will show. But the start of the new plot curve does not begin at the specified min frequency. Instead, it starts plotting at the point where the previous plot curve stopped.

**Comment by adisuciu** [comment]
Fixed with 39bf685

**Comment by amiclaus** [comment]
On Scopy build: 07076df (v0.12) the bug is fixed.
