### ISSUE TITLE
Logic analyzer - trigger does't correctly load from file

### ISSUE THREAD

**Issue by mirceacaprioru** [analogdevicesinc/scopy#434]
Steps:
1. Set rising edge trigger on Channel0
2. Run logic analyzer observe waiting state
3. Close scopy
4. Open scopy and run logic analyzer
5. Instrument is triggered.

**Comment by AlexandraTrifan** [comment]
Should be fixed with commit 08e038424a06bf7056c2ac0f433bca659a2ad672.

**Comment by amiclaus** [comment]
On Scopy build: 01f2750 (v0.12) the bug is fixed.
