### ISSUE TITLE
Measure: Custom Selection Drop-Down Issue

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#436]
Scopy build: 7d7f313

Click several times on different parts of the "Horizontal"/"Vertical" drop-down menu. Sometimes the drop-down list appears from the first click, sometimes it doesn't.

Also, when putting the mouse at the bottom of the drop-down list, it automatically scrolls down.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/0775755cd8bb8cbcf359ac75942a60009b82ce0a

**Comment by amiclaus** [comment]
On Scopy build 01d69df (v1.0.1) the bug is fixed.
