### ISSUE TITLE
Binary Counter Frequency Issue

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#437]
Scopy build: 7d7f313

Group DIO0 - DIO3 and set the Binary Counter pattern.

Set Frequency to 50KHz. 
The output pattern is correct (4 bit counter):
![image](https://user-images.githubusercontent.com/26061529/40224976-7a553486-5a90-11e8-9591-4dcc61c3f4c6.png)

Set Frequency to 51KHz.
The output is now corresponding to a 3-bit binary counter:
![image](https://user-images.githubusercontent.com/26061529/40225048-ad19410a-5a90-11e8-94ba-58cb0129184b.png)

This issue is valid for multiple frequency intervals.

**Comment by adisuciu** [comment]
Fixed with 36713226af6073ed0c3fb8e95689f19026d56544

**Comment by amiclaus** [comment]
On Scopy build: 01d69df (v1.0.1) the bug is fixed.
