### ISSUE TITLE
Option to add signals from multiple instruments in a single plot

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#439]
Do we want to have an option to add signals from multiple instruments in a single plot? Same operations on signals, but display signals in a single plot, may be called "Workspace plot".
![enh2](https://user-images.githubusercontent.com/13637543/40299752-f251fa6c-5cef-11e8-8fff-7874081e048d.png)
![enh](https://user-images.githubusercontent.com/13637543/40299757-f5268a50-5cef-11e8-87ce-51f376673adc.png)

**Comment by adisuciu** [comment]
Implemented with Scopy v1.2.0
