### ISSUE TITLE
Function Generator Initial Waveforms

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#44]
The "Sine" waveform initializes as swinging between +5 V and -5 V, while the others swing between 0 V and +5 V.  It would be good if all initial waveforms were the same -- swinging between +2 V and -2 V?

**Comment by pcercuei** [comment]
They all swing between +5V and -5V now, I fixed this a couple of days ago.

**Comment by rgetz** [comment]
Jon:

Can you try out the nightly build, and see if this is fixed?
