### ISSUE TITLE
Sweep messed up when changing SG waveform type

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#449]
Scopy version: 04c9271

Run a Sweep on Network Analyzer:

![image](https://user-images.githubusercontent.com/26061529/42322871-bc319f56-8066-11e8-8473-a4f4acd3f78b.png)

Open Signal Generator, change waveform type from Sine to i.e. Square.

Run Signal Generator.

Stop Signal Generator and run Network Analyzer again with the same configuration.

![image](https://user-images.githubusercontent.com/26061529/42322931-fe681f9e-8066-11e8-86c5-9f146191c986.png)

Sweep is messed up.

**Comment by adisuciu** [comment]
Fixed with 5603a49

**Comment by amiclaus** [comment]
On Scopy build: 01d69df (v1.0.1) the bug is fixed.
