### ISSUE TITLE
Function Generator Output Frequency Accuracy

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#45]
Ken Connor noted that when he set up the function generator to generate a 1 KHz sine wave, he measured 750 Hz on the Scopy oscilloscope.  I was able to duplicate this and verified that the error is in the function generator, not the oscilloscope.

**Comment by pcercuei** [comment]
Sorry, I can't reproduce. Make sure you use the very latest boot files.

**Comment by rgetz** [comment]
I think this is fixed now. Closing.
