### ISSUE TITLE
Items overlap in Preferences menu

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#455]
Scopy v1.0

OS X v10.11.6

Checkboxes and text overlap

![screen shot 2018-07-13 at 18 01 02](https://user-images.githubusercontent.com/26061529/42698588-0624ce7e-86c7-11e8-8bbc-4f8440f8b8d3.png)

**Comment by AlexandraTrifan** [comment]
Tested the build for v1.2.0 release candidate on MacOS 10.15 Catalina ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/oxx7gqvvslv7gf19/artifacts ) and this overlapping no longer happens. 
Marking this as fixed and closing.
