### ISSUE TITLE
Scopy crashes on Spectrum Analyzer

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#456]
Scopy version 1.0

OS High Sierra (10.13)

Open Spectrum Analyzer.

Run/Stop Instrument several times.

Scopy crashes.

This issue is avaliable only for Spectrum Analyzer.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 580b3466bcbc772920ac81d1e6c3f970ff20fab6.

**Comment by amiclaus** [comment]
On Scopy build: e3b2b4e1 (v1.0.1) the bug is fixed.
