### ISSUE TITLE
Logic Analyzer - add samplerate and number of samples

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#458]
Logic analyzer sample rate and number of samples should be configurable.
Timebase should only be a visual zoom. 
Timebase/position should also be specified in samples instead of time.

**Comment by AlexandraTrifan** [comment]
This was added on the latest master once the Logic Analyzer was revamped. Now it only has UI controls for sample rate and number of samples. This can be tested using the following build ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/reoavcxghvtlk75c/artifacts ).
Will be available in the following release, v1.2.0.
