### ISSUE TITLE
Logic Analyzer - enable stacked decoders

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#460]
Stacked decoders are present in Pulseview but not enabled in Scopy. They should be enabled.

**Comment by AlexandraTrifan** [comment]
This was added on the latest master once the Logic Analyzer was revamped. Now any added decoder detects what other decoders can be stacked and lists them in the appropriate menu.
This can be tested using the following build ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/reoavcxghvtlk75c/artifacts ).
Will be available in the following release, v1.2.0.
