### ISSUE TITLE
Cursor dots in track mode remain after cursor is disabled

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#465]
Scopy version:  [c61d5921](https://github.com/analogdevicesinc/scopy/commit/c61d5921948688ae5d829e0bb9dfb72cfec97e38)

Steps to reproduce:

Enable cursor
Then select Track
then disable cursor

As seen, the two dots are left displayed on the screen.

![bug1 1](https://user-images.githubusercontent.com/25096080/43386550-87a56e2a-9416-11e8-8def-3a8d03d25de5.PNG)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 01d69df8034b684733b406e720e467fd5ff2fcab.

**Comment by amiclaus** [comment]
On Scopy build 01d69df (v1.0.1) the bug is fixed.
