### ISSUE TITLE
Cursor horizontal lock issue

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#466]
Scopy version: [01d69df8](https://github.com/analogdevicesinc/scopy/commit/01d69df8034b684733b406e720e467fd5ff2fcab)

Horizontal cursor moves on its own and messes with the lock configuration set by the user.

Steps to reproduce

Reset Scopy first
Enable Cursor
Move one of the horizontal cursors
Enable Horizontal cursor lock
Then Move horizontal cursors

As observed, the other horizontal cursor, which was not moved earlier, moves on its own and messes with the lock configuration set by the user.
![buuug](https://user-images.githubusercontent.com/25096080/43435078-f7b8a4bc-94b0-11e8-84e7-b5e77a88b5d3.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/850638f3556f4014f7c363d2e7298c01a6595edd

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
