### ISSUE TITLE
Move Instrument Preferences to General Settings.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#468]
I think that moving the instrument preferences to the settings panel for each instrument might be more user friendly.

For example, I want to change preferences from Oscilloscope (enable labels on plot, enable graticule).

If I want to see the effect of these settings, each time I enable one of them I have to switch to Preferences panel and then back to the Oscilloscope panel and notice the changes. This might sometimes become annoying for the user (if he is not aware of the detach instrument option or prefers not to use it).

There is enough space in the settings panel to add the preferences.
![image](https://user-images.githubusercontent.com/26061529/43461748-e6eacb3e-94dc-11e8-9450-19db646c0dc7.png)

**Comment by adisuciu** [comment]
I would rather have them in the preferences menu. That's why we created it. As more options pile up, it makes sense having them all in one place.
