### ISSUE TITLE
Phase value changes when changing freq from 10MHz to 25MHz

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#469]
Scopy version:  [01d69df8](https://github.com/analogdevicesinc/scopy/commit/01d69df8034b684733b406e720e467fd5ff2fcab)

Steps to reproduce:

Enable a channel.
Increase clock frequency until 10MHz.
Then increase frequency again to 25 MHz (14 MHz when in fine interval).
As observed, the phase value becomes 270 from 0.
Then increasing further the frequency changes again its value. And decreasing the frequency would decrease phase.

**Comment by adisuciu** [comment]
Fixed with 7e560ab

**Comment by amiclaus** [comment]
On Scopy build: 7e560ab (v1.0.1) the bug is fixed.
