### ISSUE TITLE
Scopy Windows Installer

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#47]
The  Windows installer for Scopy forces a shutdown / restart without warning the user that it is about to happen. This is bad form. You need to clearly state that a re-start is needed before Scopy can be run but ask the user if it is OK to do it now or wait for them to save / close any apps that might be running first.

**Comment by pcercuei** [comment]
The installer clearly warns about the reboot and even gives you the option to perform the reboot yourself. See attached screen capture.

![ask_for_restart](https://cloud.githubusercontent.com/assets/403272/21100212/205b3038-c073-11e6-8f10-420fbffce96d.png)

You don't have that?

**Comment by damercer** [comment]
Not on my ADI issued Windows 7 laptop it doesn't. I tried twice. Otherwise why would I have posted the issue? Your response sounded like I just didn't see it or something.

**Comment by pcercuei** [comment]
So what installer are you using?

**Comment by rgetz** [comment]
I just tried the Alpha-2, and it shows things on my laptop.

-Robin
