### ISSUE TITLE
"Binary Counter" does not fit in the box

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#470]
Scopy version: [01d69df8](https://github.com/analogdevicesinc/scopy/commit/01d69df8034b684733b406e720e467fd5ff2fcab)

"Binary Counter" does not fit in the box.
Below is the screenshot of the issue.

![buggs](https://user-images.githubusercontent.com/25096080/43508873-a95fd0bc-95a3-11e8-9eb0-48896ac7b491.PNG)

**Comment by adisuciu** [comment]
fixed with  e3b2b4e

**Comment by amiclaus** [comment]
On Scopy build: e3b2b4e (v1.0.1) the bug is fixed.
