### ISSUE TITLE
Dots on cursor reappear even when cursor is disabled

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#472]
Scopy version: [01d69df8](https://github.com/analogdevicesinc/scopy/commit/01d69df8034b684733b406e720e467fd5ff2fcab)

Steps to reproduce:

Run network analyzer.
Enable Cursor.
Then disable Cursor.
Dots and the cursor are now not displayed.
Then by clicking among any of the following, the dots reappear:

- general settings icon
- instrument settings icon
- logarithmic/linear
- Min Freq
- Max Freq
- Max Magnitude
- Max Phase

As observed the dots reappears on the plot.

![bugse](https://user-images.githubusercontent.com/25096080/43570815-dbe32348-966d-11e8-928e-2e2c30342301.PNG)

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/c600154f8e926bdedaf0717335b27244c96b9685

**Comment by amiclaus** [comment]
On Scopy build: 7e560ab (v1.0.1) the bug is fixed.
