### ISSUE TITLE
Part of the cursor measurement is cut when positioned below

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#473]
Scopy version: [01d69df8](https://github.com/analogdevicesinc/scopy/commit/01d69df8034b684733b406e720e467fd5ff2fcab)

As seen in the picture below, part of the cursor measurement on magnitude is cut when positioned at the lower part of the plot.
This happens even when in full screen.

![bugss](https://user-images.githubusercontent.com/25096080/43571692-32b53452-9670-11e8-93f5-bac71ed66fd1.PNG)

**Comment by claudiupop** [comment]
Do you have screen scaling enabled?

**Comment by tagoylo** [comment]
Yes. I was at 125% when this happened. Today I checked with 100% and the issue does not show.

**Comment by adisuciu** [comment]
We cannot really guarantee that things won't look weird with Windows scaling enabled.
