### ISSUE TITLE
Signal shape modifies on Rise/Fall Time at specific frequencies

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#478]
Scopy version: e3b2b4e (v1.0.1)

Generate Square Wave at 200Hz and plot the signal's rise/fall time.

![image](https://user-images.githubusercontent.com/26061529/43641694-50b46d7a-972d-11e8-9308-d87f04c0f61a.png)

Set frequency to 400Hz.
![image](https://user-images.githubusercontent.com/26061529/43641730-73202f16-972d-11e8-9b15-74b4ed013484.png)

Set frequency to 600Hz.

![image](https://user-images.githubusercontent.com/26061529/43641766-8e138714-972d-11e8-8401-36aa67a2d78b.png)

At any other frequency, the signal looks fine. (Picture below is at 201Hz)

![image](https://user-images.githubusercontent.com/26061529/43641821-be19badc-972d-11e8-971a-e7d6bce9e8cb.png)

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/scopy/commit/a3ab408ce4106367c149404caf872bae77edfb8a

**Comment by amiclaus** [comment]
Shot taken at 400Hz:
![image](https://user-images.githubusercontent.com/26061529/43706881-3e448cda-996f-11e8-81c2-7e39c16c338a.png)

**Comment by amiclaus** [comment]
Also, there is a significant difference in the rise/fall time i.e. between 200Hz and 201Hz.

200Hz
![image](https://user-images.githubusercontent.com/26061529/43708367-f5a3e346-9972-11e8-8dee-921d3a151b94.png)

201Hz
![image](https://user-images.githubusercontent.com/26061529/43708398-0878fe02-9973-11e8-8379-c08031be1651.png)

**Comment by adisuciu** [comment]
Fixed with 272b2454be569e85e99bd9b98ad029f0174d46be

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
