### ISSUE TITLE
Scopy crashes on Cursors Settings

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#481]
Scopy build: 7e560ab

Enable Cursors.

Open Cursors Settings Panel.

Scopy crashes.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/d38f2f1e187c21dfb54c54c9a79a07ec00380638

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
