### ISSUE TITLE
Scopy crashes when loading waveform file on Buffer

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#482]
Scopy version: [7f54d454](https://github.com/analogdevicesinc/scopy/commit/7f54d454f490effdfdedc3c29d01bd8f16d7e0c7)

Load a .csv file on signal generator's buffer. Scopy then crashes after few seconds.
![buuugh](https://user-images.githubusercontent.com/25096080/43751883-54e0f506-9a31-11e8-9755-2c04704e79fd.PNG)

Similar to Item #433 

Here is the .csv file that I used.
[Stair-step.zip](https://github.com/analogdevicesinc/scopy/files/2266045/Stair-step.zip)

**Comment by rgetz** [comment]
Can you include the csv file to the bug tracker?

Thanks

**Comment by tagoylo** [comment]
Edited the issue above and attached the .csv file I used. 
Thanks

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/d38f2f1e187c21dfb54c54c9a79a07ec00380638

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
