### ISSUE TITLE
Poor Vertical resolution?

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#486]
Why is the vertical resolution so poor when Channel 2 is set to 20 mV/Div? Looks like the LSB is 14 mV. Souldn't it be about 10X better?

![image](https://user-images.githubusercontent.com/11668458/44346088-1a043100-a463-11e8-8816-31f1f65c7b84.png)

I'm trying to reproduce a new SHA experiment I developed for M1k on M2k. I'm trying to measure the hold mode pedestal step which is only about 5 mV.

Doug

**Comment by adisuciu** [comment]
It looks like channel 2 is in low-gain mode, although it should be in high-gain. I'm investigating.

**Comment by adisuciu** [comment]
It looks like you have a corner case where you set the position at -2.5V . 

This line sets the limits for low/high gain for the channels based on what can be viewed on the plot:
https://github.com/analogdevicesinc/scopy/blob/master/src/oscilloscope.cpp#L3918

We're still investigating, but this might not be a bug.

**Comment by damercer** [comment]
It most certainly is a bug. You are not using the DC offset to it's 
fullest extent.

The hardware is capable of this combination because I do it ( and larger 
offsets ) using iiolib and Python.

Doug

**Comment by damercer** [comment]
It doesn't look like you are using the hardware offset DAC AD5625?
The four channels in the AD5625 are used to offset the two AWG channels and two Scope channels.
Have you figured out how to use the HW offset functionality yet? Sorry if I seem surprised this major hardware feature has not been implemented.
After importing iio into Python and connecting to M2k I access the channels by:

```
# Offset DACs
ad5625 = ctx.find_device("ad5625")
AWG1Offset = ad5625.find_channel("voltage0", True)
AWG2Offset = ad5625.find_channel("voltage1", True)
Scope1Offset = ad5625.find_channel("voltage2", True)
Scope2Offset = ad5625.find_channel("voltage3", True)
```

Converting from requested voltage to raw binary is done much like the other paths in the hardware.

The amount of HW offset you can introduce is also a function of the input common mode voltage i.e. the voltage on the - scope input vs ground.

Doug

**Comment by mbanciso** [comment]
will change to support +-5V offset on High Gain mode

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
