### ISSUE TITLE
Logic Analyzer: Delta t display issue

### ISSUE THREAD

**Issue by mirceacaprioru** [analogdevicesinc/scopy#489]
When calculating a period or frequency using the cursors the value is not displayed completely. 

![screenshot from 2018-09-05 17-33-51](https://user-images.githubusercontent.com/8693228/45137700-7a5cd780-b1b2-11e8-8d5f-98b668b0b487.png)

**Comment by AlexandraTrifan** [comment]
The Logic Analyzer was revamped for this release. Using this build ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/reoavcxghvtlk75c/artifacts ) which is the build prepared for the release candidate v1.2.0, this bug no longer applies. Now the cursors are displayed on the plot, similar to the ones used in the Oscilloscope Tool. 
Closing this issue.
