### ISSUE TITLE
Cursor line is uneven outside the plot area

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#490]
Scopy build: [27349d52](https://github.com/analogdevicesinc/scopy/commit/27349d52299c6a99cd33f4afdbb60dae5b81440f)

As seen below, the cursor line is uneven outside the plot area.

![dd](https://user-images.githubusercontent.com/25096080/45292936-50e0da80-b529-11e8-8d93-cfcbe1dd27d4.PNG)

**Comment by DanielGuramulta** [comment]
Do you have screen scaling enabled? If so, then it's the same issue as in here: https://github.com/analogdevicesinc/scopy/issues/473. If you don't have it enabled can you tell me what screen resolution your computer has because I am unable to reproduce the bug. Thank you!

**Comment by tagoylo** [comment]
Hi, yes I have screen scaling enabled. Also verified if screen scaling is off, the issue is not showing.

**Comment by adisuciu** [comment]
We cannot really guarantee that things won't look weird with Windows scaling enabled.
