### ISSUE TITLE
Oscilloscope sometimes triggers with one sample difference

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#491]
Steps to reproduce
- Feed in a high frequency signal (10MHz) to the oscilloscope
- Set timebase to 100ns/div
- Set trigger
- Observe that the signal doesn't always intersect with the trigger point

Could this be HDL related ?

**Comment by lxTHU** [comment]
Like this compare of [ADALM2000 vs Analog Discovery 2 vs PicoScope 2205](https://www.eevblog.com/forum/testgear/adalm2000-vs-analog-discovery-2-vs-picoscope-2205-(2010my)/) shows: AD2 with Overs=16 and achieve 1.6GHz effective rate and without the trigger issue. Thank you a lot~

**Comment by adisuciu** [comment]
Should be fixed with latest firmware version

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) with FW: v0.23 the bug is fixed.
