### ISSUE TITLE
Spikes show in the oscilloscope reading of pattern generator output

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#493]
Scopy version: [1d173e63](https://github.com/analogdevicesinc/scopy/commit/1d173e633165f0632036963f0b15180598c5add9)
OS: WIndows 10
Firmware version: 0.21

There are spikes showing up when monitoring the pattern generator output on the ocilloscope. 
This happens when time base is set to 50 ms and below.

Steps to reproduce:
Enable CH0.
Set clock frequency to 5 KHz with the duty cycle of 50%. 
Run instrument.
Monitor CH0 through Oscilloscope.
Set time base to 50 ms or below.
The waveform looks like the screenshot below.
![image](https://user-images.githubusercontent.com/25096080/46595536-6b4bab00-cb0b-11e8-9108-0aaea3c697cd.png)

**Comment by DanielGuramulta** [comment]
Should be fixed with commit: https://github.com/analogdevicesinc/scopy/commit/4c27bcc2da76d52d429599532a8486ba15e438b3

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
