### ISSUE TITLE
Lowering the Time Base on multiple groups in Logic Analyzer crashes Scopy

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#494]
OS Version: Windows 10 (10.0)
FW Version: v0.21
SW Version: 1d173e6

Steps to reproduce:

1. Create two groups of 3 in Logic Analyzer. Set "Parallel" as their pattern.
2. Lower the Time base up to 100us by clicking "-"
3. Monitor Logic Analyzer.

![bug_la](https://user-images.githubusercontent.com/43806793/46601328-4c571400-cb1f-11e8-8346-c951a1378d45.png)

This bug is similar to bug #222 the only difference is that this happens on multiple groups of 3 or more.

**Comment by adisuciu** [comment]
We put in a workaround with 6c95eb480420e2556ba1cb1728531d7ce3703e1d and 72c508191a5542fd76554964452a5b57d4d66acd

**Comment by adisuciu** [comment]
A proper fix will be implemented with the logic analyzer revamp

**Comment by AlexandraTrifan** [comment]
The Logic Analyzer was completely revamped for this following release, v1.2.0. Here is the link to a prepared build for the release candidate ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/reoavcxghvtlk75c/artifacts ).
The new Logic Analyzer has a different acquisition system and no longer crashes on time base changes.

**Comment by tagoylo** [comment]
This issue is fixed on the revamped logic analyzer. Closing this item.
