### ISSUE TITLE
Marker remain even if channel is disabled

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#495]
Scopy build: [1d173e63](https://github.com/analogdevicesinc/scopy/commit/1d173e633165f0632036963f0b15180598c5add9)
OS: Windows 10

Marker remain even if channel is disabled.

Steps to reproduce:
With AWG set to 10V 800kHz sinewave.
Run channel 1.
Enable marker 1 of channel 1.
Then disable channel 1.
The marker then remains on the plot.

![image](https://user-images.githubusercontent.com/25096080/46608394-39503e00-cb37-11e8-833b-c6217cb55aeb.png)

**Comment by adisuciu** [comment]
Fixed with a5009ba1b745193c8c5121bce039ce947aee4be3

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
