### ISSUE TITLE
Start and Stop frequency inc/dec buttons skips the kHz range

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#496]
Scopy build: [1d173e63](https://github.com/analogdevicesinc/scopy/commit/1d173e633165f0632036963f0b15180598c5add9)
OS: Windows10

Steps to reproduce:
In Sweep settings, set Start 0 Hz and Stop to 50 MHz.
Increase the start frequency by clicking '+'. 
Or decrease the Stop frequency by clicking '-'
As observed, the interval is from 0Hz, then it goes up to 1 MHz immediately.

**Comment by adisuciu** [comment]
Duplicate of https://github.com/analogdevicesinc/scopy/issues/179

**Comment by DanielGuramulta** [comment]
With commit: b247736 the issue is fixed.

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
