### ISSUE TITLE
Trigger settings button in logic analyzer does not close/hide when clicked

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#497]
Scopy build: [4c27bcc2](https://github.com/analogdevicesinc/scopy/commit/4c27bcc2da76d52d429599532a8486ba15e438b3)
OS: Windows 10

The trigger settings button in logic analyzer does not close or hide when clicked.

Steps to reproduce:
Open logic analyzer.
Then click the Trigger settings button to open the panel.
Then click again on the button to close/hide it.
As observed, it does not close/hide when clicked. 

![image](https://user-images.githubusercontent.com/25096080/46642551-71dd2f80-cbaa-11e8-817d-c86368e960c2.png)

**Comment by DanielGuramulta** [comment]
Should be fixed with commit: https://github.com/analogdevicesinc/scopy/commit/e3efb5903bd9b89aff8d275be25b43111a3c65b4

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
