### ISSUE TITLE
Animation in hiding other channel parameters in logic analyzer is not implemented

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#501]
Scopy Build: [27eebb88](https://github.com/analogdevicesinc/scopy/commit/27eebb880e1ca5b0f465163e9827a4fad6863917)
OS: Windows 10

Steps to reproduce:
Open preferences and Enable Animation
Open Logic Analyzer
Click on the arrow, boxed in the picture below 
When clicked there is no animation implemented although preferences have enabled the animation.

![image](https://user-images.githubusercontent.com/25096080/46709846-137e8280-cc78-11e8-956e-f971102774d9.png)

**Comment by adisuciu** [comment]
We cannot fix this right now as it touches a lot of areas of the Logic Analyzer. We plan a major Logic Analyzer redesign, and we'll keep this in mind.

**Comment by adisuciu** [comment]
This menu no longer exists in newest Scopy version.
