### ISSUE TITLE
Window size issue when detaching instrument

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#502]
Scopy version: d6b1429
OS: Windows

Select Oscilloscope instrument, then detach the instrument.
![image](https://user-images.githubusercontent.com/26061529/46793073-8279db00-cd4d-11e8-8775-65c7d28b9c82.png)

Maximize window and then restore to previous window size.
The default window size changes and it cannot me reduced to its initial size.
![image](https://user-images.githubusercontent.com/26061529/46793174-bce37800-cd4d-11e8-9b21-517227f62e12.png)

It comes back to initial size only after closing the detatched window, selecting the Osc instrument and detaching it again.

**Comment by DanielGuramulta** [comment]
Should be fixed with commit: https://github.com/analogdevicesinc/scopy/commit/4551dd3726f6ad3c11a2287d2e8592ba6e6ef422

**Comment by amiclaus** [comment]
On Scopy build: 97405f9c (v1.2.0) the bug is fixed.
