### ISSUE TITLE
Some spikes appear in the network analyzer sweep

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#504]
Scopy build: [2e7c0985](https://github.com/analogdevicesinc/scopy/commit/2e7c0985d19d17040e44baedf16849da14fe73fb)

Some spikes appear in the network analyzer sweep
Here I tried it with a LPF and the result is shown below at 100 samples and 200 samples

![image](https://user-images.githubusercontent.com/25096080/47337421-6b7ca680-d6c6-11e8-9a87-9fe2e731b78e.png)

**Comment by DanielGuramulta** [comment]
Bug fixed with pr: #571

**Comment by tagoylo** [comment]
In scopy version 85e5674, this issue is fixed. Warning appears "signal is <50mV" that tells the user that the results might be inaccurate, including spikes.
