### ISSUE TITLE
SpectrumAnalyzer: implement frequency axis log scale

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#508]
Have an option for the spectrum analyzer to switch the frequency axis to log scale.

https://ez.analog.com/university-program/f/q-a/103879/scopy-spectrum-analyzer-question

**Comment by DanielGuramulta** [comment]
Feature implemented with commit: afff1ad

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the feature is implemented
