### ISSUE TITLE
Logic analyzer: When changing Run Mode the plot becomes distorted

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#510]
Scopy build: [e54d2038](https://github.com/analogdevicesinc/scopy/commit/e54d2038ef09512594e1f8074d83d3368689cda4)
OS: Windows 7, Windows 10

Steps to reproduce:

Do not maximize the window.

Run pattern generator DIO0 as 5 KHz clock 
Run logic analyzer DIO0, trigger set to rising edge, Run mode - repeated
Then change run mode from repeated >> stream >> repeated
The distortion will show.

This does not show when window is maximized.

![image](https://user-images.githubusercontent.com/25096080/48826768-3e471500-eda6-11e8-9040-4e383c84074c.png)

**Comment by AlexandraTrifan** [comment]
Should be fixed with 91c4f0cb0367ebd8d5f2e26ea69c5ada9f2210b8.

**Comment by tagoylo** [comment]
On Scopy version f2eb3883 (v1.0.5), the bug is fixed.
