### ISSUE TITLE
Logic Analyzer: Enabled DIOs' Outputs are not working

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#511]
Scopy build: e54d2038
OS: Windows 7, Windows 10

Steps to reproduce:

Run Pattern Generator. Enable DIO0-DIO7 then group them.
Set Pattern to "Binary Counter" and Frequency to 5kHz.
Run Logic Analyzer. Select DIO0-DIO7.
Monitor outputs.

Issue:
DIO0's and DIO1's outputs are up and working. However, DIO2-DIO7 are not.
![image](https://user-images.githubusercontent.com/43806793/48885359-fafeac00-ee62-11e8-99f6-f00848427018.png)

**Comment by adisuciu** [comment]
We rolled back libiio to v0.15 with 8fd35c1  
We rebuilt scopy with the latest dependencies and it should now work correctly.
https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/20491135

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
