### ISSUE TITLE
unable to run pluto ?on the scopy download keeps saying device not identified ? 

### ISSUE THREAD

**Issue by bigdan74** [analogdevicesinc/scopy#512]
OS Version: Windows 10 (10.0)
FW Version: 
SW Version: 91c4f0c

Description of the bug:<description>
Steps to reproduce:
-
-

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/User/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Scopy only supports the ADALM2000 currently. It does not support Pluto.
