### ISSUE TITLE
Phase Display issue

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#515]
Scopy version: 91c4f0c

Measurement unit for phase is dB instead of degrees:

![image](https://user-images.githubusercontent.com/26061529/49377311-7dfced80-f712-11e8-9a98-c6ddfb3c6e61.png)

**Comment by DanielGuramulta** [comment]
Bug fixed with pr: #571

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
