### ISSUE TITLE
Use Oscilloscope to visualize data when Network Analyzer is running.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#517]
Currently, Oscilloscope is switched off when running NA.

When running a sweep, it might be helpful for the user to be able to visualize data in time domain  (especially for a better understanding of what happens behind the NA) using the Scope Channels. 
In this setup, the oscilloscope parameters that interfere with the NA configuration should be disabled.

**Comment by damercer** [comment]
This is especially helpful if the signal was to ever over-range the current gain settings i.e clip.

**Comment by DanielGuramulta** [comment]
Feature implemented with pr: #571

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the feature is implemented.
