### ISSUE TITLE
Yanking out the unit while streaming crashes

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/scopy#52]
We can't expect students to treat things nicely...

![image](https://cloud.githubusercontent.com/assets/1017869/23867906/d4f88992-07f3-11e7-8325-c2af0dc10d88.png)

**Comment by rgetz** [comment]
Alpha 0.2, run signal generator, and scope, and the unplug unit.

**Comment by pcercuei** [comment]
It should work in master now, for some of the tools (Voltmeter, Oscilloscope, Network Analyzer).
Removing the cable when one of those is running will just bring you back to the home screen of Scopy.

**Comment by pcercuei** [comment]
Fixed in 54d0492.
