### ISSUE TITLE
Pattern Generator / Logic Analizer support in scripting

### ISSUE THREAD

**Issue by easyvolts** [analogdevicesinc/scopy#520]
I'm not sure if it's the right place to suggest an enhancement to the Scopy, please correct me if needed. My suggestion is to add in the Scopy special commands to control Pattern generator and Logic analyzer from scripts (probably the commands should be similar to Linux ones), to let scripts interact with external hardware by means of standard interfaces (like I2C, SPI, UART, etc). It would add a huge value to the ADALM2000 device and make it a more flexible link between PC and the real world. Thanks!

**Comment by adisuciu** [comment]
Thanks for the suggestion, we'll look into it !

**Comment by adisuciu** [comment]
Tracked here https://github.com/analogdevicesinc/libm2k/issues/4
