### ISSUE TITLE
LogicAnalyzer - Only load decoders that take logic inputs

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#521]
Currently all decoders are loaded up and shown in the combobox. This is wrong since some of them don't take logic inputs but take other decoders as inputs (stacked decoders). 
Solution: Only load decoders that use "logic" as inputs until we enable stacked decoders

The issue was first mentioned here:
https://ez.analog.com/university-program/f/q-a/105599/how-to-do-usb-protocol-analysis-using-m2k

**Comment by AlexandraTrifan** [comment]
This was added on the latest master once the Logic Analyzer was revamped. 
The stacked decoders were enabled in this new Logic Analyzer. The decoders that can be added initially only accept "logic" inputs, and every added decoder displays in its menu the list of accepted stacked decoders. 
This can be tested using the following build ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/reoavcxghvtlk75c/artifacts ).
Will be available in the following release, v1.2.0.
