### ISSUE TITLE
Logic Analyzer - Export to CSV - extra comma at the end of the line

### ISSUE THREAD

**Issue by gotchafr** [analogdevicesinc/scopy#524]
Hello! Just a little detail that can cause some trouble: the export produces an extra comma at the end of the line. I don't think this is intentional. In any case, here is a fix for filemanager.cpp:

````
--- /home/gotcha/win10_desk/Projects/myM2k/moded_src/filemanager_original.cpp	2019-01-17 09:18:10.811413800 +0100
+++ /home/gotcha/win10_desk/Projects/myM2k/moded_src/filemanager.cpp	2019-01-16 22:06:04.547309700 +0100
@@ -281,7 +281,7 @@
         for (int i = 0; i < data.size(); ++i) {
                 exportStream << QString::number(i) << separator;
                 for (int j = 0; j < data[i].size(); ++j) {
-                        exportStream << data[i][j] << separator;
+                        exportStream << data[i][j] << ((j < data[i].size()-1) ? separator : "");
                 }
                 exportStream << "\n";
         }

**Comment by AlexandraTrifan** [comment]
Hi,

You can open a Pull Request for this as well, in order for us to review it and merge it into master.
On your forked repository, create a new branch for this fix, create a commit and sign it using --signoff in the git commit command (for example: git commit -m "You commit message" --signoff ) . This will add a line in your commit message, similar to the following: Signed-off-by: Your name <youremail@email.com> . 
 
Please let us know if you have any questions.
Thank you

-Alexandra

**Comment by gotchafr** [comment]
Hi,
should I branch on my last commit or on the v1.0.3 commit?
Cheers.

**Comment by AlexandraTrifan** [comment]
Hi,
You can use the latest analogdevicesinc/scopy master branch.

-Alexandra

**Comment by amiclaus** [comment]
Nitpick:
On Scopy build: e28686c (v1.0.5)
The header of the table: `Sample,Channel 0,Channel 1,` still contains an extra comma at the end of the line.
Should be a quick fix @AlexandraTrifan

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/586

fixed

**Comment by gotchafr** [comment]
Hi Adrian,
I just looked at your commit... I think there is a misunderstanding here:
The problem is the extra separators at the end of the line... And if I understand correctly you are now just skipping the first one.
Cheers.

**Comment by adisuciu** [comment]
Well, yes, but now I'm also adding the separator before the value.

**Comment by amiclaus** [comment]
@gotchafr you can check if the exported csv file corresponds to the standard by downloading the latest build: https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/24523906/job/fych5dkfvuk9xrt8/artifacts

If everything works fine, please let us know so we can close the bug.

**Comment by gotchafr** [comment]
Yes, of course... I should have looked better: the name of the flag tricked me.
Cheers!
