### ISSUE TITLE
running function generator at same time as scope, causes crashes

### ISSUE THREAD

**Issue by CElkhoury** [analogdevicesinc/scopy#53]
This is all I get: 

Unit it plugged into 5.5V AC adapter, so it is not a power issue.

Running the 0.1 firmware, and the 0.2 scopy.

open the oscilloscope, and click "run",
goto to the function generator, and click "run"

get this:

![image](https://cloud.githubusercontent.com/assets/5872946/23873851/e697348a-0809-11e7-9009-d0d90bccb1e7.png)

If there is any way to get more debug info, please let me know.
-Robin

**Comment by mhennerich** [comment]
0.1 had the limited USB endpoint issue.
You need to use the latest firmware.

-Michael

**Comment by rgetz** [comment]
Which is where? 
https://github.com/analogdevicesinc/m2k-fw/releases

**Comment by mhennerich** [comment]
check your email

**Comment by mhennerich** [comment]
created a new v0.11 release

-Michael

**Comment by rgetz** [comment]
Thanks
