### ISSUE TITLE
Add window triggering

### ISSUE THREAD

**Issue by AndreiGrozav** [analogdevicesinc/scopy#530]
A window trigger is defined by two adjustable amplitude thresholds and a time counter.

The possible new features adding some simple extra logic:

- Transition time triggering
- Width triggering (glitch, duty cycle, delay, time)
- Runt triggering
- Timeout triggering
- N shot trigger
- Some measurement capabilities

Transition time triggering, allows for triggers if the time interval from the low high to low thresholds(or vice versa) is slower, or faster than a specified time.
![rize fall time](https://user-images.githubusercontent.com/13637582/52638193-16b1a580-2eda-11e9-914e-cdc85e9eb096.png)

Glitch or Duty cycle triggering. Accepting events whose pulse width are smaller or greater than a defined limit. The polarity can be positive, negative or either.
![trigger on puls width](https://user-images.githubusercontent.com/13637582/52638338-71e39800-2eda-11e9-9d5c-6b7fa10fc33b.png)

Runt triggering (Window triggering). The idea is that a signal crosses the first threshold level but does not reach the second one, in the defined window time.This can happen when a logic driver does not have a sufficient slew rate to reach a valid logic level. There can also be a design error and the signal is forced to a middle(undefined) state, neither“0” or “1”.
![runt_trigger](https://user-images.githubusercontent.com/13637582/52638495-c0913200-2eda-11e9-8914-f36994e061f0.png)

Delay triggering. Triggering for delays between channel a and b. A pass-through or polarity can be selected.
Phase difference trigger/measurement for signals with the same frequency… ?
![signal a and b difference](https://user-images.githubusercontent.com/13637582/52638572-eb7b8600-2eda-11e9-9e08-830ca1d8b899.png)

Timeout triggering. Triggering for a time window in which there are no pass-through or level “triggers”.
![dead_time](https://user-images.githubusercontent.com/13637582/52638691-2c739a80-2edb-11e9-82c5-16dc99aadf7a.png)

Measurements. Allows for precise measurements on signals that can exceed the maximum capture size and are impossible to perform in software or take a bigger toe on resources.

Feedback is highly appreciated?

**Comment by rgetz** [comment]
So, I think it is all of the above. It's more of a question of what is practical? If it is all - then add them all.

Just to clarify - this is for the scope and logic analyzer, or only the scope?

https://download.tek.com/document/55W_17291_6_0.pdf has a good description of things.

I think part of things is the ability to accept or reject conditions. For example - being able to trigger on a clock during the absence of a signal (Dead times) - I think you refer to as time out triggering - would be great.

-Robin
