### ISSUE TITLE
The signal generator does not start both channels at the same time

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#536]
The signal generator does not start both channels at the same time.

FW - 0.15
![screenshot from 2019-02-26 13-37-22](https://user-images.githubusercontent.com/8676912/53410269-f8fd3980-39cb-11e9-9ffe-249f20dd14fe.png)

Fw - 0.17
![screenshot from 2019-02-26 13-29-19](https://user-images.githubusercontent.com/8676912/53410260-f3075880-39cb-11e9-8479-39fd9e5315f3.png)

**Comment by dbogdan** [comment]
The issue will be solved by implementing gpio_chip->set_multiple() for https://github.com/analogdevicesinc/linux/blob/m2k/drivers/input/keyboard/adp5589-keys.c.

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/scopy/pull/557

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5), FW: v0.23 the bug is fixed.
