### ISSUE TITLE
Scopy Installation for Linux website link issue

### ISSUE THREAD

**Issue by rossbar** [analogdevicesinc/scopy#538]
The link under "Scopy for Linux" on the [Scopy page](https://wiki.analog.com/university/tools/m2k/scopy) points to the latest Scopy release in the scopy repo on Github. The problem is that the latest tagged release (1.0.4) doesn't contain a link to the flatpak installer. Should be a simple fix but I wanted to bring it to your attention as it took me a few minutes to figure out.

Note that I went back to the 1.0.3 tagged release which has the link to the flatpak in the Assets.

**Comment by adisuciu** [comment]
Thanks, release 1.0.4 is macOS only as it handles an issue that occured while creating the mac build. I updated the description with a link to 1.0.3 . Thanks !
