### ISSUE TITLE
Oscilloscope math - Dividing two channels causes Scopy crash, no error

### ISSUE THREAD

**Issue by rossbar** [analogdevicesinc/scopy#539]
Scopy commit: 91c4f0c | OS: Ubuntu 16.04 | FW version: v0.22

When using the math functionality for the oscilloscope, Scopy will crash if attempting to divide one channel by another. Seems like a divide-by-zero error. N.B. the crash is not accompanied by a warning/error in the UI nor in a traceback from the calling terminal.

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/scopy/pull/544

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
