### ISSUE TITLE
I2C - Inter frame space - Scopy crash

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#540]
Scopy version: 91c4f0c

Open Pattern Generator. Select two DIO channels and group them.

Set pattern to I2C. 

In the protocol settings menu change the "Inter frame space" to 1 and then try to delete the value.

Scopy eventually crashes.

This bug is not 100% reproducible.

Tested both on Linux and Windows.

**Comment by adisuciu** [comment]
Fixed with 9add4be0cd4755b8965f9ccf86d21b4c29d84f8a

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
