### ISSUE TITLE
Drag into other Scopy instance

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#542]
Open two Scopy instances.

Drag one Instrument from one instance and drop it into the other one.

The Instrument will run into the instance where the instrument is dropped
![2019-03-06_16-36-48](https://user-images.githubusercontent.com/26061529/53888880-20887d80-402e-11e9-98f3-a3a1104f68e3.gif)

See attached GIF.

**Comment by DanielGuramulta** [comment]
This bug should be fixed with the new Tool Launcher menu.

**Comment by adisuciu** [comment]
Should be fixed with https://github.com/analogdevicesinc/scopy/pull/614

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
