### ISSUE TITLE
unable to build scopy on windows

### ISSUE THREAD

**Issue by pantechsolutions** [analogdevicesinc/scopy#546]
hello unable to build scopy on windows
![image](https://user-images.githubusercontent.com/4321670/54152179-a0657c00-4462-11e9-878d-b72439e8e981.png)

can anyone help

**Comment by AlexandraTrifan** [comment]
Hi, 

Can you check the Qt version with "qmake --version"? 
Did you install Qt using these commands: 
` wget http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-qt5-5.9.1-1-any.pkg.tar.xz`
 `pacman -U --noconfirm mingw-w64-x86_64-qt5-5.9.1-1-any.pkg.tar.xz`

Can you try to update your Qt using: 
`pacman -S mingw-w64-x86_64-qt5` ?

Thank you

-Alexandra

**Comment by pantechsolutions** [comment]
Hello Alendara

Thank you so much for your reply,i follow the same steps as given by you,but still i am not able to make the build .attach is the screenshot,can you share your comments.

Thank you.
![image](https://user-images.githubusercontent.com/4321670/54189692-55864b80-44d8-11e9-9d60-daebc060ab64.png)

**Comment by pantechsolutions** [comment]
![image](https://user-images.githubusercontent.com/4321670/54190361-b19d9f80-44d9-11e9-9e27-5daaa13a44e4.png)

pls find the above screenshot for the cmake results

**Comment by AlexandraTrifan** [comment]
Can you check the Qt version with "qmake --version"?
If the Qt version is 5.12, you should copy the pre-compiled dependencies again, using: ` wget "https://ci.appveyor.com/api/projects/analogdevicesinc/scopy-mingw-build-deps/artifacts/scopy-mingw64-build-deps.tar.xz?branch=master&job=Environment: MINGW_VERSION=mingw64, ARCH=x86_64" -O- | tar -C / --strip-components=1 -xJ`

After that, please remove everything from your build folder, in order to start clean.
Run cmake and ninja again and let us know how it works. 

Thank you.

-Alexandra

**Comment by pantechsolutions** [comment]
Hello Alendra

finally i was able to make the build,after i set the environmetal variables . I am getting the following error

![image](https://user-images.githubusercontent.com/4321670/54192766-b9ac0e00-44de-11e9-8748-19ed9d2e5d29.png)

![image](https://user-images.githubusercontent.com/4321670/54192798-c892c080-44de-11e9-9b63-82ab1c73f9a0.png)


here is the qmake version
qmake --version

$ qmake --version
QMake version 3.1
Using Qt version 5.12.1 in C:/msys64/mingw64/lib
![image](https://user-images.githubusercontent.com/4321670/54192892-fa0b8c00-44de-11e9-969e-3508e5049d92.png)

![image](https://user-images.githubusercontent.com/4321670/54192960-1d363b80-44df-11e9-9d01-f39dadad8431.png)

**Comment by pantechsolutions** [comment]
Hello alexandra ,finally it worked,as the environmental variables  has to be set in the system variables.

Thank you so much for your support.

Is there any documentation available for creating  the build as a windows set up  file. We are using adalm2000 in our product.

Thank you.

**Comment by AlexandraTrifan** [comment]
Hi, 

You can find Windows installers on the Release page: https://github.com/analogdevicesinc/scopy/releases .
This is the latest release: https://github.com/analogdevicesinc/scopy/releases/tag/v1.0.3 .

All the documentation for ADALM2000 and Scopy can be found here: https://wiki.analog.com/university/tools/m2k/scopy 
and 
https://wiki.analog.com/university/tools/m2k .

You can also find information about building and creating an installer in the Appveyor file ( https://github.com/analogdevicesinc/scopy/blob/master/appveyor.yml ). Appveyor is a continuous integration service that we use to build Scopy. It uses MSYS2 and MinGW. It can provide useful information. 

Thank you

-Alexandra

**Comment by pantechsolutions** [comment]
Thank you for your reply.

I tried to connect with ADALM2000 ,when i click connect the scopy suddenly closes.i have  record a video and sent to you thru engineer zone.

can you have a look at it and reply ,thank you.

here is the screenshot
![image](https://user-images.githubusercontent.com/4321670/54267487-51713100-459f-11e9-8458-a668e31c1ef9.png)

![image](https://user-images.githubusercontent.com/4321670/54267498-57671200-459f-11e9-8289-b64754f1997e.png)


scopy closes immediately after the screenshot.

**Comment by pantechsolutions** [comment]
please find the error in the video

https://youtu.be/vIWw2cVRtog

**Comment by AlexandraTrifan** [comment]
Does this happen using the Scopy you built locally, or using the release downloaded from the github release page?

-Alexandra

**Comment by pantechsolutions** [comment]
it also happens if i install thru the installer you  provided on the link.

i am testing with three laptops with three different adalm2000, i am getting the same error.

In one laptop i have install only the driver and the installer file,but it is crashing,sometimes it display  calibrating and then closed. i am using windows 10 .teh usb cable which was supplied by analog devices.

I have installed the drivers for adalm2000.

is any other info needed,Thank you

**Comment by AlexandraTrifan** [comment]
Can you install libiio, using this installer: https://github.com/analogdevicesinc/libiio/releases/download/v0.15/libiio-0.15.g6ecff5d-Windows-setup.exe ? 
After that, open a command prompt, type **iio_info -a** and provide the output please.

-Alexandra

**Comment by pantechsolutions** [comment]
![image](https://user-images.githubusercontent.com/4321670/54300199-61f6cb00-45e2-11e9-912d-e01446063d69.png)

pls find the screen shot

**Comment by pantechsolutions** [comment]
![image](https://user-images.githubusercontent.com/4321670/54306077-953f5700-45ee-11e9-9277-15b7ee0504ad.png)

pls chk the usb version.it differs for our build

**Comment by AlexandraTrifan** [comment]
Hi, 

Please connect the M2k to your PC before running iio_info -a. It should provide more information about the detected device. Right now it seems that the board was not connected to the PC.

Thank you. 

-Alexandra

**Comment by pantechsolutions** [comment]
the device is connected ,I am using windows10 .
![image](https://user-images.githubusercontent.com/4321670/54378273-f9285500-46ac-11e9-9854-261d0c73a7b8.png)

**Comment by pantechsolutions** [comment]
is there any possibility to connect the system via any remote desktop software.

That would be of great help,as we have to deliver our adalm2000 kits to our customers.

**Comment by pantechsolutions** [comment]
Hello Alexandra
I s there any update,thank you.

**Comment by AlexandraTrifan** [comment]
Hi,

Are you connect M2k through a docking station? We've had problems with those before.

Does M2k appear as a mass storage device? 
![](https://user-images.githubusercontent.com/18142097/54416148-38838f80-4707-11e9-99f4-39e5b686ae95.png)

Can you open the Device Manager and check if you have all the following entries for M2k?
![](https://user-images.githubusercontent.com/18142097/54416163-4b965f80-4707-11e9-824e-d73e7aef8c9d.png)

Thank you.

-Alexandra

**Comment by AlexandraTrifan** [comment]
Could you also try to connect through IP? (documentation here: https://wiki.analog.com/university/tools/m2k/scopy#connecting_to_a_remote_device )

You can do it from Scopy, using the "+" button. You should also run **iio_info -u "ip:192.168.2.1"** and check the result.

**Comment by AlexandraTrifan** [comment]
You could also start Scopy using the gdb debugger. Open a Command Prompt. 
Then go to the Scopy folder (you could use the following command: **cd C:\Program Files\Scopy\** . Then run **gdb Scopy.exe** . 

The program will load, then type **run** and press Enter. (you might have to press enter 2 times, because that might happen in command prompt) . 

Scopy will start, a bit slower than usually. After it starts, try to connect to it. It will crash/hang. 

Go into the command prompt and press CTRL+C to get the gdb prompt (something like **(gdb)**). When that's visible, write **bt**, then **bt full** and post the output please.

**Comment by pantechsolutions** [comment]
Hello Alexandara

Thank you for your support,we try to build on another laptop and it worked,but not able to debug on the system which was not working.

do you have any documentation to edit the ui file and add some functions on it.

Is there any matlab integartion to the tool?

can we visualize function generator and oscilloscope at the same time.

Thank you

**Comment by AlexandraTrifan** [comment]
Hi, 

All the Scopy related documentation can be found here: https://wiki.analog.com/university/tools/m2k/scopy . For the ui we use Qt, so all the related detailed documentation can be found on their official page https://doc.qt.io/ .

There isn't any matlab integration right now. There will be, but we can't give an ETA right now.

You can visualize any tool in parallel. This is described in the documentation ( https://wiki.analog.com/university/tools/m2k/scopy#user_guides ) under the "Detaching instruments" section.

Thank you.

-Alexandra

**Comment by pantechsolutions** [comment]
Hello Alexandra,

How to remove this  button.

![image](https://user-images.githubusercontent.com/4321670/54803057-ec4ec700-4c93-11e9-96e0-993a76fb5fc5.png)

so far i sold out 20 ADALM2000 kits ,customers are asking me is the software not completed yet? on seeing this button.

pls let me how to remove this .If they report any bug ,i will report here.

Build is fine,it is working well in appveyor.

What is the use of power USB connector in ADALM2000 ,as i am always using only the USB connection.

**Comment by adisuciu** [comment]
Hi,

There is no software without bugs and lots of software(even more mature than Scopy) have this functionality - attached is a Google Chrome screenshot. Having this button makes it easy for the users to get in touch with the developers directly through the user interface, therefore I wouldn't suggest removing it. If you still want to remove it, I'm sure you can figure out how to do it, but we cannot support that version.

You can power the M2k from the USB power connector and use the M2k's OTG port in a similar way you can use it on the pluto: https://wiki.analog.com/university/tools/pluto/usb_otg_host_function_support

-Adrian

**Comment by pantechsolutions** [comment]
Hello Adrian
I could understand ,but i am finding very hard to convince my target customer. I have  a target of selling 100 nos of adalm 2000 within next two months.it would be easier for me if i could have the one. i could rebuild and deliver the updated version.
Kindly help me to remove the display.just let me know the steps i could do that

thank you

**Comment by rgetz** [comment]
It’s open source - I would suggest if you need to make a fork and change things yourself. We can’t really help with these sorts of things we don’t agree with. 

- Robin

**Comment by pantechsolutions** [comment]
Hello
I have installed code composer studio and scopy stops working after that.i have uninstalled code composer studio and reinstall the scopy from the latest release from wiki.

all input channels are not working,pls find the screencast of the error.

https://youtu.be/XLIoL96Cyq4

when i try to measure a voltage using voltmeter it hangs.
i tried to use oscilloscope it hangs.

**Comment by rgetz** [comment]
There shouldn’t be any sort of name space clashes between code composer and scopy. 

Did you reboot your PC?

**Comment by pantechsolutions** [comment]
yes,i have uninstalled ccs and also reinstallled scopy.

but it was not working,signal generator is working

**Comment by pantechsolutions** [comment]
can anyone help me to sort the issue,thanks

**Comment by rgetz** [comment]
Someone will need to try to replicate the issue before we can provide any info. 

I would suggest to uninstall both CCS and Scopy, reboot; and then install Scopy.

**Comment by pantechsolutions** [comment]
I Have done but still it is not working, i cannot format the system,is there any option to make it work.

**Comment by adisuciu** [comment]
CCS should not alter Scopy installation in any way. After uninstalling Scopy make sure all files in Program Files are deleted. Also delete all files in c:\Users\asuciu\AppData\Roaming\ADI\

I can see in the video that you are running Scopy while low on battery. Please try using a power adapter to charge your laptop.
Please connect the M2k directly to the laptop - no docking station - no USB hubs.
Try adding the 192.168.2.1 device and connect to it (it's the same device) and retry the test.

If all else fails, please try running these steps.

> You could also start Scopy using the gdb debugger. Open a Command Prompt.
> Then go to the Scopy folder (you could use the following command: **cd C:\Program Files\Scopy** . Then run **gdb Scopy.exe** .
> 
> The program will load, then type **run** and press Enter. (you might have to press enter 2 times, because that might happen in command prompt) .
> 
> Scopy will start, a bit slower than usually. After it starts, try to connect to it. It will crash/hang.
> 
> Go into the command prompt and press CTRL+C to get the gdb prompt (something like **(gdb)**). When that's visible, write **bt**, then **bt full** and post the output please.

-Adrian

**Comment by pantechsolutions** [comment]
Hello adisuciu

It worked after i delete the files from

c:\Users\jeeva\AppData\Roaming\ADI\

Thank you so much.
