### ISSUE TITLE
logic analyzer: SPI Decode faile with Clock Phase 1

### ISSUE THREAD

**Issue by kazuk** [analogdevicesinc/scopy#562]
Repro steps:

Setup Pattern Generator for SPI

SPICLK 500kHz  Clock Polarity Clock Phase 1, 2 Bytes per frame,
Data: AA55 A55A

Setup Logic Analyzer for SPI decode genarated pattern.

Decode result is 552A 2D52

**Comment by adisuciu** [comment]
Hi,

We're aware of the issue. We already have a fix that will be part of the next SW release.
https://github.com/analogdevicesinc/scopy/pull/561

**Comment by kazuk** [comment]
Oh! thanks for fix.

 I will happy on next release.

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
