### ISSUE TITLE
UART using logic analyzer

### ISSUE THREAD

**Issue by pantechsolutions** [analogdevicesinc/scopy#563]
Hello i trasnmit a character A in arduino and try to visaulize the data in logic analyzer.

i am getting the correct timing diagram,but the mapping of start bit and stop bit is wrong.is that a bug or i have to do some settings
![image](https://user-images.githubusercontent.com/4321670/55471561-a5fc4f00-5627-11e9-9708-ba891cf41f56.png)

**Comment by amiclaus** [comment]
Hello,

There is a tutorial on how to use Logic Analyzer to debug UART. (under development)
https://wiki.analog.com/university/courses/electronics/m2k-uart-debug

I hope it helps you track your issue.

**Comment by pantechsolutions** [comment]
it worked pls close the issue
