### ISSUE TITLE
Waveform generator noise was not added when i visualized in scope sometimes

### ISSUE THREAD

**Issue by pantechsolutions** [analogdevicesinc/scopy#564]
Hello

pls find the screenshot waveform generator impulse noise added in the signal generator

but not able to visualize in oscillosope

pls find the screenshot

![image](https://user-images.githubusercontent.com/4321670/55538113-511a1080-56db-11e9-9d1b-2819a81cd174.png)

**Comment by adisuciu** [comment]
Duplicate of https://github.com/analogdevicesinc/scopy/issues/338 . 
Patch will be available in next SW release.

**Comment by pantechsolutions** [comment]
Thank you.

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
