### ISSUE TITLE
network analyzer

### ISSUE THREAD

**Issue by pantechsolutions** [analogdevicesinc/scopy#566]
for analog low pass rc filter , i am getting correct response in network analyzer,but for digital filter the phase is different ,i use a dsp processor.pls find the screenshot.
![image](https://user-images.githubusercontent.com/4321670/55553485-f2b25980-56fd-11e9-9505-fe4610d2f359.png)

**Comment by pantechsolutions** [comment]
pls find the screenshot for low pass filter
![image](https://user-images.githubusercontent.com/4321670/55558333-6b6ae300-5709-11e9-91ae-1409393f2862.png)

**Comment by pantechsolutions** [comment]
![image](https://user-images.githubusercontent.com/4321670/55558684-357a2e80-570a-11e9-942b-693cdaa32342.png)

**Comment by adisuciu** [comment]
Can you confirm that is not the characteristic of the digital filter with another instrument?
It looks like the network analyser works correctly. Maybe your digital filter has a different characteristic from the analog one.
