### ISSUE TITLE
Enable labels on plot - not working

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#583]
Scopy build: e28686 (v1.0.5)

Preferences Menu:
The option to "Enable labels on the plot" for the Oscilloscope is not working. The labels are not displayed.

**Comment by DanielGuramulta** [comment]
Should be fixed with pr: #585

**Comment by amiclaus** [comment]
On Scopy build: b7cee01 (v1.0.5) the bug is fixed.
