### ISSUE TITLE
Measurement Gating - remains active after Measure option is disabled

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#584]
Scopy build: e28686c (v1.0.5)

Reset Scopy Preferences.

Open Oscilloscope. Enable Measure feature and then the Measurement Gating. 

Disable Measure feature.

Close Scopy.

Open Scopy and the Oscilloscope Instrument.

The Gating feature appears on the plot, but the "Measure" feature is disabled.

![image](https://user-images.githubusercontent.com/26061529/57448952-57b02080-7263-11e9-8e05-258e75263d30.png)

**Comment by DanielGuramulta** [comment]
Should be fixed with pr: #582

**Comment by amiclaus** [comment]
On Scopy build: 85e5674 (v1.0.5) the bug is fixed.
