### ISSUE TITLE
Voltmeter Min/Max values bug

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#588]
Scopy build: 85e5674 (v1.0.5) 

For positive input voltages only max value is displayed:

![image](https://user-images.githubusercontent.com/26061529/57620958-e6d67480-7592-11e9-824d-e2a6ab19b093.png)

For negative input voltages only min value is displayed:

![image](https://user-images.githubusercontent.com/26061529/57621006-09688d80-7593-11e9-84a2-030c3778aa21.png)

For each of the two cases above, both min and max values should be recorded.

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/commit/7003b0799772d0920256939316546a3e92b2b439

**Comment by amiclaus** [comment]
On Scopy build: 3168843 (v1.0.5) the bug is fixed.
