### ISSUE TITLE
dropdown animation has glitch

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#591]
Scopy version: 85e5674

Steps to reproduce:

Go to general settings
Click the channels dropdown menu under export
It can be observed that there is a glitch after clicking.

This is also seen on the Horizontal and Vertical dropdown menu on Measure panel.

**Comment by AlexandraTrifan** [comment]
Can this be reproduced on the latest build?

**Comment by tagoylo** [comment]
Yes, it is still happening on the latest build.
