### ISSUE TITLE
Noise does not reflect on oscilloscope reading

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#593]
Scopy version: 6f7e649
fw version: v0.23

Steps to reproduce:

Set ch1 and ch2 to any waveform except square wave
Change Noise to uniform, gaussian, impulse, etc.
Increase Noise amplitude.
Then monitor output on oscilloscope
The waveform displayed on oscillscope does not add the noise. For sine wave wave there is noise added but does not correspond to the amplitude.

I tried monitoring the output on discovery and the noise is added.
![bug3](https://user-images.githubusercontent.com/25096080/57769046-833d7a00-773f-11e9-8448-aa04a28fdcd9.PNG)

**Comment by DanielGuramulta** [comment]
Looks like a duplicate of this: https://github.com/analogdevicesinc/scopy/issues/338. If you go into "Preferences" and disable the  "adc filters", is the added noise still not showing up?

**Comment by tagoylo** [comment]
Disabled adc filters and the noise is now showing up. Closing this item as it is invalid.
