### ISSUE TITLE
Noise in stairstep seems odd

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#594]
Scopy version: 6f7e649

Not sure if this is a bug or it's expected. 

When noise is added to a stairstep the following is the result.
![bug5](https://user-images.githubusercontent.com/25096080/57769924-ab2ddd00-7741-11e9-93f4-b2717a29eab3.PNG)

Steps to reproduce: 

Go to signal generator buffer
Load stairstep waveform in .csv file format. 
[signal_generator_buffer_test.zip](https://github.com/analogdevicesinc/scopy/files/3182208/signal_generator_buffer_test.zip)

Then add noise, uniform 1V.

**Comment by adisuciu** [comment]
This is the expected behavior. Noise generator adds amplitude on top of each sample. if your input file has few samples(12), this is the expected result.

**Comment by tagoylo** [comment]
Noted. Closing this item as it is invalid.
