### ISSUE TITLE
Nyquist plot is messed up

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#595]
Scopy version: 6f7e649 

Steps to reproduce:

I used LPF as the circuit. 
Run network analyzer.
Switch to nyquist plot.
Shown below is the result.

![bug6](https://user-images.githubusercontent.com/25096080/57774609-90616580-774d-11e9-9911-550933b55ffa.PNG)

**Comment by DanielGuramulta** [comment]
Should be fixed with pr: #597

**Comment by amiclaus** [comment]
On Scopy build: f813167 (v1.0.5) the bug is fixed.
