### ISSUE TITLE
Network Analyzer stops running when Scopy is reset

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#596]
Scopy Version: 6f7e649c 
Steps to reproduce:
1.	Use the LPF circuit.
2.	Run the network analyzer.
3.	Stop simulation and reset Scopy in the “Preferences.”
4.	Run the network analyzer. Attached below is a snippet of the GUI.
The Network Analyzer doesn’t run. However, this does not happen when you reset Scopy by deleting the .ini files.
![Bug_NA_5152019](https://user-images.githubusercontent.com/43806793/57777455-8a22b780-7754-11e9-8abe-732635aa90ae.PNG)

**Comment by DanielGuramulta** [comment]
Should be fixed with pr: #597

**Comment by amiclaus** [comment]
On Scopy build: f813167 (v1.0.5) the bug is fixed.
