### ISSUE TITLE
Fine interval does not work

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#598]
Scopy version: 6f7e649

Steps to reproduce:

Open Markers.
For frequency position, enable fine interval.
Try increasing/decreasing the frequency by clicking +/-.

It can be observed that the frequency does not change.

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/602

**Comment by amiclaus** [comment]
On Scopy build: 14f2f58 (v1.0.5) the bug is fixed.
