### ISSUE TITLE
 Interval knob indicator does not fill up when increasing frequency

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#599]
Scopy version: 6f7e649

Steps to reproduce:

Open Markers.
For frequency position.
Try increasing/decreasing the frequency by clicking +/-.

The indicator does not fill up. It stays as it is.
![bug7](https://user-images.githubusercontent.com/25096080/57824772-cbf04400-77ce-11e9-9a37-52eae638ef2c.png)

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/602

**Comment by amiclaus** [comment]
On Scopy build: 14f2f58 (v1.0.5) the bug is fixed.
