### ISSUE TITLE
Scopy Minimum Size window make texts and buttons overlap.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#60]
Connect M2K. Start Scopy, select the detected device. Press ""Connect"" button. Select the Window to be displayed in its minimum size.
-select Oscilloscope; press Channel Settings button; observe the dropdown menus for selecting the proper measurement units (Ex. Vertical Volts/div ->V;mV;µV) ;
-select Oscilloscope; press Trigger Settings button; 
observe the overlapping of the External Option (on/off) overlapping the Trigger Mode Option.
-select Oscilloscope; activate the Cursors (make them visible on plot); press FFT Option button (wheel icon on top right of the window); check the FFT feature; observe the overlappings (between cursor values; channel 2 vertical display scale is covered by the plot);
-select Pattern Generation; observe the values of the plot time axis overlapping;
Actual Results: Texts, values or buttons are overlapping in minimum sized Scopy window.
Expected Results: Texts, values or buttons should be resized according to the Scopy window size.
![overlap1](https://cloud.githubusercontent.com/assets/26061529/24445237/e8dc3618-1471-11e7-8e0d-aacf01476c95.PNG)
![overlap2](https://cloud.githubusercontent.com/assets/26061529/24445238/e8dc9a54-1471-11e7-90c7-cb6942e872b3.PNG)
![overlap3](https://cloud.githubusercontent.com/assets/26061529/24445239/e8dd57fa-1471-11e7-8002-63993f6dcee9.PNG)

**Comment by rgetz** [comment]
I think the design documentation states the min screen size is 1024x768. 

What size/resolution is shown above?

**Comment by pcercuei** [comment]
@rgetz: we decided for 720p - 1280x720.

**Comment by amiclaus** [comment]
@rgetz : the window size shown above is 1296 x 758 on a screen resolution of 1600 x 900.

**Comment by dNechita** [comment]
@rgetz There is no mention in the documentation regarding the minimum screen size.
A reasonable resolution that me and Paul thought of is 1280x720.

**Comment by pcercuei** [comment]
The major problem we have is that all the GUI mockups are designed for 1080p and above... and don't work as good at lower resolutions.

**Comment by rgetz** [comment]
So, this is a mockup issue, that should be assigned to Andrei? :)

I think we need to support at least down to 720p. There are still laptops shipped with:
 - 1280×720 px (HD)
 - 1280 x 1024 (SXGA)

**Comment by pcercuei** [comment]
The MacBooks are 2560x1440, with a Hi-DPI display, which means that the effective resolution for the application is 1280x720. So 720p is definitely a necessity.

I think we can skip SXGA, though.

**Comment by amiclaus** [comment]
I'll close this post since I've splitted it into #114 , #115 and #116
