### ISSUE TITLE
Column heading of exported file does not correspond to the unit set on the spectrum analyzer

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#600]
Scopy version: 6f7e649

Steps to reproduce:
Go to general settings and click export.
Open exported file and see amplitude column.
Values are correct but the heading is not.
It always shows in db.
Column heading of exported file does not correspond to the unit set on the spectrum analyzer.

Sample screenshots are shown below.
![bug8](https://user-images.githubusercontent.com/25096080/57825703-99484a80-77d2-11e9-9c9f-cced6ad69918.PNG)

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/602

**Comment by amiclaus** [comment]
On Scopy build: 14f2f58 (v1.0.5) the bug is fixed.
