### ISSUE TITLE
Plot is cut at ends after changing position to 0

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#601]
Scopy version: 6f7e649

Steps to Reproduce:

Open Logic Analyzer
Open Settings.
Run Logic Analyzer. 
Move position by using +/- or entering value or moving blue cursor.
After changing position, enter 0 as the value which results to the screenshot below.

![bug9](https://user-images.githubusercontent.com/25096080/57830650-4fb52b00-77e5-11e9-9641-25269d594afb.PNG)
![bug10](https://user-images.githubusercontent.com/25096080/57830651-4fb52b00-77e5-11e9-8fa0-5519e50f08d5.PNG)

**Comment by AlexandraTrifan** [comment]
The Logic Analyzer was revamped for this release. Using this build ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/reoavcxghvtlk75c/artifacts ) which is the build prepared for the release candidate v1.2.0, this bug no longer applies. 
Closing this issue.
