### ISSUE TITLE
Independent Run option for each channel

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#61]
Connect M2K. Start Scopy, select the detected device. Press "Connect" button. After the connection is made, select Voltmeter feature. Press Run button.
Actual Results: Both Channels are running.
Expected Results: Enable/Disable Channel feature should be introduced for each channel so that they can run independently (similar to the Power Supply Feature).

**Comment by pcercuei** [comment]
That's debatable. I don't see any problem in having the two channels running at the same time.

**Comment by rgetz** [comment]
Yeah, I'm not sure why someone would need to turn on a channel on a voltmeter. That's not something you do on a fluke - a software defined instrument should be the same.

**Comment by amiclaus** [comment]
Since, there are no other opinions and taking into consideration the feedback received, I will close this post.
