### ISSUE TITLE
Trojan detected during 1.0.6 windows setup

### ISSUE THREAD

**Issue by timothyKennedy** [analogdevicesinc/scopy#615]
On attempt to install Scopy version 1.0.6 windows setup, Windows 10 defender detects Trojan:Win32/Emali.A!cl in the executable. The issue has been replicated on multiple devices. Previous versions install successfully after quarantining and deleting the trojan.

![scopyTrojan](https://user-images.githubusercontent.com/51235906/58708077-be1cf000-8384-11e9-9580-69a1f6a7d46d.PNG)

**Comment by adisuciu** [comment]
We removed the windows installer until further investigation.

**Comment by adisuciu** [comment]
Can you try downloading again ?

**Comment by timothyKennedy** [comment]
Looks like the issue is resolved, thanks for your quick attention!
