### ISSUE TITLE
Need to have the Scope stoped before doing auto cal

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#617]
Hi:
Thia issue was raised on engineer zone but since it is might be something to change in the software I'm re-posting it here. A user has noticed that the scope (and maybe the signal generator?) needs to be stopped before doing an (on demand) auto calibration. Probably need Scopy to check if everything is stopped or not (stopping things as needed) before doing the auto cal routine.

"I'll add that it appears that you want to stop the scope when doing the automatic calibration."

https://ez.analog.com/university-program/f/q-a/111853/adalm2000-expected-drift-of-function-generator

Doug

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/621

**Comment by amiclaus** [comment]
![image](https://user-images.githubusercontent.com/26061529/72527602-cec99a00-3871-11ea-8e61-55d0ccc5a955.png)
The UI shows that the instruments are running while calibration is ongoing.

**Comment by tagoylo** [comment]
Able to calibrate while instruments are running. This enhancement is implemented. Closing this item.
