### ISSUE TITLE
Time alignment of DAC channels when using oversampling

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#622]
Setup:
Load a csv file 
Load a waveform
Shift phase of the waveform 

Expected result:
Phase shift is smooth

Phase shift is actually random.

On further investigation, it seems that even though the signals start at the correct phase shifts, the signals are not started synced.

Reference:
CSV File:
```
0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
```
![Screenshot from 2019-06-07 11-22-45](https://user-images.githubusercontent.com/8676912/60026662-a3e4e200-96a4-11e9-8a7d-4b6aa484de05.png)

**Comment by adisuciu** [comment]
Should be fixed with latest firmware

**Comment by HRosete** [comment]
Phase shift issue fixed at Scopy v1.2.0 (verified at 33ca72f9), FW:[m2k-fw-v0.25-3-g1c38-dirty.zip](https://github.com/analogdevicesinc/scopy/files/5414289/m2k-fw-v0.25-3-g1c38-dirty.zip). Closing this issue.
