### ISSUE TITLE
Typo Wiki Building Scopy on OS X 

### ISSUE THREAD

**Issue by christophjurczyk** [analogdevicesinc/scopy#625]
Hi,
you have a minor typo at the instructions for building Scopy on a Mac ([here](https://github.com/analogdevicesinc/scopy/wiki/Building-Scopy-on-OS-X) and [here](https://wiki.analog.com/university/tools/m2k/scopy/build-osx)):

Instead of 
`brew install autoconf`
it is written
`brew install autconf`
which is not available.

-Christoph

**Comment by AlexandraTrifan** [comment]
Hi, 

Thank you for the info. We updated the pages.

-Alexandra
