### ISSUE TITLE
Can't select SPI Clock options of Logic Analyzer

### ISSUE THREAD

**Issue by shujima** [analogdevicesinc/scopy#626]
## Overview

Can't select SPI Clock options by mouse click.

* Clock polarity
* Clock phase

![スクリーンショット_2019-06-27_23_22_58](https://user-images.githubusercontent.com/45596573/60279518-2804c700-993c-11e9-8bcc-5566e02f3337.jpg)

And I found the solution of this problem ; selected by Tab key.

![control](https://user-images.githubusercontent.com/45596573/60280207-6e0e5a80-993d-11e9-8c4e-1854f6103a42.jpg)

Because of that, I think this problem is a bug of GUI.

## Versions
Scopy 01c4f0c
macOS Mojave 10.14.5

**Comment by AlexandraTrifan** [comment]
The Logic Analyzer was completely revamped for this following release, v1.2.0. Here is the link to a prepared build for the release candidate ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245/job/oxx7gqvvslv7gf19/artifacts ) for MacOS 10.15.
The Logic Analyzer channels and decoder system was changed and such crashes no longer happen in the new Logic Analyzer. Could you confirm?
