### ISSUE TITLE
Network Analyzer some bugs

### ISSUE THREAD

**Issue by ciuffoly** [analogdevicesinc/scopy#628]
Here 2 different problems found in Scopy function Network Anallyzer.

1) the cursor show the correct frequency but bad dB, there are only integer and no decimal

2) the db axe does not show decimal so many time the same db and sometimes I see 16,17,18,18,19,19,20 in the scale

![error1](https://user-images.githubusercontent.com/46751177/60424522-cd47c580-9bf0-11e9-9748-b5b21ca23a14.jpg)

![error2](https://user-images.githubusercontent.com/46751177/60424524-cde05c00-9bf0-11e9-8dc8-7465bc4a5648.jpg)

**Comment by ciuffoly** [comment]
To reproduce the problem just expand the dB scale to 1dB step or less

**Comment by ciuffoly** [comment]
At this this I am using only Windows version so I don't' know if the problem exist on other OS.

**Comment by adisuciu** [comment]
You are correct, we missed the decimal point in the implementation. We'll fix this.

**Comment by ciuffoly** [comment]
Which is the correct setting for the level and the buffer size ?  I see a correct frequency response only with High level and any buffer size (ms)

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/642

**Comment by ciuffoly** [comment]
Is necessary to download and install a new release ?

**Comment by adisuciu** [comment]
It's in testing until we create a new release. Assuming you use windows 64bit, you can download a build artifact from our CI. However it's not an official release. - https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/25988096/job/6f6d4nymm4dlg4uu/artifacts - download scopy-64-setup.exe

**Comment by ciuffoly** [comment]
Have you seen the problem of db if you reduce db scale ?

the db axe does not show decimal but I see 16,17,17,18,18,19,19,20 in the scale

**Comment by adisuciu** [comment]
Yes, it is fixed.

**Comment by ciuffoly** [comment]
the new scopy-64-setup.exe or the zip file give an error at the start on libma...9.dll

**Comment by ciuffoly** [comment]
Very good result with the new release

![RC1](https://user-images.githubusercontent.com/46751177/62350207-4db85980-b502-11e9-80d2-f17119eeea1c.jpg)
![RC2](https://user-images.githubusercontent.com/46751177/62350208-4e50f000-b502-11e9-8ebf-041ef717eff2.jpg)

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
