### ISSUE TITLE
Network Analyzer overlap

### ISSUE THREAD

**Issue by ciuffoly** [analogdevicesinc/scopy#629]
Is possible to add a new button to save the current plot and change the color of the next measurement to see the differences like in this image create with Paint ?

![incr1](https://user-images.githubusercontent.com/46751177/60436031-6b488980-9c0b-11e9-9adb-5396494ab54a.jpg)

**Comment by adisuciu** [comment]
That would be a good enhancement. We have reference waveforms for the oscilloscope instrument. You're suggesting the same for the network analyzer.

**Comment by DanielGuramulta** [comment]
Implemented with: #643

**Comment by ciuffoly** [comment]
Where I can download the new version ?

**Comment by DanielGuramulta** [comment]
You can download the installer for the latest build from: https://wiki.analog.com/university/tools/m2k/scopy

**Comment by ciuffoly** [comment]
There is no overlap button on this release

**Comment by DanielGuramulta** [comment]
On: https://wiki.analog.com/university/tools/m2k/scopy you will find 3 download links for Scopy, one for the latest release,  and two for the latest nightly builds (one for 32-bit systems and one for 64-bit systems) 
![image](https://user-images.githubusercontent.com/26142210/62274438-8e539c80-b448-11e9-822a-0bbf9923fad5.png)
Select the second or third installer depending on your system.
Once you finish installing Scopy. Open the Network Analyzer and on the right top corner select the "wheel" menu. There you will find options to import from csv or txt files already exported sweeps, there will also be a "Snapshot" button which will add as a reference the sweep that is currently on the plot, and there you will also find a "Remove Reference" button which will clear the screen.
![image2](https://user-images.githubusercontent.com/26142210/62274655-f904d800-b448-11e9-9212-96951b70ba8b.png)

**Comment by ciuffoly** [comment]
Very good result

![RCov](https://user-images.githubusercontent.com/46751177/62350176-2d889a80-b502-11e9-9f3b-cfcb586704de.jpg)

**Comment by ciuffoly** [comment]
Should be possible add more import than one plot using with different colors ?

**Comment by rgetz** [comment]
One of the things we are trying to do - is keep things accessible.

Red-green color blindness effects as many as 8 percent of men and 0.5 percent of women with Northern European ancestry.
https://www.colour-blindness.com/general/prevalence/


the other things we are trying to do, is not re-create GNU Plot, Excel, or MATLAB. There are lots of plotting packages...

What is the use case for multiple plots?

Thanks

**Comment by ciuffoly** [comment]
just to see the effect of a variations on an amplifier like the load

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the enhancement is fixed.
