### ISSUE TITLE
Network Analyzer with Low and Automatic gain bad result

### ISSUE THREAD

**Issue by ciuffoly** [analogdevicesinc/scopy#630]
Why the Network Analyzer give a good result only with High gain mode ?

Low and Automatic gain give a bad frequency response also using a super simple RC filter with 500ohm 6800pF.

![high](https://user-images.githubusercontent.com/46751177/60437075-d6935b00-9c0d-11e9-9a5b-37673c5665ed.jpg)

![low](https://user-images.githubusercontent.com/46751177/60437076-d6935b00-9c0d-11e9-9657-08129a90d8a1.jpg)

**Comment by adisuciu** [comment]
We'll reproduce this and look into this

**Comment by ciuffoly** [comment]
High gain mode increase the reference voltage or only the other channel ?

**Comment by adisuciu** [comment]
It shouldn't increase the reference, just set the gain mode of the input channel accordingly - you won't be able to analyse circuits with responses > 2.5V . Automatic should hop in between the input ranges (25V / 2.5V) based on previous circuit response.

**Comment by ciuffoly** [comment]
Very good result now, Low, Automatic and High quite the same plot

![image](https://user-images.githubusercontent.com/46751177/62350421-f961a980-b502-11e9-992e-1c4e82431316.png)

**Comment by ciuffoly** [comment]
Still some problem with auto, low and high

![low_auto_high](https://user-images.githubusercontent.com/46751177/62959920-dcc64b00-bdf9-11e9-8650-d0f5c02383d7.jpg)

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.

**Comment by adisuciu** [comment]
Is this still a problem ? Can you share your test setup ?

**Comment by ciuffoly** [comment]
[
![auto](https://user-images.githubusercontent.com/46751177/65683557-cd275c80-e05d-11e9-8343-530a8fb58e9d.jpg)
![high](https://user-images.githubusercontent.com/46751177/65683558-cd275c80-e05d-11e9-9013-c38db088f621.png)

](url)

**Comment by ciuffoly** [comment]
with 1V ref
![auto_and_high](https://user-images.githubusercontent.com/46751177/65684059-00b6b680-e05f-11e9-8ef8-c85bcddc6053.jpg)

**Comment by mhennerich** [comment]
Hmm - Scopy version 1.1.0 released and we also have a new firmware - you still seem to be using 1.0.6...

**Comment by ciuffoly** [comment]
ok, Scope v1.1.1

phase better but not perfect

still many difference from auto (red) to high (orange)

![image](https://user-images.githubusercontent.com/46751177/65783826-ebba5000-e150-11e9-8f36-e99808c422ef.png)

**Comment by ciuffoly** [comment]
Using 500mV insetad of 1V the is no problems, input saturate ?

![image](https://user-images.githubusercontent.com/46751177/65783925-30de8200-e151-11e9-9710-66b604d5c720.png)

**Comment by ciuffoly** [comment]
I am testing a Gainclone LM3886

**Comment by ciuffoly** [comment]
Using for the phase the range +180 and -180 and 500mV all is ok in auto and high mode

![image](https://user-images.githubusercontent.com/46751177/65784605-bc0c4780-e152-11e9-993e-7349f4587321.png)

**Comment by ciuffoly** [comment]
Why with 1V there are problems, the input saturate ?

**Comment by ciuffoly** [comment]
![image](https://user-images.githubusercontent.com/46751177/65784779-1f967500-e153-11e9-978b-e43ce2c3289f.png)

**Comment by adisuciu** [comment]
Yes, high gain mode has input range of +/- 2.5 V. 
You are saturating the input when using 1V amplitude for the reference waveform to the amplifier.

**Comment by ciuffoly** [comment]
Could you recognize this saturation and avoid displaying the wrong graph ?

**Comment by adisuciu** [comment]
We probably can. We'll add a feature for this next release.

**Comment by ciuffoly** [comment]
All new info has been published

http://www.audiodesignguide.com/AudioMesurement/index.html
