### ISSUE TITLE
AC coupling not working for X-Y, FFT plots

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#631]
Scopy build: 48fb6a9 (v1.0.6)

Apply input signal with offset (2V amplitude, 1V offset).

Enable AC coupling within the Oscilloscope instrument.

On the main plot, the dc offset of the signal is removed, while on the X-Y, FFT plots the offset persists.

![image](https://user-images.githubusercontent.com/26061529/60446009-1a478e00-9c29-11e9-9438-ff073aa6a289.png)

**Comment by AlexandraTrifan** [comment]
Should be fixed after commit 2b19dbd0cf4000b9e3dd658a7db551370d3ff7c7

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
