### ISSUE TITLE
Frequency parameter disabled, but still changeable via spinbox

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#634]
Scopy build: 1f47a67

1. Signal Generator

For Trapezoidal waveform the Frequency parameter is disabled.

Still, if scrolling the mouse over the spinbox, the frequency changes.

![image](https://user-images.githubusercontent.com/26061529/60674305-81ac4a80-9e82-11e9-9fa4-10b7fd6fdec0.png)

2. For Logic Analyzer

Go to the Settings panel and make sure the Run Mode is set as "Repeated".

Frequency is disabled, but still editable by scrolling over the spinbox.

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/641

**Comment by amiclaus** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
