### ISSUE TITLE
Scopy exits when generating log(t) 

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#640]
Signal generator: Math : log(t)
For frequencies under 500kHz  of the log(t) waveform Scopy app exits.

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/646

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
