### ISSUE TITLE
windows nightly version 1.0.2851 libmatio-9.dll error

### ISSUE THREAD

**Issue by jpnielsen** [analogdevicesinc/scopy#654]
I uninstalled scopy, and manually deleted the left over "decoders" dir.
I then installed Windows Nightly - version 1.0.2851 from here https://ci.appveyor.com/api/buildjobs/thntefwa59a8mo8v/artifacts/scopy-64-setup.exe
 - and rebooted.

Scopy.exe comes up with the error:

"Scopy.exe - Entry Point Not Found"
"The procedure entry point H5Rdereference could not be located in the dynamic link library D:\scopy\libmatio-9.dll."

**Comment by jpnielsen** [comment]
Followed the "build scopy on windows" here: 
https://github.com/analogdevicesinc/scopy/wiki/Building-Scopy-on-Windows
added `pacman -S mingw-w64-x86_64-qt5 --disable-download-timeout` found on ez.analog.com

This is the error i get when trying to run "scopy"

> "Scopy.exe - Entry Point Not Found"
> "The procedure entry point H5Rdereference could not be located in the dynamic link library D:\msys64\mingw64\bin\libmatio-9.dll."

**Comment by jpnielsen** [comment]
https://packages.msys2.org/package/mingw-w64-x86_64-matio?repo=mingw64

**Comment by AlexandraTrifan** [comment]
Hi, 

Thank you for this. 
We will look into it and fix the build as soon as possible.

-Alexandra

**Comment by jpnielsen** [comment]
windows build needs

pacman -S mingw-w64-x86_64-breakpad-git

**Comment by DanielGuramulta** [comment]
Windows nightly builds should be fixed with: #660

**Comment by jpnielsen** [comment]
Please also update the doc on 

https://github.com/analogdevicesinc/scopy/wiki/Building-Scopy-on-Windows
and
https://wiki.analog.com/university/tools/m2k/scopy/build-windows

**Comment by DanielGuramulta** [comment]
I've updated the documentation on both github and wiki.

**Comment by jpnielsen** [comment]
I can confirm that scopy builds.
thank you.

minor detail:

from the documentation:

> Finally, add the “SCOPY_PYTHONPATH” variable:
> 
> ```
> Click on “New…”
> In “Variable name:”, write SCOPY_PYTHONPATH
> In “Variable value:” write C:\msys64\mingw64\lib\python3.7;C:\msys64\mingw64\lib\python3.7\plat-win;C:\msys64\mingw64\lib\python3.7\lib-dynload;C:\msys64\mingw64\lib\python3.7\site-packages
> Then click OK.
> ```
> 

"C:\msys64\mingw64\lib\python3.7\plat-win" does not exist on my fresh install of http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe

**Comment by jpnielsen** [comment]
I don't like the "fix" - it's a likely to fail workaround, and you didn't give an instruction on how to lock the version of hdf5 - first time the user runs an update of msys2, the "fix" is broken.

other software offcause may be dependent on a newer version of hdf5

**Comment by DanielGuramulta** [comment]
Since: https://github.com/analogdevicesinc/scopy/commit/42f0b66b753c00c8028696330d30f18f25589de1, we no longer use an older version of hdf5.
