### ISSUE TITLE
General: Check whether you are using latest version and firmware

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#655]

**Comment by rgetz** [comment]
Most of the other implementations we have of this use github API to do this sort of thing - however - these are all rate limited. 

https://developer.github.com/v3/#rate-limiting
_For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address,_

We can check what the current rates limits to to see if we are running into issues...
https://developer.github.com/v3/rate_limit/

When I asked github support via email this is what they said:
> In general, using a single GitHub account to proxy requests from 
> multiple non-GitHub users isn't something we encourage. Instead, you 
> should use that single account to fetch+cache the file in a backend server 
> you own and maintain (or even better, use webhooks so that you are 
> notified as soon as the file is updated and then fetch it just once), and
>  then expose that via an API endpoint of your own.
> That API endpoint would then be what your devices fetch (instead of 
> calling the GitHub API), and you can then set whatever limits you want.

so swdownloads? or something like that?
