### ISSUE TITLE
Inappropriate initial channel settings panel title display

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#66]
Connect M2K. Start Scopy, select the detected device. Press "Connect" button. After the connection is made, select Signal Generator feature. The channel settings panel is automatically opened for channel 1.
Actual Results: The title of the panel initially is "Configuration", not specifying for which of the channels the panel is active.
Expected Results: The title should be set to "Configuration for Channel 1" when opening the Signal Generator feature for the first time.
![siggenconfig](https://cloud.githubusercontent.com/assets/26061529/24446839/99be1e6a-1477-11e7-8fbd-d4ed8ec106bd.PNG)

**Comment by adisuciu** [comment]
Fixed with 	5555389

**Comment by amiclaus** [comment]
On Scopy build: f759590 (v0.6) the bug is fixed.
