### ISSUE TITLE
Faulty link on wiki.analog.com/university/tools/m2k/scopy

### ISSUE THREAD

**Issue by jpnielsen** [analogdevicesinc/scopy#661]
I'm taken to an error by "Installer for latest (nightly) build (Windows 32/64-bit)" on https://wiki.analog.com/university/tools/m2k/scopy

the error is 
{"message":"\"job\" parameter must be specified if build contains multiple jobs.\r\nParameter name: job"}

**Comment by DanielGuramulta** [comment]
https://wiki.analog.com/university/tools/m2k/scopy. The links to the latest installers from the nightly builds should be working now.

**Comment by jpnielsen** [comment]
Confirmed
