### ISSUE TITLE
Logic analyzer capture is five times too slow

### ISSUE THREAD

**Issue by pcercuei** [analogdevicesinc/scopy#665]
I configure the logic analyzer in Stream mode, at 2.941 MHz. Time base 100ms, position 500ms.

If I enable the cursors and put one at each side of the available screen space, the delta t is 998 ms - close enough to one second, which is what is expected (100ms/div * 10 divs).

The problem is that the capture happens five times slower than it should. The entire capture takes about five seconds to complete. As a result, any delta I measure with the cursors is wrong and the actual value is about five times the amount.

Scopy 1.0.6 on Debian (flatpak)

**Comment by adisuciu** [comment]
This should be fixed with the newest Logic Analyzer.
