### ISSUE TITLE
Scopy crashes when stopping Network Analyzer

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#667]
Scopy Version: 2b19dbd0
Firmware Version: v0.23

Steps to Reproduce:

Run Network Analyzer
Then after a few seconds, click stop. Try these 2 steps for a few times.
When the status states "Stopping", click other icon.
![bugna1](https://user-images.githubusercontent.com/25096080/62592245-0caab580-b905-11e9-9f5a-98a32818737d.PNG)

Scopy then crashes.

![bug-na](https://user-images.githubusercontent.com/25096080/62592517-fe10ce00-b905-11e9-8f08-7f004a387efe.PNG)

**Comment by DanielGuramulta** [comment]
Issue should be fixed with pr: #670

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
