### ISSUE TITLE
Calibration Failed

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#674]
SCopy version: 4fe815a0
firmware version: v0.23

Steps to reproduce:

Given M2k is connected, Disconnect the device
Then Connect again
Click Calibrate
The status will say "Calibration Failed" and other instruments calibrating status is still shown. Even when the device is disconnected it still shows.

![bug1](https://user-images.githubusercontent.com/25096080/63082080-de1d8200-bf77-11e9-9c09-c8a243c34282.PNG)
![bug2](https://user-images.githubusercontent.com/25096080/63082091-e1b10900-bf77-11e9-8ece-7cb5dfa425e1.PNG)

**Comment by DanielGuramulta** [comment]
Should be fixed: #694

**Comment by amiclaus** [comment]
On Scopy build: 214c488 (v1.1.0) the bug is fixed.
