### ISSUE TITLE
"File not loaded due to errors" although no files have been loaded yet

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#675]
Scopy version: 4fe815a0
Firmware version: v0.23

Steps to reproduce: 

Upon opening the signal generator, go to Buffer, can be in CH1 or 2
Then under File, the status shown in Format is "File not loaded due to errors" although no files have been loaded yet.
![bug3](https://user-images.githubusercontent.com/25096080/63138550-892c4b00-c00d-11e9-9711-32e8d674f606.PNG)

**Comment by DanielGuramulta** [comment]
Should be fixed with: #683

**Comment by amiclaus** [comment]
On Scopy build: 214c48 (v1.0.6) the bug is fixed.
