### ISSUE TITLE
Enabling Software AC Coupling crashes scopy

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#677]
Scopy version: 4fe815a0
Firmware version: v0.23

Steps to reproduce:

Set signal generator ch1 to 2V 1khz sine wave, 1V offset
Then monitor on the oscilloscope
Enable Ch1 software ac coupling
Then click anywhere, after a few seconds the software hangs and then crashes
This also happens on ch2

![bug4](https://user-images.githubusercontent.com/25096080/63314347-e855cc80-c339-11e9-87c6-3ca38bccaa55.PNG)

**Comment by DanielGuramulta** [comment]
Should be fixed with: #696

**Comment by amiclaus** [comment]
On Scopy build: 214c48 (v1.10) the bug is fixed.
