### ISSUE TITLE
Averaging does not work when in Sample type

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#678]
Scopy version: 4fe815a0
firmware version: v0.23

Steps to reproduce:

Open Spectrum analyzer, set Type to Sample
Run Spectrum analyzer then increase averaging value.
When increasing the average value, there is no change to the plot.

Averaging: **1**
![buga](https://user-images.githubusercontent.com/25096080/63325185-37acf480-c35c-11e9-93f8-f22440819566.PNG)

Averaging:**90**
![bugb](https://user-images.githubusercontent.com/25096080/63325236-501d0f00-c35c-11e9-955a-6279023c2dfb.PNG)

**Comment by dNechita** [comment]
When setting the Type to "Sample" in the spectrum analyzer, it means that no averaging will be done. It will just show the samples. If no averaging is performed then the value of "Averaging" will not be used. So the behavior is expected.
Indeed, it can be confusing to allow users to change the averaging value like this. Maybe disable this UI control when in "sample" mode?

**Comment by DanielGuramulta** [comment]
Should be fixed with: #682

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
