### ISSUE TITLE
REF numbering when using snapshot goes above 4

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#679]
Scopy version: 4fe815a0
firmware version:v0.23

Steps to reproduce:

Run spectrum analyzer
Add 4 REFs by clicking Snapshot four times, then delete these 4 REFs.
Then add again a REF, now it will be named as REF 5 and so on. It does not restart at 1.
![bugg](https://user-images.githubusercontent.com/25096080/63330587-a3945a80-c366-11e9-9ac3-585160ae18a7.PNG)

**Comment by DanielGuramulta** [comment]
Should be fixed with: #687

**Comment by andreeaipop** [comment]
On Scopy build: d198b9a (v1.0.6) the bug is fixed.
