### ISSUE TITLE
When pattern generator is off, DMM(fluke) measurement is at ~500mV to 800mV dc

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#680]
Scopy version: 4fe815a0
firmware version: v0.23

Steps to Reproduce:

Monitor DIO0 output using DMM(fluke)
Do not run pattern generator.
DMM(fluke) measurement is at ~800mV dc.
But voltmeter (scopy) reading is different.
Is this behavior expected?

![Capture](https://user-images.githubusercontent.com/25096080/63403794-50c4ac80-c413-11e9-96de-d4e345049e3d.PNG)

![image](https://user-images.githubusercontent.com/25096080/63403855-98e3cf00-c413-11e9-97cb-db203cc3990c.png)

**Comment by adisuciu** [comment]
When pattern generator is not running the pins are in Hi-Z state. This behavior is expected because the two instruments have different input impedances therefore will display different voltage values.
