### ISSUE TITLE
Selection of channel disappears when trigger is changed

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#681]
Scopy version: 4fe815a0
firmware version: v0.23

Steps to reproduce:

Select a channel.
Then change trigger.
The selected channels are now not selected thus selecting it again to proceed with
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25096080/63408894-96d53c80-c422-11e9-90c5-2edccee3e587.gif)
 the grouping.

**Comment by andreeaipop** [comment]
On Scopy build: 33b6c1c  (v1.0.6) the bug is fixed.
