### ISSUE TITLE
Automatically put 255 if entered value is greater than 255

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#684]
Scopy version: 4fe815a0
Firmware version: v0.23

Steps to reproduce:

Set channels as Group, then set it as out.
Enter a value greater than 255, ex. 266.
There will be no response when hitting enter.
An enhancement would be that when entered value is greater than 255, the value will be automatically set to 255

![image](https://user-images.githubusercontent.com/25096080/63482895-0d2e7900-c4cd-11e9-82f3-f86115bddc91.png)

**Comment by adisuciu** [comment]
I cannot reproduce. There is an QIntValidator set up that prevents from entering values greater than 255.

-Adrian
