### ISSUE TITLE
Spectrum Analyzer: Can't manually enter a marker's freq position lower than the starting freq of sweep even if  the option is disabled in the Preferences

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#689]
**Environment:**
 - OS Version: Windows 10 (10.0)
 - FW Version: [v0.23](https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.23)
 - SW Version: 4fe815a

**Bug Description:**
Even when the option "Only search marker peaks in visible domain" is disabled in the Preferences, one cannot manually enter a marker's frequency position lower than the starting frequency of the sweep.

**To Reproduce**
Steps to reproduce:

1. Load attached profile: "spectrum_analyzer.ini."
2. Go to Preferences, uncheck the checkbox for "Only search marker peaks in visible domain."
3. Connect AWG1 to Scope Ch1+.
4. Turn on the Signal Generator.
5. In the Spectrum Analyzer, open Markers' setting and turn the marker table on. Run the Spectrum Analyzer.
6. Click Marker 1 and manually put the Frequency Position to 500kHz (the frequency position automatically goes to 700kHz, the starting frequency of the sweep.)
5. Click Peak (this automatically places the marker on 500kHz) and see the error.

**Expected behavior**
Scopy must successfully search for the frequency peak outside the visible domain if the option "Only search marker peaks in visible domain" is not enabled.

**Additional Context**
Profile: [spectrum_analyzer_profile.zip](https://github.com/analogdevicesinc/scopy/files/3529676/spectrum_analyzer_profile.zip)
 - 10Vpp, 500kHz Sine wave

**Comment by jpineda3** [comment]
Still exists in v.026
[spectrum_analyzer_profile.zip](https://github.com/analogdevicesinc/scopy/files/6291291/spectrum_analyzer_profile.zip)

**Comment by jpineda3** [comment]
Still exists in v 1.3-rc2.

**Comment by HRosete** [comment]
**Environment:**
 - OS Version: Windows 10 (10.0)
 - FW Version: [v0.28](https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.28)
 - SW Version: cca49b2
 
This issue is still apparent in [Scopy v1.4.0-rc2](https://github.com/analogdevicesinc/scopy/releases/tag/v1.4.0-rc2). Please see the video below:

https://user-images.githubusercontent.com/43806793/166177671-d7138d0e-2124-4516-87c3-295cb16bc8e1.mp4

**Comment by IonutMuthi** [comment]
can't reproduce
