### ISSUE TITLE
Measurement Units missing in the DIO Settings Panel

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#69]
Connect M2K. Start Scopy, select the detected
 device. Press "Connect" button. After the connection is made, select Pattern Generator feature. Observe the left side DIO settings panel.
Actual Results: The Frequency, Duty and Phase settings do not specify the measurement unit of the values introduced by the user.
Expected Results: The measurement units should be clearly stated for each property of the generated signal (Ex. 'Frequency (Hz)/Duty Cycle(%)/Phase(degrees or radians)").
![pgmsrunits](https://cloud.githubusercontent.com/assets/26061529/24447592/2f0fc4c6-147a-11e7-98aa-0aa92063ac05.PNG)

**Comment by adisuciu** [comment]
Added spinboxes that have built in unit measurements. Fixed with https://github.com/analogdevicesinc/scopy/commit/f4d391626954695bf22e9b75397d217b6885c051
