### ISSUE TITLE
Digital tools running buttons remain visible after disconnecting the board

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#698]
OS Version: Windows 10 (10.0)
FW Version: v.023
SW Version: 652c691

Description of the bug:
If the board is disconnected while Logic Analizer/ Pattern generator/ Digital I/O are running, the running buttons remain visible.
Steps to reproduce:
Open Scopy, connect m2k and run multiple tools, including Logic Analizer, Pattern generator and Digital I/O
![digital_run_button](https://user-images.githubusercontent.com/52502092/64337154-77740d00-cfe7-11e9-989c-1837d54be018.PNG)

In Home tab click Disconnect.
The board is disconnected and the tools are no longer active but running icon is still visible
![digital_run_button_disconnected](https://user-images.githubusercontent.com/52502092/64337162-7b079400-cfe7-11e9-932e-43db94445b3a.PNG)

**Comment by DanielGuramulta** [comment]
Issue should be fixed with: #701

**Comment by andreeaipop** [comment]
On Scopy build: 3975846 (v1.1.0) the bug is fixed.
