### ISSUE TITLE
Values introduced in the DIO Settings Panel not limited to a specific range or type of values.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#70]
Connect M2K. Start Scopy, select the detected device. Press "Connect" button. After the connection is made, select Pattern Generator feature. Observe the left side DIO settings panel.
Actual Results: There is no limitation for introducing frequency, duty cycle and phase values.
Expected results: For each paramenter there should be a range of values that can be introduced by the user. (Ex. when adding a value larger that 100 for the duty cycle, the Scopy tool implicitly will change it to 100).
![pgval](https://cloud.githubusercontent.com/assets/26061529/24447784/ca1aa648-147a-11e7-9fcd-8e6033ea0f5e.PNG)

**Comment by adisuciu** [comment]
Added spinboxes that have min/max values in  https://github.com/analogdevicesinc/scopy/commit/f4d391626954695bf22e9b75397d217b6885c051
