### ISSUE TITLE
Scopy: Tiny, unreadable fonts

### ISSUE THREAD

**Issue by mjkcc** [analogdevicesinc/scopy#708]
OS Version: Windows 10 (10.0)
FW Version: 
SW Version: 48fb6a9

Description of the bug: tiny, practically unreadable fonts

Screen resolution: using recommended 3840x2160 (HP laptop)
Steps to reproduce:
-
![image](https://user-images.githubusercontent.com/52003254/64714029-e93ad380-d48b-11e9-88b5-867d2f0e6891.png)

-

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/mariusz.jankowski/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Latest SW version added support for 4k resolutions on Windows. https://github.com/analogdevicesinc/scopy/releases/tag/v1.1.0
