### ISSUE TITLE
Group With Selected generates the crash - Missing Decoders

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#71]
Connect M2K. Run Scopy via build folder generated through MSYS/Qt, select the detected device. Press "Connect" button. After the connection is made, select Pattern Generator feature. Select multiple DIO and press the button Group with Selected. 
Actual Results: The Scopy Application stops working. This issue happens due to the fact that the decoders folder is missing from the build folder.
Expected Results: Application should continue working properly and decoders folder should be somehow accessed or copied to the build folder.

**Comment by pcercuei** [comment]
I don't think this is a bug, actually, as it won't happen in the release of Scopy installed with the setup installer, but only on a local development build.

**Comment by dNechita** [comment]
Some users might want to build Scopy from scratch and they will have this problem and won't know why crashes occur.
We should add documentation for this.

**Comment by rgetz** [comment]
Is this because the "correct" git submodules aren't set up properly?

**Comment by pcercuei** [comment]
There are no submodules. The 'decoders' are provided by libsigrokdecode and can be found in /usr/share/libsigrokdecode/decoders on Linux, or C:\Program Files\Scopy\decoders on Windows.

The bug here is when trying to run a dev build of Scopy if those decoders have not been installed.

**Comment by adisuciu** [comment]
I implemented c7480f639c845ca5662d2b687a13f2e15eb6e42f which shows an error message when libsigrokdecode or decoders cannot be initialized properly. Also the application no longer crashes when this happens.
