### ISSUE TITLE
Logic analizer: Scopy stops when the time base is adjusted by scrolling

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#711]
OS Version: Windows 10 (10.0)
SW Version: 6fa2c03

Description of the bug:<description>
Steps to reproduce:
Open Scopy, enable Logic Analyzer and try to adjust the Time Base by scrolling. The program stops. 
Same thing happens if you set the Run Mode to Stream and adjust the frequency by scrolling.

**Comment by AlexandraTrifan** [comment]
Using this build ( https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/35251245 ), which is the prepared release candidate build, this bug no longer applies. 
The Logic Analyzer was completely revamped in this version, the Time Base UI control does not exist anymore, and until now we are not aware of any bug related to dynamically changes done to frequency, number of samples or time delay.
