### ISSUE TITLE
General: "Calibration failed" after re connecting the board

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#712]
OS Version: Windows 10 (10.0)
FW Version: v 0.24
SW Version: 6fa2c03

Description of the bug: "Calibration failed " message appears if you disconnect and re-connect the board then press Calibrate.
Steps to reproduce:
Open Scopy, connect m2k, click Calibrate.
Click Disconnect, then Connect again. Click Calibrate and there will appear "Calibration Failed" message.
![calibr_fail_1](https://user-images.githubusercontent.com/52502092/65240588-46690180-daea-11e9-982b-aafc9bf6745c.PNG)

If you Disconnect, the message will disappear but after clicking  on Calibrate the message will appear again. If you repeat this 3-4 times, after clicking Disconnect the names of the tools which were calibrated freeze as "Calibrating..."
![calibr_fail_2](https://user-images.githubusercontent.com/52502092/65240809-cc854800-daea-11e9-97d1-c7a28f147538.PNG)

At this point, if you connect the m2k again the tools will work but the names are still replaced with "Calibrating...". The names remain like this even if you unplug the board from the USB port.
![calibr_fail_3](https://user-images.githubusercontent.com/52502092/65240897-fa6a8c80-daea-11e9-92de-67fef0d7573b.PNG)

The ini files might be useful to reproduce the error.

[Scopy.ini.zip](https://github.com/analogdevicesinc/scopy/files/3630999/Scopy.ini.zip)

**Comment by AlexandraTrifan** [comment]
This should be fixed on the latest master b677caed47d5d32ba3ceda4eb25438e36bff226f

**Comment by andreeaipop** [comment]
In Scopy v1.1.2 the bug is fixed
