### ISSUE TITLE
Drop down menu partially not working

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#72]
Select "Measure" Feature from the bottom right side of the Oscilloscope window. In the section "Custom Selection" press the Horizontal/Vertical drop down menu button. 

![capture3](https://cloud.githubusercontent.com/assets/26061529/24500752/5a3d859a-154f-11e7-8e50-d0b759dcd62c.PNG)

Actual results: the drop down list appears only if the right side of the button is selected (the one containing the down arrow indicator).
Expected Results: the drop down list should be available by pressing the button anywhere within its region.

**Comment by DanielGuramulta** [comment]
Fixed with commit: https://github.com/analogdevicesinc/scopy/commit/18190b64ff458e49fb4d8ab24959a8b6b9182a86

**Comment by amiclaus** [comment]
On Scopy build: be46948(v0.7) the bug is fixed.
