### ISSUE TITLE
Scopy 1.1.1 not compatible with macOS 10.13?

### ISSUE THREAD

**Issue by bobgates** [analogdevicesinc/scopy#722]
**Environment:**
 - OS: macOS 10.13 on MacBook Pro 2017

**Describe the bug**
Can't install: 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/422527/67958234-c193fc00-fbee-11e9-9889-cda1aa928232.png">

On the website, the install file is called Scopy-v1.1.1-osx_10.13.dmg

However, on attempting to install it, I am seeing the above error.

**Comment by AlexandraTrifan** [comment]
Hi, 

We are looking into this, it might be a packaging mistake. We will come back as soon as possible with a response/fix.

-Alexandra

**Comment by AlexandraTrifan** [comment]
Hi,

I created another dmg. Can you try this one?
https://transfer.sh/BUsF0/Scopy-v1.1.1-osx_10.13-patch.dmg.zip

-Alexandra

**Comment by bobgates** [comment]
Runs on 10.13 now. Thanks.
