### ISSUE TITLE
Scopy v1.0.4: Can't see ADALM2k on USB on Mac

### ISSUE THREAD

**Issue by bobgates** [analogdevicesinc/scopy#723]
**Environment:**
 - OS: macOS 10.13 on 2018 Macbook Pro

**Describe the bug**
I installed Scopy in /Applications. It starts up and runs okay but no ADALM2000 module appears available. I have reinstalled the HoRNDIS driver and rebooted. I've tried to find useful info in the logs, but I'm not seeing anything with the word HoRNDIS which worries me a little.

**Expected behavior**
I expected Scopy to start up, see my ADALM,  _then_ crash in some bizarre way a bit later. Forgive me, I've found using it on a Mac a little trying.

Any help appreciated.

**Comment by bobgates** [comment]
Yes.

**Comment by bobgates** [comment]
Oops – the correct answer is No. What I was seeing was one of the install packages.

I’m not seeing the ADALM2k in Finder.

**Comment by bobgates** [comment]
Further news – started to suspect the cable. Indeed – a new USB cable means I can now see the device and Scopy is working. Aaarghhh. It’s always annoying when it turns out to be hardware!

Apologies for wasting your time. It would still be good to get 1.1.1 on macOS 10.13 though.

**Comment by AlexandraTrifan** [comment]
Hello,

We will look into the 10.13 issue. Meanwhile, I am closing this issue.

Thank you,

-Alexandra
