### ISSUE TITLE
Scopy: v1.1.1 flatpak filename differs from installation documentation

### ISSUE THREAD

**Issue by cxcorp** [analogdevicesinc/scopy#729]
In the [installation instructions](https://wiki.analog.com/university/tools/m2k/scopy#installation) for Linux, the documentation says the following:

>After this, get the Scopy.flatpak file from the downloaded archive and run:
>
> ```
>flatpak install Scopy.flatpak
> ```

The flatpak .zip release for v1.0.6 does contain `Scopy.flatpak`, but v1.1.1's .zip contains `scopy-Linux-flatpak.flatpak`, meaning that the commands from the instruction's don't work as-is. While this is a really minor issue, it did cause some confusion in a classroom environment with less techincal users.

I think that a simple solution could be to just rename the flatpak in the zips for the newer releases to `Scopy.flatpak`.

**Comment by adisuciu** [comment]
I updated the documentation. We'll think about changing the flatpak file name.

-Adrian

**Comment by cxcorp** [comment]
Thank you.
