### ISSUE TITLE
M2K Min / Max vertical resolution?

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#73]
What vertical resolution ( gain settings ) are presently supported in Scopy?
It looks like it is always in the low gain range ( largest attenuation setting ). On the 20 mV/Div setting it looks like an LSB is ~18 mV which for 12 bits gives a about a +/- 35 V max range.

There also seems to be a repeatable pattern in the noise at 2.5 KHz and about 4 LSB P-P ( 70 mV).

When will the other gain setting be supported?

**Comment by CElkhoury** [comment]
splitting this into two with #83 (about gain settings). 

On the repeatable pattern - is that on the analog input side, or the output side?

Thanks
