### ISSUE TITLE
Voltmeter: Data logging function does not work on v1.1.1

### ISSUE THREAD

**Issue by keshikan** [analogdevicesinc/scopy#732]
**Environment:**
 - OS Version: Windows 10 (1903)
 - FW Version: v0.25
 - SW Version: v1.1.1

**Describe the bug**
Hello, support.
Data logging function does not work on v1.1.1, but works correctly on alpha v0.11 .

**To Reproduce**
1. Start Scopy v1.1.1, and connect to the device.
1. Click "Run" button on Voltmeter tab.
2. Click "Browse" button and select a *.csv file.
3. Click "ON" button to start logging
4. ON button can't be toggled, and"No file selected" is displayed.

![scopy](https://user-images.githubusercontent.com/16370619/69650062-5fc19780-10b1-11ea-8843-3cd403128bc9.png)

Thank you.

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/734

**Comment by amiclaus** [comment]
Scopy Version 1.1.2
The bug is fixed.
