### ISSUE TITLE
Scopy v1.1.1 crashes immediately after connection attempt

### ISSUE THREAD

**Issue by Kabron287** [analogdevicesinc/scopy#737]
**Environment:**
 - OS: Windows 10 LTSC x64
 - FW Version 0.25
 - SW Version 1.1.1

**Describe the bug**

**To Reproduce**
1. Just try to Connect

**Comment by adisuciu** [comment]
Did you install the driver for Windows ? - https://wiki.analog.com/university/tools/pluto/drivers/windows

Make sure you restart the computer after installing. If that doesn't work, can you connect through an ip context ? https://wiki.analog.com/university/tools/m2k/scopy#connecting_to_a_remote_device
Ip address should be 192.168.2.1

-Adrian

**Comment by Kabron287** [comment]
No, attempt to connect via IP also leads to crash.
At the same time Scopy 1.1.0 works fine.

**Comment by adisuciu** [comment]
Can you try this build - https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/29249927/job/90nnoc5h6nu1jvv7/artifacts ?

It should have fixed some of the crashes.

-Adrian

**Comment by Kabron287** [comment]
Hello, 
file, you suggest(https://ci.appveyor.com/api/buildjobs/90nnoc5h6nu1jvv7/artifacts/scopy-64-setup.exe) is byte-to-byte equal  with my Scopy 1.1.1 scopy-64-setup.exe.
BTW, Scopy 1.1.0 also crashes with IP access.

**Comment by adisuciu** [comment]
scopy-v1.1.1-Windows-setup.exe from the release page has 176 MB as it contains both 32 and 64 bit versions - https://github.com/analogdevicesinc/scopy/releases

The file I suggest is 90.4MB and it should've fixed some stuff from the build server since the last release.

Can you give me the git-tag of the file that crashes. It's in the title bar.
-Adrian

**Comment by Kabron287** [comment]
OK,
Scopy-v1.1.1 6f32056  from  scopy-v1.1.1-Windows-setup.exe(184MB) works like a charm.
Scopy-v1.1.1 c6e5be9 (the subject of the issue) now also works fine.
I gues new setup corrects something. 
Thanks and sorry for disturbance
