### ISSUE TITLE
ADALMA2000: Scopy window too big for Display, can't be adjusted smaller

### ISSUE THREAD

**Issue by pt1270** [analogdevicesinc/scopy#738]
**Environment:**
 - OS: elementary: OS 5.1 Hera 
 - FW Version: 0.24
 - SW Version: V1.1.1
 - Screen Resolution: 1920x1080

**Describe the bug**
When opening Scopy (installed via flatpack) the window is way too large for my screen. I am not able  to make it smaller.

**To Reproduce**
1. Run Scopy V1.1.1 on elementary OS 5.1 

**Expected behavior**
Window fitting the screen. 

**Screenshots**
![Screenshot von 2019-12-10 20 54 52](https://user-images.githubusercontent.com/58709563/70563969-91496100-1b8f-11ea-86f9-db3b959071df.png)

**Additional context**
I think  [#721](https://github.com/analogdevicesinc/scopy/issues/721) is the same problem as mine but im not able to download the fixed flatpack installer since the link is expired.

**Comment by DanielGuramulta** [comment]
Hi,

We already have the fix merged on master. We will make a new release this week, where you would be able to get the new flatpack installer.

**Comment by adisuciu** [comment]
Should be fixed.
