### ISSUE TITLE
Cursor display labels

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#74]
The labels on the cursor display are at best confusing at worst wrong.

![cursor-display](https://cloud.githubusercontent.com/assets/11668458/24565065/a27b0508-1621-11e7-8e83-0cf368ee92a0.png)

Under CurT1 and CurT2 the delta X should be delta T and 1/delta X should be 1/delta T ?
Under CurV1 and CurV2 the delta X should be delta V?

**Comment by rgetz** [comment]
Yes - according to; http://www.tek.com/manual-topic/cursor the "delta X" should be 

Time cursors display Δt, 1/ Δt
Amplitude cursors, and Magnitude cursors (FFT source) display ΔV, ΔI, etc.
