### ISSUE TITLE
Problems building Scopy on Mac - patching qwt

### ISSUE THREAD

**Issue by bobgates** [analogdevicesinc/scopy#742]
MacOs 10.14.6 Mojave - but irrelevant

I'm trying to build Scopy on my Mac, as per https://wiki.analog.com/university/tools/m2k/scopy/build-osx

I've hit an issue with compiling qwt: the instructions call for patching:
    cd ~
    git clone https://github.com/osakared/qwt -b qwt-6.1-multiaxes
    cd qwt
    curl https://raw.githubusercontent.com/analogdevicesinc/scopy/master/qwt-6.1-multiaxes.patch |patch -p1

However, the file pointed to is not on the server - what I get back is a 15 byte file that contains 404: Not Found

Is this important? I see the Linux build instructions call for patching qwt-polar, as do the Mac instructions, but they don't apply a patch when building qwt?

**Comment by AlexandraTrifan** [comment]
Hello,

If this patch is not applied, there is a big chance that the library will fail at link time.
Sorry about this. 
Please try using this updated link: 

`curl https://raw.githubusercontent.com/analogdevicesinc/scopy-snap/master/qwt-6.1-multiaxes.patch | patch -p1
`

I will also update the Wiki documentation for this link.

Thank you,
-Alexandra
