### ISSUE TITLE
Downloading AppVeyor artifacts with Windows 10

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#748]
**Environment:**
 - Windows 10
**Describe the bug**
This is not a Scopy specific problem but, since I need to download a recent build to test I'm posting this here.
I can't seem to download any artifacts from AppVeyor since I upgraded to Windows 10 this fall. I've tried on three different Windows 10 computers including the ADI issued laptop using Firefox, MS Explorer and Edge browsers. None work on any AppVeyor project.

I have a older Windows 8 table which does work.

Any ideas on what needs to be changed on these Win 10 computer / browser settings to get this working again?

I can download from many other sites ( like cloning from GitHub ) so this seems to be limited to AppVeyor.

Thanks

Doug

**Comment by adisuciu** [comment]
Looks like this is an internal ADI issue. There is nothing we can do from a repository/code point of view.
