### ISSUE TITLE
Logic Analyzer - Memory Leak

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#75]
Connect M2K. Start Scopy and connect to the detected device. Select the Logic Analyzer feature. Run the Logic Analyzer. Open Task Manager, select the Processes tab and observe the Scopy.exe process.
Actual Result: The memory used by the process is increasing continuously.
Expected Result: There should be no memory leak while running the Logic Analyzer.

![untitled](https://cloud.githubusercontent.com/assets/26061529/24602699/a9ba929c-1866-11e7-946d-1d71c7b94f32.png)

**Comment by AlexandraTrifan** [comment]
Commit 720f4cd915823c9f0c9df94ee3737669e3faefeb introduces some fixes that reduce the memory usage.  I ran some tests and the memory used did not grow so much in a short period of time. This problem is not completely solved yet, but the tool is more stable now.

**Comment by AlexandraTrifan** [comment]
This no longer happens using the latest version and the new Logic Analyzer. https://github.com/analogdevicesinc/scopy/releases/tag/v1.2.0-rc.1

**Comment by tagoylo** [comment]
This issue does not happen on v1.2. Closing this item.
