### ISSUE TITLE
Pattern Generator: OD mode produces ~1V output

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#753]
**Environment:**
 - Windows
 - FW Version: v0.25 
 - SW Version: be8a93c1

**Describe the bug**
When setting channel output to OD and monitor the output in the oscilloscope, there is a ~1V output measured. I'm not sure if this is a valid bug, but I'm logging it just in case.

**To Reproduce**
1. Go to pattern generator.
2. Click on a channel, enable it.
3. Set output to OD. 
3. Monitor the channel in oscilloscope.

**Expected behavior**
In the previous version of scopy this behavior did not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/72411353-a6746980-37a5-11ea-9e8e-65d7b3ec8e7b.png)

**Comment by adisuciu** [comment]
Output is open drain. Signal is only really driven when it is LOW to GND. When it is HIGH it is Hi-Z so the output will be floating (what you are seeing)
