### ISSUE TITLE
Pattern Generator: Imported file does not load unless frequency is changed

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#754]
**Environment:**
 - OS: Windows 10
 - FW Version: v0.25
 - SW Version: be8a93c

**Describe the bug**
When importing a file to a channel, the imported file does not reflect on the display unless the frequency is changed.

**To Reproduce**
1. Select a channel.
2. Change Pattern to import.
3. Click Open file and select a file.
4. Click import selected channels.
5. Then there is no response on the display.
6. Change frequency and the imported file will now reflect on the display. See video below.

**Screenshots**

![Hnet-image](https://user-images.githubusercontent.com/25096080/72417048-f86fbc00-37b2-11ea-99f2-be896de72306.gif)

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/755

**Comment by tagoylo** [comment]
This bug is fixed in the new pattern generator. Closing this item.
