### ISSUE TITLE
Power Supply: Tracking range

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#757]
**Environment:**
 - OS: Windows
 - FW Version v0.25
 - SW Version 1.1.2

**Describe the bug**
Small bug. Tracking lower limit is 1%. 

**To Reproduce**
1. Go to Tracking ratio control
2. Drag the control button to the lower limit.
3. 1% is the minimum value that can be reached.

**Expected behavior**
The lower limit should be 0%.

**Comment by AlexandraTrifan** [comment]
Can not reproduce it on the latest master. 
This was fixed a while ago. 
Closing this issue.
