### ISSUE TITLE
Logic analyzer: External trigger

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#758]
**Environment:**
 - OS: WIndows
 - FW v0.25
 - SW v1.1.2 -be8a93c

Logic analyzer does not initiate capture when you set conditions for external trigger.

1. From Digital I/O enable DIO 0 as output.
2. From Pattern generator enable DIO1 or any other channel and generate a signal.
3. In Logic analyzer Trigger settings enable External Trigger and set rising edge condition.
4. Toggle DIO0 from 0 to 1. Logic analyzer should start capturing signals but it is waiting.
This happens for any External trigger condition set except for Low.
When the External trigger condition is set to low Logic analyzer is constantly triggered even if the external trigger signal is in High state

**Comment by tagoylo** [comment]
This bug is fixed on v1.2. Closing this item.
