### ISSUE TITLE
Oscilloscope: Print feature- .pdf is saved as .png

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#760]
**Environment:**
 - OS: Windows
 - FW Version v0.25
 - SW Version: v1.1.2 be8a93c

**Describe the bug**
The Print file type is selected as .pdf but the file is saved as .png

1. Go to Oscilloscope, Click print.
2. In the Export File Name box, Save as type tab is set to .pdf as default
3. Click Save and go to the location where the file was saved. 
4. The file is saved as .png

If you repeat the steps above but attepmt to change the File name (wihtout changing the default file type) the file is saved as .pdf

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.
