### ISSUE TITLE
How to change the UI Language ?

### ISSUE THREAD

**Issue by top58525785** [analogdevicesinc/scopy#768]
Dear All:

How to change to the language display of the Scopy?

I didn't find the set of the language function

Thanks

**Comment by adisuciu** [comment]
We only put in the infrastructure pieces that allow us to change the language, however we don't currently have any language packs.

**Comment by top58525785** [comment]
Thanks for your answer, So how to translate to another language, and how to use the translation file to change the UI?

**Comment by top58525785** [comment]
BY the way , Is there API for ADALM 2000?

**Comment by tfcollins** [comment]
@top58525785 see here: https://wiki.analog.com/university/tools/m2k/libm2k/libm2k

**Comment by top58525785** [comment]
hi
Is open source code of scopy the latest？
thanks



发自我的iPhone


------------------ Original ------------------
