### ISSUE TITLE
Build problem with latest Qwt

### ISSUE THREAD

**Issue by wkazubski** [analogdevicesinc/scopy#769]
**Environment:**
 - OS: Linux openSUSE  15.1
 - SW Version: scopy-1.1.2 and qwt-6.1-mulitiaxes r3173

**Describe the bug**
Build for scopy package  fails with this error message:
...
[ 33%] Building CXX object CMakeFiles/scopy.dir/src/cursor_readouts.cpp.o
/usr/bin/c++  -DBOOST_ALL_DYN_LINK -DHAS_CONSTEXPR=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT=1 -DQT_NO_KEYWORDS -DQT_QML_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -I/home/wk/rpmbuild/BUILD/scopy-1.1.2/build -I/home/wk/rpmbuild/BUILD/scopy-1.1.2 -I/home/wk/rpmbuild/BUILD/scopy-1.1.2/build/scopy_autogen/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtUiTools -I/usr/include/qt5/qwt6-multiaxes -I/usr/include/qt5/qwtpolar1 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtXml -I/usr/include/python3.6m -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libftdi1 -I/usr/include/libusb-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/home/wk/rpmbuild/BUILD/scopy-1.1.2/src -I/breakpad  -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -O2 -g -DNDEBUG   -Wall -Werror=return-type -Werror=uninitialized -Werror=init-self -Werror=switch -fPIC -std=c++11 -o CMakeFiles/scopy.dir/src/cursor_readouts.cpp.o -c /home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp
/home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp: In member function ‘QPoint adiscope::CursorReadouts::plotPointToPixelPoint(const QPointF&) const’:
/home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:308:23: error: variable ‘const QwtScaleMap xMap’ has initializer but incomplete type
     const QwtScaleMap xMap = plot()->canvasMap(hAxis);
                       ^~~~
/home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:308:53: error: invalid use of incomplete type ‘class QwtScaleMap’
     const QwtScaleMap xMap = plot()->canvasMap(hAxis);
                                                     ^
In file included from /usr/include/qt5/qwt6-multiaxes/qwt_plot_dict.h:15:0,
                 from /usr/include/qt5/qwt6-multiaxes/qwt_plot.h:15,
                 from /home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:27:
/usr/include/qt5/qwt6-multiaxes/qwt_plot_item.h:17:7: note: forward declaration of ‘class QwtScaleMap’
 class QwtScaleMap;
       ^~~~~~~~~~~
/home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:309:23: error: variable ‘const QwtScaleMap yMap’ has initializer but incomplete type
     const QwtScaleMap yMap = plot()->canvasMap(vAxis);
                       ^~~~
/home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:309:53: error: invalid use of incomplete type ‘class QwtScaleMap’
     const QwtScaleMap yMap = plot()->canvasMap(vAxis);
                                                     ^
In file included from /usr/include/qt5/qwt6-multiaxes/qwt_plot_dict.h:15:0,
                 from /usr/include/qt5/qwt6-multiaxes/qwt_plot.h:15,
                 from /home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:27:
/usr/include/qt5/qwt6-multiaxes/qwt_plot_item.h:17:7: note: forward declaration of ‘class QwtScaleMap’
 class QwtScaleMap;
       ^~~~~~~~~~~
/home/wk/rpmbuild/BUILD/scopy-1.1.2/src/cursor_readouts.cpp:311:22: error: incomplete type ‘QwtScaleMap’ used in nested name specifier
  return QwtScaleMap::transform(xMap, yMap, point).toPoint();
                      ^~~~~~~~~
make[2]: *** [CMakeFiles/scopy.dir/build.make:978: CMakeFiles/scopy.dir/src/cursor_readouts.cpp.o] Error 1
make[2]: Leaving directory '/home/wk/rpmbuild/BUILD/scopy-1.1.2/build'
make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/scopy.dir/all] Error 2
make[1]: Leaving directory '/home/wk/rpmbuild/BUILD/scopy-1.1.2/build'
make: *** [Makefile:133: all] Error 2
...

Is the latest Qwt snapshot too new for scopy-1.1.2?
What snapshot shall I use?

Kind regards

**Comment by adisuciu** [comment]
Hello, did you apply the patches mentioned in the build guide ?

https://wiki.analog.com/university/tools/m2k/scopy/build-linux
