### ISSUE TITLE
Signal generator channel synchronization Bug

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#770]
**Environment:**
 - OS: Win 10
 - FW Version 0.25
 - SW 1.1.2 release

**Describe the bug**
Signal generator channel waveform outputs loose synchronization after setting waveform to Trapezoidal. Does not always come un-locked but if the correct steps are followed (see bellow) then it seems to be reproducible.

**To Reproduce**
In the following example. In the Signal generator set both channels the same. Set the Frequency to 25kHz, Amplitude to 2 V (any value will do), Offset to 2.5V  (any value will do), Phase to 0. Set to Sine waveform.
With signal generator outputs looped back to scope inputs. 
Run Signal Generator.
Run Scope. Set channel range, offset and time base to observe waveforms.
Set to trigger on channel 1. Both scope traces will be (should be) on top of each other, that is synced.
(first screen shot)
Now back in the Signal Generator. Change channel 2 to Trapezoidal with rise/fall time set to 1uS and high / low time set to 19uS. Frequency should be 25 kHz.
Go back to Scope. Waves are now sliding across each other ( see second screen shot hard to show sliding in still picture)
Back in Signal Generator set shape back to sine and wave forms still not sync'd (see third screen shot)
Now type 25 (kHz) in for Frequency  hit return. Wave forms back in sync. See fourth screen shot.

**Expected behavior**
Waveforms should always remain in sync at the set relative phase.

**Screenshots**
Waveforms are in sync.
![image](https://user-images.githubusercontent.com/11668458/75681153-009b9200-5c61-11ea-9175-8f5c49bc706a.png)

Wave forms are sliding across each other, not sync'd.
![image](https://user-images.githubusercontent.com/11668458/75681235-2cb71300-5c61-11ea-9a16-80af9aff9720.png)

Switch back to sine shape and wave forms still not sync'd
![image](https://user-images.githubusercontent.com/11668458/75680436-9cc49980-5c5f-11ea-91da-cc7cbfd96d2e.png)

After entering Frequency as 25 kHz again. Back to as expected.
![image](https://user-images.githubusercontent.com/11668458/75681600-e8784280-5c61-11ea-86cd-8a2b5f17b193.png)

**Additional context**

The ini files might be useful to reproduce the error.
[Scopy.zip](https://github.com/analogdevicesinc/scopy/files/4275714/Scopy.zip)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/782 should fix it

**Comment by HRosete** [comment]
This bug is now fixed at Scopy v1.2.0 (verified at 33ca72f9). Closing this item.
