### ISSUE TITLE
Scopy hang

### ISSUE THREAD

**Issue by ciuffoly** [analogdevicesinc/scopy#779]
OS Version: Windows 10 (10.0)
FW Version: v0.25
SW Version: 3d4c582

Description of the bug: hang
Steps to reproduce:
I have used the ADALM2000   yesterday without problems
This morning any time I start the Oscilloscope on Scopy the program hang (it is locked with Not responding)
I have update now the firmware, but was the same release
I have reboot the PC
I have reinstalled the Scopy software

Sometime the same result but Scopy crash
and only Network analyzer work 

What to do now ?

**Comment by DanielGuramulta** [comment]
Hello

Could you please upload the Scopy.ini file. It should be located in this path:
`C:/Users/<username>/AppData/Roaming/Scopy.ini`
After uploading it could you also try deleting it and then start Scopy again and check if the issue persists.

Daniel

**Comment by ciuffoly** [comment]
I don't find this fine here

C:\Users\ciuffoly\AppData\Roaming

**Comment by ciuffoly** [comment]
Found here

C:\Users\ciuffoly\AppData\Roaming\ADI[

](url)

**Comment by DanielGuramulta** [comment]
`C:/Users/<username>/AppData/Roaming/ADI/Scopy.ini` maybe in the ADI folder, I got the path wrong

**Comment by ciuffoly** [comment]
yes found
[Scopy.zip](https://github.com/analogdevicesinc/scopy/files/4507963/Scopy.zip)

**Comment by DanielGuramulta** [comment]
Thank you!

Will try to see if I can reproduce the bug. Did Scopy work after deleting this file?

**Comment by ciuffoly** [comment]
never tested, I need to try this delete ?

**Comment by DanielGuramulta** [comment]
Yes, you could try to delete this file while Scopy is not running and then try to run Scopy again

**Comment by ciuffoly** [comment]
good I have rename this file and now all work !

thank you 

on this page the Installer for latest (nightly) build (Windows 64-bit) is not a godo link
https://wiki.analog.com/university/tools/m2k/scopy
is there a release after 1.1.2 ?

**Comment by DanielGuramulta** [comment]
You can get the installer from here: https://github.com/analogdevicesinc/scopy/releases
v1.1.2 is the latest. Unfortunately the links on the wiki for the installers don't work anymore and also that build guide needs to be updated. Thanks for also reporting this problems

Daniel

**Comment by ciuffoly** [comment]
thank you very much for your support

**Comment by ciuffoly** [comment]
my webpage about this instrument
http://www.audiodesignguide.com/AudioMesurement/index.html

**Comment by ciuffoly** [comment]
do you think will be possible add some more functions:

1) modify the signal generator level in the Oscilloscope panel
2) add Vrms level in the Oscilloscope panel
3) show Slewrate

**Comment by DanielGuramulta** [comment]
Will open another issue regarding your questions of the features to be implemented and will close this one regarding the Scopy hang.

Daniel

**Comment by adisuciu** [comment]
@ciuffoly replied in the new thread
