### ISSUE TITLE
Scopy:Is the software the latest?

### ISSUE THREAD

**Issue by top58525785** [analogdevicesinc/scopy#781]
HI 

I want to asked the github for scopy here is the latest version source code?

Is there any document how to build?

And is it all open source or not?

**Comment by adisuciu** [comment]
Yes
The build guides might be a little out of  date - https://github.com/analogdevicesinc/scopy/wiki

However, https://github.com/analogdevicesinc/scopy/tree/master/CI/appveyor , contains scripts that are used on our CI servers for different environments, these could be used as reference to build your own Scopy.

-Adrian

**Comment by adisuciu** [comment]
A new build guide is available https://wiki.analog.com/university/tools/m2k/scopy/build-windows?s[]=scopy&s[]=build
