### ISSUE TITLE
Scope: unit selection should be smarter

### ISSUE THREAD

**Issue by dsandber** [analogdevicesinc/scopy#789]
If I type 500 when the voltage unit is set to Volts, it changes to 10.  It would make more sense (and be faster to use) if it changed to milliVolts -- in other words, if the given unit doesn't make sense, but another unit does, change to the closest unit where that value is allowed.

**Comment by adisuciu** [comment]
I think Scopy automatically changing the order of magnitude would be confusing. 

I don't think this is documented, but you can set absolute values to the spinboxes by using suffixes. In your case you can use 500m or 500u which will set the amplitude value to 500mV or 500uV. If you are already on the milivolt setting and want to go to 5V, that's what you write 5V. By writing only 5, you will set 5mV.
