### ISSUE TITLE
All: If program crashes, ADALM2000 can't be found when program restarted

### ISSUE THREAD

**Issue by dsandber** [analogdevicesinc/scopy#790]
Scopy crashed a few times (I'll try to provide a trace for that next time it happens) and when it did, I couldn't restart Scopy.  I had to unplug the USB and plug it back in.

**Comment by adisuciu** [comment]
There is not much that can be done about this because of the way the USB backend works. You can always connect to the board using the IP address - default is 192.168.2.1 . You will always find it this way.
