### ISSUE TITLE
Scopy: Trigger channel selection should be disabled

### ISSUE THREAD

**Issue by dsandber** [analogdevicesinc/scopy#791]
If using a logic analyzer as a trigger source, I believe it doesn't make sense to have the trigger channel source (Channel 1 or Channel 2) enabled since it's not clear how you could trigger from both the Trigger channel and the logic analyzer at the same time.

**Comment by adisuciu** [comment]
I don't see why you couldn't trigger from both Logic analyser and oscilloscope channel. You can select an OR condition between the two.
