### ISSUE TITLE
Scope: Crash

### ISSUE THREAD

**Issue by dsandber** [analogdevicesinc/scopy#792]
OS: Mac Mojave
SW: 1.1.2

I was dragging this widget to the left (possibly too far):

![image](https://user-images.githubusercontent.com/5387753/82041444-79c75480-96a8-11ea-942c-fac415b07380.png)

And the app crashed.

[scopy_crash1.txt](https://github.com/analogdevicesinc/scopy/files/4633822/scopy_crash1.txt)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/840 should fix it
