### ISSUE TITLE
Volt Meter comments:

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#8]
Here are a few observations on the Volt Meter tool.
1. Not sure what "Alternative" current is. Should it say "Alternating" current?
2. The history plot ( voltage over time ) is not a histogram. A histogram does not involve a time axis it is a probability density plot. Change histogram to history.
3. This is a recurring issue across all tools. Screen resizing is messed up. In this tool turning on and off the history plot causes the screen to go off the right side of the screen. Can't manually resize window to get it back. Left-Right resize does not work but up-down resize does?
4. The AC voltage does not seem to be True RMS as it does not include the DC component. You should consider adding True RMS readings.
5. Many DMMs have a peak hold feature. You might want to consider adding this feature for both a max ( positive ) peak hold and min ( negative ) peak hold. With a button to reset the held values of course.

**Comment by ABanut** [comment]
Bug closed as all issues initially reported were split into individual issues.
