### ISSUE TITLE
Scopy::MingGW64 Build Issue

### ISSUE THREAD

**Issue by top58525785** [analogdevicesinc/scopy#807]
HI  I use MingGW to build Scopy

But when go to the last step, It Shows not find GWT_Cmake File

So how to set for QT?

****************************************
CMake Error at CMakeLists.txt:123 (find_package):
  By not providing "FindQwt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qwt", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qwt" with any of
  the following names:

    QwtConfig.cmake
    qwt-config.cmake

  Add the installation prefix of "Qwt" to CMAKE_PREFIX_PATH or set "Qwt_DIR"
  to a directory containing one of the above files.  If "Qwt" provides a
  separate development package or SDK, be sure it has been installed.
*************************************************
Thanks Agiain
Jason.yu

**Comment by adisuciu** [comment]
You didn't install the qwt dependency correctly 
https://wiki.analog.com/university/tools/m2k/scopy/build-windows?s[]=scopy&s[]=mingw#installing_the_dependencies

This wiki page shows how to build Scopy using QWT.

-Adrian

**Comment by top58525785** [comment]
HI Adrian：
I install as what you said。
But still failed
：（



发自我的iPhone


------------------ Original ------------------

**Comment by top58525785** [comment]
HI Suciu：
I want to ask Scopy can build either using Mingw or QT creator？
Am i right？
Thanks again



发自我的iPhone


------------------ Original ------------------

**Comment by adisuciu** [comment]
QTcreator uses MinGW compiler to build. You can also build Scopy from the MSYS terminal.
https://wiki.analog.com/university/tools/m2k/scopy/build-windows?s[]=mingw#set_up_qtcreator

This chapter shows how to setup QtCreator to build Scopy.

-Adrian

**Comment by top58525785** [comment]
HI Adrian:


How are you ?&nbsp; Thanks for your support.


Now I also have some problems, I DO as what you told me,Using MinGW and QT creator.


Compile as bellows, but also failed:( I have do this for couple weeks. said...


Please help to check the attached error messages


Hope to receive you&nbsp;


Best Regards
Jason.yu





测量与测试世界 www.vihome.com.cn
专注传感器，数据采集，电子测量仪器，系统集成，工业控制的专业媒体门户资讯和技术平台。


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Adrian Suciu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 晚上9:51
收件人:&nbsp;"analogdevicesinc/scopy"<scopy@noreply.github.com&gt;;
抄送:&nbsp;"测量与测试世界"<1005452066@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [analogdevicesinc/scopy] Scopy::MingGW64 Build Issue (#807)





 
QTcreator uses MinGW compiler to build. You can also build Scopy from the MSYS terminal.
 https://wiki.analog.com/university/tools/m2k/scopy/build-windows?s[]=mingw#set_up_qtcreator
 
This chapter shows how to setup QtCreator to build Scopy.
 
-Adrian
