### ISSUE TITLE
Network Analyzer: option to keep output offset between run iterations

### ISSUE THREAD

**Issue by benfre** [analogdevicesinc/scopy#808]
I try to use Network Analyzer to measure the response of a amplifier, which has very large DC gain and some input offset. I need to give the exciting generator a constant offset to prevent saturation of the amplifier. 

As between each frequency iteration the DAC are disabled, the amplifier output will ramping from saturation and back each time the offset are applied. 

Maybe a option to keep the offset (hold DAC to the offset voltage) can be added?

I can add a waveform of the amplifier output, if it helps understanding the situation.

**Comment by benfre** [comment]
I think this will also helps for measuring response of transistor circuits.

**Comment by adisuciu** [comment]
We're looking into it ..

**Comment by benfre** [comment]
The reference wave:
![Input](https://user-images.githubusercontent.com/4619493/85272305-94ae9500-b4ae-11ea-8bd4-36a5b7b7480d.jpg)

The amplifier output:
![Output](https://user-images.githubusercontent.com/4619493/85272360-a859fb80-b4ae-11ea-83ad-fd3e566e825c.jpg)

**Comment by damercer** [comment]
A simple solution might be to allow the user to specify a delay time for the AWG / external circuit to settle between frequency changes? Other vendor's tools allow this option. It will slow down the sweeping but can be set to zero when not needed for circuit settling.

Just a suggestion.

Doug

**Comment by adisuciu** [comment]
This option is implemented - 
![image](https://user-images.githubusercontent.com/8676912/85836205-f452bc00-b79e-11ea-8f35-15bb0132a6b4.png)

The naming is a little unfortunate, the first settling time represents the (minimum) time delay between AWG output and ADC acquisition. 

The second settling time (I think this should be renamed) - represents the (minimum) time delay between frequency changes (when the AWG is in high impedance)

The buffer previewer option lets you look into the ADC buffer in time domain, to check if everything looks good.

We're looking into the DAC holding the last sample and not going to high impedance, but this requires firmware/HDL changes. This would address the initial problem a little better.

-Adrian

**Comment by benfre** [comment]
This may be a bug. The second settling time is not effective. When I increase it to 100ms, (showing in previous post pictures), the captured waveforms are still have saturation at the beginning (for other frequency not showing in picture).

Looking into the code, I guess this maybe due to retrieve waveform before the time delay.  I do not fully understand the underlying iio APIs, the line 1203 of `/src/network_analyzer.cpp` is refilling the buffer? and  line 1253 is the waiting.

**Comment by benfre** [comment]
The two are named 'pushDelay' and 'captureDelay' in the code. 

But, I think the 'captureDelay' is not effective now. A bug?  

I don't know the iio functions , I only guess by there names. In my understanding the code, [/src/network_analyzer.cpp](../blob/master/src/network_analyzer.cpp):

- line 1145: wait 'pushDelay'
- line 1146-1149: enable DAC??
- line 1203: refill ADC buffer?? 
- line 1253: wait 'captureDelay'

So the second wait miss the point?

**Comment by adisuciu** [comment]
Yes, you are correct, we changed the way the acquisition works, and we missed that. The fix is trivial, move the msleep function before refilling the buffer. Thanks for catching that. I can create a test build for you to test it out until we release the new software, if you are interested in that.

-Adrian

**Comment by benfre** [comment]
> Yes, you are correct, we changed the way the acquisition works, and we missed that. The fix is trivial, move the msleep function before refilling the buffer. Thanks for catching that. I can create a test build for you to test it out until we release the new software, if you are interested in that.
> 
> -Adrian
Thanks. we can wait appveyor build, and try it.

**Comment by adisuciu** [comment]
Did you get to try this ? 
-Adrian

**Comment by benfre** [comment]
> Did you get to try this ?
> -Adrian

We test the fix. It works. Putting 500ms of settling time, the DC offset is low enough to enable high gain mode.

The reason we are facing this problem is because our amplifier board has a low pass frequency of few Hz, so we need longer settling time. Other applications may not face the same problem.

![20200808_172900](https://user-images.githubusercontent.com/4619493/89706989-12fec200-d99d-11ea-9c04-3e320005b552.jpg)

![20200808_172802](https://user-images.githubusercontent.com/4619493/89707036-6c66f100-d99d-11ea-8c8e-7118676353aa.png)
