### ISSUE TITLE
Amplitude terminology has different interpretations in Osc and SG

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#81]
Open the Signal Generator feature from Scopy and select Waveform tab. The Amplitude parameter in this situation has the meaning of peak value.

Open the Oscilloscope and enable the Measure feature. The Amplitude parameter in the Measure Box has the meaning of peak-to-peak value.

Therefore, we have 2 parameters with same name ("Amplitude"), but different interpretations. From my point of view, this might create confusion for a student using this tool, especially when connecting the Signal Generator from Scopy to the Oscilloscope feature. A proper differentiation between the two terms should be applied.

**Comment by rgetz** [comment]
Or - they should be made the same.

Peak - Peak Amplitude or Amplitude (p-p), should be noted. 

Amplitude from zero isn't a common measurement.
