### ISSUE TITLE
Scopy:: Can't change languages macOS

### ISSUE THREAD

**Issue by vincenttl** [analogdevicesinc/scopy#810]
**Environment:**
 - OS: macOS Mojave 10.14.6
 - https://github.com/analogdevicesinc/scopy/releases/tag/v1.1.2

Cannot change language in preference.

**To Reproduce**
Steps to reproduce the behaviour:
Last part of this page
https://wiki.analog.com/university/tools/m2k/scopy/translate_scopy

**Comment by DanielGuramulta** [comment]
Hi

An issue with the translation feature might be that in v1.1.2 just some gui controls where added. Could you try one of our dev builds: https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/33753783/job/0lmbgsc99ny6aivd/artifacts and see if this works for you? Our next release should have the translation feature fully working.

The new ts files should be added in `
scopy/resources/translations/
`

**Comment by vincenttl** [comment]
It works in this dev build. Thank you
