### ISSUE TITLE
cannot build successful

### ISSUE THREAD

**Issue by Hansen0314** [analogdevicesinc/scopy#818]
Hi,
we got some trouble when building the project.
there is some error as below when we use  https://wiki.analog.com/university/tools/m2k/scopy/build-windows to building Scopy.
![image](https://user-images.githubusercontent.com/44565865/87298590-05d8e980-c53d-11ea-8d0e-60f9d8ca6938.png)
 and I have been finished step before  'cmake -GNinja $SCOPY_CMAKE_OPTS $CMAKE_OPTS ../'
  this is content of SCOPY_CMAKE_OPTS  and CMAKE_OPTS 
![image](https://user-images.githubusercontent.com/44565865/87298608-0d988e00-c53d-11ea-8215-7886092c8163.png)
and the branch of scopy source code  is master
![image](https://user-images.githubusercontent.com/44565865/87298626-138e6f00-c53d-11ea-9e9a-a9f10f42a988.png)
![image](https://user-images.githubusercontent.com/44565865/87298633-15f0c900-c53d-11ea-9463-68136ab6d433.png)
![image](https://user-images.githubusercontent.com/44565865/87298642-18532300-c53d-11ea-9a10-2bf085bbfa50.png)

**Comment by adisuciu** [comment]
It looks like log4cpp is not installed in your system. Can you confirm that you installed scopy-mingw-deps in the MSYS system succesfully ? (you ran  the following script without errors) 

```
source ../CI/appveyor/set_build_env_msys.sh
../install_msys_deps.sh
```

if yes, can you find the following file <your_msys_install_folder>/mingw64/bin/liblog4cpp.dll  ?

-Adrian

**Comment by Hansen0314** [comment]
Yes, I have been installed scope-mingw-deps in the MSYS system successfully .and I cannot find the liblog4cpp.dll at /mingw64/bin/. and I got another error when I use the ubuntu to install the env. can you give me a correct building wiki?

**Comment by Hansen0314** [comment]
and the ubuntu version is 18.04.
![image](https://user-images.githubusercontent.com/44565865/88003197-dc205380-cb36-11ea-9803-18a495a4447f.png)

**Comment by Hansen0314** [comment]
Hi @adisuciu  
do you have some idea about this question?

**Comment by adisuciu** [comment]
So you want to install mingw or ubuntu ? 
For mingw please provide an output of install_msys_deps after running set_build_env.
For ubuntu i'll update the build guide today.

-Adrian

**Comment by adisuciu** [comment]
I assume this was fixed since you sent out a PR
