### ISSUE TITLE
<Instrument>: <None of the applications for Scopy came in the app when I installed it.>

### ISSUE THREAD

**Issue by sean600** [analogdevicesinc/scopy#842]
OS Version: Windows 7 SP 1 (6.1)
FW Version: 
SW Version: 3d4c582

Description of the bug:<description>
Steps to reproduce:
-
-

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/deuce/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Can you be more specific ?

**Comment by sean600** [comment]
The circled region: I don’t have any of these parameters when I install the
program.

On Wed, Aug 5, 2020 at 3:10 AM Adrian Suciu <notifications@github.com>
wrote:

> Can you be more specific ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_analogdevicesinc_scopy_issues_842-23issuecomment-2D669022674&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=5E2uvXbpqUTOXPfdozmW2BvvI_VmXQY6CcKdT_IyUBc&s=3pPzD3jsJLSiz31ywRWNfnSTWPnd-5FS8MoETs2Zq4o&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APMENZ4SYOT4MA2KLJXKBCTR7EAUTANCNFSM4PVDRNUA&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=5E2uvXbpqUTOXPfdozmW2BvvI_VmXQY6CcKdT_IyUBc&s=yZTuED4GZ1a7-2ScZLwpwCqowdjLr8wFiSgK3Fd_HVg&e=>
> .
>
-- 
*Sean Anderson Jr.*
*Junior Electrical Engineering Major, Morgan State University*
*Morgan State Programming Team, Iota Phi Theta Fraternity, Inc.*

**Comment by adisuciu** [comment]
If you attached an image, I can't see it. 
Did you install the driver and connect to the board in Scopy ?

-Adrian

**Comment by sean600** [comment]
Yes I did.

On Wed, Aug 5, 2020 at 8:17 AM Adrian Suciu <notifications@github.com>
wrote:

> If you attached an image, I can't see it.
> Did you install the driver and connect to the board in Scopy ?
>
> -Adrian
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_analogdevicesinc_scopy_issues_842-23issuecomment-2D669159567&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=iBsBfsAakvoMWdPBFsIEFL9NtPHGtDBXeRZ9qh-4dVw&s=r4kfLGedMrD0VmG3E4aGz8YR4R2tOzY5FTypCI5Yh_Q&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APMENZ3T3O7MHO5K32KWYE3R7FEW5ANCNFSM4PVDRNUA&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=iBsBfsAakvoMWdPBFsIEFL9NtPHGtDBXeRZ9qh-4dVw&s=YFBJ1YZK6ZSF58T7Wqp8LlBYhLRy6R8l8HVq5nMfqoE&e=>
> .
>
-- 
*Sean Anderson Jr.*
*Junior Electrical Engineering Major, Morgan State University*
*Morgan State Programming Team, Iota Phi Theta Fraternity, Inc.*

**Comment by adisuciu** [comment]
Can you reattach it using the Github web interface. I'm not sure how replying by e-mail works with attachments.
When you select your device, the instruments should appear on the lefthand side. And when you connect they will be enabled. Picture attached

![image](https://user-images.githubusercontent.com/8676912/89414350-e9daf900-d732-11ea-86a5-a228862bc5ae.png)


-Adrian

**Comment by sean600** [comment]
How can I reach you on github?

On Wed, Aug 5, 2020 at 8:47 AM Adrian Suciu <notifications@github.com>
wrote:

> Can you reattach the picture using the Github web interface. I'm not sure
> how replying by e-mail works with attachments.
> When you select your device, the instruments should appear on the lefthand
> side. And when you connect they will be enabled. Picture attached
>
> [image: image]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_8676912_89414350-2De9daf900-2Dd732-2D11ea-2D86a5-2Da228862bc5ae.png&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=Y2gEcgmmRrMNSHIXQw3wHY5Tdr9yAcVEGZ60GIJ5Thw&s=Va5oOY3hd3TMJwYF27eGAXIJ0lgTlnckzO71UnNy5z8&e=>
>
> -Adrian
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_analogdevicesinc_scopy_issues_842-23issuecomment-2D669172788&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=Y2gEcgmmRrMNSHIXQw3wHY5Tdr9yAcVEGZ60GIJ5Thw&s=gUVDeCAvugaEuDClE6eZ4D5JjvMSzl8p4SDNWqosVVY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APMENZYSKBJU62PP4QDWIHDR7FIF7ANCNFSM4PVDRNUA&d=DwMCaQ&c=0CCt47_3RbNABITTvFzZbA&r=9KdjbLEJ03OOr55YM3dgWMThOfEBp7Ig_3iU-KHTJVI&m=Y2gEcgmmRrMNSHIXQw3wHY5Tdr9yAcVEGZ60GIJ5Thw&s=v717h1nrvfoykCtI5RYjBAPGbLhvJ_DjWHKngr5P-Pg&e=>
> .
>
-- 
*Sean Anderson Jr.*
*Junior Electrical Engineering Major, Morgan State University*
*Morgan State Programming Team, Iota Phi Theta Fraternity, Inc.*

**Comment by sean600** [comment]
![IMG_3890](https://user-images.githubusercontent.com/64505575/89425678-4aecd780-d707-11ea-97a4-0993acad21ba.jpg)
Here's my issue

**Comment by sean600** [comment]
I do not have any of the parameters in the circle

**Comment by adisuciu** [comment]
I need a screenshot of the actual problem. This is a modified screenshot from the wiki.
The instruments don't appear on the left hand side usually when you haven't connected to the board yet.

Once you connect, they will appear. When I say connect I mean this https://wiki.analog.com/university/tools/m2k/scopy#connecting_to_a_usb_device

-Adrian
