### ISSUE TITLE
Network Analyzer: Network Analyzer Mag. & Phase plot horizontal axis not the same, with break in cursor line & lack of agreement 

### ISSUE THREAD

**Issue by AGR-1** [analogdevicesinc/scopy#849]
OS Version: Windows 10 (10.0)
FW Version: v0.25
SW Version: 3d4c582

Description of the bug:<description>
Steps to reproduce: When measuring a simple CR, high pass filter: 10nF, 10kOhms (nominal, actual: 10.15nF & 9.94kOhms) the Network Analyzer plots Scopy puts up has the Phase plot horizontal (frequency) axis a little longer than the Magnitude plot. Place a cursor at the lowest frequency and they read the same. Place a cursor at the highest frequency and there is a nearly 3kHz discrepancy between them on the two plots (see cursor 1 & 2 in NA issue Fig. 1. JPG). 

![NA issue Fig 1](https://user-images.githubusercontent.com/69910827/90656484-5ca6a280-e210-11ea-92ed-f8fd0d279293.JPG)

Place a cursor at the -3dB frequency on the Mag. plot (comes at~1.61 kHz), should be at 45.0 deg. on the Phase plot, but the cursor on the phase plot is at 1.50kHz and not at 45 deg. (see cursor 1 in NA issue Fig. 2)

![NA issue Fig 2](https://user-images.githubusercontent.com/69910827/90656802-76e08080-e210-11ea-884a-b4dc50093e1a.JPG)

OK so it looks like maybe just an annoying offset. So where is 45 deg. on the phase plot, its at 1.57kHz (not 1.61kHz). OK, but maybe too large a scale to expect an accurate measurement. So I scanned 1000 samples from 1500kHz-1700kHz, exported and plotted the Mag. & Phase versus frequency taking best line fits to each curve to get what's shown in NA issue Fig. 3)

![NA issue Fig 3](https://user-images.githubusercontent.com/69910827/90657694-b73ffe80-e210-11ea-88db-b8c964f6ff4e.JPG)

The discrepancy between the f3dB and 45 degree frequencies is even greater. So in summary the issues are: 1) different frequency scales for the Mag. and Phase plots; 2) an apparent off-set in the cursor on the two plots and 3) a lack of agreement between the f3dB and the 45 deg. Phase frequencies that the high pass filter should obey? Please let me know if you need further information and thank you.
-
-

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/rinzler/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
This should've been fixed in the latest version
