### ISSUE TITLE
Signal generator in v0.13

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#87]
The amplitude setting in the signal generator in v0.13 was changed to be p-p but the control limits the entered value to 5. This means that it is no longer possible to generate waveforms that swing all the way from -5 to +5 ( 10 V p-p ) just 0 to +5, -2.5 to 2.5 or -5 to 0 and in between.

Either change amplitude back to peak or allow amplitudes to 10.

Doug

**Comment by pcercuei** [comment]
Good point. Thanks for the report.
