### ISSUE TITLE
Power Supply: "Enable" did not change to "Disable" after enabling channel

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#872]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7c68922a 

**Describe the bug**
When enabling the power supply outputs by clicking the "Enable" button, the label "Enable" does not change to "Disable".

**To Reproduce**
1. Go to the Power Supply instrument.
2. Click on "Enable" button on both outputs.
4. See the error that the "Enable" label is still there and did not change to "Disable" 

**Expected behavior**
"Enable" should change to "Disable".

**Screenshots**
![powersupply-bug1](https://user-images.githubusercontent.com/25096080/93857226-e0125280-fcec-11ea-85d5-ec7252e935d1.png)

**Comment by AlexandraTrifan** [comment]
Fixed with #874

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.
