### ISSUE TITLE
Pattern Generator: Displayed waveform is cut

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#875]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7c68922a

**Describe the bug**

Displayed waveform is cut when the following patterns are selected:

- Clock pattern:
-duty cycle set is multiples of 5

- Random/Binary counter/Pulse/Gray Counter pattern:
-any frequency set results to the displayed waveform cut

**To Reproduce**
1. Go to pattern generator
2. Enable a channel, ex. Dio 0
3. Then double click on Dio 0 on plot.
4. Then select any of the patterns: ClockRandom/Binary counter/Pulse/Gray Counter
     -for the clock pattern set duty cycle to multiples of 5 to see the issue.

**Expected behavior**
Waveform should not be cut.

**Screenshots**
![pg-bug1b](https://user-images.githubusercontent.com/25096080/93962829-48654080-fd8e-11ea-8eae-b9337bffb67e.png)
![pg-bug1](https://user-images.githubusercontent.com/25096080/93962834-4b603100-fd8e-11ea-9236-18a7db1ecd1f.png)
![image](https://user-images.githubusercontent.com/25096080/93962912-764a8500-fd8e-11ea-872d-10504125f516.png)

**Comment by DanielGuramulta** [comment]
Fixed with: c6e4092ca692b73701978548d3b71301940b7e61

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.

**Comment by tagoylo** [comment]
Issue reappeared on Scopy v1.3 build 441fd19.

**Comment by tagoylo** [comment]
Issue still exists in v1.2 RC2.

**Comment by tagoylo** [comment]
Issue still exists in v1.4.0 rc1.

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/1264

**Comment by tagoylo** [comment]
Bug verified fixed on v1.4.0 rc2. Closing this item.
