### ISSUE TITLE
Pattern Generator: Run and Single buttons messy sequence

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#876]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7c68922

**Describe the bug**
Clicking Run does not change the label to Stop.  
Although with the following sequence, the Stop label shows.

**To Reproduce**
1. Go to Pattern generator
2. Click Run 
3. Then click Single.
4. The Stop label shows with green box.
5. Then if we click Stop (with green box), it now changes to orange box and the Single will also change to Stop label.
6. Now both buttons are with Stop labels and to get back to their original state, click 3 times
on the supposed-to-be Single button with Stop label.

**Expected behavior**
Clicking Run should change the label to Stop. And by clicking Single, Stop should revert back to Run.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/93976691-eddadd00-fdab-11ea-9ffb-1d57e34e8712.png)
![image](https://user-images.githubusercontent.com/25096080/93976723-fdf2bc80-fdab-11ea-9802-7fa7d15335ed.png)
![pg-bug3](https://user-images.githubusercontent.com/25096080/93976552-bcfaa800-fdab-11ea-8851-4b716ec61a71.png)

**Comment by DanielGuramulta** [comment]
Fixed with: 625b2e0c40563ff6d70e9c628da2c6db971ad6c3

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.
