### ISSUE TITLE
Pattern Generator: Remove/Hide box outline in general and channel settings panel

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#879]
**Describe the solution you'd like**
Remove/Hide box outline in general and channel settings panel since it does not follow the template (or the usual look) of the panels as seen in the other instruments settings panel. 

![image](https://user-images.githubusercontent.com/25096080/94105073-1675dc00-fe6b-11ea-8a1d-f83f1d35ce1d.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/commit/fcd78da2e3961ecec4561396d859c2434530abe0 should fix it

**Comment by tagoylo** [comment]
This enhancement is implemented. Closing this item.
