### ISSUE TITLE
Connecting to a device 

### ISSUE THREAD

**Issue by DanielGuramulta** [analogdevicesinc/scopy#88]
When clicking on the add button, a new page should be opened where we have the following

![schita](https://cloud.githubusercontent.com/assets/26142210/25434781/51838e70-2a96-11e7-9feb-8292c09b4d64.PNG)
The connect button will search for the device with the given ip, Add will work only when we have found a device, and on click it will add the device, abort will return to the normal page that is usually displayed.

![capture4](https://cloud.githubusercontent.com/assets/26142210/25434861/ab9ad832-2a96-11e7-825e-08444c4d31d9.PNG)

**Comment by pcercuei** [comment]
So how would that be different from what we already have?

**Comment by DanielGuramulta** [comment]
We would be able to use the application , while it is searching for a device.

**Comment by pcercuei** [comment]
I don't really understand the point, there is nothing else that the user would or could do than waiting while trying to connect to a device.

**Comment by dNechita** [comment]
I think there are some enhancements that this approach would bring:
- avoids the application to hang (both the window and the client area). Even if the hang takes a couple seconds it's never a good idea to have things hanging, especially the window that currently cannot be moved, minimized, etc.
- avoids using dialogs. This way it gets to be consistent with the rest of the application.
- this might be the starting point of a more complex device manager.  A device manager could be used to interrogate the device (calibration details, temperature, hardware revision, firmware revision, etc), remove it from the list of devices, perform a custom calibration and other actions that we might add in the future.

**Comment by amiclaus** [comment]
On Scopy build: 07076df (v0.12) the feature is implemented.
