### ISSUE TITLE
Pattern Generator: In number pattern, the color of the number set is always red after entering 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#882]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
 In number pattern, the color of the number set is always red after entering a value although it is within the limit.

**To Reproduce**
1. Go to the pattern generator
2. Enable a channel, ex. Dio 0
3. Then set its pattern to Number. By default, the number is 0 and the color is not in red.
4. Type 0 again on the number box, now the color of 0 is red.

**Expected behavior**
Only red when the number is above the max number of grouped channels' capacity.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/94146027-f3b4e900-fea5-11ea-9e0c-fd74968adce6.png)

**Comment by DanielGuramulta** [comment]
Fixed with: 8fb53d4c46163a20faf9a831c31d522a48583efa

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.
