### ISSUE TITLE
Network Analyzer: Some UI parts of the Settings panel is cut

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#886]
**Environment:**
- OS: Windows 10
- FW Version: m2k-fw-v0.25-3-g1c38-dirty
- SW Version or git tag: 7eec50d

**Describe the bug**
Some UI parts of the Settings panel is cut. The following parts are cut: Sample Count, 2 Apply boxes, Min. Phase, Max. Phase, View Osc box, and Next box. See the picture attached for reference.
My laptop's scale setting is at 100%.

**To Reproduce**
1. Go to Network Analyzer
2. Click on Settings and scroll down to see the issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/94250082-52846c00-ff53-11ea-850d-8f4ed107e51a.png)

**Comment by adisuciu** [comment]
Does not reproduce on v1.3.0-rc2
