### ISSUE TITLE
General Settings (Preferences): Clearer statement to where the user should find the notes

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#887]
**Environment:**
OS: Windows 10
FW Version: m2k-fw-v0.25-3-g1c38-dirty
SW Git Tag: 7eec50d6

**Is your feature request related to a problem? Please describe.**
Enabling the user notes in the Preferences says that it can be found on the main page. A new user will be confused about where the "main page" is. One may assume that it is in the Home Page:
![image](https://user-images.githubusercontent.com/43806793/94252828-0cc9a280-ff57-11ea-8ae1-7dc58da924d3.png)
when in fact, it is located in a tab under the Preferences.
![image](https://user-images.githubusercontent.com/43806793/94253199-88c3ea80-ff57-11ea-82b6-6c443d2bb5ee.png)

**Describe the solution you'd like**
A better reword of the "Enable user notes in main page," befitting the right location of the user notes tab to avoid confusion.

**Comment by HRosete** [comment]
FW: 
[m2k-fw-v0.25-3-g1c38-dirty.zip](https://github.com/analogdevicesinc/scopy/files/5331268/m2k-fw-v0.25-3-g1c38-dirty.zip)

**Comment by adisuciu** [comment]
When the user notes are set, by the user, they are displayed in the main page - as you described it. I think the wording is fine.
