### ISSUE TITLE
General Settings (Preferences): Changing the language doesn't translate everything

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#889]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
Some parts of the Preference section does not translate to the language of preference.

**To Reproduce**
1. Go to "Preferences"
2. Select language
3. Restart Scopy

**Expected behavior**
Everything in the Preference section must be translated to the selected language

**Screenshots**
scopy_cn:
![image](https://user-images.githubusercontent.com/43806793/94266408-b4050480-ff6c-11ea-9568-7403096d0033.png)
scopy_fr:
![image](https://user-images.githubusercontent.com/43806793/94266532-de56c200-ff6c-11ea-8894-7f9ce359c983.png)
scopy_ro:
![image](https://user-images.githubusercontent.com/43806793/94266760-27a71180-ff6d-11ea-85fe-32e6d9b2cb66.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/937 working on it

**Comment by adisuciu** [comment]
Fixed
