### ISSUE TITLE
General Settings (Preferences): No "restart" warning when changing the language from CN

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#890]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50da

**Describe the bug**
Scopy set in scopy_cn (Chinese) language lacks the "restart" warning. It only happens the first time you opt to change the language from Chinese. Succeeding attempts display the warning.

**To Reproduce**
1. Go to "Preferences"
2. Set your language to "scopy_cn"
3. Restart Scopy.
4. Go to "Preferences"
5. Change language back to auto (or scopy_ro, scopy_fr, scopy_en)

**Expected behavior**
An attempt in changing the language must display a Scopy restart warning on the first try.
![image](https://user-images.githubusercontent.com/43806793/94268679-1a3f5680-ff70-11ea-951b-603ab6a8e3f5.png)
(taken on the 2nd attempt to change the language from Chinese)

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/43806793/94268395-ac932a80-ff6f-11ea-90a0-30732b478b05.png)
2. 
![image](https://user-images.githubusercontent.com/43806793/94268481-d0567080-ff6f-11ea-8e5b-e6b178906af1.png)
![image](https://user-images.githubusercontent.com/43806793/94269003-9afe5280-ff70-11ea-963a-36e5c922cd31.png)
![image](https://user-images.githubusercontent.com/43806793/94269165-da2ca380-ff70-11ea-8652-5955db1d2703.png)

**Comment by HRosete** [comment]
FW: [m2k-fw-v0.25-3-g1c38-dirty.zip](https://github.com/analogdevicesinc/scopy/files/5331266/m2k-fw-v0.25-3-g1c38-dirty.zip)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/937 - working on it

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/939
