### ISSUE TITLE
Network Analyzer: Wrong plot and buffer shows no signal

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#891]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
When trying to get the bode plot of a LPF, the bide plot acquired by the network analyzer is not of a LPF. When monitoring the plotting on the buffer previewer, it can be observed that there is no signal shown on the buffer previewer. See the picture attached.

**To Reproduce**
1. Set up the following for a LPF plot. 
![image](https://user-images.githubusercontent.com/25096080/94395554-89949080-0192-11eb-9c5e-8e4d0add0929.png)
2. Set frequency sweep from 10Hz to 1MHz.
3. Set sample count to 200.
4. Set amplitude to 1V, no offset
5. Enable buffer previewer to monitor buffer.
6. Run network analyzer. Observe that there is no signal showing in the buffer previewer and the plot for LPF is wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/94395171-a381a380-0191-11eb-8434-38e96f101cb3.png)
![image](https://user-images.githubusercontent.com/25096080/94395509-77b2ed80-0192-11eb-87b4-5ffce257306d.png)

**Comment by amiclaus** [comment]
@tagoylo the circuit setup looks like a HPF rather than LPF.

@adisuciu Anyway, this looks like a valid issue:

Same setup as above (same firmware, Scopy version)

Output:
![image](https://user-images.githubusercontent.com/26061529/95227620-fea53d00-0806-11eb-8e42-1c5ee522e88b.png)

**Comment by tagoylo** [comment]
Issue invalid. Did not show up after checking again. Closing this item.
