### ISSUE TITLE
Logic Analyzer: Inconsistent intervals of Sample Rate when in fine interval enabled

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#892]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
When fine interval is enabled (orange dot on knob) on sample rate, changing the value using the +/- buttons results to inconsistent intervals.

**To Reproduce**
1. Go to logic analyzer
2. Under general settings, enable fine interval for sample rate by clicking on the knob. Orange dot should appear
3. Change value by clicking +/-, it can be observe that the interval is inconsistent

**Screenshots**
![Scopy - v1 2 0 - v1 2 0 2020-09-28 15-08-48](https://user-images.githubusercontent.com/25096080/94401718-9bc7fc00-019d-11eb-9af4-39d927639778.gif)

**Comment by adisuciu** [comment]
This is the expected behavior as the available sample rates are not linear. They are 100MSPS divided by some integer.
(100MSPS / n)

-Adrian
