### ISSUE TITLE
Voltmeter: "Run" did not change to "Stop"

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#893]
**Environment:**
 - OS: Windows 10
 - FW Version : m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
After clicking Run, the label of the button did not change to Stop.

**To Reproduce**
1. Go to Voltmeter
2. Click on "Run"
3. Observe how it did not change to "Stop"

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/94409425-ba7fc000-01a8-11eb-9fac-917e26129089.png)

**Comment by DanielGuramulta** [comment]
Should be fixer with: c6d4c5ce9ff9e41dc04838d729b3ec425c428288

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.
