### ISSUE TITLE
Signal Generator: Skewed Square Waveform from 5MHz up tp 30MHz

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#901]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
The preview of the square waveform skews into somewhat a trapezoidal waveform from frequencies 5MHz up to 30MHz.
![image](https://user-images.githubusercontent.com/43806793/94664245-4165a180-033d-11eb-8b04-fdac56896b7d.png)

**To Reproduce**
1. Go to 'Signal Generator.'
2. Click on 'Waveform' and select 'Square.'
3. Set the frequency anywhere between 5MHz and 30MHz.
4. Increment/Decrement the frequency using the + and - keys and see the waveform skew.

**Expected behavior**
The square waveform must retain its shape even if the frequency's changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43806793/94664245-4165a180-033d-11eb-8b04-fdac56896b7d.png)

**Additional context**
(can't seem to upload the .ini file)

**Comment by adisuciu** [comment]
This is the expected behavior. Plot sample rate is 75MHz (the same as DAC sample rate)

**Comment by HRosete** [comment]
Thank you for the clarification, Adrian!
