### ISSUE TITLE
Signal Generator: Visible Falling Ramp Waveform's long overshoot in the preview

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#902]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
Unnecessary overshoots are seen in the preview of the Falling Ramp Sawtooth's waveform. This is visible on both Channels 1 and 2. This does not appear on the oscilloscope, though.

**To Reproduce**
1. Go to 'Signal Generator.'
2. Click on 'Waveform.' Select Falling Ramp Sawtooth.
3. Set the amplitude to 5Vp-p. See the preview graph.
4. Increment/Decrement the amplitude and observe the waveform.

**Expected behavior**
There should be no overshoots on the waveform previews.

**Screenshots**
Channel 1
![image](https://user-images.githubusercontent.com/43806793/94673054-b9859480-0348-11eb-84c8-24c1f1d70078.png)
Channel 2
![image](https://user-images.githubusercontent.com/43806793/94673131-db7f1700-0348-11eb-82b3-6113383f609b.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/gr-scopy/commit/f48b45cabe2a81f491137dbc220032ea65f080c3 should fix it

**Comment by HRosete** [comment]
Verified on 33ca72f9, bug is fixed. Closing this issue.
