### ISSUE TITLE
Network Analyzer: Nyquist plot stops plotting after first plot when capturing in continuous

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#916]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
When running network analyzer in continuous capture, the Nyquist plot seems to stop capturing/plotting after plotting the first set of data. Also, there's a line that shows connecting the end and start of the plot.

**To Reproduce**
1. Go to the Network analyzer.
2. I used an LPF circuit (with 470ohms and 1uF for the screenshot below) and used the following setup.
![image](https://user-images.githubusercontent.com/25096080/95344046-c9264f80-08eb-11eb-9f4b-e7e77ff3c1b2.png)
3. Run network analyzer.
4. Change the plot to Nyquist and observe the plot.
5. The result is that there's a line that shows connecting the end and start of the plot. And it seems that it stopped plotting the newly captured data, unlike Nichols and bode plot.

I attached the result when running only in Single and when running continuously.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/95344880-afd1d300-08ec-11eb-8611-27965f220765.png)

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/commit/7a500983a67fcefae4d50d10cee62fefbe2a2ef1 fixed

**Comment by tagoylo** [comment]
This bug is fixed. Closing this item.
