### ISSUE TITLE
ADALM2K: please release scopy as AppImage 

### ISSUE THREAD

**Issue by jpnielsen** [analogdevicesinc/scopy#918]
Many applications release as Appimage - but not scopy.
Please release scopy as AppImage, that would make my install a lot easier.

https://appimage.org/

https://github.com/AppImage/AppImageUpdate

**Comment by adisuciu** [comment]
We're currently only providing flatpak for linux binaries. Our next goal is to provide debian packages, but I can't give an ETA on that. If you have any experience with appimages, feel free to provide a recipe, and we can probably add it to our CI.

-Adrian
