### ISSUE TITLE
Network Analyzer: "Stop" label does not revert back to "Run" after clicking Single

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#919]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
"Stop" label does not revert back to "Run" after clicking Single. See steps to reproduce.

**To Reproduce**
1. Go to the network analyzer
2. Click Run.
3. Then after a few seconds, click Single.
4. It can be observed that the Stop label did not revert back to the Run label although the function and color of the button are for Run.
5. The if you click on "Stop" in green, the Single button becomes a Stop button but when clicked it still functions as single capture.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/95424689-988af800-0975-11eb-8864-741e03eafdad.png)
![image](https://user-images.githubusercontent.com/25096080/95424719-a6407d80-0975-11eb-92f7-b894c104eb54.png)
![image](https://user-images.githubusercontent.com/25096080/95424734-b0627c00-0975-11eb-8a07-2c81fd162618.png)

**Comment by DanielGuramulta** [comment]
This should be fixed with commit: 625b2e0c40563ff6d70e9c628da2c6db971ad6c3

**Comment by tagoylo** [comment]
Issue fixed. Closing this item.
