### ISSUE TITLE
Pattern Generator: Stop status on the plot does not disappear

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#929]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 33ca72f9

**Describe the bug**
After clicking Run, the clicking Stop, a stop status shown on the upper right of the plot appears. But after clicking again Run, the stop status does not disappear.

**To Reproduce**
1. Go to Pattern Generator
2. Click on Run
3. Click on Stop
4. A stop status is shown on the upper right of the plot appears.
5. But after clicking again Run, the stop status does not disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/96554908-ba776980-12e9-11eb-8025-e36eb6f20f0a.png)

**Comment by DanielGuramulta** [comment]
Should be fixed with: d97237cc5582ef7590d686ac25e0d48c9ae97aa0
