### ISSUE TITLE
Measurements Display All miscorrelation between Ch1 and Ch2

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#93]
Open Oscilloscope feature. Set both Channels to be visible, select Channel 1 and open the Measure tab. Set 'Display all' measurements to be on. 
Now select Channel 2 and open the Measure tab.  Observe that the 'Display All' feature is on for Channel 2, but the measurements window is displayed for Channel 1.
![oscmsrmiscorr](https://cloud.githubusercontent.com/assets/26061529/25954201/3532ad8a-366e-11e7-9861-c533275863a9.PNG)

**Comment by DanielGuramulta** [comment]
This commit should fix the problem: https://github.com/analogdevicesinc/scopy/commit/554c38f1d3aff3d75f03e0c5a63fd7f7674b261c

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
