### ISSUE TITLE
When the button is in Stop, the icon beside it is still the run/play (triangle) and not the stop icon (square)

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#933]
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 33ca72f

**Describe the bug**
When the button is in Stop, the icon beside it is still the run/play (triangle) and not the stop icon (square).
This exists on the following instruments:
- oscilloscope
- spectrum analyzer
- network analyzer
- signal generator
- pattern generator

**To Reproduce**
1. Click Run
2. Notice the icon when the button is in Stop status.

**Screenshots**
![image](https://user-images.githubusercontent.com/25096080/96678615-a5abdc00-13a4-11eb-94dd-0a85f2292e72.png)

**Expected behavior**
Should change to the square icon, the same with voltmeter:
![image](https://user-images.githubusercontent.com/25096080/96678584-99278380-13a4-11eb-834a-cd38c3b356c8.png)

**Comment by AlexandraTrifan** [comment]
Should be fixed with commit d6d26bec4e1908c6f0f970635ce029c1c149fbb4
