### ISSUE TITLE
Oscilloscope: Shifting the phase on Signal Generator does not implement on the Oscilloscope real-time

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#934]
**Environment:**
 - OS: Windows 10
 - FW Version: [m2k-fw-v0.25-3-g1c38-dirty.zip](https://github.com/analogdevicesinc/scopy/files/5414324/m2k-fw-v0.25-3-g1c38-dirty.zip)
 - SW Version or git tag: 33ca72f9 

**Describe the bug**

**To Reproduce**
1. Attach M2K to your laptop using a micro-USB to USB cable.
2. Open Scopy. Make sure to disconnect all connections on M2K.
3. Unzip Book1-csv.zip (see below) and save the Book1 CSV file.
4. Go to Signal Generator. Set these settings to Channel 1: Triangle waveform, 4Vpp amplitude, 1MHz frequency, 2V offset, 180 degrees phase.
5. Select Channel 2 and got to Buffer. 
6. Click 'Load File' and navigate to Book1.csv. Click 'Enter.'
7. In Channel 2 still, set these settings to Scaling (below 'Load File'): Amplitude = 5V, SampleRate = = 2.027 Msps, Offset = 0V, Phase = 0 samples.
8. Go to the Oscilloscope.
9. Set time base (Horizontal) to 1us, position to 0s, volts/div to 1V/div, and position to 0V.
10. Run Signal Generator and Oscilloscope.
11. Detach the Signal Generator by dragging the instrument away from the pane.
12. Change Channel 1's phase by clicking "+" and "-" and observe the waveforms on the Oscilloscope.
13. Do the same thing to Channel 2, change the phase. Observe.

**Expected behavior**
The waveform seen on the oscilloscope must reflect the changes applied in real-time from a running signal generator.

**Screenshots**
at Phase shift: 90 degrees; Waveform on Oscilloscope corresponds to the Signal Generator's
![image](https://user-images.githubusercontent.com/43806793/96694712-5de47f00-13bb-11eb-861e-19c330862eae.png)

at Phase shift: 180 degrees; Waveforms on Oscilloscope and Signal Generators do not match with regards to Phase
![image](https://user-images.githubusercontent.com/43806793/96694972-b1ef6380-13bb-11eb-8d75-7377c4d00be6.png)

at Phase shift: 225 degrees; Waveforms on Oscilloscope and Signal Generators do not match with regards to Phase
![image](https://user-images.githubusercontent.com/43806793/96695144-e4995c00-13bb-11eb-9d09-a8b20c087a53.png)

**Additional context**
[scopy_osc.zip](https://github.com/analogdevicesinc/scopy/files/5414438/scopy_osc.zip)
[Book1-csv.zip](https://github.com/analogdevicesinc/scopy/files/5414439/Book1-csv.zip)

**Comment by adisuciu** [comment]
Well you are setting 1M frequency for the triangle and 2.027 for the second. So the signals will never be in phase because their frequencies are not multiples of one another - they are sliding one on top of the other. If you chose 1M frequency for triangle and same frequency for the stairstep, their phase would match the settings.

-Adrian

**Comment by HRosete** [comment]
Thank you for the clarification, Adrian.

**Comment by HRosete** [comment]
Closing this issue.
