### ISSUE TITLE
Signal Generator: waveform settings

### ISSUE THREAD

**Issue by DanielGuramulta** [analogdevicesinc/scopy#94]
When selecting the mHz option for the frequency in the waveform tab:
![signalgeneratorbug1](https://cloud.githubusercontent.com/assets/26142210/25994364/45d2c000-3716-11e7-9457-8e14387e0e22.png)
Scopy will hang for about 50-60 seconds before changing it;
![signalgeneratorbug2](https://cloud.githubusercontent.com/assets/26142210/25994515/cb015462-3716-11e7-803b-b97618cf0d24.png)
Also if we use the signal generator with the mHz option (for the frequency in the waveform tab) and then disconnect the device, when connecting it again, scopy will hang for the same amount of time before we can use its tools:
![signalgeneratorbug3](https://cloud.githubusercontent.com/assets/26142210/25994561/fd070f74-3716-11e7-855f-c4aad43eaed8.png)

**Comment by pcercuei** [comment]
Yes, I don't know why, GNU Radio chokes when generating slow waveforms...

**Comment by msuciu** [comment]
If it helps I receive this error.
![wg](https://user-images.githubusercontent.com/13637543/27950698-f446429a-630a-11e7-8a1c-02ad7facd3b9.png)

**Comment by adisuciu** [comment]
This should be fixed with preview window optimizations - f2876e55e1d1ece4a1b2f3d358a623d9a0368e55 and f3e3f436ce07e6fc18038d2370f5f0a8163951df

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
