### ISSUE TITLE
Logic Analyzer improvements

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#949]
Logic analyzer:
- channel names could be 1/2/3 instead of DIO0/DIO1/DIO2 - this would make them look cleaner on the plot. The handle should have the text centered.
- Oneshot maximum buffersize: MAX_BUFFER_SIZE*64 instead of MAX_BUFFER_SIZE - use kernel buffers similar to streaming
- Streaming - sample rate max 10msps but buffer can be any size
- Oneshot mode should be selected by default
- Trigger delay should be visible for both modes

- There is an plotting artifact when plotting lare buffersizes

![image](https://user-images.githubusercontent.com/8676912/97871493-41cad100-1d1d-11eb-9b36-fd6f2f40c6e0.png)

- When MAX_BUFFER_SIZE is reached in the pattern generator - show a warning https://github.com/analogdevicesinc/scopy/issues/714
- Show buffersize and sample rate on top of plot for both logic analyzer and pattern generator similar to oscilloscope.

![image](https://user-images.githubusercontent.com/8676912/97871368-13e58c80-1d1d-11eb-972a-286a2cd74bfc.png)

**Comment by DanielGuramulta** [comment]
Created a separate issue to track the bug described in the above list: #972

**Comment by DanielGuramulta** [comment]
Implemented with: #971

**Comment by tagoylo** [comment]
On "channel names could be 1/2/3 instead of DIO0/DIO1/DIO2 - this would make them look cleaner on the plot. The handle should have the text centered."
Is it only the channel names on the handle or is it also applicable on the list of channels on the menu? 

In logic analyzer, the name of the channel only changes the handle text and not the channel name list.
![image](https://user-images.githubusercontent.com/25096080/113829535-2f672e80-97b8-11eb-9b10-85fbb4911e38.png)

But in pattern generator, both changes.
![image](https://user-images.githubusercontent.com/25096080/113829578-3c841d80-97b8-11eb-8210-30def1bdc64b.png)

**Comment by DanielGuramulta** [comment]
> On "channel names could be 1/2/3 instead of DIO0/DIO1/DIO2 - this would make them look cleaner on the plot. The handle should have the text centered."
> Is it only the channel names on the handle or is it also applicable on the list of channels on the menu?
> 
> In logic analyzer, the name of the channel only changes the handle text and not the channel name list.
> ![image](https://user-images.githubusercontent.com/25096080/113829535-2f672e80-97b8-11eb-9b10-85fbb4911e38.png)
> 
> But in pattern generator, both changes.
> ![image](https://user-images.githubusercontent.com/25096080/113829578-3c841d80-97b8-11eb-8210-30def1bdc64b.png)

Things should be more consistent now with pr: https://github.com/analogdevicesinc/scopy/pull/1087

**Comment by tagoylo** [comment]
> Streaming - sample rate max 10msps but buffer can be any size

does the sample max rate correspond to this parameter? Should this be only 10 msps?
![image](https://user-images.githubusercontent.com/25096080/116376643-0976fc00-a843-11eb-926b-820f0495e4e0.png)

**Comment by adisuciu** [comment]
Yes this is fine, if you up the nr of samples past a threshold you will get a warning.
