### ISSUE TITLE
Show libm2k version in infopage

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#950]
![image](https://user-images.githubusercontent.com/8676912/97879990-45fceb80-1d29-11eb-8bd1-9f8a9a95ef4d.png)
Show libm2k version here

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/959

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/scopy/pull/969

**Comment by tagoylo** [comment]
libm2k version not shown in this info page
![image](https://user-images.githubusercontent.com/25096080/116492667-6d470680-a8cf-11eb-8586-9fa9406d08f2.png)

but it can be seen, in the About>build info
![image](https://user-images.githubusercontent.com/25096080/116492751-a41d1c80-a8cf-11eb-9bbc-9a2d8c041f88.png)

Is it intended to be shown on the info page?

**Comment by adisuciu** [comment]
That's fine, the infopage shows device info (ADALM2000) which does not make use of libm2k
