### ISSUE TITLE
Mixed signal improvements

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#961]
![image](https://user-images.githubusercontent.com/8676912/98834594-0ed4bb80-2448-11eb-9349-76c7a9dc79ee.png)

The picture attached shows the new location of the enable mixed signal button
The label should be moved under the digital grouping
There should be a button that redirects you to the logic triggering
Investigate if logic triggering can use TI as input trigger - it should be added to the list of channels.

**Comment by DanielGuramulta** [comment]
Implemented with: #971
