### ISSUE TITLE
Scopy crash on Windows 7

### ISSUE THREAD

**Issue by 3Ferro3** [analogdevicesinc/scopy#976]
OS Version: Windows 7 Version 6.1 (Build 7601: SP 1)
FW Version: 
SW Version: v1.2.0

Description of the bug:<Scopy non started and write problem on dump file>
Steps to reproduce:
Click on scopy icon
-

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/pc/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.
![scopy_ini](https://user-images.githubusercontent.com/58090891/101285395-459eb700-37e5-11eb-98db-0320cda2522a.jpg)
![CrashDump](https://user-images.githubusercontent.com/58090891/101285441-71ba3800-37e5-11eb-9eea-9edc84155d57.jpg)

**Comment by rgetz** [comment]
I don't think anyone can debug this with the information given.

What are you doing, when does it crash? (we need the files, not pictures of the files).

**Comment by 3Ferro3** [comment]
as required I attach the crash files. The crash happens when starting the application that does not open.
waiting for an answer. Kind Regards

Ferruccio Pacciani
[2e2384dc-452f-4153-8266-b524e318f71b.zip](https://github.com/analogdevicesinc/scopy/files/5739390/2e2384dc-452f-4153-8266-b524e318f71b.zip)

**Comment by adisuciu** [comment]
We'll send over a test build in a few days. If you could test that, it would be great.

**Comment by 3Ferro3** [comment]
Thanks, as soon as the new version arrives I will try it immediately.

Starting Scopy nothing happens, the interface does not start, the dump files are written in the \ AppData \ Roaming \ ADI \ crashdmp \ folder.

Waiting for the new version to be tested

Kind regards

Ferruccio Pacciani

**Comment by adisuciu** [comment]
This is not a release but this version should have a lot of fixes - would you mind giving it a try and see how it works?

Make sure you tick delete the ini files in the setup process, or delete them manually.

https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/37944786/job/g4x6c5ep2csfs08o/artifacts

-Adrian

**Comment by adisuciu** [comment]
Closed due to inactivity - assuming fixed
