### ISSUE TITLE
Pattern Generator: application crashed when editing groups, cannot access DIO 0

### ISSUE THREAD

**Issue by lysynski** [analogdevicesinc/scopy#977]
OS Version: macOS Mojave (10.14)
FW Version: v0.26
SW Version: e02cebe

Description of the bug:application does not look as in wiki; started with creating a UART on DIO0, added DIO1, DIO2 as clock and 0, added DIO1 and 2 to a group, both became clks, tried to change DIO1 to 0 and application crashed. Relaunched application, can no longer edit DIO0.

Steps to reproduce:
occurs when laucnhed
-

The ini files might be useful to reproduce the error.
The ini file is located at: /Users/TTFG/.config/analog.com/Scopy.ini  

         - using MacOS, ini file not at this location

Please consider attaching it.

**Comment by lysynski** [comment]
Additional information:

Cannot access settings for all DIO; settings are greyed out

**Comment by adisuciu** [comment]
Yes, we're working on updating the wiki page for the logic analyzer.
Also you might have triggered this bug https://github.com/analogdevicesinc/scopy/pull/973 .. we're fixing it in the next version. 

Even though you are on macOS, the file should be at that location. If you are getting crashes on startup remove the scopy.ini file from that location and retry.

-Adrian

**Comment by adisuciu** [comment]
https://wiki.analog.com/university/tools/m2k/scopy/logicanalyzer?rev=1607337491

**Comment by lysynski** [comment]
Hi Adrian

So how do I reset the pattern generator so I can use it again?

The directory doesn’t exist; any other locations?

Thanks for the help.
Boris

**Comment by adisuciu** [comment]
You should use the terminal to get to that location, because the .config folder is hidden. 
Regardless you can go to Preferences and click reset scopy. Close the application, and restart. The application should be reset

-Adrian

**Comment by lysynski** [comment]
Sorry Adrian, I didn't have hidden files turned on - here's the ini file (remove .txt).
[Scopy.ini.txt](https://github.com/analogdevicesinc/scopy/files/5653910/Scopy.ini.txt)

**Comment by lysynski** [comment]
Reset didn't restore the pattern generator; screenshot attached, you can see the pattern generator isn't available and within the settings are greyed out.
![Screen Shot 2020-12-07 at 11 42 08 AM](https://user-images.githubusercontent.com/75596365/101378821-9106a300-3881-11eb-88c1-da5fbdef76b2.png)
![Screen Shot 2020-12-07 at 11 43 06 AM](https://user-images.githubusercontent.com/75596365/101378831-9368fd00-3881-11eb-9fd8-712b0bd2a4cc.png)

**Comment by adisuciu** [comment]
Click the cogwheel and start enabling channels. The button will come up.
-Adrian

**Comment by lysynski** [comment]
Have a look at the second screenshot; DIO0 is enabled, settings greyed out. It’s the same for all channels.

Boris

**Comment by adisuciu** [comment]
You need to select the channels .. double click dio0 and a white outline will appear, the settings will be enabled.

**Comment by lysynski** [comment]
Thanks, I see that now… I guess I did that without knowing it the first time.  “double click” the channel from the wiki led me to believe when I selected the channel.

Thanks again for the help.
Boris

**Comment by adisuciu** [comment]
We have now updated the docs from the wiki. They should now resemble the new (and improved) logic analyzer. You can use that for reference.
