### ISSUE TITLE
Switching Channel Selection generates Scopy crash

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#99]
Connect M2K. Start Scopy. Select Oscilloscope feature. Run Oscilloscope. Start switching channel selection. Scopy tool stops responding.
![untitled1](https://cloud.githubusercontent.com/assets/26061529/26200932/4b4879ea-3bd9-11e7-911c-5f7e16dfceb4.png)

It is to be mentioned that the previous situation is not valid if the Scopy tool is opened, and after calibration is restarted.

**Comment by pcercuei** [comment]
I can't reproduce...

**Comment by rgetz** [comment]
Antoniu:

What git tag of Scopy? What operating system? What firmware?

**Comment by pcercuei** [comment]
@rgetz I think it's been fixed already, about one hour before @amiclaus reported the bug.
I'm waiting for his confirmation and then the bug report can be closed.

**Comment by amiclaus** [comment]
Fixed via [60c2d62](https://github.com/analogdevicesinc/scopy/commit/60c2d622e74334ec554d65da78d8d983e94fb05c) . My Scopy version was two commits behind (Took the build in the morning).
