### ISSUE TITLE
Osciloscope: FFT wndows freeze the oscilloscope

### ISSUE THREAD

**Issue by Rmano** [analogdevicesinc/scopy#998]
**Environment:**
 - OS: Linux, Ubuntu 20.04
 - FW Version 0.26
 - SW Scopy v1.2.0
 - connected via USB
 
**Describe the bug**

When activating the FFT windows, the oscilloscope stop refreshing and no FFT is shown.

**To Reproduce**

1. Go to oscilloscope
2. Click on Run
3. Go on the options
4. activate the FFT windows
5. The signal view freeze, and the FFT is not shown

**Expected behavior**

Seeing the FFT of the signal, and the data acquisition should continue.

**Screenshots**

![image](https://user-images.githubusercontent.com/6414907/107346254-ca979c80-6ac4-11eb-8fb4-e4b7c8dc7e57.png)

**Additional context**

Temperature warnings start to fire, so it seems some kind of tight loop in the FFT code.

**Comment by adisuciu** [comment]
Fixed
